<persisted-output>
Output too large (59.6KB). Full output saved to: /root/.claude/projects/-home-user-hakmundang/b8546aae-5211-575f-825f-676b5ddc3b42/tool-results/toolu_016pqFGY1VHri7RYH1FTJcjG.json

Preview (first 2KB):
[
  {
    "type": "text",
    "text": "import { createFileRoute, Link } from \"@tanstack/react-router\";\nimport { useEffect, useRef, useState } from \"react\";\nimport { useQuery, useQueryClient } from \"@tanstack/react-query\";\nimport bearMascot from \"@/assets/bear-mascot.png\";\nimport orunLogo from \"@/assets/orun-logo.png\";\nimport { supabase } from \"@/integrations/supabase/client\";\nimport { useAuth } from \"@/lib/auth\";\nimport { BottomNav } from \"@/components/BottomNav\";\nimport { formatTimer, formatTotal, STICKER_BG, STICKER_BAR } from \"@/lib/format\";\nimport { CHARACTERS, CharacterType, nextStageProgress, characterImage, expToStage } from \"@/lib/character\";\nimport { kstDateEndISO, kstDateStartISO, useCurrentExamPeriod } from \"@/lib/exam-period\";\nimport { toast } from \"sonner\";\nimport {\n  Plus, X,\n  Sigma, Languages, BookOpen, Landmark, Globe2, FlaskConical, Atom,\n  Leaf, Music, Palette, Dumbbell, Code2, BookMarked, Calculator,\n  ScrollText, Mountain, Brain, PenTool, type LucideIcon,\n} from \"lucide-react\";\n\n// 과목 이름 → 어울리는 아이콘 매핑\nfunction subjectIcon(name: string): LucideIcon {\n  const n = name.replace(/\\s/g, \"\");\n  if (/(수학|미적|기하|확통|대수|산수)/.test(n)) return Sigma;\n  if (/(영어|영문|English|english)/.test(n)) return Languages;\n  if (/(국어|문학|독서|작문|논술)/.test(n)) return BookOpen;\n  if (/(한국사|국사|세계사|역사)/.test(n)) return Landmark;\n  if (/(사회|정치|경제|법|윤리|지리)/.test(n)) return Globe2;\n  if (/(화학)/.test(n)) return FlaskConical;\n  if (/(물리)/.test(n)) return Atom;\n  if (/(생명|생물)/.test(n)) return Leaf;\n  if (/(지구|천체)/.test(n)) return Mountain;\n  if (/(과학)/.test(n)) return FlaskConical;\n  if (/(음악)/.test(n)) return Music;\n  if (/(미술|디자인|그림)/.test(n)) return Palette;\n  if (/(체육|운동|PE)/.test(n)) return Dumbbell;\n  if (/(코딩|컴퓨터|프로그|정보|코드|IT)/.test(n)) return Code2;\n  if (/(연산|계산)/.test(n)) return Calculator;\n  if (/(한문|한자)/.test(n)) return ScrollText;\n  if (/(심리|뇌)/.test(n)) return Brain;\n  if (/(글쓰기|작문|에세이)/.test(n)) return Pen
...
</persisted-output>