import { getContentMatchPrompt } from "./contentMatch";
import { getContentMismatchPrompt } from "./contentMismatch";
import { getInferencePrompt } from "./inference";
import { getPurposePrompt } from "./purpose";
import { getClaimPrompt } from "./claim";
import { getImplicationPrompt } from "./implication";
import { getMoodPrompt } from "./mood";
import { getMainPointPrompt } from "./mainPoint";
import { getTopicPrompt } from "./topic";
import { getTitlePrompt } from "./title";
import { getVocabularyPrompt } from "./vocabulary";
import { getBlankPrompt } from "./blank";
import { getBlankMultiplePrompt } from "./blankMultiple";
import { getIrrelevantPrompt } from "./irrelevant";
import { getOrderPrompt } from "./order";
import { getInsertPrompt } from "./insert";
import { getSummaryPrompt } from "./summary";
import { getTrueOrFalsePrompt } from "./trueOrFalse";
import { getSynonymAntonymPrompt } from "./synonymAntonym";
import { getLogicFlowPrompt } from "./logicFlow";
import { getWeekendClinicPrompt } from "./weekendClinic";
import { getOrderWritingPrompt } from "./orderWriting";
import { getSummaryBlankPrompt } from "./summaryBlank";
import { getTopicWritingPrompt } from "./topicWriting";
import { getDictionaryPrompt } from "./dictionary";
import { getSungnamVocab1Prompt } from "./sungnamVocab1";
import { getSungnamVocab2Prompt } from "./sungnamVocab2";
import { getSungnamVocab3Prompt } from "./sungnamVocab3";

export * from "./contentMatch";
export * from "./contentMismatch";
export * from "./inference";
export * from "./purpose";
export * from "./claim";
export * from "./implication";
export * from "./mood";
export * from "./mainPoint";
export * from "./topic";
export * from "./title";
export * from "./vocabulary";
export * from "./blank";
export * from "./blankMultiple";
export * from "./irrelevant";
export * from "./order";
export * from "./insert";
export * from "./summary";
export * from "./trueOrFalse";
export * from "./synonymAntonym";
export * from "./logicFlow";
export * from "./weekendClinic";
export * from "./orderWriting";
export * from "./summaryBlank";
export * from "./topicWriting";
export * from "./dictionary";
export * from "./sungnamVocab1";
export * from "./sungnamVocab2";
export * from "./sungnamVocab3";
