-- Insert the test "사대천왕 옳은보카5" with 100 questions, 1 point each
INSERT INTO tests (test_id, title, question_count, is_ended, answers)
VALUES (
  '020203',
  '사대천왕 옳은보카5',
  100,
  false,
  '{
    "1": {"type": "multiple", "answer": [4], "points": 1},
    "2": {"type": "multiple", "answer": [1, 5], "points": 1},
    "3": {"type": "multiple", "answer": [3, 4], "points": 1},
    "4": {"type": "multiple", "answer": [4, 5], "points": 1},
    "5": {"type": "multiple", "answer": [1, 3], "points": 1},
    "6": {"type": "multiple", "answer": [1, 3], "points": 1},
    "7": {"type": "multiple", "answer": [1, 2], "points": 1},
    "8": {"type": "multiple", "answer": [2, 4], "points": 1},
    "9": {"type": "multiple", "answer": [1, 2], "points": 1},
    "10": {"type": "multiple", "answer": [4, 5], "points": 1},
    "11": {"type": "multiple", "answer": [1, 2], "points": 1},
    "12": {"type": "multiple", "answer": [3, 4], "points": 1},
    "13": {"type": "multiple", "answer": [1, 2], "points": 1},
    "14": {"type": "multiple", "answer": [5], "points": 1},
    "15": {"type": "multiple", "answer": [5], "points": 1},
    "16": {"type": "multiple", "answer": [1, 3], "points": 1},
    "17": {"type": "multiple", "answer": [4], "points": 1},
    "18": {"type": "multiple", "answer": [2, 5], "points": 1},
    "19": {"type": "multiple", "answer": [3], "points": 1},
    "20": {"type": "multiple", "answer": [3, 5], "points": 1},
    "21": {"type": "multiple", "answer": [2], "points": 1},
    "22": {"type": "multiple", "answer": [4], "points": 1},
    "23": {"type": "multiple", "answer": [5], "points": 1},
    "24": {"type": "multiple", "answer": [4, 5], "points": 1},
    "25": {"type": "multiple", "answer": [1, 4], "points": 1},
    "26": {"type": "multiple", "answer": [4, 5], "points": 1},
    "27": {"type": "multiple", "answer": [2, 4], "points": 1},
    "28": {"type": "multiple", "answer": [1, 5], "points": 1},
    "29": {"type": "multiple", "answer": [1, 5], "points": 1},
    "30": {"type": "multiple", "answer": [4, 5], "points": 1},
    "31": {"type": "multiple", "answer": [2], "points": 1},
    "32": {"type": "multiple", "answer": [2, 3], "points": 1},
    "33": {"type": "multiple", "answer": [2], "points": 1},
    "34": {"type": "multiple", "answer": [1], "points": 1},
    "35": {"type": "multiple", "answer": [2, 3], "points": 1},
    "36": {"type": "multiple", "answer": [2, 5], "points": 1},
    "37": {"type": "multiple", "answer": [2, 3], "points": 1},
    "38": {"type": "multiple", "answer": [1, 5], "points": 1},
    "39": {"type": "multiple", "answer": [4], "points": 1},
    "40": {"type": "multiple", "answer": [1, 2], "points": 1},
    "41": {"type": "multiple", "answer": [3], "points": 1},
    "42": {"type": "multiple", "answer": [2], "points": 1},
    "43": {"type": "multiple", "answer": [2, 5], "points": 1},
    "44": {"type": "multiple", "answer": [1, 5], "points": 1},
    "45": {"type": "multiple", "answer": [4], "points": 1},
    "46": {"type": "multiple", "answer": [4], "points": 1},
    "47": {"type": "multiple", "answer": [4, 5], "points": 1},
    "48": {"type": "multiple", "answer": [2, 4], "points": 1},
    "49": {"type": "multiple", "answer": [4, 5], "points": 1},
    "50": {"type": "multiple", "answer": [1], "points": 1},
    "51": {"type": "multiple", "answer": [1], "points": 1},
    "52": {"type": "multiple", "answer": [4, 5], "points": 1},
    "53": {"type": "multiple", "answer": [3], "points": 1},
    "54": {"type": "multiple", "answer": [4, 5], "points": 1},
    "55": {"type": "multiple", "answer": [2, 4], "points": 1},
    "56": {"type": "multiple", "answer": [1, 2], "points": 1},
    "57": {"type": "multiple", "answer": [4, 5], "points": 1},
    "58": {"type": "multiple", "answer": [2, 3], "points": 1},
    "59": {"type": "multiple", "answer": [5], "points": 1},
    "60": {"type": "multiple", "answer": [4], "points": 1},
    "61": {"type": "multiple", "answer": [2, 3], "points": 1},
    "62": {"type": "multiple", "answer": [2, 3], "points": 1},
    "63": {"type": "multiple", "answer": [2, 4], "points": 1},
    "64": {"type": "multiple", "answer": [4], "points": 1},
    "65": {"type": "multiple", "answer": [2, 5], "points": 1},
    "66": {"type": "multiple", "answer": [3, 5], "points": 1},
    "67": {"type": "multiple", "answer": [3, 5], "points": 1},
    "68": {"type": "multiple", "answer": [1, 4], "points": 1},
    "69": {"type": "multiple", "answer": [2, 4], "points": 1},
    "70": {"type": "multiple", "answer": [2, 5], "points": 1},
    "71": {"type": "multiple", "answer": [1], "points": 1},
    "72": {"type": "multiple", "answer": [2], "points": 1},
    "73": {"type": "multiple", "answer": [1, 3], "points": 1},
    "74": {"type": "multiple", "answer": [2, 5], "points": 1},
    "75": {"type": "multiple", "answer": [4], "points": 1},
    "76": {"type": "multiple", "answer": [1, 2], "points": 1},
    "77": {"type": "multiple", "answer": [3, 5], "points": 1},
    "78": {"type": "multiple", "answer": [2, 3], "points": 1},
    "79": {"type": "multiple", "answer": [2, 4], "points": 1},
    "80": {"type": "multiple", "answer": [1, 3], "points": 1},
    "81": {"type": "multiple", "answer": [1, 5], "points": 1},
    "82": {"type": "multiple", "answer": [4, 5], "points": 1},
    "83": {"type": "multiple", "answer": [4], "points": 1},
    "84": {"type": "multiple", "answer": [1, 4], "points": 1},
    "85": {"type": "multiple", "answer": [5], "points": 1},
    "86": {"type": "multiple", "answer": [4, 5], "points": 1},
    "87": {"type": "multiple", "answer": [2, 4], "points": 1},
    "88": {"type": "multiple", "answer": [1, 5], "points": 1},
    "89": {"type": "multiple", "answer": [1, 2], "points": 1},
    "90": {"type": "multiple", "answer": [1, 2], "points": 1},
    "91": {"type": "multiple", "answer": [4], "points": 1},
    "92": {"type": "multiple", "answer": [1, 2], "points": 1},
    "93": {"type": "multiple", "answer": [1, 5], "points": 1},
    "94": {"type": "multiple", "answer": [3, 4], "points": 1},
    "95": {"type": "multiple", "answer": [5], "points": 1},
    "96": {"type": "multiple", "answer": [2], "points": 1},
    "97": {"type": "multiple", "answer": [2, 3], "points": 1},
    "98": {"type": "multiple", "answer": [1, 4], "points": 1},
    "99": {"type": "multiple", "answer": [1, 5], "points": 1},
    "100": {"type": "multiple", "answer": [3, 5], "points": 1}
  }'::jsonb
);