<persisted-output>
Output too large (52.3KB). Full output saved to: /root/.claude/projects/-home-user-hakmundang/b8546aae-5211-575f-825f-676b5ddc3b42/tool-results/toolu_01BMALANgV4TYuMvtmwMut8F.json

Preview (first 2KB):
[
  {
    "type": "text",
    "text": "import React, { useMemo, useRef, useState } from \"react\";\nimport { Dialog, DialogContent, DialogHeader, DialogTitle } from \"@/components/ui/dialog\";\nimport { Tabs, TabsContent, TabsList, TabsTrigger } from \"@/components/ui/tabs\";\nimport { Button } from \"@/components/ui/button\";\nimport { Input } from \"@/components/ui/input\";\nimport {\n  Copy,\n  Users,\n  Link2,\n  Trash2,\n  Check,\n  X,\n  Minus,\n  ChevronLeft,\n  TrendingDown,\n  AlertTriangle,\n  BarChart3,\n  GraduationCap,\n  Download,\n} from \"lucide-react\";\nimport { toast } from \"sonner\";\nimport { toJpeg } from \"html-to-image\";\nimport JSZip from \"jszip\";\nimport {\n  useStudentSubmissions,\n  StudentSubmission,\n  AnswerStatus,\n} from \"@/hooks/useStudentSubmissions\";\nimport { ProblemType } from \"@/integrations/supabase/reportService\";\nimport { getSchoolLogo } from \"@/lib/schoolLogos\";\nimport { supabase } from \"@/integrations/supabase/client\";\n\ninterface Props {\n  open: boolean;\n  onOpenChange: (v: boolean) => void;\n  reportId?: string;\n  reportMeta?: { school: string; grade: string; examScope: string; examInfo?: string; teacher?: string; created_at?: string };\n  problems: ProblemType[];\n}\n\nconst statusIcon = (s?: AnswerStatus) => {\n  if (s === \"wrong\") return <X className=\"w-4 h-4 text-rose-600\" />;\n  if (s === \"partial\") return <Minus className=\"w-4 h-4 text-amber-600\" />;\n  return <Check className=\"w-4 h-4 text-emerald-600\" />;\n};\n\nconst statusBg = (s?: AnswerStatus) => {\n  if (s === \"wrong\") return \"bg-rose-50 border-rose-200\";\n  if (s === \"partial\") return \"bg-amber-50 border-amber-200\";\n  return \"bg-emerald-50 border-emerald-200\";\n};\n\nconst StudentSubmissionsDialog: React.FC<Props> = ({ open, onOpenChange, reportId, reportMeta, problems }) => {\n  const { submissions, loading, remove } = useStudentSubmissions(reportId);\n  const [selected, setSelected] = useState<StudentSubmission | nul
...
</persisted-output>