module.exports = [
{
 no:"03", key:"practice", accent:"#2E8B7F", tint:"#E3F1EE", deep:"#1E6157",
 en:"In Practice an Engineer", ko:"연습할 때는 엔지니어처럼",
 goal:"연습과 공연이 서로 어떤 관계인지 비유를 근거로 설명할 수 있다.",
 fig:"Figure 3  볼트가 제자리에 있어야 비로소 날 수 있다.",
 tip:"먼저 생각해 보자. 시험 전날의 나와 시험장 안의 나는 어떻게 달라야 할까?",
 sent:[
  "Concert pianists spend far more of their lives practising than performing.",
  "Playing the piano is not only remembering notes; it is physical work that needs reflex and endurance.",
  "You may never forget how to ride a bicycle, but if your legs are out of shape you will not finish a race.",
  "So the question is not whether to practise, but how to make the long hours offstage serve the short hours onstage.",
  "My teacher used to say, “In practice a perfectionist, in performance a realist.”",
  "At home, prepare endlessly.",
  "On stage, accept what is in front of you.",
  "Do not wish that the piano were better tuned, or the hall fuller, or that you had not missed that one passage.",
  "Being a realist sounds dull when the job is to bring a great work to life.",
  "I would put it another way: in practice an engineer, in performance a pilot.",
  "The bolts of an aircraft matter enormously, but once you sit in the cockpit your eyes look ahead, not down.",
  "We practise so that we are free to fly wherever the music asks.",
  "That destination is made of imagination, not of correct notes alone.",
  "Yet without the bolts in place, we never leave the ground."],
 kor:[
  "콘서트 피아니스트는 연주하는 시간보다 연습하는 시간에 인생의 훨씬 더 많은 부분을 쓴다.",
  "피아노 연주는 음을 외우는 일만이 아니다. 그것은 반사 신경과 지구력이 필요한 육체노동이다.",
  "자전거 타는 법은 잊지 않을지 몰라도, 다리가 예전 같지 않다면 경주를 완주하지 못할 것이다.",
  "그러니 문제는 연습을 할지 말지가 아니라, 무대 밖의 긴 시간이 무대 위의 짧은 시간에 도움이 되게 하는 방법이다.",
  "나의 스승은 “연습할 때는 완벽주의자, 공연할 때는 현실주의자”라고 말하곤 했다.",
  "집에서는 끝없이 준비하라.",
  "무대에서는 눈앞에 있는 것을 받아들이라.",
  "피아노 조율이 더 좋았더라면, 객석이 더 찼더라면, 그 한 악절을 놓치지 않았더라면 하고 바라지 마라.",
  "위대한 작품에 생명을 불어넣는 일 앞에서 현실주의자가 된다는 말은 따분하게 들린다.",
  "나라면 이렇게 바꿔 말하겠다. 연습할 때는 엔지니어, 공연할 때는 조종사라고.",
  "비행기의 볼트는 대단히 중요하지만, 일단 조종석에 앉으면 눈은 아래가 아니라 앞을 본다.",
  "우리는 음악이 요구하는 곳 어디로든 자유롭게 날아가기 위해 연습한다.",
  "그 목적지는 정확한 음만으로 이루어지지 않고 상상력으로 이루어진다.",
  "그러나 볼트가 제자리에 있지 않으면 우리는 결코 땅을 떠나지 못한다."],
 bank:[["endurance","②","지구력"],["out of shape","③","몸이 예전 같지 않은"],["offstage","④","무대 밖의"],
       ["tuned","⑧","조율된"],["dull","⑨","따분한"],["destination","⑬","목적지"]],
 defs:[["endurance","the ability to keep going for a long time"],
       ["out of shape","no longer fit or in good condition"],
       ["offstage","away from the place where a performance happens"],
       ["tuned","adjusted so that the sound is correct"],
       ["dull","not interesting or exciting"],
       ["destination","the place someone is travelling to"]],
 defOrder:[4,0,5,1,3,2],
 chunk:[
  {n:"②",en:"Playing the piano is not only remembering notes; / it is physical work / that needs reflex and endurance.",
   ko:"피아노 연주는 음을 외우는 일만이 아니다 / 그것은 육체노동이다 / 반사 신경과 지구력이 필요한"},
  {n:"④",en:"So the question is not whether to practise, / but how to make the long hours offstage / serve the short hours onstage.",
   ko:"그러니 문제는 연습을 할지 말지가 아니라 / 무대 밖의 긴 시간을 어떻게 만드느냐이다 / 무대 위의 짧은 시간에 도움이 되도록"},
  {n:"⑪",en:"The bolts of an aircraft matter enormously, / but once you sit in the cockpit / your eyes look ahead, not down.",
   ko:"비행기의 볼트는 대단히 중요하다 / 그러나 일단 조종석에 앉으면 / 눈은 앞을 보지 아래를 보지 않는다"},
  {n:"⑭",en:"Yet without the bolts in place, / we never leave the ground.",
   ko:"그러나 볼트가 제자리에 있지 않으면 / 우리는 결코 땅을 떠나지 못한다"}],
 mark:[
  {n:"②",raw:"Playing the piano is not only remembering notes; it is physical work that needs reflex and endurance.",
   ans:"Playing the piano is not only remembering notes; it is physical work [that needs reflex and endurance].",
   note:"[ ] physical work를 꾸미는 관계절 · S Playing the piano / it, V is, C remembering notes / physical work"},
  {n:"④",raw:"So the question is not whether to practise, but how to make the long hours offstage serve the short hours onstage.",
   ans:"So the question is not [whether to practise], but [how to make the long hours (offstage) serve the short hours (onstage)].",
   note:"두 개의 [ ]가 「not A but B」로 묶여 보어 자리에 온다 · ( ) 앞의 명사를 꾸미는 말 · S the question / V is"}],
 flow:[["사실","연주 행위는 반사 신경과 (  ①  )이 필요한 육체노동이다","지구력"],
       ["문제","무대 밖의 긴 시간을 무대 위의 (  ②  ) 시간에 어떻게 쓸 것인가","짧은"],
       ["스승의 말","연습할 때는 완벽주의자, 공연할 때는 (  ③  )","현실주의자"],
       ["필자의 비유","연습할 때는 엔지니어, 공연할 때는 (  ④  )","조종사"],
       ["결론","볼트가 제자리에 없으면 결코 땅을 떠나지 못한다",null]],
 flowBogi:"지구력 · 짧은 · 현실주의자 · 조종사 · 완벽주의자 · 긴",
 para:[["④ how to make the long hours offstage serve the short hours onstage","Practice should ______ the performance, not replace it.","support"],
       ["⑨ Being a realist sounds dull","Accepting things as they are can seem ______.","boring"],
       ["⑭ without the bolts in place, we never leave the ground","Without solid ______, no free performance is possible.","basics"]],
 paraBogi:"support · boring · basics · exciting · notes · speed",
 check:[
  {t:"title",q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Hardest Piece for a Pianist","Why Bicycles and Pianos Are Alike",
       "How to Tune a Concert Piano","Perfectionists Make the Best Performers",
       "Practice Builds the Freedom to Play"],ans:5},
  {t:"fact",q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["피아노 연주에는 반사 신경과 지구력이 필요하다.","무대에서는 눈앞의 상황을 받아들여야 한다.",
       "필자의 스승은 ‘연습할 때는 엔지니어’라고 말했다.","조종석에 앉으면 눈은 앞을 본다.",
       "볼트가 제자리에 없으면 땅을 떠날 수 없다."],ans:3},
  {t:"write",q:"필자가 말한 ‘볼트(the bolts)’가 피아노 연주에서 무엇을 뜻하는지 우리말 한 문장으로 써 보세요.",
   ans:"무대에서 자유롭게 연주하기 위해 무대 밖에서 갖춰 두어야 할 기본기와 준비를 뜻한다."}]
},
{
 no:"04", key:"shelter", accent:"#C2557A", tint:"#FAE9EF", deep:"#8E3454",
 en:"The Safest Room in the Castle", ko:"성에서 가장 안전한 방",
 goal:"위험을 없앤 보호가 왜 보호가 아닌지 이야기의 근거로 설명할 수 있다.",
 fig:"Figure 4  유리 돔 안의 성 — 위험이 하나도 없는 세계.",
 tip:"먼저 생각해 보자. 누군가가 나를 위해 모든 위험을 미리 치워 준다면, 나는 무엇을 배우지 못하게 될까?",
 sent:[
  "In the film Sleeping Beauty, a king and queen finally have a daughter, Aurora.",
  "They plan a great celebration and welcome everyone who loves her — everyone except Maleficent.",
  "She comes anyway and curses the child: on her sixteenth birthday Aurora will prick her finger on a spinning wheel and die.",
  "A good fairy softens the curse into sleep, which love can undo.",
  "The frightened parents burn every spinning wheel in the kingdom and hide their daughter deep in a forest.",
  "Notice what the story is really describing.",
  "The two rulers are building a world around Aurora with nothing dangerous in it.",
  "It looks like protection, but it is not.",
  "Sixteen years without risk leave her innocent, untested, and weak.",
  "When she is finally brought back to the castle, she has no way to face what is waiting there.",
  "A door opens, a spinning wheel appears, and she falls asleep.",
  "Only after the curse is broken does she begin to grow.",
  "At the end she is no longer a girl kept safe by others.",
  "She is someone ready to take charge of her own life."],
 kor:[
  "영화 ‘잠자는 숲속의 공주’에서 왕과 왕비는 마침내 딸 오로라를 얻는다.",
  "그들은 성대한 잔치를 계획하고 그녀를 사랑하는 모든 사람을 맞이한다 — 말레피센트만 빼고.",
  "그녀는 그래도 찾아와 아이에게 저주를 내린다. 열여섯 번째 생일에 오로라가 물레에 손가락을 찔려 죽으리라는 것이다.",
  "착한 요정이 그 저주를 잠으로 누그러뜨리고, 그 잠은 사랑으로 풀 수 있다.",
  "겁에 질린 부모는 왕국의 물레를 모두 태우고 딸을 숲 깊은 곳에 숨긴다.",
  "이 이야기가 실제로 무엇을 그리고 있는지 눈여겨보라.",
  "두 통치자는 오로라 주위에 위험한 것이 하나도 없는 세계를 세우고 있다.",
  "그것은 보호처럼 보이지만 보호가 아니다.",
  "위험이 없는 열여섯 해는 그녀를 순진하고, 시험받지 못하고, 나약한 사람으로 남겨 둔다.",
  "마침내 성으로 돌아왔을 때, 그녀에게는 그곳에서 기다리는 것을 감당할 방법이 없다.",
  "문이 열리고, 물레가 나타나고, 그녀는 잠든다.",
  "저주가 풀린 뒤에야 그녀는 비로소 성장하기 시작한다.",
  "마지막에 그녀는 더 이상 남이 안전하게 지켜 주는 소녀가 아니다.",
  "그녀는 자기 삶을 스스로 책임질 준비가 된 사람이다."],
 bank:[["curse","③","저주를 내리다"],["undo","④","(효력을) 되돌리다"],["frightened","⑤","겁에 질린"],
       ["untested","⑨","시험받아 본 적 없는"],["face","⑩","감당하다, 맞서다"],["take charge of","⑭","~을 책임지다"]],
 defs:[["curse","to use magic words to bring bad luck to someone"],
       ["undo","to cancel the effect of something"],
       ["frightened","feeling afraid"],
       ["untested","never having been put in a difficult situation"],
       ["face","to deal with something difficult"],
       ["take charge of","to take control and responsibility for something"]],
 defOrder:[5,2,0,4,1,3],
 chunk:[
  {n:"⑦",en:"The two rulers are building a world / around Aurora / with nothing dangerous in it.",
   ko:"두 통치자는 세계를 세우고 있다 / 오로라 주위에 / 그 안에 위험한 것이 하나도 없는"},
  {n:"⑨",en:"Sixteen years without risk / leave her innocent, untested, and weak.",
   ko:"위험이 없는 열여섯 해가 / 그녀를 순진하고 시험받지 못하고 나약한 채로 남겨 둔다"},
  {n:"⑩",en:"When she is finally brought back to the castle, / she has no way / to face what is waiting there.",
   ko:"마침내 성으로 돌아왔을 때 / 그녀에게는 방법이 없다 / 그곳에서 기다리는 것을 감당할"},
  {n:"⑫",en:"Only after the curse is broken / does she begin to grow.",
   ko:"저주가 풀린 뒤에야 / 비로소 그녀는 성장하기 시작한다"}],
 mark:[
  {n:"②",raw:"They plan a great celebration and welcome everyone who loves her — everyone except Maleficent.",
   ans:"They plan a great celebration and welcome everyone [who loves her] — everyone (except Maleficent).",
   note:"[ ] everyone을 꾸미는 관계절 · ( ) 앞의 명사를 한정하는 전치사구 · S They / V₁ plan + O₁ a great celebration / V₂ welcome + O₂ everyone"},
  {n:"⑩",raw:"When she is finally brought back to the castle, she has no way to face what is waiting there.",
   ans:"[When she is finally brought back (to the castle)], she has no way to face [what is waiting there].",
   note:"첫 [ ] 시간을 나타내는 부사절 · 둘째 [ ] face의 목적어가 되는 명사절 · S she / V has / O no way"}],
 flow:[["발단","오로라의 탄생과 말레피센트의 (  ①  )","저주"],
       ["부모의 대응","왕국의 물레를 모두 태우고 딸을 숲에 (  ②  )","숨긴다"],
       ["이야기의 뜻","위험이 하나도 없는 세계는 보호처럼 보이지만 (  ③  )","보호가 아니다"],
       ["결과","위험 없는 열여섯 해가 그녀를 (  ④  ) 만든다","나약하게"],
       ["결말","저주가 풀린 뒤 스스로 삶을 책임질 사람으로 성장한다",null]],
 flowBogi:"저주 · 숨긴다 · 보호가 아니다 · 나약하게 · 잔치 · 튼튼하게",
 para:[["⑧ It looks like protection, but it is not.","Removing every danger only ______ to keep her safe.","seems"],
       ["⑨ leave her innocent, untested, and weak","She grows up without ever being ______.","challenged"],
       ["⑭ someone ready to take charge of her own life","She can now ______ her own decisions.","make"]],
 paraBogi:"seems · challenged · make · protected · avoid · follow",
 check:[
  {t:"title",q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Magic That Saved a Princess","A World Without Risk Makes Us Weak",
       "How to Break a Fairy's Curse","Why Parents Should Plan Big Celebrations",
       "The History of Spinning Wheels"],ans:2},
  {t:"fact",q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["말레피센트는 초대받지 못했지만 찾아왔다.","착한 요정은 저주를 잠으로 누그러뜨렸다.",
       "부모는 왕국의 물레를 모두 태웠다.","오로라는 성으로 돌아온 뒤에도 아무 일도 겪지 않았다.",
       "오로라는 저주가 풀린 뒤에 성장하기 시작한다."],ans:4},
  {t:"write",q:"필자가 왕과 왕비의 행동을 ‘보호가 아니다’라고 말한 이유를 우리말 한 문장으로 써 보세요.",
   ans:"위험을 모두 없앤 세계에서 자란 오로라가 순진하고 나약해져 실제 위험을 감당할 수 없게 되었기 때문이다."}]
},
{
 no:"05", key:"talk", accent:"#2F7CB8", tint:"#E4EFF8", deep:"#1D5686",
 en:"Reading Is a Conversation", ko:"읽기는 대화다",
 goal:"이해가 어떻게 ‘과정’에서 자라나는지 근거를 들어 설명할 수 있다.",
 fig:"Figure 5  한 권의 책을 사이에 두고 오가는 말들.",
 tip:"먼저 생각해 보자. 같은 책을 읽고도 친구와 이야기한 뒤에 생각이 달라진 적이 있는가?",
 sent:[
  "Every field of study builds its own words and its own methods, and literature is no exception.",
  "Knowing a few of them changes what you get from a book.",
  "Literature also has a context and a history.",
  "Learning a little about them can change how much pleasure and insight you take from a story.",
  "Reading widely helps too.",
  "When you read different kinds of writing, from different times and places, you often come to love books you would never have chosen alone.",
  "You may even enjoy books you would have misunderstood if you had read them by yourself.",
  "But the most important step comes after the reading.",
  "Writing about a work, and talking about it with a teacher and with other students, forces you to look more closely and to consider views that are not your own.",
  "A clear understanding of what a story is doing does not arrive like lightning from a blue sky.",
  "It grows out of a process.",
  "You try to put into words why the book affected you, and then you answer what others say about it.",
  "Literature itself is one long conversation, and you join it fully only when you start talking."],
 kor:[
  "모든 학문 분야는 저마다의 용어와 방법을 만들어 내며, 문학도 예외가 아니다.",
  "그중 몇 가지를 아는 것만으로도 책에서 얻는 것이 달라진다.",
  "문학에는 또한 맥락과 역사가 있다.",
  "그것에 대해 조금 배우는 일은 한 편의 이야기에서 얻는 즐거움과 통찰의 크기를 바꿔 놓을 수 있다.",
  "널리 읽는 것도 도움이 된다.",
  "서로 다른 시대와 장소의, 서로 다른 종류의 글을 읽다 보면, 혼자서는 결코 고르지 않았을 책을 사랑하게 되는 일이 자주 있다.",
  "혼자 읽었더라면 오해했을 책을 즐기게 될 수도 있다.",
  "그러나 가장 중요한 단계는 읽기가 끝난 뒤에 온다.",
  "작품에 대해 글을 쓰고 선생님이나 다른 학생들과 그것에 대해 이야기하는 일은, 더 가까이 들여다보게 하고 자기 것이 아닌 관점을 고려하게 만든다.",
  "한 편의 이야기가 무엇을 하고 있는지에 대한 분명한 이해는 맑은 하늘의 번개처럼 오지 않는다.",
  "그것은 하나의 과정에서 자라난다.",
  "그 책이 왜 나를 움직였는지 말로 옮겨 보고, 그다음 다른 사람들이 그것에 대해 하는 말에 답한다.",
  "문학 그 자체가 하나의 긴 대화이며, 우리는 말을 하기 시작할 때에야 비로소 그 대화에 온전히 참여한다."],
 bank:[["field","①","(학문) 분야"],["exception","①","예외"],["insight","④","통찰"],
       ["consider","⑨","고려하다"],["process","⑪","과정"],["affect","⑫","영향을 미치다"]],
 defs:[["field","an area of study or work"],
       ["exception","a case that does not follow the usual rule"],
       ["insight","a clear and deep understanding of something"],
       ["consider","to think about something carefully"],
       ["process","a series of steps that lead to a result"],
       ["affect","to make a change in someone or something"]],
 defOrder:[1,3,5,0,4,2],
 chunk:[
  {n:"⑥",en:"When you read different kinds of writing, / from different times and places, / you often come to love books / you would never have chosen alone.",
   ko:"서로 다른 종류의 글을 읽을 때 / 서로 다른 시대와 장소의 / 여러분은 자주 책을 사랑하게 된다 / 혼자서는 결코 고르지 않았을"},
  {n:"⑨",en:"Writing about a work, and talking about it with others, / forces you to look more closely / and to consider views that are not your own.",
   ko:"작품에 대해 글을 쓰고 다른 사람과 이야기하는 일은 / 더 가까이 들여다보게 만든다 / 그리고 자기 것이 아닌 관점을 고려하게 만든다"},
  {n:"⑩",en:"A clear understanding of what a story is doing / does not arrive / like lightning from a blue sky.",
   ko:"한 편의 이야기가 무엇을 하고 있는지에 대한 분명한 이해는 / 오지 않는다 / 맑은 하늘의 번개처럼"},
  {n:"⑬",en:"Literature itself is one long conversation, / and you join it fully / only when you start talking.",
   ko:"문학 그 자체가 하나의 긴 대화다 / 그리고 여러분은 그것에 온전히 참여한다 / 말을 하기 시작할 때에야 비로소"}],
 mark:[
  {n:"⑨",raw:"Writing about a work, and talking about it with other students, forces you to look more closely and to consider views that are not your own.",
   ans:"[Writing (about a work)], and [talking (about it) (with other students)], forces you to look more closely and to consider views [that are not your own].",
   note:"앞의 두 [ ]가 함께 주어(동명사구) · 마지막 [ ] views를 꾸미는 관계절 · V forces / O you"},
  {n:"⑩",raw:"A clear understanding of what a story is doing does not arrive like lightning from a blue sky.",
   ans:"A clear understanding (of [what a story is doing]) does not arrive (like lightning) (from a blue sky).",
   note:"[ ] 전치사 of의 목적어가 되는 명사절 · ( ) 앞말을 꾸미는 전치사구 · S A clear understanding / V does not arrive"}],
 flow:[["도입","학문마다 고유한 용어와 방법이 있고 문학도 마찬가지다",null],
       ["도움 1","문학의 (  ①  )과 역사를 조금 알면 얻는 것이 달라진다","맥락"],
       ["도움 2","널리 읽으면 혼자서는 (  ②  ) 않았을 책도 사랑하게 된다","고르지"],
       ["가장 중요한 단계","읽은 뒤에 쓰고 (  ③  )하며 다른 관점을 고려한다","이야기"],
       ["결론","이해는 번개처럼 오지 않고, 문학은 곧 (  ④  )다","대화"]],
 flowBogi:"맥락 · 고르지 · 이야기 · 대화 · 번개 · 방법",
 para:[["⑩ does not arrive like lightning from a blue sky","Understanding is never ______; it takes time.","sudden"],
       ["⑨ forces you to look more closely","Writing and talking make you read more ______.","carefully"],
       ["⑬ you join it fully only when you start talking","You become a full ______ in the conversation by speaking.","participant"]],
 paraBogi:"sudden · carefully · participant · silent · quickly · reader",
 check:[
  {t:"title",q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["Books You Should Read Before You Graduate","Why Literature Needs Difficult Words",
       "Reading Alone Is Always Best","Understanding Grows When You Talk",
       "How to Write a Perfect Book Report"],ans:4},
  {t:"fact",q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["학문 분야마다 고유한 용어와 방법이 있다.","널리 읽으면 혼자서는 고르지 않았을 책을 좋아하게 되기도 한다.",
       "가장 중요한 단계는 읽기가 시작되기 전에 온다.","분명한 이해는 번개처럼 갑자기 오지 않는다.",
       "말을 하기 시작할 때 대화에 온전히 참여하게 된다."],ans:3},
  {t:"write",q:"필자가 문학을 ‘하나의 긴 대화’라고 부른 이유를 우리말 한 문장으로 써 보세요.",
   ans:"이해가 글을 쓰고 다른 사람의 말에 답하는 주고받음의 과정에서 자라나기 때문이다."}]
}];
