module.exports = [
{
 no:"01", key:"translation", accent:"#5B57A6", tint:"#EEEDF8", deep:"#3C3878",
 en:"Can a Poem Cross a Border?", ko:"시 한 편은 국경을 넘을 수 있을까",
 goal:"번역이 원작에서 무엇을 옮기고 무엇을 잃는지 설명할 수 있다.",
 fig:"Figure 1  원작에서 번역본으로 건너가는 동안 옅어지는 것들.",
 tip:"먼저 생각해 보자. 좋아하는 노래 가사를 다른 나라 말로 옮긴다면, 가장 먼저 사라지는 것은 무엇일까?",
 sent:[
  "Literature carries feelings that people everywhere can share.",
  "Yet there is no single language that everyone in the world reads or speaks.",
  "Each country writes its literature in its own tongue, so no reader can reach all of it.",
  "Translation seems to solve the problem.",
  "But how faithful is a translation to the original?",
  "A work is born at a moment of strong feeling, when the words flow under the writer's hand.",
  "That moment never comes back.",
  "If the writer cannot repeat it, a translator in another country certainly cannot reproduce it.",
  "Literature also has a local colour.",
  "A word may sound bright and alive to people who grew up with it, and mean almost nothing to everyone else.",
  "A careful translator knows this and chooses the safest words instead.",
  "The result reads smoothly, but something has quietly been given up.",
  "Moods, images, and even thoughts are tied to words; once the words change, the rest changes as well.",
  "A translation, then, is not a copy of a book.",
  "It is a concession."],
 kor:[
  "문학은 어디에 사는 사람이든 함께 나눌 수 있는 감정을 담고 있다.",
  "그러나 세상 모든 사람이 읽거나 말하는 단 하나의 언어는 없다.",
  "나라마다 자기 언어로 문학을 쓰기 때문에, 어떤 독자도 그것을 전부 읽을 수는 없다.",
  "번역이 그 문제를 풀어 줄 것처럼 보인다.",
  "하지만 번역본은 원작에 얼마나 충실한가?",
  "작품은 강렬한 감정의 순간에 태어나며, 그때 말은 작가의 손 아래로 흘러간다.",
  "그 순간은 다시 오지 않는다.",
  "작가조차 그 순간을 되풀이할 수 없다면, 다른 나라의 번역자는 더더욱 그것을 재현할 수 없다.",
  "문학에는 또한 그 지역만의 색채가 있다.",
  "어떤 낱말은 그것과 함께 자란 사람들에게는 환하고 생생하게 들리지만, 그 밖의 사람들에게는 거의 아무 의미가 없다.",
  "신중한 번역자는 이 사실을 알기에 대신 가장 안전한 낱말을 고른다.",
  "그 결과는 매끄럽게 읽히지만, 무엇인가가 조용히 포기된 것이다.",
  "분위기와 이미지, 심지어 생각까지도 말에 묶여 있어서, 말이 바뀌면 나머지도 함께 바뀐다.",
  "그러므로 번역은 책의 복사본이 아니다.",
  "그것은 양보다."],
 bank:[["tongue","③","(한 민족이 쓰는) 언어"],["faithful","⑤","충실한"],["flow","⑥","흘러가다"],
       ["reproduce","⑧","재현하다"],["local","⑨","그 지역의"],["concession","⑮","양보"]],
 defs:[["tongue","the language spoken by a group of people"],
       ["faithful","keeping closely to the original"],
       ["flow","to move along easily and without stopping"],
       ["reproduce","to make something again in exactly the same form"],
       ["local","belonging to one particular place and its people"],
       ["concession","something you give up so that an agreement can be reached"]],
 defOrder:[3,5,0,4,1,2],
 chunk:[
  {n:"③",en:"Each country writes its literature / in its own tongue, / so no reader can reach all of it.",
   ko:"나라마다 자기 문학을 쓴다 / 자기 언어로 / 그래서 어떤 독자도 그것을 전부 읽을 수 없다"},
  {n:"⑥",en:"A work is born / at a moment of strong feeling, / when the words flow under the writer's hand.",
   ko:"작품은 태어난다 / 강렬한 감정의 순간에 / 그때 말은 작가의 손 아래로 흘러간다"},
  {n:"⑩",en:"A word may sound bright and alive / to people who grew up with it, / and mean almost nothing to everyone else.",
   ko:"어떤 낱말은 환하고 생생하게 들릴 수 있다 / 그것과 함께 자란 사람들에게는 / 그리고 그 밖의 사람들에게는 거의 아무 의미가 없다"},
  {n:"⑬",en:"Moods, images, and even thoughts are tied to words; / once the words change, / the rest changes as well.",
   ko:"분위기와 이미지, 심지어 생각까지도 말에 묶여 있다 / 말이 바뀌면 / 나머지도 함께 바뀐다"}],
 mark:[
  {n:"⑧",raw:"If the writer cannot repeat it, a translator in another country certainly cannot reproduce it.",
   ans:"[If the writer cannot repeat it], a translator (in another country) certainly cannot reproduce it.",
   note:"[ ] 조건을 나타내는 부사절 · ( ) a translator를 꾸미는 전치사구 · S a translator / V cannot reproduce / O it"},
  {n:"⑩",raw:"A word may sound bright and alive to people who grew up with it, and mean almost nothing to everyone else.",
   ans:"A word may sound bright and alive (to people [who grew up with it]), and mean almost nothing (to everyone else).",
   note:"[ ] people을 꾸미는 관계절 · S A word / V₁ may sound + C bright and alive / V₂ (may) mean + O almost nothing"}],
 flow:[["문제","보편적인 언어가 없어 세계의 문학을 다 읽을 수 없다",null],
       ["해법처럼 보이는 것","(  ①  )이 그 문제를 풀어 줄 것처럼 보인다","번역"],
       ["한계 1","작품이 태어난 (  ②  )은 다시 오지 않아 재현할 수 없다","순간"],
       ["한계 2","지역의 색채가 담긴 낱말은 다른 독자에게 (  ③  )","아무 의미가 없다"],
       ["결론","번역은 복사본이 아니라 (  ④  )이다","양보"]],
 flowBogi:"번역 · 순간 · 아무 의미가 없다 · 양보 · 복사본 · 문법",
 para:[["⑤ how faithful is a translation to the original?","Does the new version stay ______ to the first one?","true"],
       ["⑫ something has quietly been given up","The translator has ______ something without saying so.","sacrificed"],
       ["⑮ It is a concession.","A translation always ______ something in return for being readable.","loses"],
       ["② Yet there is no single language that everyone in the world reads or speaks.","No single language is ______ by all the world’s readers.","shared"],
       ["⑦ That moment never comes back.","The moment of writing cannot be ______.","repeated"]],
 paraBogi:"true · sacrificed · loses · shared · repeated · copies · adds · counted",
 check:[
  {t:"title",q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["Why Every Country Needs Its Own Language","Translation: A Smooth Copy of the Original",
       "What a Translation Must Give Up","How to Become a Careful Translator",
       "The Best Way to Learn a Foreign Language"],ans:3},
  {t:"fact",q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["세상 모든 사람이 읽는 단 하나의 언어는 없다.","작품이 태어난 순간은 다시 오지 않는다.",
       "지역의 색채가 담긴 낱말은 누구에게나 똑같이 생생하다.","신중한 번역자는 가장 안전한 낱말을 고른다.",
       "말이 바뀌면 분위기와 생각도 함께 바뀐다."],ans:3},
  {t:"write",q:"필자가 번역을 <i>a concession</i>(양보)이라고 부른 이유를 우리말 한 문장으로 써 보세요.",
   ans:"매끄럽게 읽히도록 만드는 대신 원작의 순간과 지역색을 포기하기 때문이다."}]
},
{
 no:"02", key:"image", accent:"#E07A3E", tint:"#FDEEE3", deep:"#A8501E",
 en:"This Is Not a Pipe", ko:"이것은 파이프가 아니다",
 goal:"이미지가 왜 사물 그 자체가 아닌지 근거를 들어 설명할 수 있다.",
 fig:"Figure 2  액자 안의 파이프와 액자 밖의 파이프는 같은 것이 아니다.",
 tip:"먼저 생각해 보자. 우리가 뉴스 사진을 ‘사실’이라고 믿는 이유는 무엇일까?",
 sent:[
  "People often say that seeing is believing.",
  "A photograph, we feel, cannot lie the way words can.",
  "Words are clearly made by people.",
  "They are invented sounds, written with invented letters, and joined by a grammar that a culture has agreed on.",
  "Everyone who speaks English understands the word “food,” even though each person pictures a different dish.",
  "Looser words such as “cool” change their meaning again and again.",
  "An image feels different.",
  "When we see a thing, nothing seems to stand between us and it.",
  "The picture appears to arrive directly, so we treat it as reality itself.",
  "But an image is made too.",
  "Someone chose the angle, the light, and the moment.",
  "Whether it is painted, photographed, or built on a screen, it is still a version of the thing, not the thing.",
  "The Belgian painter René Magritte turned this into a joke.",
  "He painted a pipe and wrote underneath, “This is not a pipe.”",
  "He was right: it is a picture of a pipe."],
 kor:[
  "사람들은 흔히 보는 것이 믿는 것이라고 말한다.",
  "사진은 말과 달리 거짓말을 할 수 없다고 우리는 느낀다.",
  "말은 분명히 사람이 만든 것이다.",
  "말은 만들어진 소리이고, 만들어진 문자로 적히며, 한 문화가 합의한 문법으로 이어진다.",
  "각자 떠올리는 음식은 다르더라도, 영어를 쓰는 사람은 누구나 ‘food’라는 말을 이해한다.",
  "‘cool’ 같은 느슨한 말은 그 뜻이 계속해서 달라진다.",
  "이미지는 느낌이 다르다.",
  "어떤 것을 볼 때, 우리와 그것 사이에는 아무것도 없는 것처럼 보인다.",
  "그림은 곧바로 도착하는 것처럼 보여서, 우리는 그것을 현실 그 자체로 여긴다.",
  "그러나 이미지 역시 만들어진 것이다.",
  "누군가가 각도와 빛과 순간을 골랐다.",
  "그림이든 사진이든 화면 위에 만든 것이든, 그것은 여전히 그 사물의 한 판본일 뿐 그 사물 자체는 아니다.",
  "벨기에 화가 르네 마그리트는 이것을 하나의 농담으로 만들었다.",
  "그는 파이프를 그리고 그 아래에 ‘이것은 파이프가 아니다’라고 썼다.",
  "그의 말이 옳다. 그것은 파이프의 그림이다."],
 bank:[["invented","④","(사람이) 만들어 낸"],["agree on","④","합의하다"],["picture","⑤","머릿속에 그리다"],
       ["stand between","⑧","사이를 가로막다"],["version","⑫","(여러 형태 중) 한 판본"],["underneath","⑭","그 아래에"]],
 defs:[["invented","made up by people rather than found in nature"],
       ["agree on","to decide something together"],
       ["picture","to form an image of something in your mind"],
       ["stand between","to come in the way of two things"],
       ["version","one form of something that exists in several forms"],
       ["underneath","in or to a lower place than something"]],
 defOrder:[2,4,0,5,3,1],
 chunk:[
  {n:"④",en:"They are invented sounds, / written with invented letters, / and joined by a grammar / that a culture has agreed on.",
   ko:"그것들은 만들어진 소리이다 / 만들어진 문자로 적히고 / 그리고 문법으로 이어진다 / 한 문화가 합의한"},
  {n:"⑧",en:"When we see a thing, / nothing seems to stand / between us and it.",
   ko:"우리가 어떤 것을 볼 때 / 아무것도 가로막고 있지 않은 것처럼 보인다 / 우리와 그것 사이를"},
  {n:"⑨",en:"The picture appears to arrive directly, / so we treat it / as reality itself.",
   ko:"그림은 곧바로 도착하는 것처럼 보인다 / 그래서 우리는 그것을 여긴다 / 현실 그 자체로"},
  {n:"⑫",en:"Whether it is painted, photographed, or built on a screen, / it is still a version of the thing, / not the thing.",
   ko:"그것이 그려졌든 사진으로 찍혔든 화면 위에 만들어졌든 / 그것은 여전히 그 사물의 한 판본이다 / 그 사물 자체가 아니라"}],
 mark:[
  {n:"⑤",raw:"Everyone who speaks English understands the word “food,” even though each person pictures a different dish.",
   ans:"Everyone [who speaks English] understands the word “food,” [even though each person pictures a different dish].",
   note:"첫 [ ] Everyone을 꾸미는 관계절 · 둘째 [ ] 양보를 나타내는 부사절 · S Everyone / V understands / O the word “food”"},
  {n:"⑫",raw:"Whether it is painted, photographed, or built on a screen, it is still a version of the thing, not the thing.",
   ans:"[Whether it is painted, photographed, or built (on a screen)], it is still a version (of the thing), not the thing.",
   note:"[ ] 양보를 나타내는 부사절 · ( ) 앞의 명사를 꾸미는 전치사구 · S it / V is / C a version of the thing"}],
 flow:[["통념","보는 것이 믿는 것이다 — 사진은 거짓말하지 않는다",null],
       ["통념의 근거","말은 사람이 (  ①  ) 것이라 사물 그 자체가 아니다","만든"],
       ["통념 강화","이미지는 우리와 사물 사이에 아무것도 없이 (  ②  ) 전달되는 듯하다","곧바로"],
       ["반전","그러나 이미지도 누군가가 각도·빛·순간을 (  ③  ) 만든 것이다","고른"],
       ["결론","이미지는 사물의 한 판본일 뿐 (  ④  )가 아니다","사물 자체"]],
 flowBogi:"만든 · 곧바로 · 고른 · 사물 자체 · 거짓말 · 문법",
 para:[["⑧ nothing seems to stand between us and it","The image feels ______ — as if nothing were in the way.","direct"],
       ["⑫ it is still a version of the thing, not the thing","A picture only ______ an object; it never becomes one.","represents"],
       ["⑭ “This is not a pipe.”","The painting is a ______ of a pipe, not a pipe.","picture"],
       ["③ Words are clearly made by people.","Language is ______, not something found in nature.","artificial"],
       ["⑪ Someone chose the angle, the light, and the moment.","Every image carries the ______ of the person who made it.","choices"]],
 paraBogi:"direct · represents · picture · artificial · choices · reality · hides · copies",
 check:[
  {t:"title",q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["Why Photographs Never Lie","How Words Lost Their Meaning",
       "An Image Is Always Someone's Version","Magritte: The Painter Who Loved Pipes",
       "Learning English Through Pictures"],ans:3},
  {t:"fact",q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["말은 한 문화가 합의한 문법으로 이어진다.","영어를 쓰는 사람은 누구나 ‘food’를 이해한다.",
       "‘cool’ 같은 말의 뜻은 계속 달라진다.","사진은 만들어지지 않고 있는 그대로 전달된다.",
       "마그리트는 파이프 그림 아래에 한 문장을 적었다."],ans:4},
  {t:"write",q:"마그리트가 파이프 그림 아래에 “This is not a pipe.”라고 쓴 이유를 우리말 한 문장으로 써 보세요.",
   ans:"그림은 파이프를 그린 것일 뿐 파이프 그 자체는 아니기 때문이다."}]
}];
