/* 영문 플로차트 · Check Up 오답 이유 · Knowledge Bank */
module.exports = {
"01":{
 flow:[["Problem","There is no single language, so no one can read all literature",null],
       ["A possible answer","(  ①  ) seems to solve the problem","translation"],
       ["Limit 1","The (  ②  ) when a work is born never comes back","moment"],
       ["Limit 2","Local colour means (  ③  ) to readers elsewhere","nothing"],
       ["Conclusion","A translation is not a copy but a (  ④  )","concession"]],
 flowBogi:"translation · moment · nothing · concession · copy · grammar",
 why:[["글의 배경일 뿐, 필자가 내리는 결론이 아니다"],["글은 번역이 매끄러운 ‘복사본’이 아니라고 말한다 — 정반대다"],
      ["정답"],["번역자가 되는 방법은 이 글에서 다루지 않는다"],["외국어 학습법은 글에 나오지 않는다"]],
 src:[["②"],["⑦"],["⑩과 어긋남 — 지역색은 함께 자란 사람에게만 생생하다"],["⑪"],["⑬"]],
 kb:{title:"번역이 바꿔 놓은 것들",lead:"한 낱말을 잘못 옮기면 무슨 일이 벌어질까?",
  items:[["화성에 운하가 있다고 믿은 100년",
   "1877년 이탈리아 천문학자 스키아파렐리는 화성 표면의 줄무늬를 ‘canali’(자연 수로)라고 적었다. 영어로 옮기는 과정에서 이 말이 ‘canals’(사람이 판 운하)가 되었고, 사람들은 화성인이 운하를 만들었다고 믿기 시작했다. 낱말 하나가 만든 오해였다."],
   ["옮길 말이 없는 낱말들",
    "일본어 tsundoku는 사서 읽지 않고 쌓아 둔 책을, 포르투갈어 saudade는 없는 것을 향한 그리움을, 독일어 Waldeinsamkeit는 숲속에 혼자 있는 느낌을 가리킨다. 영어에는 대응하는 한 낱말이 없어 설명으로 풀거나 그대로 들여온다."],
   ["가장 여러 언어로 건너간 이야기",
    "생텍쥐페리의 『어린 왕자』는 500개가 넘는 언어와 방언으로 번역되었다. 그만큼 여러 번 ‘양보’를 거친 셈이기도 하다."]],
  ask:"우리말에도 영어로 한 낱말로는 옮기기 어려운 말이 있다. 어떤 말이 떠오르는가?"}},
"02":{
 flow:[["Common belief","Seeing is believing — a photograph cannot lie",null],
       ["Why we believe it","Words are (  ①  ) by people, so they are not the thing","made"],
       ["Belief grows","An image seems to arrive (  ②  ), with nothing in the way","directly"],
       ["The turn","But someone (  ③  ) the angle, the light, and the moment","chose"],
       ["Conclusion","An image is a version of the thing, not the (  ④  )","thing"]],
 flowBogi:"made · directly · chose · thing · lie · grammar",
 why:[["글은 사진도 만들어진 것이라고 말한다 — 정반대다"],["말의 뜻이 사라졌다는 이야기는 나오지 않는다"],
      ["정답"],["마그리트의 취향이나 생애는 글의 주제가 아니다"],["영어 학습 방법은 글에 없다"]],
 src:[["④"],["⑤"],["⑦"],["⑩⑪과 어긋남 — 이미지도 누군가 만든 것이다"],["⑭"]],
 kb:{title:"사진은 언제부터 거짓말했을까",lead:"‘있는 그대로’처럼 보이는 이미지의 뒷면.",
  items:[["링컨의 유명한 초상은 합성 사진이다",
   "널리 알려진 링컨의 당당한 전신 초상은 링컨의 머리에 정치가 존 C. 칼훈의 몸을 붙여 만든 것이다. 사진이 발명된 지 20여 년 만에 이미 합성이 시작되었다."],
   ["화성의 ‘얼굴’",
    "1976년 바이킹 1호가 찍은 화성 사진에는 사람 얼굴을 닮은 바위가 있었다. 20년 뒤 고해상도로 다시 찍자 평범한 언덕이었다. 빛과 그림자, 그리고 얼굴을 찾으려는 우리 뇌가 만든 얼굴이었다."],
   ["《이미지의 배반》",
    "마그리트가 파이프를 그리고 ‘이것은 파이프가 아니다’라고 쓴 작품은 1929년작이다. 그는 “내 그림에 담배를 채워 넣을 수 있겠는가?”라고 되물었다."]],
  ask:"오늘 본 사진 중 ‘사실’이라고 믿은 것이 있는가? 그 사진을 찍은 사람은 무엇을 골랐을까?"}},
"03":{
 flow:[["Fact","Playing is physical work that needs reflex and (  ①  )","endurance"],
       ["Question","How can the long hours offstage serve the (  ②  ) hours onstage?","short"],
       ["The teacher's rule","In practice a perfectionist, in performance a (  ③  )","realist"],
       ["The writer's version","In practice an engineer, in performance a (  ④  )","pilot"],
       ["Conclusion","Without the bolts in place, we never leave the ground",null]],
 flowBogi:"endurance · short · realist · pilot · perfectionist · long",
 why:[["가장 어려운 곡이 무엇인지는 글에 나오지 않는다"],["자전거는 연습의 필요성을 보이는 비유일 뿐 주제가 아니다"],
      ["피아노 조율법은 글의 소재가 아니다"],["글은 무대에서는 완벽주의를 내려놓으라고 말한다 — 정반대다"],["정답"]],
 src:[["②③"],["⑦"],["⑩과 어긋남 — 엔지니어 비유는 필자가 새로 든 것이다"],["⑪"],["⑭"]],
 kb:{title:"무대 뒤에서 벌어지는 일",lead:"우리가 보지 못하는 시간에 관하여.",
  items:[["피아노 한 대에 부품 1만 2천 개",
   "스타인웨이 콘서트 그랜드 한 대는 1만 2천 개가 넘는 부품으로 이루어지고, 만드는 데 대략 1년이 걸린다. 글에 나오는 ‘너트와 볼트’는 과장이 아니다."],
   ["‘1만 시간’이라는 말의 원래 뜻",
    "이 말의 출발점인 에릭손의 1993년 연구는 시간의 양보다 ‘의도적 연습(deliberate practice)’, 곧 못하는 부분을 골라 고치는 연습의 질을 강조했다. 시간만 채우는 연습은 그가 말한 연습이 아니다."],
   ["조종사의 체크리스트가 생긴 이유",
    "1935년 시험 비행에서 최신 폭격기가 추락했다. 원인은 기계 결함이 아니라 잠금장치 하나를 푸는 절차를 빠뜨린 것이었다. 그 뒤 조종사 체크리스트가 표준이 되었다."]],
  ask:"내 공부에서 ‘너트와 볼트’에 해당하는 것은 무엇일까? 시험장에서 내려놓아야 할 것은?"}},
"04":{
 flow:[["Beginning","Aurora is born and Maleficent lays a (  ①  ) on her","curse"],
       ["The parents act","They burn every spinning wheel and (  ②  ) her in a forest","hide"],
       ["What it means","A world with no danger looks like protection, but (  ③  )","it is not"],
       ["Result","Sixteen years without risk leave her (  ④  )","weak"],
       ["Ending","After the curse is broken she grows into someone ready to take charge",null]],
 flowBogi:"curse · hide · it is not · weak · celebration · strong",
 why:[["마법은 사건일 뿐, 글이 말하려는 바가 아니다"],["정답"],
      ["저주를 푸는 방법은 글의 관심사가 아니다"],["잔치는 이야기의 도입일 뿐이다"],["물레의 역사는 글에 나오지 않는다"]],
 src:[["②③"],["④"],["⑤"],["⑨⑩과 어긋남 — 성으로 돌아온 뒤 저주가 실현된다"],["⑫⑬⑭"]],
 kb:{title:"‘잠자는 공주’의 뒷이야기",lead:"이야기는 시대마다 다시 쓰인다.",
  items:[["원래는 100년을 잤다",
   "1697년 샤를 페로가 정리한 판본에서 공주는 100년 동안 잠들고, 1812년 그림 형제 판본에서는 가시나무 울타리가 성을 뒤덮는다. 디즈니가 영화로 만든 것은 1959년이다."],
   ["‘헬리콥터 부모’라는 말의 출발",
    "1969년에 나온 하임 기너트의 책에서 한 십 대가 “엄마는 헬리콥터처럼 내 위를 맴돈다”고 말한 대목이 이 표현의 출발점으로 꼽힌다. 50년이 지나도 여전히 쓰이는 말이다."],
   ["위험이 없는 놀이터의 역설",
    "모든 위험 요소를 없앤 놀이터보다 적당한 도전이 있는 놀이터에서 아이들이 스스로 위험을 가늠하는 법을 배운다는 연구가 이어지고 있다. 안전과 성장은 늘 같은 방향이 아니다."]],
  ask:"나를 위해 누군가가 미리 치워 준 ‘물레’가 있었다면, 그것은 무엇이었을까?"}},
"05":{
 flow:[["Opening","Every field builds its own words and methods; literature is no exception",null],
       ["Help 1","Learning the (  ①  ) and history of literature changes what you get","context"],
       ["Help 2","Reading widely brings you books you would never have (  ②  ) alone","chosen"],
       ["The key step","After reading, you write about a work and (  ③  ) about it","talk"],
       ["Conclusion","Understanding grows in a process — literature is one long (  ④  )","conversation"]],
 flowBogi:"context · chosen · talk · conversation · lightning · method",
 why:[["읽어야 할 책 목록은 글에 나오지 않는다"],["어려운 용어가 필요하다는 주장은 하지 않는다"],
      ["글은 혼자 읽기만으로는 부족하다고 말한다 — 정반대다"],["정답"],["독후감 쓰는 요령은 글의 주제가 아니다"]],
 src:[["①"],["⑥"],["⑧과 어긋남 — 가장 중요한 단계는 읽기가 끝난 뒤에 온다"],["⑩"],["⑬"]],
 kb:{title:"함께 읽으면 달라지는 것",lead:"읽기는 언제부터 ‘대화’였을까.",
  items:[["살롱에서 시작된 문학 토론",
   "17~18세기 파리의 살롱에서는 작품을 소리 내어 읽고 그 자리에서 토론했다. 모임을 열고 이끈 사람은 대개 여성이었고, 이 자리에서 오간 말들이 그대로 다음 작품이 되기도 했다."],
   ["책 한 권을 베스트셀러로 만든 북클럽",
    "1996년 시작된 한 방송 북클럽이 책을 고르면 판매량이 수십 배로 뛰었다. 사람들은 책이 좋아서가 아니라 ‘함께 이야기할 사람이 생겨서’ 그 책을 샀다."],
   ["소리 내어 생각하며 읽기",
    "읽으면서 머릿속 생각을 말로 꺼내는 방법(think-aloud)은 독해 연구에서 오래 검증된 훈련이다. 혼자 읽을 때도 스스로에게 설명해 보면 이해가 달라진다."]],
  ask:"최근에 누군가와 이야기한 뒤 생각이 바뀐 책이나 영화가 있는가?"}}
};
