<persisted-output>
Output too large (53.2KB). Full output saved to: /root/.claude/projects/-home-user-hakmundang/b8546aae-5211-575f-825f-676b5ddc3b42/tool-results/toolu_01LKAXyM93AaCqVGugZ67BUJ.json

Preview (first 2KB):
[
  {
    "type": "text",
    "text": "import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LabelList } from \"recharts\";\nimport { SchoolData, SCHOOL_ICONS } from \"./SchoolForm\";\nimport { Trophy, GraduationCap, Award, Sparkles, Loader2, AlertTriangle, TrendingDown } from \"lucide-react\";\nimport { ReactNode, useEffect, useMemo, useState } from \"react\";\nimport { SCHOOL_LOGOS } from \"@/data/schoolLogos\";\nimport orunLogo from \"@/assets/orun-academy-logo.jpg.asset.json\";\nimport brainiacLogo from \"@/assets/brainiac-logo.png.asset.json\";\nimport { supabase } from \"@/integrations/supabase/client\";\n\ninterface AchievementChartProps {\n  middleSchools: SchoolData[];\n}\n\nconst GRADE_COLORS = {\n  A: \"hsl(220, 45%, 22%)\",\n  B: \"hsl(155, 28%, 42%)\",\n  C: \"hsl(265, 25%, 52%)\",\n  D: \"hsl(22, 55%, 55%)\",\n  E: \"hsl(355, 45%, 55%)\",\n};\n\nconst HIGH_SCHOOL_DATA = {\n  \"1등급\": 10,\n  \"2등급\": 24,\n  \"3등급\": 32,\n  \"4등급\": 24,\n  \"5등급\": 10,\n};\n\nconst HIGH_SCHOOL_COLORS = [\n  \"hsl(220, 45%, 22%)\",\n  \"hsl(155, 28%, 42%)\",\n  \"hsl(265, 25%, 52%)\",\n  \"hsl(22, 55%, 55%)\",\n  \"hsl(355, 45%, 55%)\",\n];\n\nconst GOLD = \"#b08d4f\";\nconst GOLD_LIGHT = \"#d4b87a\";\n\n// A4 page wrapper — 210mm x 297mm at 96dpi ≈ 794 × 1123 px\nconst A4Page = ({\n  children,\n  pageNumber,\n  total,\n  eyebrow,\n}: {\n  children: ReactNode;\n  pageNumber: number;\n  total: number;\n  eyebrow?: string;\n}) => (\n  <div\n    data-a4-page\n    className=\"a4-page relative bg-white mx-auto shadow-[0_8px_40px_-12px_rgba(28,25,23,0.18)] border border-stone-200/80 overflow-hidden\"\n    style={{ width: \"794px\", height: \"1123px\" }}\n  >\n    {/* page header rule */}\n    <div className=\"absolute top-0 left-0 right-0 px-14 pt-8 flex items-center justify-between text-[10px] tracking-[0.35em] uppercase text-stone-400\">\n      <span className=\"font-medium\" style={{ color: GOLD }}>\n        The Achievement Report\n      </span>\
...
</persisted-output>