
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpanpwbdlhsxnyaldddm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwYW5wd2JkbGhzeG55YWxkZGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4MDI2MzgsImV4cCI6MjA1MDM3ODYzOH0.lyofnzjEvGs0ZeAHmAK6mz_1ysNYryr70-eYbSpjEXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to recursively delete related records
export const deleteClassWithRelatedData = async (classId: string) => {
  try {
    // Delete test_schedules related to the class
    const { error: testSchedulesError } = await supabase
      .from('test_schedules')
      .delete()
      .eq('class_id', classId);
    
    if (testSchedulesError) throw testSchedulesError;

    // Delete curriculum_calendar entries for the class
    const { error: calendarError } = await supabase
      .from('curriculum_calendar')
      .delete()
      .eq('class_id', classId);
    
    if (calendarError) throw calendarError;

    // Delete manual_classes entries for the class
    const { error: manualClassesError } = await supabase
      .from('manual_classes')
      .delete()
      .eq('class_id', classId);
    
    if (manualClassesError) throw manualClassesError;

    // Delete progress_records for the class
    const { error: progressRecordsError } = await supabase
      .from('progress_records')
      .delete()
      .eq('class_id', classId);
    
    if (progressRecordsError) throw progressRecordsError;

    // Delete students in the class
    const { error: studentsError } = await supabase
      .from('students')
      .delete()
      .eq('class_id', classId);
    
    if (studentsError) throw studentsError;

    // Finally, delete the class itself
    const { error: classError } = await supabase
      .from('classes')
      .delete()
      .eq('id', classId);
    
    if (classError) throw classError;

    return { success: true };
  } catch (error) {
    console.error('Error deleting class with related data:', error);
    return { success: false, error };
  }
};
