/* Unit 1 READ RIGHT 표기 */
module.exports = {
 "01": [
  [["Literature","s"],["carries","v"],["feelings",null],["that","c"],["people everywhere","s2"],["can share.","v2"]],
  [["Yet","c"],["there",null],["is","v"],["no single language",null],["that","c"],["everyone in the world","s2"],["reads","v2"],["or","c"],["speaks.","v2"]],
  [["Each country","s"],["writes","v"],["its literature",null],["in its own tongue,","m"],["so","c"],["no reader","s2"],["can reach","v2"],["all of it.",null]],
  [["Translation","s"],["seems","v"],["to solve the problem.",null]],
  [["But","c"],["how faithful",null],["is","v"],["a translation","s"],["to the original?","m"]],
  [["A work","s"],["is born","v"],["at a moment of strong feeling,","m"],["when","c"],["the words","s2"],["flow","v2"],["under the writer's hand.","m"]],
  [["That moment","s"],["never",null],["comes back.","v"]],
  [["If","c"],["the writer","s2"],["cannot repeat","v2"],["it,",null],["a translator","s"],["in another country","m"],["certainly",null],["cannot reproduce","v"],["it.",null]],
  [["Literature","s"],["also",null],["has","v"],["a local colour.",null]],
  [["A word","s"],["may sound","v"],["bright and alive",null],["to people who grew up with it,","m"],["and","c"],["mean","v"],["almost nothing",null],["to everyone else.","m"]],
  [["A careful translator","s"],["knows","v"],["this",null],["and","c"],["chooses","v"],["the safest words",null],["instead.","m"]],
  [["The result","s"],["reads","v"],["smoothly,","m"],["but","c"],["something","s"],["has quietly been given up.","v"]],
  [["Moods, images, and even thoughts","s"],["are tied","v"],["to words;","m"],["once","c"],["the words","s2"],["change,","v2"],["the rest","s"],["changes","v"],["as well.","m"]],
  [["A translation,","s"],["then,","m"],["is not","v"],["a copy of a book.",null]],
  [["It","s"],["is","v"],["a concession.",null]]
 ],
 "02": [
  [["People","s"],["often",null],["say","v"],["that","c"],["seeing","s2"],["is","v2"],["believing.",null]],
  [["A photograph,","s"],["we feel,","m"],["cannot lie","v"],["the way","c"],["words","s2"],["can.","v2"]],
  [["Words","s"],["are clearly made","v"],["by people.","m"]],
  [["They","s"],["are","v"],["invented sounds,",null],["written with invented letters,","m"],["and",null],["joined by a grammar","m"],["that","c"],["a culture","s2"],["has agreed on.","v2"]],
  [["Everyone","s"],["who speaks English","m"],["understands","v"],["the word “food,”",null],["even though","c"],["each person","s2"],["pictures","v2"],["a different dish.",null]],
  [["Looser words","s"],["such as “cool”","m"],["change","v"],["their meaning",null],["again and again.","m"]],
  [["An image","s"],["feels","v"],["different.",null]],
  [["When","c"],["we","s2"],["see","v2"],["a thing,",null],["nothing","s"],["seems","v"],["to stand between us and it.",null]],
  [["The picture","s"],["appears","v"],["to arrive",null],["directly,","m"],["so","c"],["we","s2"],["treat","v2"],["it",null],["as reality itself.","m"]],
  [["But","c"],["an image","s"],["is made","v"],["too.","m"]],
  [["Someone","s"],["chose","v"],["the angle, the light, and the moment.",null]],
  [["Whether","c"],["it","s2"],["is painted, photographed, or built","v2"],["on a screen,","m"],["it","s"],["is","v"],["still",null],["a version of the thing, not the thing.",null]],
  [["The Belgian painter René Magritte","s"],["turned","v"],["this",null],["into a joke.","m"]],
  [["He","s"],["painted","v"],["a pipe",null],["and","c"],["wrote","v"],["underneath,","m"],["“This is not a pipe.”",null]],
  [["He","s"],["was","v"],["right:",null],["it","s"],["is","v"],["a picture of a pipe.",null]]
 ],
 "03": [
  [["Concert pianists","s"],["spend","v"],["far more of their lives",null],["practising",null],["than performing.","m"]],
  [["Playing the piano","s"],["is","v"],["not only remembering notes;",null],["it","s"],["is","v"],["physical work",null],["that","c"],["needs","v2"],["reflex and endurance.",null]],
  [["You","s"],["may never forget","v"],["how to ride a bicycle,",null],["but","c"],["if","c"],["your legs","s2"],["are","v2"],["out of shape",null],["you","s"],["will not finish","v"],["a race.",null]],
  [["So","c"],["the question","s"],["is","v"],["not whether to practise, but how to make the long hours offstage serve the short hours onstage.",null]],
  [["My teacher","s"],["used to say,","v"],["“In practice a perfectionist, in performance a realist.”",null]],
  [["At home,","m"],["prepare","v"],["endlessly.","m"]],
  [["On stage,","m"],["accept","v"],["what is in front of you.",null]],
  [["Do not wish","v"],["that","c"],["the piano","s2"],["were better tuned,","v2"],["or","c"],["the hall fuller,",null],["or","c"],["that","c"],["you","s2"],["had not missed","v2"],["that one passage.",null]],
  [["Being a realist","s"],["sounds","v"],["dull",null],["when","c"],["the job","s2"],["is","v2"],["to bring a great work to life.",null]],
  [["I","s"],["would put","v"],["it",null],["another way:","m"],["in practice an engineer, in performance a pilot.",null]],
  [["The bolts","s"],["of an aircraft","m"],["matter","v"],["enormously,","m"],["but","c"],["once","c"],["you","s2"],["sit","v2"],["in the cockpit","m"],["your eyes","s"],["look","v"],["ahead, not down.","m"]],
  [["We","s"],["practise","v"],["so that","c"],["we","s2"],["are","v2"],["free to fly",null],["wherever the music asks.","m"]],
  [["That destination","s"],["is made","v"],["of imagination, not of correct notes alone.","m"]],
  [["Yet","c"],["without the bolts in place,","m"],["we","s"],["never",null],["leave","v"],["the ground.",null]]
 ],
 "04": [
  [["In the film Sleeping Beauty,","m"],["a king and queen","s"],["finally",null],["have","v"],["a daughter, Aurora.",null]],
  [["They","s"],["plan","v"],["a great celebration",null],["and","c"],["welcome","v"],["everyone",null],["who","c"],["loves","v2"],["her —",null],["everyone except Maleficent.","m"]],
  [["She","s"],["comes","v"],["anyway","m"],["and","c"],["curses","v"],["the child:",null],["on her sixteenth birthday","m"],["Aurora","s"],["will prick","v"],["her finger",null],["on a spinning wheel","m"],["and","c"],["die.","v"]],
  [["A good fairy","s"],["softens","v"],["the curse",null],["into sleep,","m"],["which","c"],["love","s2"],["can undo.","v2"]],
  [["The frightened parents","s"],["burn","v"],["every spinning wheel in the kingdom",null],["and","c"],["hide","v"],["their daughter",null],["deep in a forest.","m"]],
  [["Notice","v"],["what the story is really describing.",null]],
  [["The two rulers","s"],["are building","v"],["a world",null],["around Aurora","m"],["with nothing dangerous in it.","m"]],
  [["It","s"],["looks","v"],["like protection,","m"],["but","c"],["it","s"],["is not.","v"]],
  [["Sixteen years","s"],["without risk","m"],["leave","v"],["her",null],["innocent, untested, and weak.",null]],
  [["When","c"],["she","s2"],["is finally brought back","v2"],["to the castle,","m"],["she","s"],["has","v"],["no way to face what is waiting there.",null]],
  [["A door","s"],["opens,","v"],["a spinning wheel","s"],["appears,","v"],["and","c"],["she","s"],["falls","v"],["asleep.",null]],
  [["Only after","c"],["the curse","s2"],["is broken","v2"],["does",null],["she","s"],["begin","v"],["to grow.",null]],
  [["At the end","m"],["she","s"],["is no longer","v"],["a girl",null],["kept safe by others.","m"]],
  [["She","s"],["is","v"],["someone",null],["ready to take charge of her own life.","m"]]
 ],
 "05": [
  [["Every field of study","s"],["builds","v"],["its own words and its own methods,",null],["and","c"],["literature","s"],["is","v"],["no exception.",null]],
  [["Knowing a few of them","s"],["changes","v"],["what you get from a book.",null]],
  [["Literature","s"],["also",null],["has","v"],["a context and a history.",null]],
  [["Learning a little about them","s"],["can change","v"],["how much pleasure and insight you take from a story.",null]],
  [["Reading widely","s"],["helps","v"],["too.","m"]],
  [["When","c"],["you","s2"],["read","v2"],["different kinds of writing,",null],["from different times and places,","m"],["you","s"],["often",null],["come to love","v"],["books",null],["you would never have chosen alone.","m"]],
  [["You","s"],["may even enjoy","v"],["books",null],["you would have misunderstood","m"],["if","c"],["you","s2"],["had read","v2"],["them",null],["by yourself.","m"]],
  [["But","c"],["the most important step","s"],["comes","v"],["after the reading.","m"]],
  [["Writing about a work, and talking about it with a teacher and with other students,","s"],["forces","v"],["you",null],["to look more closely and to consider views",null],["that","c"],["are not","v2"],["your own.",null]],
  [["A clear understanding","s"],["of what a story is doing","m"],["does not arrive","v"],["like lightning from a blue sky.","m"]],
  [["It","s"],["grows","v"],["out of a process.","m"]],
  [["You","s"],["try","v"],["to put into words why the book affected you,",null],["and","c"],["then","m"],["you","s"],["answer","v"],["what others say about it.",null]],
  [["Literature itself","s"],["is","v"],["one long conversation,",null],["and","c"],["you","s"],["join","v"],["it",null],["fully","m"],["only when you start talking.","m"]]
 ]
};
