/* Unit 2 READ RIGHT 표기 */
module.exports = {
 "06": [
  [["A cat","s"],["runs","v"],["to the kitchen","m"],["the moment","c"],["it","s2"],["hears","v2"],["a can open.",null]],
  [["A biologist and a psychologist","s"],["both","m"],["watch","v"],["this,",null],["and","c"],["both","s"],["ask","v"],["why.",null]],
  [["But","c"],["they","s"],["are not asking","v"],["the same question.",null]],
  [["The biologist","s"],["looks for","v"],["a mechanism.",null]],
  [["She","s"],["asks","v"],["which nerves carry the sound and how the muscles move.",null]],
  [["Her answer","s"],["is","v"],["a chain of causes",null],["that","c"],["anyone","s2"],["could measure","v2"],["with instruments.","m"]],
  [["The psychologist","s"],["looks for","v"],["a meaning.",null]],
  [["He","s"],["asks","v"],["what the cat expects and how a past meal shaped today's run.",null]],
  [["His answer","s"],["is","v"],["a story about experience rather than parts.",null]],
  [["Neither answer","s"],["is","v"],["wrong,",null],["and","c"],["neither","s"],["is","v"],["complete",null],["on its own.","m"]],
  [["A pure chain of chemicals","s"],["cannot explain","v"],["why","c"],["the cat","s2"],["ignores","v2"],["the same sound",null],["in a strange house.","m"]],
  [["A pure story about expectation","s"],["cannot explain","v"],["why","c"],["the cat","s2"],["still","m"],["runs","v2"],["when","c"],["it","s2"],["is not","v2"],["hungry.",null]],
  [["Science","s"],["makes","v"],["progress",null],["when","c"],["the two questions","s2"],["are allowed to meet.","v2"]],
  [["The best explanations","s"],["describe","v"],["both the machinery and the experience.",null]],
  [["To ask why well,","m"],["you","s"],["must first know","v"],["which why you mean.",null]]
 ],
 "07": [
  [["In 2020","m"],["a team at MIT","s"],["asked","v"],["forty adults",null],["to spend ten hours completely alone.","m"]],
  [["No phone, no message, no other person","s"],["entered","v"],["the room.",null]],
  [["On a different day","m"],["the same people","s"],["spent","v"],["ten hours",null],["without food.","m"]],
  [["After each day","m"],["the researchers","s"],["scanned","v"],["their brains.",null]],
  [["The hungry brain and the lonely brain","s"],["lit up","v"],["in almost the same place.","m"]],
  [["A small region","s"],["deep in the middle of the brain","m"],["became","v"],["active",null],["in both cases.","m"]],
  [["That region","s"],["also","m"],["becomes","v"],["active",null],["when","c"],["people","s2"],["want","v2"],["a drug or a reward.",null]],
  [["The researchers","s"],["called","v"],["the feeling",null],["a craving for company.",null]],
  [["The result","s"],["suggests","v"],["that","c"],["being with others","s2"],["is","v2"],["not a luxury but a need.",null]],
  [["Still,","m"],["a bright spot on a scan","s"],["is not","v"],["a feeling.",null]],
  [["The picture","s"],["shows","v"],["where","c"],["blood","s2"],["is moving,","v2"],["not what the person is thinking.","m"]],
  [["Forty people","s"],["is","v"],["also","m"],["a small number",null],["for such a large claim.","m"]],
  [["The study","s"],["is","v"],["a good beginning rather than a final answer.",null]],
  [["It","s"],["tells","v"],["us",null],["where to look next,",null],["which","c"],["is","v2"],["what a careful experiment should do.",null]],
  [["Science","s"],["often","m"],["starts","v"],["with a picture","m"],["and","c"],["then","m"],["asks","v"],["what the picture leaves out.",null]]
 ],
 "08": [
  [["Aristotle","s"],["divided","v"],["the world",null],["into two regions,","m"],["and","c"],["the line between them","s"],["was","v"],["the moon.",null]],
  [["Below the moon","m"],["everything","s"],["was made","v"],["of earth, water, air, and fire.","m"]],
  [["Things","s"],["down here","m"],["were born,","v"],["changed,","v"],["and","c"],["died.","v"]],
  [["Above the moon","m"],["he","s"],["placed","v"],["a fifth material",null],["that","c"],["could not change","v2"],["at all.","m"]],
  [["The stars","s"],["were made","v"],["of it,","m"],["so","c"],["they","s2"],["could only turn","v2"],["in perfect circles for ever.","m"]],
  [["This picture","s"],["matched","v"],["what people saw every night.",null]],
  [["Fire","s"],["rose,","v"],["stones","s"],["fell,","v"],["and","c"],["the stars","s"],["kept","v"],["the same shapes",null],["year after year.","m"]],
  [["For almost two thousand years","m"],["the two regions","s"],["were treated","v"],["as settled fact.","m"]],
  [["Then","m"],["in 1572","m"],["a new star","s"],["appeared","v"],["in the sky","m"],["and","c"],["stayed","v"],["for months.","m"]],
  [["Tycho Brahe","s"],["measured","v"],["it",null],["carefully","m"],["and","c"],["found","v"],["that","c"],["it","s2"],["stood","v2"],["far beyond the moon.","m"]],
  [["Something in the changeless region","s"],["had changed.","v"]],
  [["Later","m"],["Galileo","s"],["turned","v"],["a telescope",null],["on the moon","m"],["and","c"],["saw","v"],["mountains and shadows.",null]],
  [["The perfect sphere","s"],["had","v"],["a rough surface,",null],["like the ground under his feet.","m"]],
  [["The old picture","s"],["had not been","v"],["foolish,",null],["because","c"],["it","s2"],["explained","v2"],["what the eye could reach.",null]],
  [["It","s"],["fell","v"],["only","m"],["when","c"],["the eye","s2"],["was given","v2"],["a better instrument.",null]]
 ],
 "09": [
  [["Ask","v"],["anyone",null],["whether they know how a zipper works.",null]],
  [["Almost everyone","s"],["says","v"],["yes",null],["without pausing.","m"]],
  [["Then","m"],["ask","v"],["them",null],["to explain it","m"],["step by step,","m"],["out loud,","m"],["without using their hands.","m"]],
  [["The confident voice","s"],["slows down,","v"],["searches for","v"],["words,",null],["and","c"],["often","m"],["stops","v"],["altogether.","m"]],
  [["Psychologists","s"],["call","v"],["this gap",null],["the illusion of explanatory depth.",null]],
  [["We","s"],["mistake","v"],["being familiar with something",null],["for understanding it.","m"]],
  [["A zipper","s"],["is","v"],["close to us",null],["every day,","m"],["so","c"],["the feeling of knowing","s2"],["comes","v2"],["easily.","m"]],
  [["In one study","m"],["people","s"],["were asked","v"],["to draw a bicycle",null],["from memory,","m"],["with the frame and chain in place.","m"]],
  [["Many","s"],["drew","v"],["chains",null],["that","c"],["could never turn","v2"],["the wheels.",null]],
  [["The drawings","s"],["were","v"],["wrong",null],["in ways the artists had never noticed.","m"]],
  [["The illusion","s"],["is not","v"],["a sign of a lazy mind.",null]],
  [["It","s"],["is","v"],["useful,",null],["because","c"],["we","s2"],["cannot carry","v2"],["full explanations of every object we touch.",null]],
  [["The danger","s"],["appears","v"],["when","c"],["the same easy feeling","s2"],["reaches","v2"],["much larger questions about the world.",null]],
  [["People","s"],["who","c"],["have never explained","v2"],["a policy",null],["still","m"],["argue","v"],["about it","m"],["with certainty.","m"]],
  [["One cure","s"],["is","v"],["simple:",null],["try","v"],["to explain the thing,",null],["and","c"],["let","v"],["the gap show itself.",null]]
 ],
 "10": [
  [["People","s"],["often","m"],["use","v"],["the word skeptic",null],["to mean someone","m"],["who","c"],["refuses","v2"],["to believe.",null]],
  [["In science","m"],["the word","s"],["means","v"],["almost the opposite.",null]],
  [["A skeptic","s"],["does not close","v"],["the question;",null],["a skeptic","s"],["asks","v"],["what would settle it.",null]],
  [["The rule behind this habit","s"],["is","v"],["simple to state,",null],["though","c"],["it","s2"],["is","v2"],["harder to live by.",null]],
  [["The stronger","c"],["a claim","s"],["is,","v"],["the heavier","c"],["the evidence",null],["it has to carry.","m"]],
  [["A report","s"],["that","c"],["a train","s2"],["was","v2"],["late",null],["needs","v"],["little more than a timetable and a witness.",null]],
  [["A report","s"],["that","c"],["a train","s2"],["travelled","v2"],["faster than light","m"],["needs","v"],["far more.",null]],
  [["This","s"],["is not","v"],["unfairness;",null],["it","s"],["is","v"],["bookkeeping.",null]],
  [["Ordinary claims","s"],["fit","v"],["neatly","m"],["into the world we have already measured and written down.","m"]],
  [["Extraordinary ones","s"],["ask","v"],["us",null],["to pull down and rebuild part of that world.","m"]],
  [["In 2011","m"],["a laboratory","s"],["announced","v"],["particles",null],["that","c"],["seemed","v2"],["to beat light.",null]],
  [["Other teams","s"],["did not shout,","v"],["and","c"],["they","s"],["did not stay","v"],["silent",null],["either.","m"]],
  [["They","s"],["repeated","v"],["the measurement",null],["and","c"],["found","v"],["a loose cable",null],["in the timing system.","m"]],
  [["The claim","s"],["fell,","v"],["and","c"],["no one","s"],["had to be called","v"],["a liar.",null]],
  [["Doubt","s"],["had done","v"],["its work",null],["quietly,","m"],["the way","c"],["it","s2"],["is supposed to.","v2"]]
 ]
};
