/* Unit 3 READ RIGHT 표기 */
module.exports = {
 "11": [
  [["A subway map","s"],["shows","v"],["straight lines and even spaces between stations.",null]],
  [["The real tunnels","s"],["curve,","v"],["and","c"],["the distances","s"],["are never","v"],["equal.",null]],
  [["The map","s"],["lies","v"],["about the ground,","m"],["and","c"],["that","s"],["is","v"],["exactly why it works.",null]],
  [["It","s"],["answers","v"],["one question",null],["well:","m"],["which train takes you where.",null]],
  [["Economic models","s"],["are built","v"],["in the same spirit.","m"]],
  [["A model of a market","s"],["may assume","v"],["that","c"],["every buyer","s2"],["knows","v2"],["every price.",null]],
  [["No real shopper","s"],["knows","v"],["that,",null],["and","c"],["the modeller","s"],["knows","v"],["it",null],["too.","m"]],
  [["The assumption","s"],["is","v"],["not a mistake but a tool for holding one thing still.",null]],
  [["By freezing information,","m"],["the model","s"],["can show","v"],["what","c"],["supply and demand alone","s2"],["would do.","v2"]],
  [["Trouble","s"],["begins","v"],["when","c"],["people","s2"],["forget","v2"],["which parts were frozen on purpose.",null]],
  [["A map","s"],["drawn for trains","m"],["cannot tell","v"],["you",null],["where to find a quiet street.",null]],
  [["In 2008","m"],["several models","s"],["assumed","v"],["that","c"],["house prices","s2"],["could not fall","v2"],["everywhere","m"],["at once.","m"]],
  [["The assumption","s"],["had been","v"],["useful",null],["for years,","m"],["and","c"],["then","m"],["it","s"],["was not.","v"]],
  [["A good reader of models","s"],["asks","v"],["what was left out",null],["before asking what was proved.","m"]],
  [["Every model","s"],["is","v"],["a map,",null],["and","c"],["no map","s"],["is","v"],["the city.",null]]
 ],
 "12": [
  [["Most jokes","s"],["work","v"],["by building one meaning and then swapping it for another.","m"]],
  [["The listener","s"],["follows","v"],["a path,",null],["and","c"],["the last word","s"],["moves","v"],["the ground under it.",null]],
  [["Nothing","s"],["is","v"],["funny",null],["about the words themselves,","m"],["taken one at a time.","m"]],
  [["The laugh","s"],["comes","v"],["from the sudden repair","m"],["the mind has to make.","m"]],
  [["This","s"],["is","v"],["why","c"],["a joke","s2"],["dies","v2"],["when","c"],["you","s2"],["explain","v2"],["it.",null]],
  [["Explanation","s"],["does","v"],["the repair",null],["for the listener,","m"],["and","c"],["the work","s"],["is","v"],["what was enjoyable.",null]],
  [["Timing","s"],["matters","v"],["for the same reason,","m"],["and","c"],["every comedian","s"],["learns","v"],["it",null],["early.","m"]],
  [["A pause","s"],["holds","v"],["the first meaning",null],["in place","m"],["until","c"],["it","s2"],["is","v2"],["heavy enough to drop.",null]],
  [["Jokes","s"],["also","m"],["carry","v"],["a quiet social test",null],["that","c"],["nobody","s2"],["announces.","v2"]],
  [["To laugh,","m"],["you","s"],["must share","v"],["the knowledge",null],["the joke assumes.","m"]],
  [["A joke about a school rule","s"],["means","v"],["nothing",null],["to someone outside that school.","m"]],
  [["So","c"],["laughing together","s"],["is","v"],["partly","m"],["a way of saying we know the same things.",null]],
  [["That","s"],["is","v"],["why","c"],["humour","s2"],["can bind","v2"],["a group",null],["and","c"],["shut","v2"],["others",null],["out in the same breath.","m"]],
  [["Comedians","s"],["know","v"],["both effects",null],["and","c"],["choose","v"],["which one they want.",null]],
  [["A joke","s"],["is never","v"],["only a joke.",null]]
 ],
 "13": [
  [["People","s"],["often","m"],["say","v"],["that","c"],["numbers","s2"],["speak","v2"],["for themselves","m"],["and","c"],["settle","v2"],["an argument.",null]],
  [["They","s"],["do not;","v"],["someone","s"],["always","m"],["chooses","v"],["which numbers to show.",null]],
  [["Imagine","v"],["a school",null],["that","c"],["proudly","m"],["reports","v2"],["higher test scores",null],["this year than last.","m"]],
  [["The figure","s"],["is","v"],["true,",null],["and","c"],["it","s"],["still","m"],["hides","v"],["several decisions.",null]],
  [["Which students","s"],["were counted,","v"],["and","c"],["which","s"],["had already left?","v"]],
  [["Was","v"],["the test","s"],["the same one,",null],["and","c"],["was","v"],["it","s"],["marked","v"],["the same way?","m"]],
  [["None of these questions","s"],["accuse","v"],["anyone",null],["of lying.","m"]],
  [["They","s"],["only","m"],["remind","v"],["us",null],["that","c"],["a number","s2"],["arrives","v2"],["with a history.","m"]],
  [["The same problem","s"],["appears","v"],["in charts,","m"],["where","c"],["the shape of a line","s2"],["does","v2"],["the arguing.",null]],
  [["A line","s"],["that","c"],["starts","v2"],["at ninety instead of zero","m"],["makes","v"],["a small rise",null],["look steep.",null]],
  [["Nothing in the data","s"],["has changed,","v"],["but","c"],["the reader's eye","s"],["has been steered.","v"]],
  [["Careful writers","s"],["therefore","m"],["report","v"],["how the data was gathered,",null],["not only what it shows.","m"]],
  [["Careful readers","s"],["ask","v"],["what a number would look like from the other side.",null]],
  [["Honesty with data","s"],["is","v"],["less about the figures than about the choices behind them.",null]],
  [["A number","s"],["is","v"],["an answer,",null],["and","c"],["every answer","s"],["had","v"],["a question",null],["first.","m"]]
 ],
 "14": [
  [["Try","v"],["writing down the rule",null],["that","c"],["tells","v2"],["a dog",null],["from a cat.","m"]],
  [["Every rule","s"],["you write","m"],["will fail","v"],["on some real animal.","m"]],
  [["A neural network","s"],["is never handed","v"],["such a rule",null],["at any point.","m"]],
  [["It","s"],["is shown","v"],["thousands of labelled pictures",null],["instead.","m"]],
  [["Inside,","m"],["numbers","s"],["pass","v"],["through layers,","m"],["and","c"],["each layer","s"],["passes on","v"],["what it found.",null]],
  [["Early layers","s"],["notice","v"],["edges;",null],["later ones","s"],["notice","v"],["ears, eyes, and shapes.",null]],
  [["When","c"],["the answer","s2"],["is","v2"],["wrong,",null],["the network","s"],["changes","v"],["its numbers",null],["a little.","m"]],
  [["Repeat","v"],["this",null],["millions of times","m"],["and","c"],["the guesses","s"],["grow","v"],["accurate.",null]],
  [["But","c"],["the network","s"],["has learned","v"],["the pattern in its examples,",null],["not the world.","m"]],
  [["Feed","v"],["it",null],["only photographs",null],["taken outdoors","m"],["and","c"],["it","s"],["may quietly learn","v"],["about grass.","m"]],
  [["Such a system","s"],["can be","v"],["right",null],["for a reason","m"],["nobody chose and nobody checked.","m"]],
  [["It","s"],["also","m"],["cannot say","v"],["in plain words","m"],["why it answered as it did.",null]],
  [["The numbers","s"],["are","v"],["visible,",null],["yet","c"],["no sentence","s"],["explains","v"],["them.",null]],
  [["This","s"],["is","v"],["why","c"],["careful teams","s2"],["test","v2"],["a model",null],["on cases","m"],["it has never seen.","m"]],
  [["A machine","s"],["that","c"],["guesses","v2"],["well","m"],["is not","v"],["the same as a machine",null],["that","c"],["knows.","v2"]]
 ],
 "15": [
  [["A feed","s"],["is not","v"],["a window;",null],["it","s"],["is","v"],["a selection.",null]],
  [["Software","s"],["watches","v"],["what you stop to read",null],["and","c"],["offers","v"],["more of the same.",null]],
  [["The aim behind that choice","s"],["is","v"],["simple,",null],["and","c"],["it","s"],["is not","v"],["agreement.",null]],
  [["The aim","s"],["is","v"],["attention,",null],["because","c"],["attention","s2"],["is","v2"],["what advertisers pay for.",null]],
  [["Posts","s"],["that","c"],["make","v2"],["people angry",null],["hold","v"],["attention",null],["very well.","m"]],
  [["So","c"],["the calmest account of an issue","s"],["is","v"],["rarely","m"],["the one",null],["that","c"],["spreads.","v2"]],
  [["Over months","m"],["the feed","s"],["narrows","v"],["without ever announcing it.","m"]],
  [["You","s"],["still","m"],["see","v"],["disagreement,",null],["but mostly the weakest version of it.",null]],
  [["The other side","s"],["arrives","v"],["already made to look foolish.","m"]],
  [["This","s"],["is","v"],["in one way","m"],["worse than never meeting the other side at all.",null]],
  [["A reader","s"],["who","c"],["has seen","v2"],["only weak arguments",null],["believes","v"],["the question","s2"],["is settled.","v2"]],
  [["Researchers","s"],["disagree","v"],["about how strong this effect is in practice.","m"]],
  [["Some studies","s"],["find","v"],["that","c"],["most people","s2"],["still","m"],["meet","v2"],["a fairly wide mix of views.",null]],
  [["Even so,","m"],["the machine","s"],["has","v"],["a direction,",null],["and","c"],["the direction","s"],["is not","v"],["neutral.",null]],
  [["Knowing that the room was arranged","s"],["is","v"],["the first step out of it.",null]]
 ]
};
