/* Unit 4 READ RIGHT 표기 */
module.exports = {
 "16": [
  [["When","c"],["a plane","s2"],["lands,","v2"],["you","s"],["change","v"],["your watch",null],["in one second.","m"]],
  [["Your body","s"],["needs","v"],["about a week",null],["to do the same thing.","m"]],
  [["Deep in the brain","m"],["sits","v"],["a group of cells","s"],["that","c"],["keeps","v2"],["its own time.",null]],
  [["This clock","s"],["runs","v"],["on a cycle of roughly twenty-four hours","m"],["even in total darkness.","m"]],
  [["Light","s"],["is","v"],["the main signal",null],["that","c"],["keeps","v2"],["it matched to the world outside.",null]],
  [["Morning light","s"],["pushes","v"],["the clock",null],["earlier;","m"],["evening light","s"],["pushes","v"],["it",null],["later.","m"]],
  [["Flying east","s"],["asks","v"],["the body",null],["to fall asleep","m"],["before","c"],["it","s2"],["is","v2"],["ready.",null]],
  [["Flying west","s"],["only","m"],["asks","v"],["it",null],["to stay up longer,","m"],["which","c"],["is","v2"],["far easier.",null]],
  [["This","s"],["is","v"],["why the same distance can feel very different in the two directions.",null]],
  [["The body","s"],["shifts","v"],["by about one hour a day,","m"],["and","c"],["it","s"],["cannot be hurried","v"],["much.","m"]],
  [["Still,","m"],["the shift","s"],["can be helped","v"],["instead of fought.","m"]],
  [["Travellers","s"],["who","c"],["seek","v2"],["morning light",null],["in the east","m"],["recover","v"],["faster","m"],["than those","m"],["who","c"],["hide","v2"],["indoors.","m"]],
  [["Eating and sleeping","s"],["on the new clock","m"],["also","m"],["give","v"],["the body",null],["a clearer signal.",null]],
  [["None of this","s"],["removes","v"],["jet lag,",null],["and","c"],["no habit","s"],["makes","v"],["the cells move faster.",null]],
  [["It","s"],["only","m"],["lines up","v"],["the signals",null],["so","c"],["the clock","s2"],["is not pulled","v2"],["two ways at once.","m"]]
 ],
 "17": [
  [["Before anaesthesia,","m"],["speed","s"],["was","v"],["the greatest surgical skill.",null]],
  [["A leg","s"],["could be removed","v"],["in under a minute,","m"],["and","c"],["the patient","s"],["screamed","v"],["throughout.","m"]],
  [["Once","c"],["patients","s2"],["could be put","v2"],["to sleep,","m"],["that reason for hurry","s"],["disappeared.","v"]],
  [["Many surgeons","s"],["kept","v"],["hurrying",null],["anyway,","m"],["because","c"],["habit","s2"],["is","v2"],["slower to change than knowledge.",null]],
  [["William Halsted","s"],["worked","v"],["in the other direction.","m"]],
  [["He","s"],["handled","v"],["tissue",null],["gently,","m"],["closed","v"],["wounds",null],["in layers,","m"],["and","c"],["took","v"],["as long","m"],["as","c"],["the work","s2"],["needed.","v2"]],
  [["His operations","s"],["were","v"],["slow,",null],["and","c"],["his patients","s"],["survived","v"],["more often.","m"]],
  [["He","s"],["also","m"],["changed","v"],["the room itself.",null]],
  [["When","c"],["a nurse's hands","s2"],["were harmed","v2"],["by the cleaning fluid,","m"],["he","s"],["had","v"],["thin rubber gloves made for her.",null]],
  [["The gloves","s"],["were meant","v"],["for her skin,","m"],["not for the patient.","m"]],
  [["Only later","m"],["did","v"],["the profession","s"],["see","v"],["that","c"],["they","s2"],["kept","v2"],["the wound cleaner",null],["too.","m"]],
  [["Halsted's largest change","s"],["was","v"],["in training rather than technique.","m"]],
  [["He","s"],["built","v"],["a long residency",null],["in which","c"],["young doctors","s2"],["treated","v2"],["patients",null],["under watch","m"],["for years.","m"]],
  [["The idea","s"],["that","c"],["a surgeon","s2"],["is made","v2"],["slowly,","m"],["not born,","m"],["came","v"],["from that programme.","m"]],
  [["Modern hospitals","s"],["still","m"],["run","v"],["on the shape he gave them.","m"]]
 ],
 "18": [
  [["A virus","s"],["is","v"],["a set of instructions",null],["wrapped in a coat of protein.","m"]],
  [["On its own","m"],["it","s"],["does","v"],["nothing",null],["at all.","m"]],
  [["It","s"],["does not eat,","v"],["it","s"],["does not grow,","v"],["and","c"],["it","s"],["cannot copy","v"],["itself",null],["even once.","m"]],
  [["Left on a doorknob,","m"],["it","s"],["simply","m"],["waits,","v"],["sometimes for hours.","m"]],
  [["Everything","s"],["changes","v"],["the moment","c"],["it","s2"],["meets","v2"],["a suitable cell.",null]],
  [["It","s"],["enters,","v"],["hands over","v"],["its instructions,",null],["and","c"],["the cell","s"],["obediently","m"],["begins","v"],["building new viruses.",null]],
  [["The machinery","s"],["is borrowed;","v"],["only","m"],["the plan","s"],["belongs","v"],["to the virus.","m"]],
  [["This","s"],["is","v"],["why biologists have argued for a century about whether viruses are alive.",null]],
  [["By most definitions","m"],["they","s"],["fail,","v"],["because","c"],["they","s2"],["cannot reproduce","v2"],["without help.","m"]],
  [["Yet","c"],["they","s"],["evolve,","v"],["they","s"],["carry","v"],["genes,",null],["and","c"],["they","s"],["shape","v"],["every living thing around them.",null]],
  [["The argument","s"],["is not","v"],["merely","m"],["a matter of words.",null]],
  [["How we classify something","s"],["decides","v"],["which tools","c"],["we","s2"],["reach for.","v2"]],
  [["A medicine","s"],["that","c"],["attacks","v2"],["living cells",null],["will not touch","v"],["a set of instructions.",null]],
  [["Vaccines","s"],["work","v"],["differently:","m"],["they","s"],["teach","v"],["the body",null],["to recognise the coat.",null]],
  [["The border of life","s"],["turns out","v"],["to be a place",null],["where","c"],["useful questions","s2"],["live.","v2"]]
 ],
 "19": [
  [["In 1854","m"],["cholera","s"],["was killing","v"],["people",null],["in a London street,","m"],["and","c"],["nobody","s"],["knew","v"],["why.",null]],
  [["John Snow","s"],["marked","v"],["each death",null],["on a map","m"],["and","c"],["watched","v"],["a pattern appear.",null]],
  [["The deaths","s"],["gathered","v"],["tightly","m"],["around a single water pump on Broad Street.","m"]],
  [["He","s"],["asked","v"],["the council",null],["to remove the pump handle,","m"],["and","c"],["the outbreak","s"],["faded.","v"]],
  [["Snow","s"],["could not see","v"],["the bacterium;",null],["the microscope work","s"],["came","v"],["later.","m"]],
  [["He","s"],["only","m"],["needed","v"],["to see where the sick people had been drinking their water.",null]],
  [["Prevention","s"],["often","m"],["works","v"],["like this,","m"],["without a full explanation.","m"]],
  [["It","s"],["also","m"],["works","v"],["invisibly,","m"],["which","c"],["is","v2"],["its lasting political problem.",null]],
  [["A cure","s"],["produces","v"],["a grateful patient",null],["who","c"],["can be photographed and thanked","v2"],["in public.","m"]],
  [["Prevention","s"],["produces","v"],["a person",null],["who","c"],["never","m"],["became","v2"],["a patient",null],["at all.","m"]],
  [["No one","s"],["thanks","v"],["a clean pipe,",null],["and","c"],["no one","s"],["remembers","v"],["the illness they did not get.",null]],
  [["So","c"],["budgets for prevention","s"],["are cut","v"],["first","m"],["and","c"],["restored","v"],["last.","m"]],
  [["The pattern","s"],["repeats","v"],["in every century,","m"],["under every kind of government.","m"]],
  [["Public health","s"],["is","v"],["the strange field",null],["where","c"],["success","s2"],["looks","v2"],["like nothing happening.","m"]],
  [["Learning to value that emptiness","s"],["is","v"],["harder",null],["than learning the science.","m"]]
 ],
 "20": [
  [["Medical training","s"],["long","m"],["treated","v"],["exhaustion",null],["as a badge rather than a risk.","m"]],
  [["Young doctors","s"],["worked","v"],["thirty hours","m"],["at a stretch","m"],["and","c"],["were openly praised","v"],["for it.","m"]],
  [["The reasoning","s"],["sounded","v"],["noble:",null],["patients","s"],["need","v"],["someone",null],["who","c"],["never","m"],["leaves.","v2"]],
  [["Sleep research,","s"],["gathered over several decades,","m"],["told","v"],["a different story.",null]],
  [["After about seventeen hours awake,","m"],["performance","s"],["falls","v"],["to the level of mild drunkenness.","m"]],
  [["Attention","s"],["narrows,","v"],["and","c"],["errors of the careless kind","s"],["become","v"],["far more likely.",null]],
  [["A tired doctor","s"],["is not","v"],["lazy;",null],["a tired brain","s"],["simply","m"],["works","v"],["worse.","m"]],
  [["When","c"],["hospitals","s2"],["shortened","v2"],["shifts,",null],["serious mistakes","s"],["dropped","v"],["in several studies.","m"]],
  [["But","c"],["shorter shifts","s"],["create","v"],["a new danger",null],["at every handover.","m"]],
  [["Each time","c"],["one doctor","s2"],["passes","v2"],["a patient",null],["to another,","m"],["information","s"],["can be lost.","v"]],
  [["So","c"],["the answer to the problem","s"],["was never","v"],["simply","m"],["fewer hours on the ward.",null]],
  [["It","s"],["was","v"],["fewer hours plus a written, spoken, checked handover.",null]],
  [["Naming exhaustion a personal weakness","s"],["had hidden","v"],["a design problem",null],["for a century.","m"]],
  [["Systems","s"],["that","c"],["depend","v2"],["on nobody ever being tired","m"],["are","v"],["badly built.",null]],
  [["Good design","s"],["assumes","v"],["the human being it actually has.",null]]
 ]
};
