/* Unit 5 READ RIGHT 표기 */
module.exports = {
 "21": [
  [["Scholars","s"],["who","c"],["study","v2"],["religion",null],["often","m"],["begin","v"],["with a question","m"],["that","c"],["sounds","v2"],["odd.",null]],
  [["They","s"],["ask","v"],["not whether a belief is true, but what the belief does.",null]],
  [["A ritual","s"],["gathers","v"],["people",null],["at the same hour","m"],["and","c"],["asks","v"],["them",null],["to move together.",null]],
  [["Standing, kneeling, singing the same line —","m"],["the body","s"],["learns","v"],["before","c"],["the mind","s2"],["agrees.","v2"]],
  [["Emile Durkheim","s"],["argued","v"],["that","c"],["such moments","s2"],["make","v2"],["a group feel like one thing.",null]],
  [["The feeling","s"],["is","v"],["real",null],["even for those","m"],["who","c"],["cannot explain","v2"],["it",null],["afterwards.","m"]],
  [["Rituals","s"],["also","m"],["cut","v"],["time",null],["into pieces","m"],["that","c"],["a person","s2"],["can hold.","v2"]],
  [["A week","s"],["has","v"],["a shape",null],["because","c"],["something","s2"],["returns","v2"],["on the seventh day.","m"]],
  [["Birth, marriage, and death","s"],["are marked","v"],["so that","c"],["they","s2"],["are not simply endured.","v2"]],
  [["Beliefs","s"],["carry","v"],["memory",null],["as well,","m"],["storing what a community wants to keep.","m"]],
  [["A story","s"],["repeated for centuries","m"],["outlives","v"],["the people",null],["who","c"],["first","m"],["told","v2"],["it.",null]],
  [["None of this","s"],["settles","v"],["the question of whether the beliefs are true.",null]],
  [["That","s"],["is","v"],["a separate question,",null],["and","c"],["a different kind of evidence","s"],["answers","v"],["it.",null]],
  [["But","c"],["the social work","s"],["is","v"],["visible,",null],["and","c"],["it","s"],["can be studied","v"],["like any other pattern.","m"]],
  [["Asking what a practice does","s"],["is not","v"],["the same",null],["as judging it.","m"]]
 ],
 "22": [
  [["Darwin's account","s"],["explains","v"],["how living forms changed over long stretches of time.",null]],
  [["It","s"],["describes","v"],["variation, inheritance, and the slow filtering of survival.",null]],
  [["That","s"],["is","v"],["an answer to a question about mechanism.",null]],
  [["Many arguments","s"],["treat","v"],["it",null],["as an answer to a different question altogether.","m"]],
  [["They","s"],["read","v"],["it",null],["as a claim about what human life is for.","m"]],
  [["But","c"],["a description of how something came about","s"],["does not tell","v"],["us",null],["how to live.",null]],
  [["Philosophers","s"],["call","v"],["this gap",null],["the difference between is and ought.",null]],
  [["No list of facts,","s"],["however long,","m"],["produces","v"],["a duty",null],["on its own.","m"]],
  [["The gap","s"],["runs","v"],["in both directions,","m"],["which","c"],["is","v2"],["easy to forget.",null]],
  [["A moral conviction","s"],["cannot decide","v"],["what happened in the fossil record",null],["either.","m"]],
  [["Recognising the gap","s"],["does not end","v"],["disagreement,",null],["and","c"],["it","s"],["is not meant","v"],["to.",null]],
  [["People","s"],["still","m"],["differ","v"],["deeply","m"],["about meaning,","m"],["and","c"],["those differences","s"],["are","v"],["real.",null]],
  [["What the gap does","s"],["is","v"],["keep two questions from being mistaken for one.",null]],
  [["A biologist and a believer","s"],["may be answering","v"],["different questions",null],["entirely.","m"]],
  [["Much heat","s"],["is produced","v"],["by arguments","m"],["that","c"],["were","v2"],["never","m"],["about the same thing.","m"]]
 ],
 "23": [
  [["In ancient Athens,","m"],["a citizen","s"],["who","c"],["could speak","v2"],["well","m"],["could change","v"],["his own life.",null]],
  [["Courts","s"],["had","v"],["no lawyers,",null],["so","c"],["each man","s2"],["argued","v2"],["his case",null],["himself.","m"]],
  [["Teachers","s"],["appeared","v"],["who","c"],["promised","v2"],["to make any student persuasive.",null]],
  [["They","s"],["were called","v"],["sophists,",null],["and","c"],["at first","m"],["the word","s"],["was not","v"],["an insult.",null]],
  [["They","s"],["taught","v"],["structure, timing, and the art of anticipating an objection.",null]],
  [["Much of that teaching","s"],["is","v"],["still","m"],["sound,",null],["and","c"],["debate classes","s"],["use","v"],["it",null],["today.","m"]],
  [["The trouble","s"],["began","v"],["with a further promise.","m"]],
  [["Some","s"],["claimed","v"],["they","s2"],["could make","v2"],["the weaker argument appear the stronger.",null]],
  [["Plato","s"],["attacked","v"],["this",null],["fiercely,","m"],["and","c"],["the word","s"],["has carried","v"],["his scorn",null],["ever since.","m"]],
  [["His complaint","s"],["was not","v"],["that","c"],["persuasion","s2"],["is","v2"],["bad.",null]],
  [["It","s"],["was","v"],["that","c"],["a skill","s2"],["aimed only at winning","m"],["has","v2"],["no reason to stop at the truth.",null]],
  [["The same tools","s"],["that","c"],["clarify","v2"],["a good case",null],["can dress up","v"],["a poor one.",null]],
  [["This","s"],["is","v"],["why we teach argument and evidence together rather than separately.",null]],
  [["A student","s"],["who","c"],["learns","v2"],["only","m"],["to win",null],["becomes","v"],["harder to correct, not easier.",null]],
  [["Rhetoric","s"],["is","v"],["a tool,",null],["and","c"],["tools","s"],["take","v"],["the direction the hand gives them.",null]]
 ],
 "24": [
  [["Epictetus","s"],["was born","v"],["a slave",null],["and","c"],["taught","v"],["philosophy",null],["after","c"],["he","s2"],["was freed.","v2"]],
  [["His starting point","s"],["was","v"],["a single division.",null]],
  [["Some things","s"],["are","v"],["up to us,",null],["and","c"],["some things","s"],["are not.","v"]],
  [["Our judgements and our efforts","s"],["belong","v"],["to the first group.","m"]],
  [["Our reputation, our health, and the weather","s"],["belong","v"],["to the second.","m"]],
  [["Suffering,","s"],["he argued,",null],["comes","v"],["from treating the second group","m"],["as if","c"],["it","s2"],["were","v2"],["the first.",null]],
  [["A runner","s"],["who","c"],["demands","v2"],["victory",null],["has staked","v"],["himself",null],["on what he cannot control.","m"]],
  [["A runner","s"],["who","c"],["demands","v2"],["good training",null],["has staked","v"],["himself",null],["on what he can.","m"]],
  [["The second runner","s"],["may still lose,","v"],["and","c"],["he","s"],["will still be disappointed.","v"]],
  [["But","c"],["the disappointment","s"],["will not become","v"],["the collapse of his whole footing.",null]],
  [["This","s"],["is often misread","v"],["as advice to stop caring.","m"]],
  [["The Stoics","s"],["cared","v"],["a great deal","m"],["and","c"],["held","v"],["public office",null],["throughout their lives.","m"]],
  [["Marcus Aurelius","s"],["wrote","v"],["these notes",null],["while running an empire at war.","m"]],
  [["The point","s"],["was","v"],["never","m"],["to want less but to place wanting where it can act.",null]],
  [["Effort","s"],["is","v"],["the part",null],["that","c"],["answers","v2"],["when","c"],["you","s2"],["call","v2"],["it.",null]]
 ],
 "25": [
  [["Schopenhauer","s"],["began","v"],["from an observation anyone can check.","m"]],
  [["Getting what you wanted","s"],["feels","v"],["wonderful,",null],["and","c"],["the feeling","s"],["does not last.","v"]],
  [["The satisfied wish","s"],["leaves","v"],["a quiet space,",null],["and","c"],["a new wish","s"],["moves in.","v"]],
  [["He","s"],["called","v"],["the force behind this restlessness",null],["the will.",null]],
  [["The will","s"],["has","v"],["no goal of its own;",null],["it","s"],["only","m"],["continues.","v"]],
  [["On this account,","m"],["pleasure","s"],["is","v"],["mostly","m"],["the removal of a want",null],["rather than a positive gain.","m"]],
  [["Boredom","s"],["is","v"],["what remains when nothing is missing,",null],["and","c"],["he","s"],["thought","v"],["it revealing.",null]],
  [["His conclusion","s"],["was","v"],["famously dark,",null],["and","c"],["many readers","s"],["stop","v"],["there.","m"]],
  [["But","c"],["he","s"],["also","m"],["described","v"],["two ways out of the circle.",null]],
  [["The first","s"],["is","v"],["art,",null],["where","c"],["for a moment","m"],["you","s2"],["look","v2"],["without wanting anything.","m"]],
  [["Music","s"],["was","v"],["his highest example,",null],["because","c"],["it","s2"],["asks for","v2"],["nothing outside itself.",null]],
  [["The second","s"],["is","v"],["compassion,",null],["in which","c"],["the wall between self and other","s2"],["thins.","v2"]],
  [["Neither escape","s"],["is","v"],["permanent,",null],["and","c"],["he","s"],["never","m"],["claimed","v"],["otherwise.","m"]],
  [["Later thinkers","s"],["disagreed","v"],["sharply","m"],["about whether the picture is accurate.","m"]],
  [["Even so,","m"],["the description of the treadmill","s"],["is","v"],["hard to forget",null],["once read.","m"]]
 ]
};
