/* Unit 6 READ RIGHT 표기 */
module.exports = {
 "26": [
  [["A message","s"],["that","c"],["takes","v2"],["ten seconds",null],["to read","m"],["does not really cost","v"],["you",null],["ten seconds.",null]],
  [["Part of your attention","s"],["stays","v"],["with it","m"],["after","c"],["you","s2"],["have closed","v2"],["the window.",null]],
  [["Researchers","s"],["call","v"],["this leftover portion",null],["attention residue.",null]],
  [["The next task","s"],["begins","v"],["with a mind","m"],["that","c"],["is not","v2"],["entirely present.",null]],
  [["Work","s"],["that","c"],["needs","v2"],["a long, quiet run",null],["suffers","v"],["most","m"],["from this.","m"]],
  [["Writing, planning, and debugging","s"],["all","m"],["require","v"],["holding several pieces at once.",null]],
  [["Each interruption","s"],["drops","v"],["the pieces,",null],["and","c"],["picking them up again","s"],["takes","v"],["time.",null]],
  [["The count of interruptions","s"],["matters","v"],["less","m"],["than their unpredictability.","m"]],
  [["A worker","s"],["who","c"],["knows","v2"],["nothing will arrive before noon",null],["can build","v"],["a real stretch.",null]],
  [["A worker","s"],["who","c"],["might be pinged","v2"],["at any second","m"],["never fully","m"],["settles.","v"]],
  [["Framing this as a matter of self-control","s"],["misses","v"],["where the problem lives.",null]],
  [["If","c"],["a reply within minutes","s2"],["is expected,","v2"],["no amount of discipline","s"],["creates","v"],["quiet.",null]],
  [["Several countries","s"],["have written","v"],["a right to disconnect",null],["into law.","m"]],
  [["Other workplaces","s"],["simply","m"],["agree","v"],["on hours","m"],["when","c"],["nobody","s2"],["sends","v2"],["anything.",null]],
  [["Both approaches","s"],["treat","v"],["attention",null],["as something a group protects, not a private virtue.","m"]]
 ],
 "27": [
  [["Most people","s"],["meet","v"],["virtual worlds",null],["through games,","m"],["and","c"],["stop","v"],["there.","m"]],
  [["The interesting uses","s"],["are","v"],["quieter and older",null],["than the entertainment ones.","m"]],
  [["A surgeon","s"],["can rehearse","v"],["a rare operation",null],["on a copy of the real patient's scan.","m"]],
  [["The copy","s"],["allows","v"],["a mistake",null],["that","c"],["costs","v2"],["nothing.",null]],
  [["Pilots","s"],["have trained","v"],["this way","m"],["since long before","c"],["the headsets","s2"],["arrived.","v2"]],
  [["Therapists","s"],["use","v"],["exactly the same property",null],["to treat severe fear.","m"]],
  [["A patient","s"],["afraid of heights","m"],["can stand","v"],["on a virtual balcony","m"],["and","c"],["step back","v"],["at will.","m"]],
  [["The fear","s"],["is","v"],["real,",null],["but","c"],["the danger","s"],["is not,","v"],["and","c"],["control","s"],["stays","v"],["with the patient.","m"]],
  [["Architects","s"],["walk","v"],["clients",null],["through buildings","m"],["that","c"],["have not been built.","v2"]],
  [["Problems","s"],["that","c"],["a drawing","s2"],["hides","v2"],["become","v"],["obvious",null],["when","c"],["you","s2"],["turn","v2"],["your head.",null]],
  [["None of this","s"],["makes","v"],["the technology",null],["neutral or free of cost.",null]],
  [["Headsets","s"],["are","v"],["expensive,",null],["and","c"],["long sessions","s"],["still","m"],["make","v"],["many users",null],["ill.",null]],
  [["A simulation","s"],["also","m"],["teaches","v"],["only","m"],["what its designers thought to include.",null]],
  [["A pilot","s"],["trained on clean weather","m"],["has not been trained","v"],["on everything.","m"]],
  [["The value","s"],["lies","v"],["in rehearsing what would otherwise be too costly to try.","m"]]
 ],
 "28": [
  [["Headlines about screens and unhappiness","s"],["appear","v"],["every year.","m"]],
  [["The studies","s"],["behind them","m"],["are","v"],["more careful, and much less certain.",null]],
  [["Most","s"],["report","v"],["a correlation",null],["that","c"],["is","v2"],["real but very small.",null]],
  [["One well-known analysis","s"],["found","v"],["the link",null],["no larger",null],["than that for eating potatoes.","m"]],
  [["Small","s"],["does not mean","v"],["zero,",null],["and","c"],["it","s"],["does not mean","v"],["the same",null],["for everyone.","m"]],
  [["What people do on a screen","s"],["turns out","v"],["to matter",null],["more than how long they stay.","m"]],
  [["Messaging a friend and scrolling past strangers","s"],["are counted","v"],["as the same hour.","m"]],
  [["Active use,","s"],["where","c"],["you","s2"],["speak","v2"],["and","c"],["are spoken to,","v2"],["looks","v"],["different",null],["from passive watching.","m"]],
  [["There",null],["is","v"],["also","m"],["a measurement problem","s"],["that","c"],["is rarely mentioned.","v2"]],
  [["Most studies","s"],["rely","v"],["on people estimating their own hours,","m"],["and","c"],["those estimates","s"],["are","v"],["poor.",null]],
  [["Direction","s"],["is","v"],["a further puzzle:",null],["unhappy teenagers","s"],["may simply reach","v"],["for a phone","m"],["more.","m"]],
  [["Displacement","s"],["may matter","v"],["most of all.","m"]],
  [["An hour online","s"],["costs","v"],["little","m"],["if","c"],["it","s2"],["replaces","v2"],["television,",null],["and","c"],["more","m"],["if","c"],["it","s2"],["replaces","v2"],["sleep.",null]],
  [["The useful question","s"],["is","v"],["therefore","m"],["not how long but instead of what.",null]],
  [["A number","s"],["without that context","m"],["explains","v"],["almost nothing.",null]]
 ],
 "29": [
  [["In the summer of 1956","m"],["a small group of researchers","s"],["met","v"],["at Dartmouth College","m"],["for two months.","m"]],
  [["Their proposal","s"],["used","v"],["a new phrase:",null],["artificial intelligence.",null]],
  [["They","s"],["believed","v"],["that","c"],["a serious effort","s2"],["could make","v2"],["real progress",null],["in one summer.","m"]],
  [["The confidence","s"],["was not","v"],["foolish,",null],["given what they had already achieved.","m"]],
  [["Machines","s"],["were proving","v"],["theorems",null],["and","c"],["playing","v"],["respectable checkers.",null]],
  [["The problems","s"],["that","c"],["looked","v2"],["hard",null],["to them","m"],["were","v"],["the ones",null],["that","c"],["felt","v2"],["hard",null],["to people.","m"]],
  [["Chess, logic, and algebra","s"],["sat","v"],["firmly","m"],["at the top of their list.","m"]],
  [["Those","s"],["turned out","v"],["to be comparatively easy to program.",null]],
  [["The hard problems","s"],["were","v"],["the ones a child solves without noticing.",null]],
  [["Recognising","v"],["a face,",null],["crossing","v"],["a room,",null],["or","c"],["understanding","v"],["a plain sentence",null],["in context.","m"]],
  [["This reversal","s"],["is now called","v"],["Moravec's paradox.",null]],
  [["Funding","s"],["collapsed","v"],["twice","m"],["when","c"],["promises","s2"],["went","v2"],["unmet,",null],["and","c"],["those years","s"],["are called","v"],["AI winters.",null]],
  [["The lesson","s"],["was not","v"],["that","c"],["the early researchers","s2"],["were","v2"],["wrong",null],["about everything.","m"]],
  [["It","s"],["was","v"],["that","c"],["we","s2"],["are","v2"],["poor judges of which tasks are difficult.",null]],
  [["Our own skills","s"],["feel","v"],["effortless",null],["precisely because","c"],["they","s2"],["run","v2"],["beneath awareness.","m"]]
 ],
 "30": [
  [["Ask","v"],["a friend",null],["how the film was,",null],["and","c"],["hear","v"],["the answer:",null],["the seats were comfortable.",null]],
  [["Nothing negative","s"],["has been said,","v"],["yet","c"],["you","s"],["know","v"],["exactly","m"],["what was meant.",null]],
  [["You","s"],["reached","v"],["the meaning",null],["by assuming your friend was being cooperative.","m"]],
  [["A cooperative speaker","s"],["gives","v"],["as much information",null],["as","c"],["the moment","s2"],["requires.","v2"]],
  [["Since","c"],["a comment about seats","s2"],["says","v2"],["far too little about a film,","m"],["the gap itself","s"],["speaks.","v"]],
  [["Paul Grice","s"],["described","v"],["this kind of unspoken reasoning",null],["in the 1960s.","m"]],
  [["He","s"],["argued","v"],["that","c"],["conversation","s2"],["runs","v2"],["on shared expectations","m"],["rather than on words alone.","m"]],
  [["Say","v"],["enough,",null],["say","v"],["what you believe true,",null],["stay","v"],["relevant,",null],["be","v"],["clear.",null]],
  [["Breaking one of these on purpose","s"],["is","v"],["how irony and hints work.",null]],
  [["This","s"],["is","v"],["also","m"],["why literal translation so often fails.",null]],
  [["The words","s"],["cross","v"],["the border,",null],["and","c"],["the expectations","s"],["behind them","m"],["do not.","v"]],
  [["It","s"],["is","v"],["why written messages start arguments that speech would not.",null]],
  [["A short reply","s"],["carries","v"],["a tone",null],["in one culture","m"],["and coldness",null],["in another.","m"]],
  [["Machines","s"],["meet","v"],["the same wall",null],["when","c"],["they","s2"],["process","v2"],["language",null],["without shared ground.","m"]],
  [["Meaning","s"],["has never lived","v"],["only","m"],["in the sentence.","m"]]
 ]
};
