/* Unit 7 READ RIGHT 표기 */
module.exports = {
 "31": [
  [["The loudest coach","s"],["on the field","m"],["is","v"],["rarely","m"],["the most effective one.",null]],
  [["Beginners","s"],["do need","v"],["clear instruction,",null],["and","c"],["nobody","s"],["learns","v"],["a grip",null],["by guessing.","m"]],
  [["But","c"],["after the basics,","m"],["constant correction","s"],["starts","v"],["to work against the learner.","m"]],
  [["A player","s"],["told what to fix","m"],["stops","v"],["asking what went wrong.",null]],
  [["The judgement","s"],["that","c"],["should grow","v2"],["inside the athlete","m"],["stays","v"],["outside,","m"],["in the coach.","m"]],
  [["Studies of motor learning","s"],["found","v"],["this pattern",null],["again and again.","m"]],
  [["Groups","s"],["given feedback after every attempt","m"],["performed","v"],["well","m"],["during practice.","m"]],
  [["The same groups","s"],["performed","v"],["worse","m"],["a week later","m"],["than groups told far less.","m"]],
  [["Immediate feedback","s"],["improves","v"],["today","m"],["and","c"],["weakens","v"],["tomorrow.","m"]],
  [["A good coach","s"],["therefore","m"],["chooses","v"],["when to speak,",null],["not merely what to say.","m"]],
  [["Silence","s"],["after a poor attempt","m"],["gives","v"],["the athlete",null],["room to notice something.",null]],
  [["The question What did you feel there?","s"],["teaches","v"],["more","m"],["than","c"],["a correction","s2"],["does.","v2"]],
  [["None of this","s"],["means","v"],["coaches","s2"],["should stand back","v2"],["and","c"],["watch.","v2"]],
  [["Someone","s"],["must design","v"],["the practice,",null],["spot","v"],["the danger,",null],["and","c"],["keep","v"],["the standard honest.",null]],
  [["The skill","s"],["is","v"],["knowing which of those jobs the moment actually calls for.",null]]
 ],
 "32": [
  [["Watching other people play games","s"],["is","v"],["older",null],["than the internet.","m"]],
  [["Arcades","s"],["had","v"],["crowds,",null],["and","c"],["a good player","s"],["drew","v"],["a ring of watchers.",null]],
  [["What changed","s"],["was","v"],["distance:",null],["streaming","s"],["let","v"],["that ring grow",null],["without a room.","m"]],
  [["A single match","s"],["can now be followed","v"],["by more people","m"],["than","c"],["fill","v2"],["a stadium.",null]],
  [["The money","s"],["followed","v"],["the audience,",null],["as","c"],["it","s2"],["always","m"],["does.","v2"]],
  [["Prize pools","s"],["passed","v"],["several million dollars,",null],["and","c"],["sponsors","s"],["arrived","v"],["after them.","m"]],
  [["Universities","s"],["began","v"],["offering scholarships,",null],["which","c"],["surprised","v2"],["almost everyone.",null]],
  [["Whether this counts as sport","s"],["is argued","v"],["more loudly","m"],["than","c"],["it","s2"],["needs","v2"],["to be.",null]],
  [["One side","s"],["points","v"],["to the training load, the reflexes, and the team structure.","m"]],
  [["The other","s"],["points","v"],["to the absence of physical exertion","m"],["as the deciding line.","m"]],
  [["The disagreement","s"],["is","v"],["mostly","m"],["about the definition","m"],["rather than the facts.","m"]],
  [["Both sides","s"],["agree","v"],["on what players actually do all day.","m"]],
  [["A more useful question","s"],["concerns","v"],["who owns the game itself.",null]],
  [["A football league","s"],["does not need","v"],["permission",null],["from the inventor of football.","m"]],
  [["An e-sports league","s"],["plays","v"],["a game",null],["that","c"],["one company","s2"],["can change","v2"],["or","c"],["close.","v2"]]
 ],
 "33": [
  [["A crowd scene","s"],["used to require","v"],["a crowd.",null]],
  [["Now","m"],["a few dozen people","s"],["are filmed","v"],["and","c"],["the rest of the square","s"],["is filled in.","v"]],
  [["The same tools","s"],["smooth","v"],["a face,",null],["age","v"],["an actor,",null],["or","c"],["replace","v"],["a sky",null],["after the shoot.","m"]],
  [["Dubbing","s"],["has changed","v"],["even more quietly","m"],["than","c"],["the pictures","s2"],["have.","v2"]],
  [["A voice","s"],["can now be carried","v"],["into a language","m"],["the actor","s2"],["never","m"],["spoke.","v2"]],
  [["Studios","s"],["describe","v"],["all of this",null],["as saving money,","m"],["which","c"],["is","v2"],["true and incomplete.",null]],
  [["Each of these tools","s"],["also","m"],["moves","v"],["a decision",null],["from the set to a later room.","m"]],
  [["What used to be settled by a hundred people on a Tuesday","s"],["is now settled","v"],["by three.","m"]],
  [["That shift","s"],["is","v"],["why the disputes are about consent rather than quality.",null]],
  [["An extra","s"],["who","c"],["is scanned","v2"],["once","m"],["may appear","v"],["in films","m"],["she","s2"],["never","m"],["worked on.","v2"]],
  [["A voice","s"],["used for training","m"],["may return","v"],["in a performance","m"],["nobody","s2"],["agreed to.","v2"]],
  [["Recent contracts","s"],["in the industry","m"],["now","m"],["spell out","v"],["permission and payment",null],["for reuse.","m"]],
  [["The technical question","s"],["was answered","v"],["years ago;","m"],["the harder question","s"],["was not.","v"]],
  [["Audiences,","s"],["meanwhile,","m"],["mostly","m"],["do not notice,","v"],["and","c"],["that","s"],["is","v"],["the point of the craft.",null]],
  [["A tool","s"],["that","c"],["hides","v2"],["its own work",null],["makes","v"],["the rules around it matter more, not less.",null]]
 ],
 "34": [
  [["Twenty years ago","m"],["a shop","s"],["could stock","v"],["only a few thousand albums.",null]],
  [["Shelf space","s"],["decided","v"],["what most people would ever hear.",null]],
  [["Streaming","s"],["removed","v"],["that limit",null],["completely,","m"],["and","c"],["predictions","s"],["followed","v"],["at once.","m"]],
  [["Writers","s"],["expected","v"],["a long tail:",null],["countless small artists each finding a small audience.","m"]],
  [["The tail","s"],["did appear,","v"],["and","c"],["it","s"],["is","v"],["longer",null],["than","c"],["anyone","s2"],["imagined.","v2"]],
  [["What nobody predicted","s"],["was","v"],["how steep the head would become.",null]],
  [["A tiny share of tracks","s"],["still","m"],["collects","v"],["most of the listening.",null]],
  [["The reason","s"],["is","v"],["simple",null],["once stated:","m"],["shelves","s"],["were never","v"],["the only bottleneck.",null]],
  [["Attention","s"],["is","v"],["the scarcer resource,",null],["and","c"],["it","s"],["did not expand","v"],["with the catalogue.","m"]],
  [["A listener","s"],["with unlimited choice","m"],["needs","v"],["help choosing",null],["more than before, not less.","m"]],
  [["So","c"],["the gatekeeper","s"],["moved","v"],["rather than disappeared.","m"]],
  [["It","s"],["used to be","v"],["a buyer",null],["in a shop;","m"],["it","s"],["is","v"],["now","m"],["a playlist and a recommendation.",null]],
  [["Being available","s"],["is","v"],["easy",null],["now,","m"],["and","c"],["being found","s"],["is","v"],["harder",null],["than","c"],["it","s2"],["ever","m"],["was.","v2"]],
  [["Many musicians","s"],["describe","v"],["reaching more countries and earning less money.",null]],
  [["Access and opportunity","s"],["turned out","v"],["to be different things.",null]]
 ],
 "35": [
  [["Audiences","s"],["complain","v"],["that","c"],["films","s2"],["have stopped","v2"],["being new,",null],["and","c"],["they","s"],["are","v"],["partly","m"],["right.",null]],
  [["The reason","s"],["is","v"],["less","m"],["about imagination","m"],["than about how the money is arranged.","m"]],
  [["A large film","s"],["is financed","v"],["before","c"],["anyone","s2"],["knows","v2"],["whether it will work.",null]],
  [["Most releases","s"],["lose","v"],["money,",null],["and","c"],["a few","s"],["pay","v"],["for all of them.","m"]],
  [["That shape","s"],["pushes","v"],["every decision",null],["toward reducing uncertainty.","m"]],
  [["A familiar character","s"],["is","v"],["a piece of evidence",null],["that","c"],["an audience","s2"],["already","m"],["exists.","v2"]],
  [["So","m"],["is","v"],["a novel","s"],["that","c"],["sold","v2"],["well,","m"],["or a film","s"],["that","c"],["worked","v2"],["in another country.","m"]],
  [["Marketing costs","s"],["make","v"],["the pressure sharper still.",null]],
  [["A studio","s"],["may spend","v"],["as much",null],["on advertising as on filming.","m"]],
  [["That money","s"],["must be committed","v"],["months","m"],["before","c"],["a single ticket","s2"],["is sold.","v2"]],
  [["Opening weekend","s"],["then","m"],["decides","v"],["almost everything,",null],["because","c"],["screens","s2"],["are reassigned","v2"],["by Monday.","m"]],
  [["A story","s"],["that","c"],["needs","v2"],["word of mouth",null],["has","v"],["very little time",null],["to collect it.","m"]],
  [["None of this","s"],["means","v"],["original films","s2"],["cannot succeed,","v2"],["and","c"],["each year","m"],["several","s"],["do.","v"]],
  [["It","s"],["means","v"],["they","s2"],["carry","v2"],["a risk",null],["the sequel","s2"],["does not,","v2"],["and","c"],["are judged","v2"],["faster.","m"]],
  [["Repetition","s"],["is not","v"],["a failure of imagination",null],["so much as a response to a structure.","m"]]
 ]
};
