/* Unit 8 READ RIGHT 표기 */
module.exports = {
 "36": [
  [["A family","s"],["that","c"],["fears","v2"],["losing work",null],["will spend","v"],["less","m"],["and","c"],["save","v"],["more.","m"]],
  [["Considered alone,","m"],["that decision","s"],["is","v"],["careful and sensible.",null]],
  [["The trouble","s"],["is","v"],["that","c"],["one household's spending","s2"],["is","v2"],["another household's income.",null]],
  [["When","c"],["every family","s2"],["cuts","v2"],["at once,","m"],["the incomes","s"],["they","s2"],["were protecting","v2"],["shrink.","v"]],
  [["Shops","s"],["sell","v"],["less,","m"],["hire","v"],["fewer people,",null],["and","c"],["the fear","s"],["that","c"],["started","v2"],["it",null],["turns out","v"],["to be right.",null]],
  [["Economists","s"],["call","v"],["this",null],["the paradox of thrift.",null]],
  [["It","s"],["is","v"],["a case",null],["where","c"],["the sum of good choices","s2"],["produces","v2"],["a bad result.",null]],
  [["This","s"],["is","v"],["why governments often spend during a downturn instead of saving.",null]],
  [["Someone","s"],["has to keep","v"],["buying",null],["while","c"],["everyone else","s2"],["is","v2"],["afraid to.",null]],
  [["Central banks","s"],["act","v"],["on the same logic","m"],["by making borrowing cheaper.","m"]],
  [["How much of this works, and for how long,","s"],["is genuinely disputed.","v"]],
  [["Some","s"],["argue","v"],["the debt","s2"],["merely moves","v2"],["the cost",null],["to a later year.","m"]],
  [["Others","s"],["reply","v"],["that","c"],["a deep recession","s2"],["also","m"],["costs","v2"],["later,","m"],["through skills","m"],["that","c"],["decay","v2"],["unused.","m"]],
  [["The disagreement","s"],["is","v"],["about size and timing,","m"],["not about the mechanism.","m"]],
  [["Almost no one","s"],["denies","v"],["that","c"],["the loop","s2"],["exists.","v2"]]
 ],
 "37": [
  [["For most of the nineteenth century","m"],["a president","s"],["spoke","v"],["mainly","m"],["to a room.","m"]],
  [["Speeches","s"],["were printed","v"],["the next day,","m"],["edited by whoever ran the paper.","m"]],
  [["The audience","s"],["was","v"],["real but slow,",null],["and","c"],["it","s"],["arrived","v"],["through other people's hands.","m"]],
  [["Radio","s"],["removed","v"],["those hands",null],["in a single step.","m"]],
  [["Franklin Roosevelt","s"],["used","v"],["it",null],["to speak into kitchens","m"],["without a newspaper in between.","m"]],
  [["His tone","s"],["changed","v"],["to match the setting:","m"],["quieter, closer, more like explanation than oratory.",null]],
  [["Television","s"],["changed","v"],["the calculation",null],["again,","m"],["because","c"],["now","m"],["appearance","s2"],["carried","v2"],["argument.",null]],
  [["After the first televised debate in 1960,","m"],["radio listeners and viewers","s"],["reported","v"],["different winners.",null]],
  [["The claim","s"],["is often exaggerated,","v"],["but","c"],["the worry","s"],["it","s2"],["raised","v2"],["was","v"],["new and lasting.",null]],
  [["Each new channel","s"],["narrowed","v"],["the gap between saying and being heard.",null]],
  [["That","s"],["sounds","v"],["like pure gain,","m"],["and","c"],["part of it","s"],["is.","v"]],
  [["Yet","c"],["a leader","s"],["who","c"],["can reach","v2"],["everyone",null],["directly","m"],["can also bypass","v"],["everyone",null],["who","c"],["would question","v2"],["him.",null]],
  [["The press","s"],["was","v"],["slow,",null],["but","c"],["it","s"],["asked","v"],["follow-up questions.",null]],
  [["Every technology","s"],["that","c"],["shortens","v2"],["the distance",null],["also","m"],["removes","v"],["something",null],["that","c"],["stood","v2"],["in the middle.","m"]],
  [["What stood there","s"],["is","v"],["worth naming",null],["before","c"],["it","s2"],["goes.","v2"]]
 ],
 "38": [
  [["Before 1136","m"],["the name Arthur","s"],["appears","v"],["only","m"],["in scattered fragments.","m"]],
  [["A line in a Welsh poem, a battle list, a saint's tale",null],["mentioning","v"],["him",null],["in passing.","m"]],
  [["There",null],["is","v"],["no court, no round table, and no sword in a stone.","s"]],
  [["Then","m"],["Geoffrey of Monmouth","s"],["wrote","v"],["a long book",null],["in Latin","m"],["called The History of the Kings of Britain.","m"]],
  [["He","s"],["presented","v"],["it",null],["as history","m"],["and","c"],["claimed","v"],["an ancient source",null],["nobody","s2"],["has ever found.","v2"]],
  [["In it","m"],["Arthur","s"],["becomes","v"],["a full king",null],["with a reign, campaigns, and a betrayal at the end.","m"]],
  [["The book","s"],["was copied","v"],["across Europe","m"],["faster than almost anything before it.","m"]],
  [["Later writers","s"],["then","m"],["added","v"],["what their own audiences wanted.",null]],
  [["French poets","s"],["supplied","v"],["the romance;",null],["a Cistercian cycle","s"],["supplied","v"],["the grail.",null]],
  [["Malory","s"],["gathered","v"],["the pieces",null],["again","m"],["in English","m"],["three centuries later.","m"]],
  [["Each layer","s"],["was written","v"],["by someone answering the taste of a particular year.","m"]],
  [["Calling the result a legend","s"],["is","v"],["accurate but slightly misleading.",null]],
  [["It","s"],["suggests","v"],["a slow drift,",null],["when","c"],["much of it","s2"],["was composed","v2"],["on purpose.","m"]],
  [["Traditions","s"],["often","m"],["have","v"],["authors,",null],["and","c"],["the authors","s"],["are often forgotten.","v"]],
  [["What we inherit as ancient","s"],["is","v"],["frequently","m"],["the work of one busy writer.",null]]
 ],
 "39": [
  [["For most of human history","m"],["people","s"],["gathered","v"],["food",null],["and","c"],["followed","v"],["it.",null]],
  [["That life","s"],["is often described","v"],["as short and desperate,","m"],["and","c"],["it","s"],["was","v"],["neither simple nor safe.",null]],
  [["But","c"],["skeletons","s"],["from the last hunting societies","m"],["tell","v"],["a more complicated story.",null]],
  [["They","s"],["are","v"],["taller",null],["on average","m"],["than the farming skeletons","m"],["that","c"],["follow","v2"],["them.",null]],
  [["They","s"],["show","v"],["fewer signs of the diseases",null],["that","c"],["come","v2"],["from crowding.","m"]],
  [["Their teeth","s"],["are","v"],["in better condition,","m"],["because","c"],["grain","s2"],["is","v2"],["hard",null],["on teeth.","m"]],
  [["Farming","s"],["did not arrive","v"],["because","c"],["it","s2"],["made","v2"],["individual lives",null],["more comfortable.",null]],
  [["It","s"],["arrived","v"],["because","c"],["it","s2"],["produced","v2"],["more calories",null],["from the same piece of ground.","m"]],
  [["More calories","s"],["meant","v"],["more children,",null],["and","c"],["more children","s"],["meant","v"],["more farmers.",null]],
  [["Once","c"],["a region","s2"],["filled","v2"],["with farmers,","m"],["going back","s"],["was","v"],["no longer possible.",null]],
  [["The land","s"],["could not feed","v"],["that many people",null],["any other way.","m"]],
  [["Farming","s"],["also","m"],["created","v"],["something new:",null],["a harvest",null],["that","c"],["could be stored.","v2"]],
  [["Stored grain","s"],["can be counted, taxed, taken, and defended.","v"]],
  [["Kings, armies, and written records","s"],["all","m"],["follow","v"],["the granary",null],["rather than the field.","m"]],
  [["The bargain","s"],["bought","v"],["numbers and permanence,",null],["and","c"],["it","s"],["was paid for","v"],["in health and freedom.","m"]]
 ],
 "40": [
  [["Most accounts of the American Revolution","s"],["begin","v"],["with a dramatic scene.","m"]],
  [["Tea in a harbour, shots on a green, a document",null],["signed","v"],["in summer.","m"]],
  [["The scenes","s"],["are","v"],["real,",null],["but","c"],["they","s"],["explain","v"],["less","m"],["than","c"],["they","s2"],["appear","v2"],["to.",null]],
  [["A crowd","s"],["can be gathered","v"],["in a night","m"],["and","c"],["dispersed","v"],["just as fast.","m"]],
  [["What turned scattered anger into a movement","s"],["was","v"],["slower and much duller.",null]],
  [["In 1772","m"],["Samuel Adams","s"],["helped","v"],["set up a committee of correspondence",null],["in Boston.","m"]],
  [["Its work","s"],["was","v"],["to write letters to other towns and to answer the ones that came back.",null]],
  [["Within a year,","m"],["towns","s"],["across Massachusetts","m"],["had","v"],["committees of their own.",null]],
  [["Within two,","m"],["the colonies","s"],["were exchanging","v"],["accounts of the same events.",null]],
  [["A grievance","s"],["in one port","m"],["became","v"],["known,",null],["in the same words,","m"],["in another.","m"]],
  [["This","s"],["is","v"],["unglamorous work,",null],["and","c"],["it","s"],["is","v"],["why the response could be coordinated at all.",null]],
  [["Adams","s"],["understood","v"],["that","c"],["outrage","s2"],["without a channel","m"],["simply","m"],["fades.","v2"]],
  [["The letters","s"],["built","v"],["the channel",null],["before","c"],["the outrage","s2"],["arrived.","v2"]],
  [["Historians","s"],["still","m"],["argue","v"],["about how decisive the committees were.","m"]],
  [["They","s"],["do not argue","v"],["about whether patient organisation matters.","m"]]
 ]
};
