/* Unit 9 READ RIGHT 표기 */
module.exports = {
 "41": [
  [["A child","s"],["is left","v"],["with one marshmallow","m"],["and","c"],["told","v"],["that","c"],["waiting","s2"],["will bring","v2"],["a second.",null]],
  [["Chimpanzees","s"],["have been given","v"],["versions of the same test",null],["in several laboratories.","m"]],
  [["Both","s"],["can wait,","v"],["and","c"],["both","s"],["find","v"],["it hard,",null],["which","c"],["is","v2"],["less surprising",null],["than","c"],["it","s2"],["sounds.","v2"]],
  [["The famous version of the study","s"],["was long read","v"],["as a test of willpower.","m"]],
  [["Later work","s"],["showed","v"],["that","c"],["the picture","s2"],["is","v2"],["more crowded than that.",null]],
  [["Children","s"],["who","c"],["had learned","v2"],["that","c"],["promises","s2"],["are kept","v2"],["waited","v"],["far longer.","m"]],
  [["Children","s"],["in rooms","m"],["where","c"],["earlier promises","s2"],["had been broken","v2"],["took","v"],["the first one",null],["quickly.","m"]],
  [["That","s"],["is not","v"],["weakness;",null],["it","s"],["is","v"],["a sensible reading of the evidence in front of them.",null]],
  [["Method","s"],["matters","v"],["as much","m"],["as","c"],["trust","s2"],["does.","v2"]],
  [["A child","s"],["who","c"],["covers","v2"],["the sweet,",null],["or","c"],["sings,","v2"],["or","c"],["turns","v2"],["the chair",null],["around,","m"],["waits","v"],["longer.","m"]],
  [["The successful ones","s"],["rarely","m"],["stare","v"],["at the reward","m"],["and","c"],["resist.","v"]],
  [["They","s"],["change","v"],["the situation",null],["so that","c"],["resisting","s2"],["is not required.","v2"]],
  [["Chimps","s"],["improve","v"],["in the same way","m"],["when","c"],["a toy","s2"],["is placed","v2"],["within reach.","m"]],
  [["So","c"],["the question","s"],["is not","v"],["simply","m"],["who can wait.",null]],
  [["It","s"],["is","v"],["who has reason to believe waiting pays, and who knows how to make it easier.",null]]
 ],
 "42": [
  [["Blood","s"],["cannot be manufactured,","v"],["so","c"],["every unit","s"],["comes","v"],["from a person","m"],["who","c"],["chose","v2"],["to give.",null]],
  [["The obvious way","s"],["to get more","m"],["seemed","v"],["to be paying for it.",null]],
  [["Several countries","s"],["tried,","v"],["and","c"],["the results","s"],["were","v"],["stranger than expected.",null]],
  [["In some studies","m"],["the number of donors","s"],["fell","v"],["after","c"],["payment","s2"],["was introduced.","v2"]],
  [["Richard Titmuss","s"],["argued","v"],["in 1970","m"],["that","c"],["money","s2"],["changes","v2"],["what the act means.",null]],
  [["An unpaid donation","s"],["says","v"],["something",null],["about the giver and about the stranger.","m"]],
  [["A paid one","s"],["is","v"],["a transaction,",null],["and","c"],["transactions","s"],["are judged","v"],["by their rate.","m"]],
  [["Once","c"],["the act","s2"],["has","v2"],["a price,",null],["the question","s"],["becomes","v"],["whether the price is worth it.",null]],
  [["For most people,","m"],["a small fee","s"],["is not","v"],["worth an hour and a needle.",null]],
  [["Later research","s"],["found","v"],["the effect","s2"],["is","v2"],["neither universal nor simple.",null]],
  [["Some payment schemes","s"],["do raise","v"],["supply,",null],["especially with vouchers rather than cash.","m"]],
  [["The safest reading","s"],["is","v"],["that","c"],["motives","s2"],["can be crowded out,","v2"],["not","m"],["that","c"],["they","s2"],["always are.","v2"]],
  [["Blood services","s"],["now","m"],["compete","v"],["for time and convenience","m"],["instead of paying.","m"]],
  [["They","s"],["shorten","v"],["queues,",null],["send","v"],["reminders,",null],["and","c"],["thank","v"],["donors",null],["by name.","m"]],
  [["The design","s"],["assumes","v"],["people","s2"],["already","m"],["want","v2"],["to help,",null],["and","c"],["removes","v"],["what stops them.",null]]
 ],
 "43": [
  [["English","s"],["once","m"],["had","v"],["two words",null],["where","c"],["it","s2"],["now","m"],["has","v2"],["one.",null]],
  [["Thou","s"],["was","v"],["for one person","m"],["you","s2"],["knew","v2"],["well;","m"],["you","s"],["was","v"],["plural, and also formal.",null]],
  [["Choosing between them","s"],["was never","v"],["only a matter of grammar.",null]],
  [["To say thou to a stranger of higher rank","s"],["was","v"],["to make a claim about the distance between you.",null]],
  [["Court records","s"],["show","v"],["insults",null],["built entirely on the wrong pronoun.","m"]],
  [["The same split","s"],["still","m"],["exists","v"],["in French, German, and dozens of other languages.","m"]],
  [["In English","m"],["the formal form","s"],["slowly","m"],["took over","v"],["everything.",null]],
  [["By the eighteenth century","m"],["thou","s"],["survived","v"],["mainly","m"],["in poetry and prayer.","m"]],
  [["The reasons","s"],["were","v"],["social rather than linguistic.",null]],
  [["Cities","s"],["grew,","v"],["strangers","s"],["met","v"],["more often,","m"],["and","c"],["politeness","s"],["became","v"],["the safe default.",null]],
  [["Some groups","s"],["resisted,","v"],["and","c"],["their reasons","s"],["are","v"],["revealing.",null]],
  [["Early Quakers","s"],["insisted","v"],["on thou","m"],["for everyone,","m"],["including judges and lords.","m"]],
  [["They","s"],["were fined and imprisoned","v"],["for it,","m"],["which","c"],["shows","v2"],["how much a pronoun carried.",null]],
  [["Today","m"],["the loss","s"],["is","v"],["invisible,",null],["and","c"],["most speakers","s"],["never notice","v"],["the missing word.",null]],
  [["A language","s"],["keeps","v"],["the distinctions",null],["its speakers","s2"],["still","m"],["need","v2"],["to make.",null]]
 ],
 "44": [
  [["A recorded lecture","s"],["can be paused, replayed, and watched","v"],["at double speed.","m"]],
  [["For delivering information,","m"],["that","s"],["is","v"],["plainly","m"],["better than a fixed hour in a hall.",null]],
  [["So","c"],["a reasonable plan","s"],["appeared:","v"],["move","v"],["the lecture",null],["out","m"],["and","c"],["keep","v"],["the room",null],["for work.","m"]],
  [["The idea","s"],["is usually called","v"],["flipping,",null],["and","c"],["where","c"],["it","s2"],["is done","v2"],["well","m"],["it","s"],["works.","v"]],
  [["Students","s"],["arrive","v"],["having met the material","m"],["and","c"],["spend","v"],["the hour",null],["using it.","m"]],
  [["But","c"],["the plan","s"],["asks","v"],["something",null],["the old lecture","s2"],["never asked.","v2"]],
  [["It","s"],["assumes","v"],["the watching","s2"],["actually","m"],["happened.","v2"]],
  [["A hall","s"],["enforced","v"],["attention",null],["crudely,","m"],["by holding people in one place for an hour.","m"]],
  [["A video","s"],["enforces","v"],["nothing,",null],["and","c"],["the least prepared students","s"],["fall","v"],["furthest behind.","m"]],
  [["Successful courses","s"],["therefore","m"],["build in","v"],["a small check",null],["before the class.","m"]],
  [["Three questions,","s"],["due the night before,","m"],["change","v"],["the pattern",null],["completely.","m"]],
  [["What could not be moved","s"],["is","v"],["the part",null],["that","c"],["was never","v2"],["in the lecture.","m"]],
  [["Noticing that a student is lost before she says so","s"],["is not","v"],["information delivery.",null]],
  [["It","s"],["is","v"],["reading a room,",null],["and","c"],["no recording","s"],["does","v"],["it.",null]],
  [["The technology","s"],["moved","v"],["the easy half",null],["and","c"],["left","v"],["the hard half",null],["where","c"],["it","s2"],["was.","v2"]]
 ],
 "45": [
  [["Ask","v"],["people",null],["to name their favourite music",null],["and","c"],["the answers","s"],["cluster","v"],["oddly.","m"]],
  [["Most of it","s"],["was released","v"],["when","c"],["the listener","s2"],["was","v2"],["between fourteen and twenty-four.","m"]],
  [["The pattern","s"],["is","v"],["strong enough",null],["that","c"],["researchers","s2"],["have given","v2"],["it a name:",null],["the reminiscence bump.",null]],
  [["It","s"],["appears","v"],["for films, books, and public events","m"],["as well as for songs.","m"]],
  [["One explanation","s"],["is","v"],["that","c"],["those years","s2"],["contain","v2"],["an unusual number of firsts.",null]],
  [["First independence, first friendships",null],["chosen","v"],["rather than given,","m"],["first serious feelings.",null]],
  [["Memories","s"],["formed alongside strong emotion","m"],["are recalled","v"],["more easily later.","m"]],
  [["A second explanation","s"],["is","v"],["simpler and slightly uncomfortable.",null]],
  [["We","s"],["hear","v"],["far more new music",null],["at seventeen","m"],["than at forty.","m"]],
  [["Familiarity itself","s"],["increases","v"],["liking,",null],["a finding replicated many times.","m"]],
  [["So","c"],["the songs of that decade","s"],["get","v"],["more chances",null],["to become familiar.","m"]],
  [["Both explanations","s"],["can be","v"],["true",null],["at once,","m"],["and","c"],["probably are.","v"]],
  [["The uncomfortable part","s"],["is","v"],["what follows for judgement.",null]],
  [["The feeling","s"],["that music has got worse","m"],["is","v"],["exactly what the pattern predicts.",null]],
  [["Knowing this","s"],["does not remove","v"],["the feeling,",null],["but","c"],["it","s"],["does change","v"],["what the feeling proves.",null]]
 ]
};
