/* Unit 10 READ RIGHT 표기 */
module.exports = {
 "46": [
  [["Comparing how equally two countries share their income","s"],["sounds","v"],["simple.",null]],
  [["It","s"],["stops","v"],["sounding simple",null],["the moment","c"],["you","s2"],["try","v2"],["to write it",null],["as one number.","m"]],
  [["The Gini coefficient","s"],["does","v"],["exactly that,",null],["on a scale from zero to one.","m"]],
  [["Zero","s"],["would mean","v"],["everyone","s2"],["receives","v2"],["the same amount.",null]],
  [["One","s"],["would mean","v"],["a single household","s2"],["receives","v2"],["everything.",null]],
  [["Real countries","s"],["sit","v"],["between about 0.25 and 0.6,","m"],["and","c"],["the figure","s"],["travels","v"],["well.","m"]],
  [["Journalists","s"],["like","v"],["it",null],["because","c"],["two nations","s2"],["can be placed","v2"],["side by side","m"],["in a sentence.","m"]],
  [["The trouble","s"],["is","v"],["that","c"],["very different shapes","s2"],["can produce","v2"],["the same score.",null]],
  [["A country","s"],["where","c"],["the top","s2"],["earns","v2"],["hugely","m"],["can match","v"],["one",null],["where","c"],["the bottom","s2"],["earns","v2"],["almost nothing.",null]],
  [["The number","s"],["cannot tell","v"],["you",null],["which of those two it is describing.",null]],
  [["It","s"],["also","m"],["says","v"],["nothing",null],["about who makes the rules.","m"]],
  [["Studies of legislative influence","s"],["find","v"],["that","c"],["policy","s2"],["tracks","v2"],["the preferences of higher earners",null],["more closely.","m"]],
  [["That","s"],["is","v"],["a claim about power,",null],["and","c"],["no distribution figure","s"],["captures","v"],["it.",null]],
  [["The coefficient","s"],["remains","v"],["useful,",null],["and","c"],["abandoning it","s"],["would lose","v"],["real information.",null]],
  [["It","s"],["is","v"],["a headline,",null],["and","c"],["headlines","s"],["are read","v"],["before articles,","m"],["not instead of them.","m"]]
 ],
 "47": [
  [["A story","s"],["where","c"],["the hero","s2"],["simply defeats","v2"],["a monster",null],["is","v"],["easy to follow and easy to forget.",null]],
  [["The ones","s"],["that","c"],["stay","v2"],["involve","v"],["a character",null],["who","c"],["wants","v2"],["two things",null],["that","c"],["cannot both be had.","v2"]],
  [["Safety and honesty.",null],["Loyalty and truth.",null],["Staying and leaving.","v"]],
  [["The outer events","s"],["then","m"],["become","v"],["a way of forcing that choice into the open.",null]],
  [["Writers","s"],["have known","v"],["this",null],["for a very long time.","m"]],
  [["Marketing","s"],["discovered","v"],["it",null],["more recently","m"],["and","c"],["uses","v"],["it",null],["constantly.","m"]],
  [["The strongest advertisements","s"],["rarely","m"],["claim","v"],["that","c"],["a product","s2"],["is","v2"],["good.",null]],
  [["They","s"],["stage","v"],["a small internal conflict",null],["and","c"],["place","v"],["the product",null],["at the resolution.","m"]],
  [["A parent","s"],["who","c"],["wants","v"],["to work and to be present.",null],["A student","s"],["who","c"],["wants","v"],["rest and results.",null]],
  [["Nothing","s"],["is asserted,","v"],["so","c"],["nothing","s2"],["has to be proved.","v2"]],
  [["This","s"],["is","v"],["more effective than a list of features,",null],["and also harder to argue with.",null]],
  [["You","s"],["cannot fact-check","v"],["a feeling of recognition.",null]],
  [["That","s"],["is","v"],["exactly why the technique deserves attention rather than alarm.",null]],
  [["The same device","s"],["that","c"],["makes","v2"],["a novel worth rereading",null],["can sell","v"],["a thing",null],["you","s2"],["do not need.","v2"]],
  [["Learning to notice the shape","s"],["is not","v"],["the same as refusing to enjoy it.",null]]
 ],
 "48": [
  [["For most of the twentieth century,","m"],["a job","s"],["meant","v"],["one employer and a long relationship.",null]],
  [["You","s"],["were hired,","v"],["you","s"],["stayed,","v"],["and","c"],["the firm","s"],["carried","v"],["the risk of a slow quarter.",null]],
  [["That arrangement","s"],["is no longer","v"],["the only shape",null],["work","s2"],["takes.","v2"]],
  [["Companies","s"],["now","m"],["buy","v"],["labour",null],["the way","c"],["they","s2"],["buy","v2"],["electricity,",null],["in the amounts they need.","m"]],
  [["Platforms","s"],["match","v"],["a driver, a translator, or a cleaner",null],["to a task","m"],["within minutes.","m"]],
  [["For the worker","m"],["the appeal","s"],["is","v"],["real:",null],["you","s"],["choose","v"],["the hours",null],["and","c"],["answer","v"],["to no manager.","m"]],
  [["The cost","s"],["is","v"],["that","c"],["the risk","s2"],["has quietly moved","v2"],["from the firm to the individual.","m"]],
  [["An empty afternoon","s"],["used to be","v"],["the company's problem,",null],["and","c"],["now","m"],["it","s"],["is","v"],["yours.",null]],
  [["Pensions, sick pay, and training","s"],["were bundled","v"],["into the old contract","m"],["without anyone noticing.","m"]],
  [["Unbundled,","m"],["they","s"],["become","v"],["purchases",null],["that","c"],["a variable income","s2"],["struggles","v2"],["to make.",null]],
  [["Defenders","s"],["argue","v"],["that","c"],["flexibility","s2"],["suits","v2"],["students, carers, and anyone leaving a rigid office.",null]],
  [["Critics","s"],["reply","v"],["that","c"],["a choice","s2"],["made under pressure","m"],["is not","v2"],["much of a choice.",null]],
  [["Several countries","s"],["have begun","v"],["writing a third category between employee and contractor.",null]],
  [["Whether that solves the problem or simply names it","s"],["remains","v"],["an open question.",null]],
  [["The real issue","s"],["is not","v"],["that work has changed, but who absorbs the shock.",null]]
 ],
 "49": [
  [["A supermarket","s"],["looks","v"],["like a plain warehouse,","m"],["but","c"],["it","s"],["is","v"],["closer to a designed path.",null]],
  [["Milk and bread","s"],["sit","v"],["at the back,","m"],["so","c"],["the most common errand","s"],["walks","v"],["you",null],["past everything else.","m"]],
  [["The route","s"],["is","v"],["no accident,",null],["and","c"],["neither","m"],["is","v"],["the light above the fruit.","s"]],
  [["Slower music","s"],["has been found","v"],["to lengthen the time",null],["customers","s2"],["spend","v2"],["in the aisles.","m"]],
  [["Longer visits","s"],["tend to produce","v"],["fuller baskets,",null],["which","c"],["is","v2"],["the only measure",null],["that","c"],["matters","v2"],["here.","m"]],
  [["Prices","s"],["ending in nine","m"],["survive","v"],["because","c"],["the eye","s2"],["reads","v2"],["the first digit",null],["and","c"],["moves on.","v2"]],
  [["A shelf","s"],["at eye level","m"],["earns","v"],["more",null],["than the same shelf near the floor.","m"]],
  [["Suppliers","s"],["know","v"],["this,",null],["and","c"],["they","s"],["pay","v"],["for the height.","m"]],
  [["None of these tricks","s"],["forces","v"],["anyone",null],["to buy a thing.",null]],
  [["They","s"],["simply tilt","v"],["a hundred small decisions",null],["in one direction.","m"]],
  [["Defenders","s"],["call","v"],["this",null],["good service,",null],["since","c"],["a pleasant shop","s2"],["is not","v2"],["a crime.",null]],
  [["Critics","s"],["answer","v"],["that","c"],["the shopper","s2"],["is playing","v2"],["a game",null],["whose","c"],["rules","s2"],["were never explained.","v2"]],
  [["The asymmetry","s"],["is","v"],["the point:",null],["one side","s"],["has","v"],["data,",null],["and","c"],["the other","s"],["has","v"],["a list.",null]],
  [["Knowing the design","s"],["does not switch","v"],["it off,",null],["but","c"],["it","s"],["does change","v"],["what you notice.",null]],
  [["You","s"],["can still enjoy","v"],["the shop",null],["while","c"],["seeing the shape of the floor.","m"]]
 ],
 "50": [
  [["The first rule","s"],["anyone","s2"],["learns","v2"],["in economics","m"],["is","v"],["that","c"],["demand","s2"],["falls","v2"],["as","c"],["price","s2"],["rises.","v2"]],
  [["The rule","s"],["holds","v"],["for rice, for petrol, and for almost everything on a shelf.","m"]],
  [["It","s"],["fails","v"],["for a small family of goods,","m"],["and","c"],["the failure","s"],["is","v"],["instructive.",null]],
  [["A handbag","s"],["that","c"],["doubles","v2"],["in price","m"],["can sell","v"],["more units",null],["than before.","m"]],
  [["Nothing","s"],["inside the bag","m"],["has changed,","v"],["and","c"],["the stitching","s"],["is","v"],["the same.",null]],
  [["What changed","s"],["is","v"],["the message",null],["the price","s2"],["sends","v2"],["to everyone","m"],["who","c"],["sees","v2"],["it.",null]],
  [["Thorstein Veblen","s"],["described","v"],["this",null],["in 1899","m"],["as consumption meant to be observed.","m"]],
  [["The good","s"],["is bought","v"],["partly for the buyer and partly for the audience.","m"]],
  [["This","s"],["only","m"],["works","v"],["while","c"],["the price","s2"],["stays","v2"],["out of most people's reach.","m"]],
  [["A luxury","s"],["that","c"],["everyone","s2"],["can afford","v2"],["stops","v"],["performing the job it was bought for.",null]],
  [["Brands","s"],["therefore","m"],["protect","v"],["scarcity",null],["as carefully","m"],["as","c"],["they","s2"],["protect","v2"],["quality.",null]],
  [["The pattern","s"],["is","v"],["easy to mock and harder to escape.",null]],
  [["School uniforms, wedding rules, and gifts","s"],["all","m"],["carry","v"],["similar signals.",null]],
  [["Reading a price as information about goods","s"],["misses","v"],["half of what it does.",null]],
  [["It","s"],["is","v"],["also","m"],["information about the person",null],["who","c"],["is willing to pay","v2"],["it.",null]]
 ]
};
