/* Unit 11 READ RIGHT 표기 */
module.exports = {
 "51": [
  [["Nobody","s"],["owns","v"],["the sea,",null],["and","c"],["that","s"],["is","v"],["exactly","m"],["where the trouble starts.",null]],
  [["A field","s"],["has","v"],["a fence, a name on a document, and someone",null],["who","c"],["loses","v2"],["money",null],["if","c"],["it","s2"],["is ruined.","v2"]],
  [["A fishery","s"],["has","v"],["none of these,",null],["so","c"],["every boat","s"],["has","v"],["a reason to take one more.",null]],
  [["Each captain","s"],["knows","v"],["the stock","s2"],["is falling","v2"],["and","c"],["knows","v"],["that","c"],["restraint alone","s2"],["will not save","v2"],["it.",null]],
  [["Economists","s"],["call","v"],["this pattern",null],["the tragedy of the commons.",null]],
  [["The usual remedy","s"],["is","v"],["to hand the resource to an owner",null],["who","c"],["will care","v2"],["about next year.","m"]],
  [["Private quotas","s"],["have rebuilt","v"],["some fisheries",null],["that","c"],["free access","s2"],["had emptied.","v2"]],
  [["Yet","c"],["ownership","s"],["travels","v"],["badly","m"],["across water, air, and moving animals.","m"]],
  [["A river","s"],["crosses","v"],["borders,",null],["and","c"],["a cloud","s"],["refuses","v"],["to stay",null],["above one farm.","m"]],
  [["Elinor Ostrom","s"],["studied","v"],["villages",null],["that","c"],["solved","v2"],["this",null],["without markets or governments.","m"]],
  [["Their rules","s"],["were","v"],["local, written by the users, and enforced by neighbours.",null]],
  [["Monitoring","s"],["was","v"],["cheap",null],["because","c"],["everyone","s2"],["could see","v2"],["everyone else's boat.",null]],
  [["Her work","s"],["suggests","v"],["that","c"],["the question","s2"],["is not","v2"],["private or public.",null]],
  [["It","s"],["is","v"],["whether","c"],["the people who bear the cost","s2"],["also make","v2"],["the rules.",null]],
  [["Where","c"],["those two","s2"],["come apart,","v2"],["the resource","s"],["usually","m"],["loses.","v"]]
 ],
 "52": [
  [["The lake in the middle of the city","s"],["turned","v"],["green",null],["one summer","m"],["and","c"],["stayed","v"],["that way.",null]],
  [["Residents","s"],["blamed","v"],["the ducks, then the boats, then a factory",null],["that","c"],["had closed.","v2"]],
  [["The actual cause","s"],["was arriving","v"],["invisibly","m"],["with every rainfall.","m"]],
  [["Lawn fertiliser, road dust, and dog waste","s"],["all","m"],["ran","v"],["off the streets","m"],["into one basin.","m"]],
  [["Nutrients","s"],["feed","v"],["algae,",null],["algae","s"],["block","v"],["the light,",null],["and","c"],["the plants below the surface","s"],["die.","v"]],
  [["When","c"],["those plants","s2"],["die,","v2"],["the sediment","s"],["loosens","v"],["and","c"],["releases","v"],["still more nutrients.",null]],
  [["A lake in this state","s"],["keeps","v"],["feeding itself",null],["long after","c"],["the inflow","s2"],["is reduced.","v2"]],
  [["The city","s"],["first","m"],["tried","v"],["the visible remedy",null],["and","c"],["dredged","v"],["the bottom",null],["at great expense.","m"]],
  [["The water","s"],["cleared","v"],["for two seasons","m"],["and","c"],["then","m"],["turned","v"],["green",null],["again.","m"]],
  [["The second attempt","s"],["worked","v"],["on the streets","m"],["instead of the water.","m"]],
  [["Rain gardens, swept gutters, and planted verges","s"],["intercepted","v"],["the runoff",null],["before","c"],["it","s2"],["arrived.","v2"]],
  [["Nothing about this","s"],["looked","v"],["like restoration,","m"],["and","c"],["no photograph","s"],["showed","v"],["a difference.",null]],
  [["Four years later","m"],["the lake","s"],["held","v"],["plants, insects, and a returning heron.",null]],
  [["The lesson","s"],["is","v"],["that","c"],["a lake","s2"],["is","v2"],["the last page of its catchment.",null]],
  [["Reading only the last page","s"],["explains","v"],["very little.",null]]
 ],
 "53": [
  [["Mars","s"],["has","v"],["an atmosphere,",null],["but","c"],["it","s"],["is","v"],["thin enough to be almost useless.",null]],
  [["The pressure at the surface","s"],["is","v"],["less than one percent of ours.",null]],
  [["Water","s"],["cannot stay","v"],["liquid",null],["there,","m"],["and","c"],["an unprotected body","s"],["would not last","v"],["long.","m"]],
  [["The obvious fix","s"],["is","v"],["to make the atmosphere thicker.",null]],
  [["Frozen carbon dioxide","s"],["sits","v"],["at the poles and inside the soil.","m"]],
  [["Warm","v"],["the planet",null],["slightly","m"],["and","c"],["some of it","s"],["should return","v"],["to the air.","m"]],
  [["That gas","s"],["would trap","v"],["heat,",null],["which","c"],["would release","v2"],["more gas,",null],["which","c"],["would trap","v2"],["more heat.",null]],
  [["The idea","s"],["depends on","v"],["there being enough carbon dioxide",null],["to start with.","m"]],
  [["A recent survey of the known reserves","s"],["suggests","v"],["there is not.",null]],
  [["Even","m"],["releasing everything available","s"],["would raise","v"],["the pressure",null],["to about seven percent.","m"]],
  [["That","s"],["is","v"],["thicker air,",null],["but","c"],["it","s"],["is still not","v"],["air",null],["anyone","s2"],["could breathe.","v2"]],
  [["Importing gas from elsewhere in the solar system","s"],["is discussed","v"],["seriously.","m"]],
  [["The timescales","s"],["involved","m"],["are measured","v"],["in centuries rather than decades.","m"]],
  [["Meanwhile","m"],["the same physics","s"],["explains","v"],["what our own thin blanket does here.",null]],
  [["A planet","s"],["is","v"],["easier to change by accident than on purpose.",null]]
 ],
 "54": [
  [["Pain research","s"],["has","v"],["an uncomfortable requirement",null],["built into its own question.","m"]],
  [["To learn how pain works,","m"],["someone","s"],["has to be","v"],["in pain.","m"]],
  [["For most of the last century","m"],["that someone","s"],["has been","v"],["an animal.",null]],
  [["The results","s"],["have been","v"],["useful,",null],["and","c"],["modern surgery","s"],["would be","v"],["unthinkable",null],["without them.","m"]],
  [["The difficulty","s"],["appears","v"],["when","c"],["you","s2"],["ask","v2"],["why a mouse is chosen at all.",null]],
  [["It","s"],["is chosen","v"],["because","c"],["its nervous system","s2"],["is","v2"],["close enough to ours to be informative.","m"]],
  [["That closeness","s"],["is","v"],["also","m"],["the reason",null],["the mouse","s2"],["can suffer.","v2"]],
  [["The more useful","c"],["an animal","s2"],["is","v2"],["as a model,","m"],["the stronger","c"],["its claim on us","s"],["becomes.","v"]],
  [["The usefulness and the moral problem","s"],["come","v"],["from the same fact.","m"]],
  [["Regulations","s"],["respond","v"],["with limits rather than answers.","m"]],
  [["Researchers","s"],["must replace","v"],["animals",null],["where possible,","m"],["reduce","v"],["numbers,",null],["and","c"],["refine","v"],["procedures.",null]],
  [["These three words","s"],["are printed","v"],["in every ethics application in the field.","m"]],
  [["Critics","s"],["say","v"],["the rules","s2"],["manage","v2"],["discomfort",null],["without ever confronting it.","m"]],
  [["Defenders","s"],["reply","v"],["that","c"],["a system with rules","s2"],["is","v2"],["better than one without.",null]],
  [["Neither side","s"],["claims","v"],["the question","s2"],["has been settled.","v2"]]
 ],
 "55": [
  [["Darwin","s"],["is remembered","v"],["for competition,","m"],["which","c"],["is","v2"],["only half of what he wrote.",null]],
  [["The Descent of Man","s"],["spends","v"],["many pages",null],["on sympathy rather than struggle.","m"]],
  [["He","s"],["collected","v"],["reports of animals",null],["that","c"],["helped","v2"],["one another",null],["at some cost.","m"]],
  [["A blind pelican","s"],["fed by its companions","m"],["appears","v"],["in his notes.","m"]],
  [["Monkeys","s"],["were described","v"],["rescuing a keeper from an angry baboon.",null]],
  [["Darwin","s"],["did not treat","v"],["these stories",null],["as decoration.","m"]],
  [["He","s"],["argued","v"],["that","c"],["social instincts","s2"],["were themselves shaped","v2"],["by selection.","m"]],
  [["A group","s"],["whose","c"],["members","s2"],["warn and defend","v2"],["each other",null],["survives","v"],["longer than one","m"],["that","c"],["does not.","v2"]],
  [["Sympathy,","s"],["in this reading,","m"],["is","v"],["not the opposite of fitness but a source of it.",null]],
  [["Later writers","s"],["narrowed","v"],["the theory",null],["into a slogan about the strongest.","m"]],
  [["The phrase survival of the fittest","s"],["was not","v"],["even","m"],["his own.",null]],
  [["Modern work on rats","s"],["freeing trapped companions","m"],["has revived","v"],["his older question.",null]],
  [["Whether such acts show feeling or reflex","s"],["is still argued.","v"]],
  [["What is no longer argued","s"],["is","v"],["that","c"],["they","s2"],["exist.","v2"]],
  [["Darwin","s"],["would have found","v"],["the second point",null],["more interesting than the first.",null]]
 ]
};
