/* Unit 12 READ RIGHT 표기 */
module.exports = {
 "56": [
  [["A heavy snowstorm","s"],["is often used","v"],["as evidence against a warming world.","m"]],
  [["The argument","s"],["sounds","v"],["reasonable",null],["and","c"],["is wrong","v"],["for an interesting reason.","m"]],
  [["Warm air","s"],["holds","v"],["more water vapour",null],["than","c"],["cold air","s2"],["does.","v2"]],
  [["Every degree of warming","s"],["raises","v"],["that capacity",null],["by about seven percent.","m"]],
  [["Snow","s"],["requires","v"],["two conditions:",null],["moisture in the air and a temperature below freezing.",null]],
  [["Warming","s"],["removes","v"],["the second condition",null],["slowly","m"],["and","c"],["adds","v"],["to the first immediately.","m"]],
  [["The result","s"],["is","v"],["fewer snowy days but heavier snow",null],["on the days","m"],["that","c"],["remain.","v2"]],
  [["A town","s"],["may lose","v"],["two weeks of winter",null],["and","c"],["still break","v"],["its record",null],["for one storm.","m"]],
  [["Coastal storms","s"],["have loaded","v"],["more water",null],["into the same cold air","m"],["over recent decades.","m"]],
  [["A second argument","s"],["concerns","v"],["the ring of wind",null],["circling the Arctic.","m"]],
  [["Some researchers","s"],["link","v"],["a warming Arctic",null],["to a weaker, wavier polar vortex.","m"]],
  [["A wavy vortex","s"],["lets","v"],["cold air spill",null],["much farther south than usual.","m"]],
  [["This second claim","s"],["is debated","v"],["and","c"],["the evidence","s"],["is not settled.","v"]],
  [["The first one","s"],["is","v"],["simple physics",null],["and","c"],["requires","v"],["no debate",null],["at all.","m"]],
  [["A cold week","s"],["is","v"],["weather,",null],["and","c"],["the capacity of air","s"],["is","v"],["climate.",null]]
 ],
 "57": [
  [["A cut on your hand","s"],["closes","v"],["without any instruction from you.","m"]],
  [["Cells at the edge","s"],["divide,","v"],["move","v"],["inward,","m"],["and","c"],["stop","v"],["when","c"],["they","s2"],["meet.","v2"]],
  [["Medicine,","s"],["for most of its history,","m"],["has worked","v"],["alongside this process","m"],["rather than replacing it.","m"]],
  [["A surgeon","s"],["holds","v"],["the edges",null],["together,","m"],["and","c"],["the body","s"],["does","v"],["the joining.",null]],
  [["Antibiotics","s"],["remove","v"],["a competitor;",null],["they","s"],["do not build","v"],["new tissue.",null]],
  [["This division of labour","s"],["is","v"],["easy to forget",null],["in a hospital full of machines.","m"]],
  [["It","s"],["matters","v"],["because","c"],["it","s2"],["changes","v2"],["what counts as success.",null]],
  [["Some conditions","s"],["cannot be closed","v"],["the way","c"],["a cut","s2"],["can.","v2"]],
  [["Diabetes and arthritis","s"],["are managed","v"],["for decades","m"],["rather than cured.","m"]],
  [["A vocabulary","s"],["built around cure","m"],["leaves","v"],["those patients",null],["sounding like failures.",null]],
  [["Researchers","s"],["now","m"],["separate","v"],["healing",null],["from curing","m"],["more carefully.","m"]],
  [["Curing","s"],["removes","v"],["a disease,",null],["and","c"],["healing","s"],["restores","v"],["a life",null],["around it.","m"]],
  [["The distinction","s"],["is not","v"],["decoration;",null],["it","s"],["decides","v"],["which treatments are funded.",null]],
  [["A drug","s"],["that","c"],["adds","v2"],["two months",null],["may matter","v"],["less than one that returns sleep.","m"]],
  [["Both questions","s"],["are","v"],["medical,",null],["and","c"],["only one","s"],["has","v"],["an easy number.",null]]
 ],
 "58": [
  [["Every nation","s"],["tells","v"],["itself",null],["a story",null],["about who belongs inside it and who does not.","m"]],
  [["One version","s"],["says","v"],["that","c"],["anyone","s2"],["who","c"],["accepts","v2"],["the laws",null],["belongs.","v2"]],
  [["The other","s"],["says","v"],["that","c"],["belonging","s2"],["is inherited,","v2"],["like a language or a face.","m"]],
  [["Historians","s"],["call","v"],["these two pictures",null],["the civic and the ethnic idea of a nation.",null]],
  [["The civic version","s"],["is","v"],["easier to defend and harder to feel.",null]],
  [["The ethnic version","s"],["offers","v"],["something",null],["the other","s2"],["cannot:","v2"],["ancestors.",null]],
  [["It","s"],["answers","v"],["the question",null],["of why strangers should sacrifice for one another.","m"]],
  [["That answer","s"],["has held","v"],["armies",null],["together","m"],["and","c"],["emptied","v"],["villages.",null]],
  [["The trouble","s"],["begins","v"],["where","c"],["populations","s2"],["do not match","v2"],["the map.",null]],
  [["No border in Europe","s"],["has ever separated","v"],["one people",null],["cleanly","m"],["from another.","m"]],
  [["A nation","s"],["defined by descent","m"],["therefore","m"],["always","m"],["contains","v"],["the wrong people.",null]],
  [["The twentieth century","s"],["recorded,","v"],["in some detail,","m"],["what states did about that arithmetic.",null]],
  [["Civic nationalism","s"],["is not","v"],["innocent",null],["either,","m"],["since","c"],["laws","s2"],["can exclude","v2"],["quietly.","m"]],
  [["But","c"],["it","s"],["can admit","v"],["a newcomer",null],["without rewriting anyone's grandparents.","m"]],
  [["That difference","s"],["is","v"],["small",null],["on paper","m"],["and enormous",null],["in practice.","m"]]
 ],
 "59": [
  [["The old story about automation","s"],["had","v"],["two characters and one ending.",null]],
  [["A machine","s"],["arrived","v"],["one morning,","m"],["and","c"],["a worker","s"],["left","v"],["for good.","m"]],
  [["That version","s"],["still","m"],["happens,","v"],["but","c"],["it","s"],["is no longer","v"],["the only one.",null]],
  [["Collaborative robots","s"],["are built","v"],["to share a bench","m"],["rather than clear it.","m"]],
  [["They","s"],["are","v"],["slow enough to work",null],["beside a person","m"],["without a cage.","m"]],
  [["The machine","s"],["holds","v"],["the heavy part",null],["while","c"],["the human","s2"],["decides","v2"],["where it goes.",null]],
  [["Each side","s"],["keeps","v"],["the task",null],["it","s2"],["is","v2"],["unreasonably good at.",null]],
  [["Force and repetition","s"],["belong","v"],["to the arm,","m"],["and","c"],["judgement","s"],["stays","v"],["with the person.","m"]],
  [["Factories","s"],["report","v"],["fewer injuries and faster changeovers between products.",null]],
  [["Critics","s"],["point","v"],["at a quieter risk than unemployment.","m"]],
  [["When","c"],["a machine","s2"],["handles","v2"],["the difficult half,",null],["the human half","s"],["becomes","v"],["routine.",null]],
  [["Skill","s"],["that","c"],["is never practised","v2"],["disappears","v"],["within a few years.","m"]],
  [["The split between the two halves","s"],["is","v"],["a design decision, not a law of physics.",null]],
  [["Someone","s"],["always","m"],["chooses","v"],["which part of the work stays interesting.",null]],
  [["That someone","s"],["is","v"],["rarely","m"],["the person",null],["standing at the bench.","m"]]
 ],
 "60": [
  [["A need","s"],["feels","v"],["like a fact,","m"],["and","c"],["a want","s"],["feels","v"],["like a choice.","m"]],
  [["The line between them","s"],["moves","v"],["more","m"],["than","c"],["either word","s2"],["suggests.","v2"]],
  [["Nobody in 1900","s"],["believed","v"],["that","c"],["mouth odour","s2"],["was","v2"],["a medical problem.",null]],
  [["A company","s"],["selling floor cleaner","m"],["renamed","v"],["it",null],["a mouthwash",null],["and","c"],["named","v"],["the condition.",null]],
  [["Halitosis","s"],["was","v"],["a real word,",null],["but","c"],["it","s"],["had lived","v"],["quietly","m"],["in medical dictionaries.","m"]],
  [["Advertising","s"],["moved","v"],["it",null],["into ordinary conversation","m"],["and into ordinary anxiety.","m"]],
  [["Sales","s"],["rose","v"],["from a hundred thousand dollars to eight million","m"],["in seven years.","m"]],
  [["The same method","s"],["has been used","v"],["for deodorant, for orange juice, and for bottled water.","m"]],
  [["Critics","s"],["conclude","v"],["that","c"],["capitalism","s2"],["manufactures","v2"],["needs",null],["as efficiently as it manufactures goods.","m"]],
  [["Defenders","s"],["answer","v"],["that","c"],["all needs above survival","s2"],["are","v2"],["social",null],["anyway.","m"]],
  [["Nobody","s"],["needs","v"],["a chair,",null],["and","c"],["few of us","s"],["would give","v"],["one",null],["up.","m"]],
  [["Both sides","s"],["are","v"],["partly right,",null],["which","c"],["is","v2"],["why the argument never ends.",null]],
  [["The useful move","s"],["is","v"],["smaller than choosing a side.",null]],
  [["It","s"],["is","v"],["asking,",null],["before a purchase,","m"],["when this particular need first appeared.",null]],
  [["Sometimes","m"],["the answer","s"],["is","v"],["a childhood,",null],["and","c"],["sometimes","m"],["it","s"],["is","v"],["a campaign.",null]]
 ]
};
