<persisted-output>
Output too large (56.1KB). Full output saved to: /root/.claude/projects/-home-user-hakmundang/b8546aae-5211-575f-825f-676b5ddc3b42/tool-results/toolu_01Rs12oqjPscxASqFdCWsMyk.json

Preview (first 2KB):
[
  {
    "type": "text",
    "text": "import { CalendarDays, LayoutDashboard, MessageCircle, MessageSquare } from \"lucide-react\";\nimport React, { useState, useEffect, useMemo } from \"react\";\nimport { useOwnerFilter } from \"@/hooks/useOwnerFilter\";\nimport {\n  Users,\n  ClipboardCheck,\n  Clock,\n  UserX,\n  CalendarIcon,\n  Sparkles,\n  BarChart3,\n  BookOpen,\n  Mic,\n  X,\n  RotateCcw } from\n\"lucide-react\";\nimport { Card, CardContent, CardDescription, CardHeader, CardTitle } from \"@/components/ui/card\";\nimport { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from \"@/components/ui/table\";\nimport { Badge } from \"@/components/ui/badge\";\nimport { Button } from \"@/components/ui/button\";\nimport { Calendar } from \"@/components/ui/calendar\";\nimport { useQuery, useMutation, useQueryClient } from \"@tanstack/react-query\";\nimport { supabase } from \"@/integrations/supabase/client\";\nimport { DailySubmissionStatus } from \"@/components/dashboard/DailySubmissionStatus\";\nimport { RTSubmissionStatus } from \"@/components/dashboard/RTSubmissionStatus\";\n\nimport { QuickMessageDialog } from \"@/components/dashboard/QuickMessageDialog\";\nimport { BulkMessageDialog } from \"@/components/dashboard/BulkMessageDialog\";\nimport { BulkKakaoDialog } from \"@/components/dashboard/BulkKakaoDialog\";\nimport { QuickKakaoDialog } from \"@/components/dashboard/QuickKakaoDialog\";\nimport { format, subDays } from \"date-fns\";\nimport { ko } from \"date-fns/locale\";\nimport { Avatar, AvatarFallback, AvatarImage } from \"@/components/ui/avatar\";\nimport { ScrollArea } from \"@/components/ui/scroll-area\";\nimport { toast } from \"sonner\";\n\nimport { useAuth } from \"@/contexts/AuthContext\";\n\ninterface MissingAssignment {\n  id: string;\n  studentId: string;\n  studentName: string;\n  studentPhone: string | null;\n  parentPhone: string | null;\n  gradeName: string;\n  gradeId: string;\n  schoolName: string;\n  schoolId: string;\n  schoo
...
</persisted-output>