/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrunDongjakHighRouteImport } from './routes/orun-dongjak-high'
import { Route as OrunDongjakRouteImport } from './routes/orun-dongjak'
import { Route as BrainiacSongpaHighRouteImport } from './routes/brainiac-songpa-high'
import { Route as BrainiacSongpaRouteImport } from './routes/brainiac-songpa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSchoolinfoProxyRouteImport } from './routes/api/schoolinfo-proxy'
import { Route as ApiSchoolBundleRouteImport } from './routes/api/school-bundle'
import { Route as ApiDebugNeisRouteImport } from './routes/api/debug-neis'

const OrunDongjakHighRoute = OrunDongjakHighRouteImport.update({
  id: '/orun-dongjak-high',
  path: '/orun-dongjak-high',
  getParentRoute: () => rootRouteImport,
} as any)
const OrunDongjakRoute = OrunDongjakRouteImport.update({
  id: '/orun-dongjak',
  path: '/orun-dongjak',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainiacSongpaHighRoute = BrainiacSongpaHighRouteImport.update({
  id: '/brainiac-songpa-high',
  path: '/brainiac-songpa-high',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainiacSongpaRoute = BrainiacSongpaRouteImport.update({
  id: '/brainiac-songpa',
  path: '/brainiac-songpa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchoolinfoProxyRoute = ApiSchoolinfoProxyRouteImport.update({
  id: '/api/schoolinfo-proxy',
  path: '/api/schoolinfo-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchoolBundleRoute = ApiSchoolBundleRouteImport.update({
  id: '/api/school-bundle',
  path: '/api/school-bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugNeisRoute = ApiDebugNeisRouteImport.update({
  id: '/api/debug-neis',
  path: '/api/debug-neis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brainiac-songpa': typeof BrainiacSongpaRoute
  '/brainiac-songpa-high': typeof BrainiacSongpaHighRoute
  '/orun-dongjak': typeof OrunDongjakRoute
  '/orun-dongjak-high': typeof OrunDongjakHighRoute
  '/api/debug-neis': typeof ApiDebugNeisRoute
  '/api/school-bundle': typeof ApiSchoolBundleRoute
  '/api/schoolinfo-proxy': typeof ApiSchoolinfoProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brainiac-songpa': typeof BrainiacSongpaRoute
  '/brainiac-songpa-high': typeof BrainiacSongpaHighRoute
  '/orun-dongjak': typeof OrunDongjakRoute
  '/orun-dongjak-high': typeof OrunDongjakHighRoute
  '/api/debug-neis': typeof ApiDebugNeisRoute
  '/api/school-bundle': typeof ApiSchoolBundleRoute
  '/api/schoolinfo-proxy': typeof ApiSchoolinfoProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brainiac-songpa': typeof BrainiacSongpaRoute
  '/brainiac-songpa-high': typeof BrainiacSongpaHighRoute
  '/orun-dongjak': typeof OrunDongjakRoute
  '/orun-dongjak-high': typeof OrunDongjakHighRoute
  '/api/debug-neis': typeof ApiDebugNeisRoute
  '/api/school-bundle': typeof ApiSchoolBundleRoute
  '/api/schoolinfo-proxy': typeof ApiSchoolinfoProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brainiac-songpa'
    | '/brainiac-songpa-high'
    | '/orun-dongjak'
    | '/orun-dongjak-high'
    | '/api/debug-neis'
    | '/api/school-bundle'
    | '/api/schoolinfo-proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brainiac-songpa'
    | '/brainiac-songpa-high'
    | '/orun-dongjak'
    | '/orun-dongjak-high'
    | '/api/debug-neis'
    | '/api/school-bundle'
    | '/api/schoolinfo-proxy'
  id:
    | '__root__'
    | '/'
    | '/brainiac-songpa'
    | '/brainiac-songpa-high'
    | '/orun-dongjak'
    | '/orun-dongjak-high'
    | '/api/debug-neis'
    | '/api/school-bundle'
    | '/api/schoolinfo-proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainiacSongpaRoute: typeof BrainiacSongpaRoute
  BrainiacSongpaHighRoute: typeof BrainiacSongpaHighRoute
  OrunDongjakRoute: typeof OrunDongjakRoute
  OrunDongjakHighRoute: typeof OrunDongjakHighRoute
  ApiDebugNeisRoute: typeof ApiDebugNeisRoute
  ApiSchoolBundleRoute: typeof ApiSchoolBundleRoute
  ApiSchoolinfoProxyRoute: typeof ApiSchoolinfoProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orun-dongjak-high': {
      id: '/orun-dongjak-high'
      path: '/orun-dongjak-high'
      fullPath: '/orun-dongjak-high'
      preLoaderRoute: typeof OrunDongjakHighRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orun-dongjak': {
      id: '/orun-dongjak'
      path: '/orun-dongjak'
      fullPath: '/orun-dongjak'
      preLoaderRoute: typeof OrunDongjakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brainiac-songpa-high': {
      id: '/brainiac-songpa-high'
      path: '/brainiac-songpa-high'
      fullPath: '/brainiac-songpa-high'
      preLoaderRoute: typeof BrainiacSongpaHighRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brainiac-songpa': {
      id: '/brainiac-songpa'
      path: '/brainiac-songpa'
      fullPath: '/brainiac-songpa'
      preLoaderRoute: typeof BrainiacSongpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schoolinfo-proxy': {
      id: '/api/schoolinfo-proxy'
      path: '/api/schoolinfo-proxy'
      fullPath: '/api/schoolinfo-proxy'
      preLoaderRoute: typeof ApiSchoolinfoProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/school-bundle': {
      id: '/api/school-bundle'
      path: '/api/school-bundle'
      fullPath: '/api/school-bundle'
      preLoaderRoute: typeof ApiSchoolBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-neis': {
      id: '/api/debug-neis'
      path: '/api/debug-neis'
      fullPath: '/api/debug-neis'
      preLoaderRoute: typeof ApiDebugNeisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainiacSongpaRoute: BrainiacSongpaRoute,
  BrainiacSongpaHighRoute: BrainiacSongpaHighRoute,
  OrunDongjakRoute: OrunDongjakRoute,
  OrunDongjakHighRoute: OrunDongjakHighRoute,
  ApiDebugNeisRoute: ApiDebugNeisRoute,
  ApiSchoolBundleRoute: ApiSchoolBundleRoute,
  ApiSchoolinfoProxyRoute: ApiSchoolinfoProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
