// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://offvlzgotgqlnecpktfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mZnZsemdvdGdxbG5lY3BrdGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMDA4NTUsImV4cCI6MjA1MDY3Njg1NX0.-Z9xhWHQmXaqqTXNbWi0hGglpcImPmSeSYsmLphkBEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);