// 영어공부 동기부여 명언 100개
export const englishStudyQuotes = [
  { en: "The limits of my language mean the limits of my world.", ko: "언어의 한계가 곧 세계의 한계다." },
  { en: "One language sets you in a corridor for life. Two languages open every door along the way.", ko: "하나의 언어는 인생의 복도에 세우고, 두 언어는 모든 문을 열어준다." },
  { en: "Learning another language is like becoming another person.", ko: "다른 언어를 배우는 것은 다른 사람이 되는 것과 같다." },
  { en: "A different language is a different vision of life.", ko: "다른 언어는 삶을 보는 다른 시각이다." },
  { en: "To have another language is to possess a second soul.", ko: "다른 언어를 가진다는 것은 두 번째 영혼을 가지는 것이다." },
  { en: "Language is the road map of a culture.", ko: "언어는 문화의 지도다." },
  { en: "You can never understand one language until you understand at least two.", ko: "최소 두 개의 언어를 이해해야 하나의 언어를 이해할 수 있다." },
  { en: "The more languages you know, the more you are human.", ko: "더 많은 언어를 알수록 더 인간적이 된다." },
  { en: "With languages, you are at home anywhere.", ko: "언어와 함께라면 어디서든 편안하다." },
  { en: "Language is the key to the heart of people.", ko: "언어는 사람들의 마음을 여는 열쇠다." },
  { en: "Every new language is a new window to look at the world.", ko: "모든 새로운 언어는 세상을 바라보는 새로운 창이다." },
  { en: "Practice makes perfect.", ko: "연습이 완벽을 만든다." },
  { en: "Mistakes are proof that you are trying.", ko: "실수는 노력하고 있다는 증거다." },
  { en: "Don't be afraid to make mistakes.", ko: "실수를 두려워하지 마라." },
  { en: "The secret of getting ahead is getting started.", ko: "앞서 나가는 비결은 시작하는 것이다." },
  { en: "Success is the sum of small efforts repeated day in and day out.", ko: "성공은 매일 반복되는 작은 노력의 합이다." },
  { en: "A journey of a thousand miles begins with a single step.", ko: "천 리 길도 한 걸음부터 시작된다." },
  { en: "Learning is a treasure that will follow its owner everywhere.", ko: "배움은 어디서든 주인을 따르는 보물이다." },
  { en: "Education is the passport to the future.", ko: "교육은 미래로 가는 여권이다." },
  { en: "Knowledge is power.", ko: "아는 것이 힘이다." },
  { en: "Reading is to the mind what exercise is to the body.", ko: "독서가 정신에 미치는 것은 운동이 몸에 미치는 것과 같다." },
  { en: "The beautiful thing about learning is that no one can take it away from you.", ko: "배움의 아름다운 점은 아무도 그것을 빼앗을 수 없다는 것이다." },
  { en: "Live as if you were to die tomorrow. Learn as if you were to live forever.", ko: "내일 죽을 것처럼 살고, 영원히 살 것처럼 배워라." },
  { en: "Speak a new language so that the world will be a new world.", ko: "새로운 언어를 말하라, 그러면 세상이 새로워질 것이다." },
  { en: "If you talk to a man in a language he understands, that goes to his head.", ko: "그가 이해하는 언어로 말하면 그의 머리에 닿는다." },
  { en: "If you talk to him in his own language, that goes to his heart.", ko: "그의 언어로 말하면 그의 마음에 닿는다." },
  { en: "Do something today that your future self will thank you for.", ko: "미래의 자신이 고마워할 일을 오늘 하라." },
  { en: "Small progress is still progress.", ko: "작은 진전도 여전히 진전이다." },
  { en: "Believe you can and you're halfway there.", ko: "할 수 있다고 믿으면 이미 절반은 온 것이다." },
  { en: "It does not matter how slowly you go as long as you do not stop.", ko: "멈추지 않는 한 얼마나 천천히 가느냐는 중요하지 않다." },
  { en: "The best time to plant a tree was 20 years ago. The second best time is now.", ko: "나무를 심기 가장 좋은 때는 20년 전이었다. 두 번째로 좋은 때는 지금이다." },
  { en: "You don't have to be great to start, but you have to start to be great.", ko: "시작하기 위해 대단할 필요는 없지만, 대단해지려면 시작해야 한다." },
  { en: "Today a reader, tomorrow a leader.", ko: "오늘의 독자가 내일의 리더다." },
  { en: "Every expert was once a beginner.", ko: "모든 전문가도 한때는 초보자였다." },
  { en: "The only way to do great work is to love what you do.", ko: "훌륭한 일을 하는 유일한 방법은 자신이 하는 일을 사랑하는 것이다." },
  { en: "Never stop learning because life never stops teaching.", ko: "인생은 끊임없이 가르치니, 배움을 멈추지 마라." },
  { en: "Your only limit is your mind.", ko: "당신의 유일한 한계는 당신의 마음이다." },
  { en: "Dream big, work hard, stay focused.", ko: "크게 꿈꾸고, 열심히 일하고, 집중하라." },
  { en: "The more you read, the more things you will know.", ko: "더 많이 읽을수록 더 많이 알게 된다." },
  { en: "Great things never come from comfort zones.", ko: "위대한 것은 안전지대에서 나오지 않는다." },
  { en: "Difficult roads often lead to beautiful destinations.", ko: "어려운 길은 종종 아름다운 목적지로 이끈다." },
  { en: "Start where you are. Use what you have. Do what you can.", ko: "지금 있는 곳에서 시작하라. 가진 것을 사용하라. 할 수 있는 것을 하라." },
  { en: "Don't watch the clock; do what it does. Keep going.", ko: "시계를 보지 말고, 시계처럼 계속 가라." },
  { en: "Push yourself, because no one else is going to do it for you.", ko: "스스로를 밀어붙여라, 아무도 대신해주지 않는다." },
  { en: "Wake up with determination. Go to bed with satisfaction.", ko: "결심을 가지고 일어나고, 만족감을 가지고 잠들어라." },
  { en: "Hard work beats talent when talent doesn't work hard.", ko: "재능이 노력하지 않을 때, 노력은 재능을 이긴다." },
  { en: "The future depends on what you do today.", ko: "미래는 오늘 무엇을 하느냐에 달려 있다." },
  { en: "Don't let yesterday take up too much of today.", ko: "어제가 오늘을 너무 많이 차지하게 하지 마라." },
  { en: "You are never too old to set another goal or dream a new dream.", ko: "새로운 목표를 세우거나 새 꿈을 꾸기에 늦은 때는 없다." },
  { en: "Quality is not an act, it is a habit.", ko: "품질은 행동이 아니라 습관이다." },
  { en: "Success doesn't just find you. You have to go out and get it.", ko: "성공은 저절로 오지 않는다. 나가서 잡아야 한다." },
  { en: "If you can dream it, you can do it.", ko: "꿈꿀 수 있다면, 할 수 있다." },
  { en: "What you get by achieving your goals is not as important as what you become.", ko: "목표를 달성해서 얻는 것보다 어떤 사람이 되느냐가 더 중요하다." },
  { en: "Don't be pushed around by the fears in your mind.", ko: "마음속 두려움에 휘둘리지 마라." },
  { en: "Everything you've ever wanted is on the other side of fear.", ko: "원하는 모든 것은 두려움 저편에 있다." },
  { en: "Be the change you wish to see in the world.", ko: "세상에서 보고 싶은 변화가 되어라." },
  { en: "It always seems impossible until it's done.", ko: "완성되기 전까지는 항상 불가능해 보인다." },
  { en: "Stay hungry, stay foolish.", ko: "갈망하라, 우직하게." },
  { en: "The only person you should try to be better than is who you were yesterday.", ko: "어제의 자신보다 더 나은 사람이 되려고 노력하라." },
  { en: "Keep your face always toward the sunshine and shadows will fall behind you.", ko: "항상 햇빛을 향하면 그림자는 뒤에 남는다." },
  { en: "Happiness is not something ready-made. It comes from your own actions.", ko: "행복은 이미 만들어진 것이 아니다. 당신의 행동에서 온다." },
  { en: "In the middle of difficulty lies opportunity.", ko: "어려움 속에 기회가 있다." },
  { en: "The best preparation for tomorrow is doing your best today.", ko: "내일을 위한 최선의 준비는 오늘 최선을 다하는 것이다." },
  { en: "Your time is limited, don't waste it living someone else's life.", ko: "시간은 한정되어 있다, 다른 사람의 삶을 사느라 낭비하지 마라." },
  { en: "Strive for progress, not perfection.", ko: "완벽이 아닌 진전을 위해 노력하라." },
  { en: "You miss 100% of the shots you don't take.", ko: "시도하지 않으면 100% 실패한다." },
  { en: "Action is the foundational key to all success.", ko: "행동은 모든 성공의 기본 열쇠다." },
  { en: "The way to get started is to quit talking and begin doing.", ko: "시작하는 방법은 말을 멈추고 행동하는 것이다." },
  { en: "Don't count the days, make the days count.", ko: "날을 세지 말고, 날이 의미 있게 하라." },
  { en: "A winner is a dreamer who never gives up.", ko: "승자는 포기하지 않는 꿈꾸는 자다." },
  { en: "Challenges are what make life interesting.", ko: "도전은 삶을 흥미롭게 만든다." },
  { en: "Overcoming them is what makes life meaningful.", ko: "그것을 극복하는 것이 삶을 의미 있게 만든다." },
  { en: "The expert in anything was once a beginner.", ko: "어떤 분야의 전문가도 한때는 초보자였다." },
  { en: "Learn from yesterday, live for today, hope for tomorrow.", ko: "어제에서 배우고, 오늘을 살고, 내일을 희망하라." },
  { en: "Education is not preparation for life; education is life itself.", ko: "교육은 삶의 준비가 아니라 삶 그 자체다." },
  { en: "The roots of education are bitter, but the fruit is sweet.", ko: "교육의 뿌리는 쓰지만, 열매는 달다." },
  { en: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", ko: "말해주면 잊고, 가르쳐주면 기억하고, 참여시키면 배운다." },
  { en: "An investment in knowledge pays the best interest.", ko: "지식에 대한 투자가 최고의 이자를 낸다." },
  { en: "The only true wisdom is in knowing you know nothing.", ko: "진정한 지혜는 아무것도 모른다는 것을 아는 것이다." },
  { en: "Reading is essential for those who seek to rise above the ordinary.", ko: "평범함을 넘어서려는 자에게 독서는 필수다." },
  { en: "Once you learn to read, you will be forever free.", ko: "읽는 법을 배우면 영원히 자유로워진다." },
  { en: "Children must be taught how to think, not what to think.", ko: "아이들에게 무엇을 생각할지가 아니라 어떻게 생각할지를 가르쳐야 한다." },
  { en: "I am always doing what I cannot do yet, in order to learn how to do it.", ko: "나는 항상 아직 할 수 없는 것을 한다, 그것을 배우기 위해." },
  { en: "Learning never exhausts the mind.", ko: "배움은 결코 마음을 지치게 하지 않는다." },
  { en: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", ko: "지혜는 학교 교육의 산물이 아니라 평생 습득하려는 시도의 산물이다." },
  { en: "The capacity to learn is a gift; the ability to learn is a skill.", ko: "배울 수 있는 능력은 선물이고, 배우는 능력은 기술이다." },
  { en: "The willingness to learn is a choice.", ko: "배우려는 의지는 선택이다." },
  { en: "Anyone who stops learning is old, whether at twenty or eighty.", ko: "배움을 멈추는 사람은 스물이든 여든이든 늙은 것이다." },
  { en: "Anyone who keeps learning stays young.", ko: "배움을 계속하는 사람은 젊음을 유지한다." },
  { en: "I have not failed. I've just found 10,000 ways that won't work.", ko: "나는 실패하지 않았다. 효과가 없는 만 가지 방법을 찾았을 뿐이다." },
  { en: "Try again. Fail again. Fail better.", ko: "다시 시도하라. 다시 실패하라. 더 잘 실패하라." },
  { en: "Genius is one percent inspiration and ninety-nine percent perspiration.", ko: "천재는 1%의 영감과 99%의 노력이다." },
  { en: "There is no substitute for hard work.", ko: "노력을 대신할 것은 없다." },
  { en: "Success is not final, failure is not fatal.", ko: "성공은 끝이 아니고, 실패는 치명적이지 않다." },
  { en: "It is the courage to continue that counts.", ko: "중요한 것은 계속할 용기다." },
  { en: "I find that the harder I work, the more luck I seem to have.", ko: "열심히 일할수록 더 운이 좋아지는 것 같다." },
  { en: "There are no secrets to success. It is the result of preparation and hard work.", ko: "성공에는 비밀이 없다. 준비와 노력의 결과다." },
];

// 날짜 기반으로 오늘의 명언 인덱스 계산
export function getTodayQuoteIndex(): number {
  const today = new Date();
  const startOfYear = new Date(today.getFullYear(), 0, 0);
  const diff = today.getTime() - startOfYear.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return dayOfYear % englishStudyQuotes.length;
}

// 오늘의 명언 가져오기
export function getTodayQuote() {
  return englishStudyQuotes[getTodayQuoteIndex()];
}
