/* Unit 2 · Field 2 — Science & Technology 과학·기술
   원서 Theme 06–10 의 주제를 예비고1 수준으로 다시 쓴 것. */
module.exports = {
 no: 2,
 field: "Science & Technology",
 ko: "과학·기술",
 tagline: "묻는 법 — 무엇을 증거로 삼을 것인가",
 next: { en: "Social Matters", ko: "사람들이 모여 만든 규칙과 그 값을 읽습니다", words: "175–205 words" },
 lessons: [
{
 no: "06", key: "twowhys",
 accent: "#2C6E8F", tint: "#E3EFF5", deep: "#1B4A61",
 en: "Two Ways to Ask Why",
 ko: "'왜'라는 말의 두 가지 뜻",
 goal: "같은 현상에 대해 기제를 묻는 질문과 의미를 묻는 질문을 구분할 수 있다.",
 fig: "Figure 1  같은 장면 앞에 선 두 과학자, 서로 다른 질문.",
 tip: "먼저 생각해 보자. 친구가 갑자기 화를 냈다. '왜?'라고 물을 때 나는 몸의 작동을 묻는 걸까, 마음의 이유를 묻는 걸까?",
 sent: [
  "A cat runs to the kitchen the moment it hears a can open.",
  "A biologist and a psychologist both watch this, and both ask why.",
  "But they are not asking the same question.",
  "The biologist looks for a mechanism.",
  "She asks which nerves carry the sound and how the muscles move.",
  "Her answer is a chain of causes that anyone could measure with instruments.",
  "The psychologist looks for a meaning.",
  "He asks what the cat expects and how a past meal shaped today's run.",
  "His answer is a story about experience rather than parts.",
  "Neither answer is wrong, and neither is complete on its own.",
  "A pure chain of chemicals cannot explain why the cat ignores the same sound in a strange house.",
  "A pure story about expectation cannot explain why the cat still runs when it is not hungry.",
  "Science makes progress when the two questions are allowed to meet.",
  "The best explanations describe both the machinery and the experience.",
  "To ask why well, you must first know which why you mean."
 ],
 kor: [
  "고양이는 캔이 열리는 소리를 듣는 순간 부엌으로 달려간다.",
  "생물학자와 심리학자가 함께 이 장면을 보고, 둘 다 '왜'냐고 묻는다.",
  "그러나 두 사람이 던지는 질문은 같은 질문이 아니다.",
  "생물학자는 작동 원리를 찾는다.",
  "그녀는 어떤 신경이 그 소리를 나르는지, 근육이 어떻게 움직이는지를 묻는다.",
  "그녀의 답은 누구나 기구로 측정할 수 있는 원인의 사슬이다.",
  "심리학자는 의미를 찾는다.",
  "그는 고양이가 무엇을 기대하는지, 지난 식사가 오늘의 달리기를 어떻게 만들었는지를 묻는다.",
  "그의 답은 부품이라기보다 경험에 관한 이야기다.",
  "어느 답도 틀리지 않았고, 어느 답도 그것만으로는 완전하지 않다.",
  "화학 물질의 사슬만으로는 그 고양이가 낯선 집에서는 같은 소리를 무시하는 이유를 설명할 수 없다.",
  "기대에 관한 이야기만으로는 배가 고프지 않은데도 고양이가 달려가는 이유를 설명할 수 없다.",
  "과학은 두 질문이 서로 만나도록 허용될 때 진전한다.",
  "가장 좋은 설명은 기계 장치와 경험을 함께 그려 낸다.",
  "'왜'를 잘 물으려면, 내가 어느 '왜'를 뜻하는지부터 알아야 한다."
 ],
 bank: [["mechanism","④","작동 원리, 기제"],["nerve","⑤","신경"],["instrument","⑥","(측정) 기구"],
        ["expectation","⑫","기대"],["machinery","⑭","기계 장치, 구조"],["progress","⑬","진전"]],
 defs: [["mechanism","the way the parts of something work together"],
        ["nerve","a thin fibre that carries signals through the body"],
        ["instrument","a tool used to measure or observe something"],
        ["expectation","a belief that something will happen"],
        ["machinery","the working parts that make something run"],
        ["progress","movement toward a better or fuller state"]],
 defOrder: [2,4,0,5,1,3],
 flow: [
  ["Scene","A cat runs when a can opens; two scientists both ask why",null],
  ["Question 1","The biologist looks for a (  ①  )","mechanism"],
  ["Question 2","The psychologist looks for a (  ②  )","meaning"],
  ["Limit","Each answer alone leaves something (  ③  )","unexplained"],
  ["Conclusion","Good science lets the two questions (  ④  )","meet"]
 ],
 flowBogi: "mechanism · meaning · unexplained · meet · measure · instrument",
 para: [
  ["③ But they are not asking the same question.","The two scientists ask ______ questions.","different"],
  ["⑥ a chain of causes that anyone could measure","The biologist's answer can be ______.","measured"],
  ["⑨ a story about experience rather than parts","The psychologist explains ______, not parts.","experience"],
  ["⑩ neither is complete on its own","Alone, each answer stays ______.","incomplete"],
  ["⑭ describe both the machinery and the experience","The best answers ______ two views.","combine"]
 ],
 paraBogi: "different · measured · experience · incomplete · combine · identical · ignore · simple",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How Cats Learn to Wait for Food","Two Different Ways to Ask Why",
       "Why Biology Explains Everything","The Tools Scientists Use in a Lab",
       "A Short History of Psychology"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["생물학자는 어떤 신경이 소리를 나르는지 묻는다.","심리학자는 고양이가 무엇을 기대하는지 묻는다.",
       "두 답 가운데 하나만 옳고 나머지는 틀리다.","배가 고프지 않을 때도 고양이가 달려가는 일이 있다.",
       "가장 좋은 설명은 기계 장치와 경험을 함께 다룬다."], ans:3},
  {t:"write", q:"필자가 과학이 진전한다고 본 조건을 우리말 한 문장으로 써 보세요.",
   ans:"기제를 묻는 질문과 의미를 묻는 질문이 서로 만나도록 허용될 때이다."}
 ],
 fl: {
  model: { n:"⑪",
   toks: [["A pure chain of chemicals","s"],["cannot explain","v"],["why","c"],
          ["the cat","s2"],["ignores","v2"],["the same sound",null],["in a strange house","m"]],
   ko:"화학 물질의 사슬만으로는 그 고양이가 낯선 집에서는 같은 소리를 무시하는 이유를 설명할 수 없다." },
  drill: [
   { n:"②", en:"A biologist and a psychologist both watch this, and both ask why.",
     ans:"S A biologist and a psychologist · △V watch · O this · [and] S both · △V ask",
     ko:"생물학자와 심리학자가 함께 이 장면을 보고, 둘 다 '왜'냐고 묻는다." },
   { n:"⑥", en:"Her answer is a chain of causes that anyone could measure with instruments.",
     ans:"S Her answer · △V is · C a chain of causes · M that anyone could measure with instruments",
     ko:"그녀의 답은 누구나 기구로 측정할 수 있는 원인의 사슬이다." },
   { n:"⑬", en:"Science makes progress when the two questions are allowed to meet.",
     ans:"S Science · △V makes · O progress · [when] S′ the two questions · △V′ are allowed to meet",
     ko:"과학은 두 질문이 서로 만나도록 허용될 때 진전한다." }
  ]
 },
 syn: [
  { n:"⑤", name:"간접의문문 — 의문사 + 주어 + 동사",
    q:"She asks «which nerves carry the sound» and how the muscles move.",
    d:"의문사절이 동사의 목적어로 올 때는 <b>의문사 + 주어 + 동사</b> 어순이다. 의문문처럼 도치하지 않는다.",
    k:"그녀는 어떤 신경이 그 소리를 나르는지를 묻는다." },
  { n:"⑬", name:"be allowed to + 동사원형 (수동태)",
    q:"Science makes progress when the two questions «are allowed to meet».",
    d:"allow A to B 의 수동형. <b>be allowed to + 동사원형</b>은 '~하도록 허용되다'라는 뜻이다.",
    k:"두 질문이 서로 만나도록 허용될 때 과학은 진전한다." }
 ],
 synd: [
  { u:"구문 1", en:"No one knows which road the car took last night.",
    k:"아무도 그 차가 어젯밤 어느 길로 갔는지 알지 못한다." },
  { u:"구문 2", en:"Students are allowed to ask questions during the talk.",
    k:"학생들은 강연 중에 질문하도록 허용된다." },
  { u:"구문 1 + 2", en:"She explained which students are allowed to enter the lab.",
    k:"그녀는 어떤 학생들이 실험실에 들어가도 되는지 설명했다." }
 ],
 wtype: ["지엽","정답","반대","무관","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["고양이는 예로 든 장면일 뿐 주제가 아니다"],["정답"],
       ["글은 생물학만으로는 부족하다고 말한다 — 정반대다"],
       ["실험 도구 목록은 글에 나오지 않는다"],["심리학의 역사는 글의 소재가 아니다"]],
 src: [["⑤"],["⑧"],["⑩과 어긋남 — 어느 답도 틀리지 않았다"],["⑫"],["⑭"]],
 kb: {
  title:"같은 장면, 다른 질문",
  lead:"한 가지 행동을 두고 학문마다 다른 것을 묻는다.",
  items: [
   ["틴베르헌의 네 가지 질문",
    "1963년 동물행동학자 니코 틴베르헌은 동물 행동을 설명하려면 네 질문이 모두 필요하다고 했다. 어떻게 작동하는가(기제), 어떻게 발달했는가, 어떤 쓸모가 있는가(기능), 어떻게 진화했는가. 앞의 둘은 '가까운 원인', 뒤의 둘은 '먼 원인'이라 부른다."],
   ["소리에 침을 흘린 개",
    "1900년대 초 이반 파블로프는 먹이를 주기 전에 신호를 들려주는 일을 반복했다. 나중에는 신호만 들려도 개가 침을 흘렸다. 몸의 반응과 학습된 기대가 한 장면에서 겹친다는 것을 보여 준 실험이다."],
   ["노벨상에 심리학상은 없다",
    "노벨상 분야에 심리학은 없지만, 심리학자 대니얼 카너먼은 2002년 노벨 경제학상을 받았다. 질문이 학문의 경계를 넘어갈 때 생기는 일이다."]
  ],
  ask:"오늘 내가 한 행동 하나를 골라 '어떻게 일어났나'와 '왜 그러고 싶었나'로 각각 답해 보자."
 }
},
{
 no: "07", key: "hunger",
 accent: "#B0542C", tint: "#FBEBE2", deep: "#7C3514",
 en: "Why Being Alone Feels Like Hunger",
 ko: "외로움이 배고픔처럼 느껴지는 이유",
 goal: "뇌 영상 실험이 무엇을 보여 주고 무엇을 보여 주지 못하는지 설명할 수 있다.",
 fig: "Figure 1  하루를 굶은 뇌와 하루를 혼자 보낸 뇌, 겹쳐 밝아지는 자리.",
 tip: "먼저 생각해 보자. 하루 종일 아무와도 말하지 않은 날, 몸에서는 어떤 느낌이 들었는가?",
 sent: [
  "In 2020 a team at MIT asked forty adults to spend ten hours completely alone.",
  "No phone, no message, no other person entered the room.",
  "On a different day the same people spent ten hours without food.",
  "After each day the researchers scanned their brains.",
  "The hungry brain and the lonely brain lit up in almost the same place.",
  "A small region deep in the middle of the brain became active in both cases.",
  "That region also becomes active when people want a drug or a reward.",
  "The researchers called the feeling a craving for company.",
  "The result suggests that being with others is not a luxury but a need.",
  "Still, a bright spot on a scan is not a feeling.",
  "The picture shows where blood is moving, not what the person is thinking.",
  "Forty people is also a small number for such a large claim.",
  "The study is a good beginning rather than a final answer.",
  "It tells us where to look next, which is what a careful experiment should do.",
  "Science often starts with a picture and then asks what the picture leaves out."
 ],
 kor: [
  "2020년 MIT의 한 연구진은 성인 마흔 명에게 열 시간을 완전히 혼자 보내게 했다.",
  "휴대전화도, 메시지도, 다른 사람도 그 방에 들어오지 않았다.",
  "다른 날에는 같은 사람들이 열 시간을 음식 없이 보냈다.",
  "각각의 하루가 끝난 뒤 연구자들은 그들의 뇌를 촬영했다.",
  "배고픈 뇌와 외로운 뇌는 거의 같은 자리에서 밝아졌다.",
  "뇌 한가운데 깊숙이 있는 작은 영역이 두 경우 모두에서 활성화되었다.",
  "그 영역은 사람이 약물이나 보상을 원할 때도 활성화된다.",
  "연구자들은 그 느낌을 '사람에 대한 갈망'이라고 불렀다.",
  "이 결과는 다른 사람과 함께 있는 일이 사치가 아니라 필요라는 것을 시사한다.",
  "그렇지만 촬영 사진 위의 밝은 점이 곧 감정인 것은 아니다.",
  "그 사진은 피가 어디로 움직이는지를 보여 줄 뿐, 그 사람이 무엇을 생각하는지를 보여 주지는 않는다.",
  "마흔 명이라는 수도 그만큼 큰 주장을 하기에는 적은 편이다.",
  "이 연구는 최종 답이라기보다 좋은 출발점이다.",
  "그것은 다음에 어디를 보아야 할지 알려 주며, 신중한 실험이라면 마땅히 해야 할 일이 그것이다.",
  "과학은 흔히 한 장의 사진에서 시작해, 그 사진이 무엇을 빼놓았는지를 묻는다."
 ],
 bank: [["scan","④","(영상으로) 촬영하다"],["region","⑥","영역, 부위"],["reward","⑦","보상"],
        ["craving","⑧","갈망"],["luxury","⑨","사치"],["claim","⑫","주장"]],
 defs: [["scan","to make a detailed picture of the inside of a body"],
        ["region","one particular area of a larger whole"],
        ["reward","something good given in return for an action"],
        ["craving","a very strong wish for something"],
        ["luxury","something pleasant that you do not really need"],
        ["claim","a statement that something is true"]],
 defOrder: [1,3,0,5,2,4],
 flow: [
  ["Setup","The same adults spent ten hours alone, and ten hours without food",null],
  ["Finding","Both days lit up almost the same (  ①  ) of the brain","region"],
  ["Reading","The researchers named the feeling a (  ②  ) for company","craving"],
  ["Caution","A bright spot shows blood, not a (  ③  )","feeling"],
  ["Conclusion","The study is a (  ④  ), not a final answer","beginning"]
 ],
 flowBogi: "region · craving · feeling · beginning · reward · picture",
 para: [
  ["⑤ lit up in almost the same place","Both states used nearly the same brain ______.","area"],
  ["⑨ being with others is not a luxury but a need","Company is a ______, not an extra.","need"],
  ["⑩ a bright spot on a scan is not a feeling","An image cannot ______ an emotion by itself.","show"],
  ["⑫ a small number for such a large claim","The sample was too ______ for the claim.","small"],
  ["⑬ a good beginning rather than a final answer","The study ______ the question, not closes it.","opens"]
 ],
 paraBogi: "area · need · show · small · opens · luxury · closes · wide",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Live Ten Hours Without Food","A Brain Picture Is a Start, Not a Proof",
       "Loneliness Has Been Fully Explained","Why MIT Is the Best Research Centre",
       "The Safest Way to Use a Brain Scanner"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["같은 사람들이 굶은 날과 혼자 지낸 날을 모두 겪었다.","약물이나 보상을 원할 때도 같은 영역이 활성화된다.",
       "연구자들은 이 결과로 외로움의 정체가 밝혀졌다고 보았다.","촬영 사진은 피가 어디로 움직이는지를 보여 준다.",
       "참가자는 마흔 명이었다."], ans:3},
  {t:"write", q:"필자가 이 실험을 '최종 답이 아니라 출발점'이라고 본 이유를 우리말 한 문장으로 써 보세요.",
   ans:"밝은 점은 감정이 아니라 혈류를 보여 줄 뿐이고, 참가자 수도 큰 주장을 하기에는 적기 때문이다."}
 ],
 fl: {
  model: { n:"⑪",
   toks: [["The picture","s"],["shows","v"],["where","c"],["blood","s2"],["is moving","v2"],
          [",",null],["not what the person is thinking","m"]],
   ko:"그 사진은 피가 어디로 움직이는지를 보여 줄 뿐, 그 사람이 무엇을 생각하는지를 보여 주지는 않는다." },
  drill: [
   { n:"①", en:"In 2020 a team at MIT asked forty adults to spend ten hours completely alone.",
     ans:"M In 2020 · S a team at MIT · △V asked · O forty adults · M to spend ten hours completely alone",
     ko:"2020년 MIT의 한 연구진은 성인 마흔 명에게 열 시간을 완전히 혼자 보내게 했다." },
   { n:"⑨", en:"The result suggests that being with others is not a luxury but a need.",
     ans:"S The result · △V suggests · [that] S′ being with others · △V′ is · C not a luxury but a need",
     ko:"이 결과는 다른 사람과 함께 있는 일이 사치가 아니라 필요라는 것을 시사한다." },
   { n:"⑭", en:"It tells us where to look next, which is what a careful experiment should do.",
     ans:"S It · △V tells · O us · O where to look next · M which is what a careful experiment should do",
     ko:"그것은 다음에 어디를 보아야 할지 알려 주며, 신중한 실험이라면 마땅히 해야 할 일이 그것이다." }
  ]
 },
 syn: [
  { n:"⑨", name:"not A but B",
    q:"The result suggests that being with others is «not a luxury but a need».",
    d:"<b>not A but B</b>는 'A가 아니라 B'. A와 B 자리에는 같은 성격의 말이 온다.",
    k:"이 결과는 함께 있는 일이 사치가 아니라 필요임을 시사한다." },
  { n:"⑭", name:"의문사 + to부정사",
    q:"It tells us «where to look next», which is what a careful experiment should do.",
    d:"<b>의문사 + to부정사</b>는 '무엇을/어디를 ~할지'라는 뜻의 명사 덩어리로, 목적어 자리에 온다.",
    k:"그것은 다음에 어디를 보아야 할지 알려 준다." }
 ],
 synd: [
  { u:"구문 1", en:"The problem was not the machine but the question behind it.",
    k:"문제는 기계가 아니라 그 뒤에 있는 질문이었다." },
  { u:"구문 2", en:"Nobody told the students when to stop the experiment.",
    k:"아무도 학생들에게 언제 실험을 멈춰야 할지 말해 주지 않았다." },
  { u:"구문 1 + 2", en:"She learned not what to measure but how to read the result.",
    k:"그녀는 무엇을 측정할지가 아니라 결과를 어떻게 읽을지를 배웠다." }
 ],
 wtype: ["무관","정답","반대","무관","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["단식하는 방법은 글의 관심사가 아니다"],["정답"],
       ["글은 아직 최종 답이 아니라고 말한다 — 정반대다"],
       ["연구 기관을 비교하는 글이 아니다"],["장비 사용법은 글에 나오지 않는다"]],
 src: [["①③"],["⑦"],["⑬과 어긋남 — 최종 답이 아니라 출발점이라고 했다"],["⑪"],["①"]],
 kb: {
  title:"뇌 사진으로 알 수 있는 것",
  lead:"밝은 점 하나가 마음을 다 설명해 주지는 않는다.",
  items: [
   ["fMRI는 피를 본다",
    "기능적 자기공명영상은 신경세포가 아니라 혈류의 산소량 변화를 잰다. 활동이 늘어난 자리에 피가 더 가는 것을 이용한 간접 측정이라, 밝은 점과 생각 사이에는 늘 한 단계가 남는다."],
   ["죽은 연어의 뇌가 반응했다",
    "2009년 크레이그 베넷 연구진은 죽은 연어를 스캐너에 넣고 사람 사진을 보여 준 뒤, 통계 보정을 하지 않으면 '반응'이 나타난다는 것을 보였다. 이 연구는 이그노벨상을 받았고, 이후 뇌 영상 연구의 통계 기준을 바꾸는 계기가 되었다."],
   ["외로움은 몸에도 남는다",
    "여러 장기 추적 연구에서 사회적 고립은 흡연·비만에 견줄 만한 건강 위험 요인으로 보고되어 왔다. 외로움이 '기분 문제'로만 다뤄지지 않게 된 배경이다."]
  ],
  ask:"뇌 사진 한 장으로 '이 사람은 지금 무엇을 느낀다'고 말할 수 있을까? 왜 그렇게 생각하는가?"
 }
},
{
 no: "08", key: "spheres",
 accent: "#4A7C46", tint: "#E7F1E5", deep: "#2E5429",
 en: "The Sky That Never Changed",
 ko: "변하지 않는다고 믿었던 하늘",
 goal: "아리스토텔레스의 두 세계 구분이 왜 오래 유지되었고 어떻게 무너졌는지 설명할 수 있다.",
 fig: "Figure 1  달을 경계로 나뉜 두 세계 — 아래는 변하고, 위는 변하지 않는다.",
 tip: "먼저 생각해 보자. 밤하늘은 어제와 오늘이 똑같아 보인다. 이 인상만으로 무엇을 결론지을 수 있을까?",
 sent: [
  "Aristotle divided the world into two regions, and the line between them was the moon.",
  "Below the moon everything was made of earth, water, air, and fire.",
  "Things down here were born, changed, and died.",
  "Above the moon he placed a fifth material that could not change at all.",
  "The stars were made of it, so they could only turn in perfect circles for ever.",
  "This picture matched what people saw every night.",
  "Fire rose, stones fell, and the stars kept the same shapes year after year.",
  "For almost two thousand years the two regions were treated as settled fact.",
  "Then in 1572 a new star appeared in the sky and stayed for months.",
  "Tycho Brahe measured it carefully and found that it stood far beyond the moon.",
  "Something in the changeless region had changed.",
  "Later Galileo turned a telescope on the moon and saw mountains and shadows.",
  "The perfect sphere had a rough surface, like the ground under his feet.",
  "The old picture had not been foolish, because it explained what the eye could reach.",
  "It fell only when the eye was given a better instrument."
 ],
 kor: [
  "아리스토텔레스는 세계를 두 영역으로 나누었고, 그 경계선은 달이었다.",
  "달 아래에서는 모든 것이 흙과 물과 공기와 불로 이루어져 있었다.",
  "이 아래의 것들은 태어나고, 변하고, 죽었다.",
  "달 위에는 전혀 변할 수 없는 다섯 번째 물질을 두었다.",
  "별들은 그것으로 만들어졌기에, 영원히 완전한 원을 그리며 돌 수밖에 없었다.",
  "이 그림은 사람들이 밤마다 보던 것과 들어맞았다.",
  "불은 올라갔고, 돌은 떨어졌으며, 별들은 해마다 같은 모양을 지켰다.",
  "거의 이천 년 동안 이 두 영역은 정해진 사실처럼 다루어졌다.",
  "그러다 1572년, 새로운 별 하나가 하늘에 나타나 몇 달 동안 머물렀다.",
  "튀코 브라헤는 그것을 정밀하게 측정했고, 그 별이 달보다 훨씬 멀리 있다는 것을 알아냈다.",
  "변하지 않는다던 영역에서 무언가가 변한 것이다.",
  "뒤에 갈릴레오는 망원경을 달에 겨누었고, 산과 그림자를 보았다.",
  "완전한 구는 발밑의 땅처럼 거친 표면을 지니고 있었다.",
  "옛 그림이 어리석었던 것은 아니다. 눈이 닿는 범위를 설명해 냈기 때문이다.",
  "그것은 눈에 더 좋은 도구가 주어졌을 때에야 무너졌다."
 ],
 bank: [["divide","①","나누다"],["material","④","물질"],["settled","⑧","정해진, 확정된"],
        ["measure","⑩","측정하다"],["sphere","⑬","구(球)"],["surface","⑬","표면"]],
 defs: [["divide","to separate something into parts"],
        ["material","the substance that a thing is made of"],
        ["settled","fixed and no longer open to argument"],
        ["measure","to find the exact size or amount of something"],
        ["sphere","a perfectly round solid shape"],
        ["surface","the outside layer of an object"]],
 defOrder: [4,0,5,2,3,1],
 flow: [
  ["The picture","Aristotle split the world at the moon: changing below, perfect above",null],
  ["Why it held","It matched what the (  ①  ) could see every night","eye"],
  ["First crack","In 1572 a new star appeared beyond the (  ②  )","moon"],
  ["Second crack","Galileo's telescope showed a rough (  ③  ) on the moon","surface"],
  ["Conclusion","The old picture fell when the eye got a better (  ④  )","instrument"]
 ],
 flowBogi: "eye · moon · surface · instrument · circle · fire",
 para: [
  ["③ Things down here were born, changed, and died.","Below the moon nothing stayed ______.","fixed"],
  ["⑧ the two regions were treated as settled fact","For centuries nobody ______ the division.","questioned"],
  ["⑪ Something in the changeless region had changed.","The 1572 star ______ the old rule.","broke"],
  ["⑬ The perfect sphere had a rough surface","The moon looked less ______ than believed.","perfect"],
  ["⑮ when the eye was given a better instrument","Better ______ ended the old picture.","tools"]
 ],
 paraBogi: "fixed · questioned · broke · perfect · tools · proved · rough · faith",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Life of Aristotle","How Telescopes Are Built",
       "A Picture That Held Until Better Tools Came","Why the Stars Move in Circles",
       "The Five Materials of the Ancient World"], ans:3},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["아리스토텔레스는 달을 두 영역의 경계로 삼았다.","달 위의 물질은 변할 수 없다고 여겨졌다.",
       "튀코 브라헤는 새 별이 달보다 가까이 있다고 밝혔다.","갈릴레오는 달에서 산과 그림자를 보았다.",
       "필자는 옛 그림이 어리석었던 것은 아니라고 본다."], ans:3},
  {t:"write", q:"필자가 옛 그림을 '어리석지 않았다'고 본 이유를 우리말 한 문장으로 써 보세요.",
   ans:"당시 눈이 닿는 범위 안의 관찰을 잘 설명해 냈기 때문이다."}
 ],
 fl: {
  model: { n:"⑤",
   toks: [["The stars","s"],["were made","v"],["of it","m"],["so","c"],["they","s2"],
          ["could only turn","v2"],["in perfect circles for ever","m"]],
   ko:"별들은 그것으로 만들어졌기에, 영원히 완전한 원을 그리며 돌 수밖에 없었다." },
  drill: [
   { n:"①", en:"Aristotle divided the world into two regions, and the line between them was the moon.",
     ans:"S Aristotle · △V divided · O the world · M into two regions · [and] S the line between them · △V was · C the moon",
     ko:"아리스토텔레스는 세계를 두 영역으로 나누었고, 그 경계선은 달이었다." },
   { n:"⑩", en:"Tycho Brahe measured it carefully and found that it stood far beyond the moon.",
     ans:"S Tycho Brahe · △V measured · O it · M carefully · [and] △V found · [that] S′ it · △V′ stood · M far beyond the moon",
     ko:"튀코 브라헤는 그것을 정밀하게 측정했고, 그 별이 달보다 훨씬 멀리 있다는 것을 알아냈다." },
   { n:"⑭", en:"The old picture had not been foolish, because it explained what the eye could reach.",
     ans:"S The old picture · △V had not been · C foolish · [because] S′ it · △V′ explained · O what the eye could reach",
     ko:"옛 그림이 어리석었던 것은 아니다. 눈이 닿는 범위를 설명해 냈기 때문이다." }
  ]
 },
 syn: [
  { n:"⑭", name:"과거완료 had p.p.",
    q:"The old picture «had not been» foolish, because it explained what the eye could reach.",
    d:"<b>had + p.p.</b>는 과거의 어느 시점보다 <b>더 앞선 때</b>를 가리킨다. 무너진 때보다 앞선 사정을 말한다.",
    k:"그 옛 그림이 (그때까지) 어리석었던 것은 아니었다." },
  { n:"⑮", name:"수여동사의 수동태 — be given",
    q:"It fell only when the eye «was given» a better instrument.",
    d:"give A B 에서 A를 주어로 올리면 <b>be given + B</b> 가 된다. 뒤에 목적어 하나가 그대로 남는다.",
    k:"그것은 눈에 더 좋은 도구가 주어졌을 때에야 무너졌다." }
 ],
 synd: [
  { u:"구문 1", en:"By 1600 the old model had already lost most of its defenders.",
    k:"1600년 무렵 그 옛 모형은 이미 지지자 대부분을 잃은 상태였다." },
  { u:"구문 2", en:"Each student was given a small telescope for the night.",
    k:"학생들은 저마다 그날 밤에 쓸 작은 망원경을 받았다." },
  { u:"구문 1 + 2", en:"He had been given the data long before he understood it.",
    k:"그는 그 자료를 이해하기 훨씬 전에 이미 받아 두었었다." }
 ],
 wtype: ["무관","무관","정답","지엽","배경"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["아리스토텔레스의 생애는 글의 주제가 아니다"],["망원경 제작법은 글에 나오지 않는다"],["정답"],
       ["별의 원운동은 옛 그림의 한 부분일 뿐이다"],["네 원소는 설명의 배경이지 결론이 아니다"]],
 src: [["①"],["④"],["⑩과 어긋남 — 달보다 훨씬 멀리 있었다"],["⑫"],["⑭"]],
 kb: {
  title:"하늘이 바뀐 순간들",
  lead:"관측 도구가 바뀌면 세계의 지도도 바뀐다.",
  items: [
   ["1572년의 새 별",
    "튀코 브라헤가 관측한 이 별은 오늘날 초신성 SN 1572로 불린다. 그는 시차가 나타나지 않는 것을 근거로 이 별이 달보다 훨씬 멀리 있다고 결론지었다. 하늘도 변한다는 첫 정밀 증거였다."],
   ["갈릴레오의 1610년 『별의 소식』",
    "갈릴레오는 달의 산과 목성의 위성 네 개를 기록해 『Sidereus Nuncius』로 펴냈다. 목성을 도는 천체가 있다는 사실은 모든 것이 지구를 돈다는 전제를 흔들었다."],
   ["에테르는 왜 오래 남았나",
    "달 위를 채운다던 제5원소는 뒤에 '에테르'라는 이름으로 19세기까지 살아남았다. 1887년 마이컬슨·몰리 실험이 그 흔적을 찾지 못하면서 물리학은 다시 한 번 그림을 고쳐 그렸다."]
  ],
  ask:"지금 우리가 '당연하다'고 여기는 것 가운데, 더 좋은 도구가 나오면 흔들릴 만한 것은 무엇일까?"
 }
},
{
 no: "09", key: "zipper",
 accent: "#7A4FA3", tint: "#F0EAF7", deep: "#4E2E70",
 en: "The Zipper You Cannot Explain",
 ko: "설명하지 못하는 지퍼",
 goal: "'안다는 느낌'과 '실제로 아는 것'의 차이를 예를 들어 설명할 수 있다.",
 fig: "Figure 1  머릿속의 자전거와 실제 자전거 사이의 거리.",
 tip: "먼저 생각해 보자. 지퍼가 어떻게 잠기는지 그림 없이 말로만 설명할 수 있는가?",
 sent: [
  "Ask anyone whether they know how a zipper works.",
  "Almost everyone says yes without pausing.",
  "Then ask them to explain it step by step, out loud, without using their hands.",
  "The confident voice slows down, searches for words, and often stops altogether.",
  "Psychologists call this gap the illusion of explanatory depth.",
  "We mistake being familiar with something for understanding it.",
  "A zipper is close to us every day, so the feeling of knowing comes easily.",
  "In one study people were asked to draw a bicycle from memory, with the frame and chain in place.",
  "Many drew chains that could never turn the wheels.",
  "The drawings were wrong in ways the artists had never noticed.",
  "The illusion is not a sign of a lazy mind.",
  "It is useful, because we cannot carry full explanations of every object we touch.",
  "The danger appears when the same easy feeling reaches much larger questions about the world.",
  "People who have never explained a policy still argue about it with certainty.",
  "One cure is simple: try to explain the thing, and let the gap show itself."
 ],
 kor: [
  "누구에게든 지퍼가 어떻게 작동하는지 아느냐고 물어보라.",
  "거의 모두가 망설임 없이 안다고 답한다.",
  "그런 다음 손을 쓰지 말고 소리 내어 단계별로 설명해 보라고 해 보라.",
  "자신 있던 목소리가 느려지고, 말을 더듬다가, 흔히 아예 멈춘다.",
  "심리학자들은 이 간극을 '설명 깊이의 착각'이라고 부른다.",
  "우리는 무언가에 익숙한 것을 그것을 이해한 것으로 착각한다.",
  "지퍼는 날마다 우리 곁에 있으므로, 안다는 느낌이 쉽게 생긴다.",
  "한 연구에서는 사람들에게 기억만으로, 뼈대와 체인까지 제자리에 넣어 자전거를 그려 보게 했다.",
  "많은 사람이 결코 바퀴를 돌릴 수 없는 체인을 그렸다.",
  "그 그림들은 그린 사람이 한 번도 알아채지 못한 방식으로 틀려 있었다.",
  "이 착각은 게으른 머리의 표시가 아니다.",
  "그것은 쓸모가 있다. 우리가 만지는 모든 물건의 완전한 설명을 지니고 다닐 수는 없기 때문이다.",
  "위험은 그 손쉬운 느낌이 세상에 관한 훨씬 큰 질문에까지 닿을 때 나타난다.",
  "어떤 정책을 한 번도 설명해 본 적 없는 사람들이 그것을 두고 확신에 차서 다툰다.",
  "한 가지 치료법은 간단하다. 그것을 설명해 보고, 간극이 스스로 드러나게 하는 것이다."
 ],
 bank: [["pause","②","잠시 멈추다"],["gap","⑤","간극, 틈"],["illusion","⑤","착각"],
        ["familiar","⑥","익숙한"],["certainty","⑭","확신"],["cure","⑮","치료법, 해결책"]],
 defs: [["pause","to stop for a short time before going on"],
        ["gap","a space between two things that should meet"],
        ["illusion","a belief that does not match what is real"],
        ["familiar","well known because it is often seen"],
        ["certainty","the state of having no doubt at all"],
        ["cure","something that ends a problem or an illness"]],
 defOrder: [3,0,4,2,5,1],
 flow: [
  ["Test","Ask people to explain a zipper, and the confident voice stops",null],
  ["Name","Psychologists call this the illusion of explanatory (  ①  )","depth"],
  ["Cause","We mistake being (  ②  ) with a thing for understanding it","familiar"],
  ["Defence","The illusion is (  ③  ), since we cannot store every explanation","useful"],
  ["Warning","It turns dangerous on (  ④  ) questions, and explaining is the cure","larger"]
 ],
 flowBogi: "depth · familiar · useful · larger · lazy · drawing",
 para: [
  ["② Almost everyone says yes without pausing.","People answer with instant ______.","confidence"],
  ["⑥ We mistake being familiar with something","Closeness gets ______ for knowledge.","mistaken"],
  ["⑩ wrong in ways the artists had never noticed","The errors stayed ______ to the drawers.","invisible"],
  ["⑪ The illusion is not a sign of a lazy mind.","The gap does not mean people are ______.","careless"],
  ["⑮ let the gap show itself","Explaining ______ what we do not know.","reveals"]
 ],
 paraBogi: "confidence · mistaken · invisible · careless · reveals · doubt · hides · lazy",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The History of the Zipper","Feeling You Know Is Not Knowing",
       "How to Draw a Bicycle Correctly","Why Most People Have Lazy Minds",
       "A Guide to Explaining Government Policy"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["대부분은 지퍼를 안다고 곧바로 답한다.","기억만으로 자전거를 그리게 한 연구가 있었다.",
       "필자는 이 착각을 게으름의 증거로 본다.","익숙함은 안다는 느낌을 쉽게 만든다.",
       "설명해 보는 것이 한 가지 해결책이다."], ans:3},
  {t:"write", q:"필자가 이 착각을 '쓸모 있다'고 본 이유를 우리말 한 문장으로 써 보세요.",
   ans:"우리가 만지는 모든 물건의 완전한 설명을 지니고 다닐 수는 없기 때문이다."}
 ],
 fl: {
  model: { n:"⑫",
   toks: [["It","s"],["is","v"],["useful","c"],["because","c"],["we","s2"],
          ["cannot carry","v2"],["full explanations","m"],["of every object we touch","m"]],
   ko:"그것은 쓸모가 있다. 우리가 만지는 모든 물건의 완전한 설명을 지니고 다닐 수는 없기 때문이다." },
  drill: [
   { n:"⑥", en:"We mistake being familiar with something for understanding it.",
     ans:"S We · △V mistake · O being familiar with something · M for understanding it",
     ko:"우리는 무언가에 익숙한 것을 그것을 이해한 것으로 착각한다." },
   { n:"⑩", en:"The drawings were wrong in ways the artists had never noticed.",
     ans:"S The drawings · △V were · C wrong · M in ways the artists had never noticed",
     ko:"그 그림들은 그린 사람이 한 번도 알아채지 못한 방식으로 틀려 있었다." },
   { n:"⑭", en:"People who have never explained a policy still argue about it with certainty.",
     ans:"S People · M who have never explained a policy · △V argue · M about it, with certainty",
     ko:"어떤 정책을 한 번도 설명해 본 적 없는 사람들이 그것을 두고 확신에 차서 다툰다." }
  ]
 },
 syn: [
  { n:"⑥", name:"mistake A for B",
    q:"We «mistake being familiar with something for understanding it».",
    d:"<b>mistake A for B</b>는 'A를 B로 잘못 알다'. A·B 자리에 동명사가 오면 '~하는 것'으로 옮긴다.",
    k:"우리는 익숙한 것을 이해한 것으로 착각한다." },
  { n:"⑭", name:"주격 관계대명사절 + 현재완료",
    q:"People «who have never explained a policy» still argue about it with certainty.",
    d:"who 뒤의 절이 주어 People 을 꾸민다. <b>have never p.p.</b>는 '지금까지 한 번도 ~한 적 없다'.",
    k:"어떤 정책을 한 번도 설명해 본 적 없는 사람들이 그것을 두고 확신에 차서 다툰다." }
 ],
 synd: [
  { u:"구문 1", en:"Do not mistake a loud voice for a good argument.",
    k:"큰 목소리를 좋은 논증으로 착각하지 마라." },
  { u:"구문 2", en:"The student who has never drawn a map still finished first.",
    k:"지도를 한 번도 그려 본 적 없는 그 학생이 그래도 가장 먼저 끝냈다." },
  { u:"구문 1 + 2", en:"Readers who have never built anything mistake plans for buildings.",
    k:"무언가를 만들어 본 적 없는 독자들은 설계도를 건물로 착각한다." }
 ],
 wtype: ["무관","정답","지엽","반대","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["지퍼의 역사는 글에 나오지 않는다"],["정답"],
       ["자전거 그림은 착각을 보여 주는 실험 하나일 뿐이다"],
       ["글은 게으른 머리의 표시가 아니라고 말한다 — 정반대다"],
       ["정책 설명 요령을 알려 주는 글이 아니다"]],
 src: [["②"],["⑧"],["⑪과 어긋남 — 게으름의 표시가 아니라고 했다"],["⑦"],["⑮"]],
 kb: {
  title:"안다는 느낌의 정체",
  lead:"머릿속 그림은 생각보다 훨씬 성기다.",
  items: [
   ["'설명 깊이의 착각'이라는 이름",
    "2002년 레오니드 로젠블릿과 프랭크 케일은 사람들에게 변기·자물쇠·헬리콥터의 작동을 설명하게 한 뒤, 설명 전후로 자기 이해도를 매기게 했다. 설명을 시도한 뒤 점수는 일관되게 떨어졌다."],
   ["자전거를 그려 보라고 하면",
    "심리학자 리베카 로슨의 연구에서 성인 대다수가 체인·페달·프레임의 위치를 틀리게 그렸다. 자전거를 매일 타는 사람도 예외가 아니었다."],
   ["파인만이 남긴 기준",
    "물리학자 리처드 파인만은 어떤 개념을 처음 배우는 사람에게 쉬운 말로 설명해 보는 것을 이해의 시험으로 삼았다. 막히는 지점이 곧 모르는 지점이다."]
  ],
  ask:"내가 '안다'고 여기는 것 하나를 골라 3분 동안 소리 내어 설명해 보자. 어디에서 막히는가?"
 }
},
{
 no: "10", key: "doubt",
 accent: "#C2455E", tint: "#FAE7EB", deep: "#8C2740",
 en: "Doubt Is the Method",
 ko: "의심은 방법이다",
 goal: "과학적 회의가 '거부'가 아니라 '증거 요구'임을 구별해 설명할 수 있다.",
 fig: "Figure 1  주장의 크기만큼 무거워지는 증거의 저울.",
 tip: "먼저 생각해 보자. 친구가 '어제 유령을 봤다'고 한다. 믿거나 안 믿거나 말고, 세 번째 반응이 있을까?",
 sent: [
  "People often use the word skeptic to mean someone who refuses to believe.",
  "In science the word means almost the opposite.",
  "A skeptic does not close the question; a skeptic asks what would settle it.",
  "The rule behind this habit is simple to state, though it is harder to live by.",
  "The stronger a claim is, the heavier the evidence it has to carry.",
  "A report that a train was late needs little more than a timetable and a witness.",
  "A report that a train travelled faster than light needs far more.",
  "This is not unfairness; it is bookkeeping.",
  "Ordinary claims fit neatly into the world we have already measured and written down.",
  "Extraordinary ones ask us to pull down and rebuild part of that world.",
  "In 2011 a laboratory announced particles that seemed to beat light.",
  "Other teams did not shout, and they did not stay silent either.",
  "They repeated the measurement and found a loose cable in the timing system.",
  "The claim fell, and no one had to be called a liar.",
  "Doubt had done its work quietly, the way it is supposed to."
 ],
 kor: [
  "사람들은 흔히 '회의론자'라는 말을 믿기를 거부하는 사람이라는 뜻으로 쓴다.",
  "과학에서 그 말은 거의 반대를 뜻한다.",
  "회의론자는 질문을 닫지 않는다. 무엇이 그 질문을 결판낼지를 묻는다.",
  "이 태도의 밑에 있는 규칙은 말하기는 쉽지만, 지키기는 더 어렵다.",
  "주장이 강할수록, 그것이 져야 할 증거도 무거워진다.",
  "기차가 늦었다는 보고에는 시간표와 목격자 정도면 충분하다.",
  "기차가 빛보다 빨리 갔다는 보고에는 훨씬 더 많은 것이 필요하다.",
  "이것은 불공평이 아니라 장부 정리다.",
  "평범한 주장은 우리가 이미 측정하고 적어 둔 세계에 무리 없이 들어맞는다.",
  "비범한 주장은 그 세계의 일부를 헐고 다시 세우라고 요구한다.",
  "2011년 한 실험실이 빛을 이긴 것처럼 보이는 입자를 발표했다.",
  "다른 연구진들은 소리치지 않았고, 그렇다고 잠자코 있지도 않았다.",
  "그들은 측정을 되풀이했고, 시간 측정 장치에서 헐거워진 케이블 하나를 찾아냈다.",
  "주장은 무너졌고, 아무도 거짓말쟁이로 불릴 필요가 없었다.",
  "의심은 제 일을 조용히 해냈다. 본래 그래야 하는 방식대로."
 ],
 bank: [["refuse","①","거부하다"],["settle","③","결판내다"],["claim","⑤","주장"],
        ["evidence","⑤","증거"],["extraordinary","⑩","비범한, 이례적인"],["repeat","⑬","되풀이하다"]],
 defs: [["refuse","to say that you will not do something"],
        ["settle","to end a question by deciding it"],
        ["claim","a statement offered as true without proof yet"],
        ["evidence","facts that support or test a statement"],
        ["extraordinary","far beyond what is usual or expected"],
        ["repeat","to do the same thing again"]],
 defOrder: [2,4,0,3,5,1],
 flow: [
  ["Wrong sense","Everyday use makes a skeptic someone who refuses to believe",null],
  ["Right sense","A skeptic asks what would (  ①  ) the question","settle"],
  ["The rule","The stronger the claim, the heavier the (  ②  )","evidence"],
  ["Case","In 2011 a faster-than-light result was (  ③  ) by other teams","repeated"],
  ["Result","A loose (  ④  ) explained it, and no one was blamed","cable"]
 ],
 flowBogi: "settle · evidence · repeated · cable · refuse · silence",
 para: [
  ["③ a skeptic asks what would settle it","A skeptic keeps the question ______.","open"],
  ["⑤ the heavier the evidence it has to carry","Big claims need ______ support.","stronger"],
  ["⑧ This is not unfairness; it is bookkeeping.","The rule is ______, not hostile.","fair"],
  ["⑫ they did not stay silent either","The other teams neither shouted nor stayed ______.","quiet"],
  ["⑭ no one had to be called a liar","The result fell without ______ anyone.","blaming"]
 ],
 paraBogi: "open · stronger · fair · quiet · blaming · closed · weaker · trusting",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["Why Trains Are Often Late","Doubt That Asks Instead of Refusing",
       "How to Win a Scientific Argument","The 2011 Discovery That Changed Physics",
       "A Beginner's Guide to Cable Repair"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["일상에서 '회의론자'는 믿기를 거부하는 사람을 뜻하곤 한다.","주장이 강할수록 필요한 증거도 무거워진다.",
       "2011년의 발표는 다른 연구진의 침묵 속에 잊혔다.","문제의 원인은 헐거워진 케이블이었다.",
       "필자는 이 규칙을 불공평이 아니라 장부 정리로 본다."], ans:3},
  {t:"write", q:"필자가 말하는 과학적 회의가 일상의 '거부'와 어떻게 다른지 우리말 한 문장으로 써 보세요.",
   ans:"질문을 닫아 버리는 대신 무엇이 그 질문을 결판낼지를 묻는다는 점에서 다르다."}
 ],
 fl: {
  model: { n:"⑤",
   toks: [["The stronger","c"],["a claim","s2"],["is","v2"],[",",null],
          ["the heavier","c"],["the evidence","s"],["it has to carry","m"]],
   ko:"주장이 강할수록, 그것이 져야 할 증거도 무거워진다." },
  drill: [
   { n:"③", en:"A skeptic does not close the question; a skeptic asks what would settle it.",
     ans:"S A skeptic · △V does not close · O the question · S a skeptic · △V asks · O what would settle it",
     ko:"회의론자는 질문을 닫지 않는다. 무엇이 그 질문을 결판낼지를 묻는다." },
   { n:"⑪", en:"In 2011 a laboratory announced particles that seemed to beat light.",
     ans:"M In 2011 · S a laboratory · △V announced · O particles · M that seemed to beat light",
     ko:"2011년 한 실험실이 빛을 이긴 것처럼 보이는 입자를 발표했다." },
   { n:"⑬", en:"They repeated the measurement and found a loose cable in the timing system.",
     ans:"S They · △V repeated · O the measurement · [and] △V found · O a loose cable · M in the timing system",
     ko:"그들은 측정을 되풀이했고, 시간 측정 장치에서 헐거워진 케이블 하나를 찾아냈다." }
  ]
 },
 syn: [
  { n:"⑤", name:"the 비교급 ~, the 비교급 …",
    q:"«The stronger a claim is, the heavier the evidence» it has to carry.",
    d:"<b>the + 비교급 ~, the + 비교급 …</b>는 '~할수록 더 …하다'. 앞뒤 절의 순서를 바꾸지 않는다.",
    k:"주장이 강할수록 그것이 져야 할 증거도 무거워진다." },
  { n:"⑪", name:"seem to + 동사원형",
    q:"A laboratory announced particles that «seemed to beat» light.",
    d:"<b>seem to + 동사원형</b>은 '~하는 것처럼 보이다'. 사실 단정이 아니라 관찰자의 인상을 나타낸다.",
    k:"빛을 이긴 것처럼 보이는 입자들을 발표했다." }
 ],
 synd: [
  { u:"구문 1", en:"The louder the room became, the harder the test felt.",
    k:"방이 시끄러워질수록 시험은 더 어렵게 느껴졌다." },
  { u:"구문 2", en:"The second team seemed to find the same error.",
    k:"두 번째 연구진도 같은 오류를 찾아낸 것처럼 보였다." },
  { u:"구문 1 + 2", en:"The stranger a result seems to be, the longer it should be checked.",
    k:"결과가 이상해 보일수록 더 오래 검증해야 한다." }
 ],
 wtype: ["지엽","정답","무관","지엽","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["기차는 규칙을 설명하는 예시일 뿐이다"],["정답"],
       ["논쟁에서 이기는 법은 글의 관심사가 아니다"],
       ["2011년 사례는 주장을 뒷받침하는 한 예이고, 물리학이 바뀌지도 않았다"],
       ["케이블 수리법은 글에 나오지 않는다"]],
 src: [["①"],["⑤"],["⑫과 어긋남 — 잠자코 있지 않고 측정을 되풀이했다"],["⑬"],["⑧"]],
 kb: {
  title:"의심이 일한 방식",
  lead:"무너뜨리는 일도 절차를 지켜야 한다.",
  items: [
   ["OPERA 실험, 2011",
    "이탈리아 그란사소 연구소의 OPERA 팀은 중성미자가 빛보다 약 60나노초 빨리 도착한 것으로 보인다고 발표하면서, 확정이 아니라 검증 요청임을 분명히 했다. 2012년 광섬유 연결 불량과 발진기 문제가 원인으로 확인되었다."],
   ["'비범한 주장에는 비범한 증거를'",
    "이 표현은 1979년 칼 세이건이 널리 퍼뜨렸지만, 뿌리는 18세기 흄과 라플라스의 논의로 거슬러 올라간다. 증거의 무게를 주장의 크기에 맞추라는 원칙이다."],
   ["재현이 곧 검증이다",
    "2010년대 여러 분야에서 재현 실험이 실패하는 사례가 잇따르자, 학술지들은 자료와 분석 코드 공개, 사전등록 같은 절차를 도입했다. 의심을 개인의 태도가 아니라 제도로 옮긴 셈이다."]
  ],
  ask:"내가 최근에 믿은 이야기 하나를 골라 보자. 그것이 틀렸다면 무엇을 보고 알 수 있을까?"
 }
}
]};
