/* Unit 3 · Field 3 — Social Matters 사회 문제
   원서 Theme 11–15 의 주제를 예비고1 수준으로 다시 쓴 것. */
module.exports = {
 no: 3,
 field: "Social Matters",
 ko: "사회 문제",
 tagline: "단순화의 값 — 모형·농담·숫자가 덜어 낸 것들",
 next: { en: "Medicine & Health", ko: "몸을 다루는 지식이 어떻게 쌓였는지 읽습니다", words: "175–205 words" },
 lessons: [
{
 no: "11", key: "model",
 accent: "#3E6FA8", tint: "#E5EDF7", deep: "#25476E",
 en: "The Map Is Not the City",
 ko: "지도는 도시가 아니다",
 goal: "경제 모형이 무엇을 일부러 버리고 그 대가로 무엇을 얻는지 설명할 수 있다.",
 fig: "Figure 1  지하철 노선도와 실제 거리 — 버린 것과 남긴 것.",
 tip: "먼저 생각해 보자. 지하철 노선도는 실제 거리와 다르다. 그런데도 왜 더 쓸모가 있을까?",
 sent: [
  "A subway map shows straight lines and even spaces between stations.",
  "The real tunnels curve, and the distances are never equal.",
  "The map lies about the ground, and that is exactly why it works.",
  "It answers one question well: which train takes you where.",
  "Economic models are built in the same spirit.",
  "A model of a market may assume that every buyer knows every price.",
  "No real shopper knows that, and the modeller knows it too.",
  "The assumption is not a mistake but a tool for holding one thing still.",
  "By freezing information, the model can show what supply and demand alone would do.",
  "Trouble begins when people forget which parts were frozen on purpose.",
  "A map drawn for trains cannot tell you where to find a quiet street.",
  "In 2008 several models assumed that house prices could not fall everywhere at once.",
  "The assumption had been useful for years, and then it was not.",
  "A good reader of models asks what was left out before asking what was proved.",
  "Every model is a map, and no map is the city."
 ],
 kor: [
  "지하철 노선도는 곧은 선과 역 사이의 고른 간격을 보여 준다.",
  "실제 터널은 굽어 있고, 거리도 결코 똑같지 않다.",
  "그 지도는 땅에 대해 거짓말을 하는데, 바로 그 때문에 쓸모가 있다.",
  "그것은 한 가지 질문에 잘 답한다. 어느 열차가 나를 어디로 데려다주는가.",
  "경제 모형도 같은 정신으로 만들어진다.",
  "어떤 시장 모형은 모든 구매자가 모든 가격을 안다고 가정할 수 있다.",
  "실제로 그런 것을 아는 손님은 없고, 모형을 만든 사람도 그것을 안다.",
  "그 가정은 실수가 아니라 한 가지를 고정해 두기 위한 도구다.",
  "정보를 얼려 둠으로써, 그 모형은 공급과 수요만으로 무슨 일이 일어날지를 보여 줄 수 있다.",
  "문제는 어느 부분이 일부러 얼려진 것인지 사람들이 잊을 때 시작된다.",
  "열차를 위해 그린 지도는 조용한 거리가 어디인지 알려 줄 수 없다.",
  "2008년, 여러 모형은 집값이 모든 곳에서 동시에 떨어질 수는 없다고 가정하고 있었다.",
  "그 가정은 여러 해 동안 쓸모가 있었고, 그러다 아니게 되었다.",
  "모형을 잘 읽는 사람은 무엇이 증명되었는지 묻기 전에 무엇이 빠졌는지를 묻는다.",
  "모든 모형은 지도이며, 어떤 지도도 도시 그 자체는 아니다."
 ],
 bank: [["curve","②","굽다"],["assume","⑥","가정하다"],["assumption","⑧","가정"],
        ["supply","⑨","공급"],["demand","⑨","수요"],["prove","⑭","증명하다"]],
 defs: [["curve","to bend in a smooth line"],
        ["assume","to accept something as true before checking"],
        ["assumption","a thing taken as true so that work can start"],
        ["supply","the amount of a good that is offered for sale"],
        ["demand","the amount of a good that buyers want"],
        ["prove","to show beyond doubt that something is true"]],
 defOrder: [1,4,0,5,2,3],
 flow: [
  ["Image","A subway map straightens the tunnels, and that is why it works",null],
  ["Parallel","A market model may (  ①  ) that buyers know every price","assume"],
  ["Purpose","The assumption is a tool for holding one thing (  ②  )","still"],
  ["Risk","Trouble starts when people forget what was frozen on (  ③  )","purpose"],
  ["Rule","Ask what was left (  ④  ) before asking what was proved","out"]
 ],
 flowBogi: "assume · still · purpose · out · prove · curve",
 para: [
  ["③ The map lies about the ground","The map is not ______ to the real city.","faithful"],
  ["⑦ No real shopper knows that","The assumption never matches ______ life.","real"],
  ["⑧ not a mistake but a tool","The gap is ______, not an error.","deliberate"],
  ["⑩ forget which parts were frozen on purpose","Danger comes from ______ the assumptions.","forgetting"],
  ["⑮ no map is the city","A model never ______ the world itself.","becomes"]
 ],
 paraBogi: "faithful · real · deliberate · forgetting · becomes · careless · listing · leaves",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Read a Subway Map","Why Models Simplify, and What That Costs",
       "Economic Models Are Always Wrong","The Housing Crash of 2008",
       "A Short History of Supply and Demand"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["지하철 노선도의 간격은 실제 거리와 다르다.","모형을 만든 사람도 가정이 현실과 다름을 안다.",
       "필자는 가정을 모형의 실수로 본다.","2008년의 가정은 여러 해 동안 쓸모가 있었다.",
       "모형을 잘 읽으려면 빠진 것을 먼저 물어야 한다."], ans:3},
  {t:"write", q:"필자가 모형의 가정을 '실수가 아니다'라고 본 이유를 우리말 한 문장으로 써 보세요.",
   ans:"한 가지를 고정해 두어야 나머지가 어떻게 움직이는지 볼 수 있기 때문이다."}
 ],
 fl: {
  model: { n:"⑨",
   toks: [["By freezing information","m"],[",",null],["the model","s"],["can show","v"],
          ["what","c"],["supply and demand alone","s2"],["would do","v2"]],
   ko:"정보를 얼려 둠으로써, 그 모형은 공급과 수요만으로 무슨 일이 일어날지를 보여 줄 수 있다." },
  drill: [
   { n:"③", en:"The map lies about the ground, and that is exactly why it works.",
     ans:"S The map · △V lies · M about the ground · [and] S that · △V is · C exactly why it works",
     ko:"그 지도는 땅에 대해 거짓말을 하는데, 바로 그 때문에 쓸모가 있다." },
   { n:"⑩", en:"Trouble begins when people forget which parts were frozen on purpose.",
     ans:"S Trouble · △V begins · [when] S′ people · △V′ forget · O which parts were frozen on purpose",
     ko:"문제는 어느 부분이 일부러 얼려진 것인지 사람들이 잊을 때 시작된다." },
   { n:"⑭", en:"A good reader of models asks what was left out before asking what was proved.",
     ans:"S A good reader of models · △V asks · O what was left out · M before asking what was proved",
     ko:"모형을 잘 읽는 사람은 무엇이 증명되었는지 묻기 전에 무엇이 빠졌는지를 묻는다." }
  ]
 },
 syn: [
  { n:"⑨", name:"by + 동명사 (수단)",
    q:"«By freezing information», the model can show what supply and demand alone would do.",
    d:"<b>by + 동명사</b>는 '~함으로써'라는 수단·방법을 나타낸다. 문장 앞에 오면 쉼표로 끊는다.",
    k:"정보를 얼려 둠으로써 그 모형은 무슨 일이 일어날지를 보여 줄 수 있다." },
  { n:"⑧", name:"not A but B",
    q:"The assumption is «not a mistake but a tool» for holding one thing still.",
    d:"<b>not A but B</b>는 'A가 아니라 B'. 필자가 오해를 바로잡을 때 즐겨 쓰는 형태다.",
    k:"그 가정은 실수가 아니라 한 가지를 고정해 두기 위한 도구다." }
 ],
 synd: [
  { u:"구문 1", en:"By leaving out the hills, the designer made the map easier to read.",
    k:"언덕을 빼 버림으로써 설계자는 그 지도를 읽기 쉽게 만들었다." },
  { u:"구문 2", en:"The line on the chart is not a promise but a guess.",
    k:"도표 위의 그 선은 약속이 아니라 추측이다." },
  { u:"구문 1 + 2", en:"By fixing one number, the team built not a forecast but a test.",
    k:"한 수치를 고정함으로써 그 팀은 예측이 아니라 시험을 만들었다." }
 ],
 wtype: ["지엽","정답","반대","지엽","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["노선도는 비유로 든 예일 뿐이다"],["정답"],
       ["글은 모형이 일부러 단순화한다고 말한다 — 정반대다"],
       ["2008년은 근거로 든 사례 하나일 뿐이다"],["수요·공급의 역사는 글에 나오지 않는다"]],
 src: [["①②"],["⑦"],["⑧과 어긋남 — 실수가 아니라 도구라고 했다"],["⑬"],["⑭"]],
 kb: {
  title:"단순하게 그려서 얻은 것",
  lead:"버릴 것을 정하는 일이 곧 설계다.",
  items: [
   ["1933년, 거리를 버린 지도",
    "런던 지하철 노선도를 새로 그린 해리 벡은 실제 거리와 지형을 버리고 선을 수직·수평·45도로만 그었다. 승객이 알아야 할 것은 '어디서 갈아타는가'뿐이라는 판단이었고, 이 형식은 지금 세계 대부분의 도시가 쓴다."],
   ["구형 소를 가정하시오",
    "물리학자들 사이에는 문제를 풀기 쉽게 만들려고 소를 완전한 구로 가정한다는 오래된 농담이 있다. 웃기려는 말이지만, 모든 모형이 무엇을 버릴지부터 정한다는 점을 정확히 짚는다."],
   ["'모든 모형은 틀렸다'",
    "통계학자 조지 박스는 1976년 논문에서 \"모든 모형은 틀렸지만 일부는 쓸모가 있다\"고 썼다. 모형을 옳고 그름이 아니라 쓸모로 평가하자는 제안이었다."]
  ],
  ask:"내가 무언가를 설명할 때 늘 빼고 말하는 것이 있는가? 그것을 빼면 무엇이 쉬워지고 무엇이 가려지는가?"
 }
},
{
 no: "12", key: "joke",
 accent: "#C9743A", tint: "#FBEDE1", deep: "#8F4A1B",
 en: "The Language of Jokes",
 ko: "농담이라는 언어",
 goal: "농담이 웃음을 만드는 구조와, 그 구조가 사회적으로 하는 일을 설명할 수 있다.",
 fig: "Figure 1  한 줄에서 두 갈래로 갈라지는 뜻.",
 tip: "먼저 생각해 보자. 어떤 농담은 설명하는 순간 재미가 사라진다. 왜 그럴까?",
 sent: [
  "Most jokes work by building one meaning and then swapping it for another.",
  "The listener follows a path, and the last word moves the ground under it.",
  "Nothing is funny about the words themselves, taken one at a time.",
  "The laugh comes from the sudden repair the mind has to make.",
  "This is why a joke dies when you explain it.",
  "Explanation does the repair for the listener, and the work is what was enjoyable.",
  "Timing matters for the same reason, and every comedian learns it early.",
  "A pause holds the first meaning in place until it is heavy enough to drop.",
  "Jokes also carry a quiet social test that nobody announces.",
  "To laugh, you must share the knowledge the joke assumes.",
  "A joke about a school rule means nothing to someone outside that school.",
  "So laughing together is partly a way of saying we know the same things.",
  "That is why humour can bind a group and shut others out in the same breath.",
  "Comedians know both effects and choose which one they want.",
  "A joke is never only a joke."
 ],
 kor: [
  "대부분의 농담은 한 가지 뜻을 세워 놓았다가 다른 뜻으로 바꿔치기하는 방식으로 작동한다.",
  "듣는 사람은 하나의 길을 따라가고, 마지막 낱말이 그 발밑의 땅을 옮겨 놓는다.",
  "낱말을 하나씩 떼어 놓고 보면 그 안에 웃긴 것은 없다.",
  "웃음은 머리가 급히 해야 하는 수선에서 나온다.",
  "농담을 설명하면 죽어 버리는 이유가 여기에 있다.",
  "설명은 그 수선을 듣는 사람 대신 해 주는데, 즐거웠던 것은 바로 그 수고였다.",
  "타이밍이 중요한 것도 같은 이유이며, 코미디언이라면 누구나 일찍 배운다.",
  "잠깐의 멈춤은 첫 번째 뜻을 떨어뜨릴 만큼 무거워질 때까지 붙들어 둔다.",
  "농담은 아무도 말하지 않는 조용한 사회적 시험도 함께 지닌다.",
  "웃으려면 그 농담이 전제하는 지식을 나눠 가지고 있어야 한다.",
  "어떤 학교의 규칙에 관한 농담은 그 학교 밖의 사람에게는 아무 뜻도 없다.",
  "그래서 함께 웃는 일은 우리가 같은 것을 안다고 말하는 한 방식이기도 하다.",
  "유머가 한 집단을 묶으면서 동시에 다른 사람을 밀어낼 수 있는 까닭이 그것이다.",
  "코미디언들은 두 효과를 다 알고, 어느 쪽을 원하는지 고른다.",
  "농담은 결코 농담이기만 한 것이 아니다."
 ],
 bank: [["swap","①","바꿔치기하다"],["repair","④","수선, 고침"],["timing","⑦","때 맞추기"],
        ["assume","⑩","전제하다"],["bind","⑬","묶다"],["effect","⑭","효과"]],
 defs: [["swap","to put one thing in place of another"],
        ["repair","the act of fixing something that has broken"],
        ["timing","the choice of the exact moment to act"],
        ["assume","to take something as already known"],
        ["bind","to hold people or things together"],
        ["effect","a change produced by an action"]],
 defOrder: [3,0,5,2,4,1],
 flow: [
  ["Mechanism","A joke builds one meaning and then swaps it for another",null],
  ["Source of the laugh","The listener enjoys doing the (  ①  ) himself","repair"],
  ["Consequence 1","Explaining the joke (  ②  ) it, because the work is taken away","kills"],
  ["Consequence 2","Laughing proves you (  ③  ) the assumed knowledge","share"],
  ["Conclusion","Humour can (  ④  ) a group and shut others out at once","bind"]
 ],
 flowBogi: "repair · kills · share · bind · pause · explain",
 para: [
  ["④ the sudden repair the mind has to make","The laugh rewards a quick mental ______.","fix"],
  ["⑥ the work is what was enjoyable","The listener enjoys the ______, not the answer.","effort"],
  ["⑧ until it is heavy enough to drop","The pause lets the first meaning ______.","settle"],
  ["⑪ means nothing to someone outside","Outsiders are ______ from the joke.","excluded"],
  ["⑮ A joke is never only a joke.","Humour always does ______ work too.","social"]
 ],
 paraBogi: "fix · effort · settle · excluded · social · answer · vanish · private",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Write a Funny Story","Why Comedians Earn So Much",
       "A Joke Tests What We Share","Jokes Should Never Be Explained",
       "The History of Stand-Up Comedy"], ans:3},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["웃음은 뜻이 갑자기 바뀔 때 생기는 수선에서 나온다.","설명은 듣는 사람이 할 일을 대신해 버린다.",
       "낱말 자체에 웃긴 성질이 들어 있다.","농담은 전제된 지식을 나눠 가진 사람에게만 통한다.",
       "유머는 묶는 일과 밀어내는 일을 함께 한다."], ans:3},
  {t:"write", q:"필자가 '농담은 농담이기만 한 것이 아니다'라고 말한 이유를 우리말 한 문장으로 써 보세요.",
   ans:"함께 웃는 일이 같은 지식을 나눠 가졌는지 확인하며 집단을 묶고 다른 사람을 밀어내기 때문이다."}
 ],
 fl: {
  model: { n:"⑬",
   toks: [["That","s"],["is","v"],["why","c"],["humour","s2"],["can bind","v2"],
          ["a group","m"],["and shut others out in the same breath","m"]],
   ko:"유머가 한 집단을 묶으면서 동시에 다른 사람을 밀어낼 수 있는 까닭이 그것이다." },
  drill: [
   { n:"①", en:"Most jokes work by building one meaning and then swapping it for another.",
     ans:"S Most jokes · △V work · M by building one meaning and then swapping it for another",
     ko:"대부분의 농담은 한 뜻을 세웠다가 다른 뜻으로 바꿔치기하는 방식으로 작동한다." },
   { n:"⑥", en:"Explanation does the repair for the listener, and the work is what was enjoyable.",
     ans:"S Explanation · △V does · O the repair · M for the listener · [and] S the work · △V is · C what was enjoyable",
     ko:"설명은 그 수선을 듣는 사람 대신 해 주는데, 즐거웠던 것은 바로 그 수고였다." },
   { n:"⑩", en:"To laugh, you must share the knowledge the joke assumes.",
     ans:"M To laugh · S you · △V must share · O the knowledge · M the joke assumes",
     ko:"웃으려면 그 농담이 전제하는 지식을 나눠 가지고 있어야 한다." }
  ]
 },
 syn: [
  { n:"⑧", name:"형용사 + enough to + 동사원형",
    q:"A pause holds the first meaning in place until it is «heavy enough to drop».",
    d:"<b>형용사 + enough + to부정사</b>는 '~할 만큼 충분히 …한'. enough 가 형용사 <b>뒤</b>에 온다.",
    k:"잠깐의 멈춤은 첫 번째 뜻이 떨어질 만큼 무거워질 때까지 그것을 붙들어 둔다." },
  { n:"⑬", name:"That is why + 절",
    q:"«That is why» humour can bind a group and shut others out in the same breath.",
    d:"<b>That is why ~</b>는 '그것이 ~한 이유다'. 앞 내용이 <b>원인</b>, why 뒤가 <b>결과</b>다.",
    k:"유머가 집단을 묶으면서 동시에 남을 밀어낼 수 있는 까닭이 그것이다." }
 ],
 synd: [
  { u:"구문 1", en:"The pause was long enough to make everyone lean forward.",
    k:"그 멈춤은 모두를 앞으로 기울이게 만들 만큼 길었다." },
  { u:"구문 2", en:"That is why the same joke fails in another country.",
    k:"같은 농담이 다른 나라에서 통하지 않는 까닭이 그것이다." },
  { u:"구문 1 + 2", en:"That is why a hint must be small enough to leave the work undone.",
    k:"힌트가 할 일을 남겨 둘 만큼 작아야 하는 까닭이 그것이다." }
 ],
 wtype: ["무관","무관","정답","지엽","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["웃기는 글 쓰는 법을 알려 주는 글이 아니다"],["코미디언의 수입은 글에 나오지 않는다"],["정답"],
       ["설명하면 죽는다는 것은 논지의 한 부분일 뿐이다"],["스탠드업의 역사는 글의 소재가 아니다"]],
 src: [["①④"],["⑥"],["③과 어긋남 — 낱말 자체에는 웃긴 것이 없다"],["⑩⑪"],["⑬"]],
 kb: {
  title:"웃음이 하는 일",
  lead:"웃음은 감정이자 신호다.",
  items: [
   ["'부조화 해소' 이론",
    "18세기 칸트와 쇼펜하우어에서 시작해 20세기 심리학이 다듬은 설명이다. 기대한 것과 실제가 어긋나고, 그 어긋남이 순간적으로 해소될 때 웃음이 난다고 본다. 이 글의 '수선'이 바로 그 해소다."],
   ["혼자 있을 때는 잘 웃지 않는다",
    "심리학자 로버트 프로바인은 일상 대화 1,200건을 기록해, 웃음의 대부분이 농담이 아니라 평범한 말 뒤에 나오며 혼자 있을 때보다 함께 있을 때 훨씬 자주 나온다는 것을 보고했다. 웃음은 내용보다 관계에 붙어 있다."],
   ["번역하기 가장 어려운 것",
    "말장난은 소리와 뜻이 한 언어 안에서 겹칠 때 생기므로, 번역하면 대개 무너진다. 그래서 자막 번역자는 원문을 옮기는 대신 그 자리에서 통하는 다른 농담을 새로 만들곤 한다."]
  ],
  ask:"우리 반에서만 통하는 농담이 있는가? 그것이 통하려면 무엇을 알고 있어야 하는가?"
 }
},
{
 no: "13", key: "data",
 accent: "#2F8074", tint: "#E2F0ED", deep: "#1B564D",
 en: "Numbers Do Not Speak",
 ko: "숫자는 스스로 말하지 않는다",
 goal: "같은 자료가 어떻게 서로 다른 결론에 쓰이는지 예를 들어 설명할 수 있다.",
 fig: "Figure 1  같은 점들, 다르게 그은 선.",
 tip: "먼저 생각해 보자. '10명 중 9명이 만족'이라는 문장에서 우리가 모르는 것은 무엇일까?",
 sent: [
  "People often say that numbers speak for themselves and settle an argument.",
  "They do not; someone always chooses which numbers to show.",
  "Imagine a school that proudly reports higher test scores this year than last.",
  "The figure is true, and it still hides several decisions.",
  "Which students were counted, and which had already left?",
  "Was the test the same one, and was it marked the same way?",
  "None of these questions accuse anyone of lying.",
  "They only remind us that a number arrives with a history.",
  "The same problem appears in charts, where the shape of a line does the arguing.",
  "A line that starts at ninety instead of zero makes a small rise look steep.",
  "Nothing in the data has changed, but the reader's eye has been steered.",
  "Careful writers therefore report how the data was gathered, not only what it shows.",
  "Careful readers ask what a number would look like from the other side.",
  "Honesty with data is less about the figures than about the choices behind them.",
  "A number is an answer, and every answer had a question first."
 ],
 kor: [
  "사람들은 흔히 숫자가 스스로 말하며 논쟁을 끝내 준다고 한다.",
  "그렇지 않다. 어떤 숫자를 보여 줄지는 언제나 누군가가 고른다.",
  "지난해보다 올해 시험 점수가 올랐다고 자랑스럽게 발표한 학교를 떠올려 보라.",
  "그 수치는 사실이지만, 그래도 여러 결정을 감추고 있다.",
  "어떤 학생들이 셈에 들어갔고, 어떤 학생들은 이미 떠났는가?",
  "시험은 같은 시험이었고, 채점 방식도 같았는가?",
  "이 질문들 가운데 누구를 거짓말쟁이로 모는 것은 하나도 없다.",
  "그저 하나의 숫자가 내력을 지니고 도착한다는 사실을 일깨울 뿐이다.",
  "같은 문제가 도표에서도 나타나는데, 거기서는 선의 모양이 대신 주장을 한다.",
  "0이 아니라 90에서 시작하는 선은 작은 상승을 가파르게 보이게 만든다.",
  "자료에서 바뀐 것은 없지만, 읽는 사람의 눈이 이끌린 것이다.",
  "그래서 신중한 필자는 자료가 무엇을 보여 주는지만이 아니라 어떻게 모였는지를 함께 밝힌다.",
  "신중한 독자는 그 숫자가 반대편에서 보면 어떻게 보일지를 묻는다.",
  "자료를 정직하게 다루는 일은 수치보다 그 뒤의 선택에 달려 있다.",
  "숫자는 하나의 답이고, 모든 답에는 먼저 질문이 있었다."
 ],
 bank: [["figure","④","수치"],["count","⑤","셈에 넣다"],["mark","⑥","채점하다"],
        ["accuse","⑦","(~라고) 몰아붙이다"],["steer","⑪","이끌다, 몰다"],["gather","⑫","모으다"]],
 defs: [["figure","a number that stands for an amount"],
        ["count","to include something in a total"],
        ["mark","to give a score to a piece of work"],
        ["accuse","to say that someone has done wrong"],
        ["steer","to guide something in a chosen direction"],
        ["gather","to collect things from many places"]],
 defOrder: [4,1,0,5,3,2],
 flow: [
  ["Claim to reject","People say numbers speak for themselves",null],
  ["Case 1","A school's higher score still hides several (  ①  )","decisions"],
  ["Case 2","A chart starting at ninety makes a small rise look (  ②  )","steep"],
  ["Advice to writers","Report how the data was (  ③  ), not only what it shows","gathered"],
  ["Advice to readers","Ask what the number looks like from the other (  ④  )","side"]
 ],
 flowBogi: "decisions · steep · gathered · side · figure · lying",
 para: [
  ["② someone always chooses which numbers to show","Every figure has been ______ by someone.","selected"],
  ["⑦ None of these questions accuse anyone","Asking is not the same as ______ someone.","blaming"],
  ["⑧ a number arrives with a history","Each figure carries its own ______.","background"],
  ["⑪ the reader's eye has been steered","The picture ______ the reader, not the data.","guides"],
  ["⑭ less about the figures than about the choices","Honesty lies in the ______ behind numbers.","choices"]
 ],
 paraBogi: "selected · blaming · background · guides · choices · random · trusting · totals",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Raise a School's Test Scores","Every Number Comes with a Question",
       "Charts Are Always Dishonest","The Best Way to Mark an Exam",
       "Why Schools Should Publish Less Data"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["점수가 올랐다는 수치 자체는 사실일 수 있다.","축의 시작점을 바꾸면 같은 자료가 달리 보인다.",
       "필자는 이런 질문이 누군가를 거짓말쟁이로 몬다고 본다.","신중한 필자는 자료를 모은 방법도 함께 밝힌다.",
       "정직함은 수치보다 그 뒤의 선택에 달려 있다."], ans:3},
  {t:"write", q:"필자가 '숫자는 스스로 말하지 않는다'고 한 이유를 우리말 한 문장으로 써 보세요.",
   ans:"어떤 숫자를 어떻게 모아 보여 줄지를 언제나 사람이 고르기 때문이다."}
 ],
 fl: {
  model: { n:"⑩",
   toks: [["A line","s"],["that starts at ninety instead of zero","m"],["makes","v"],
          ["a small rise","m"],["look steep","m"]],
   ko:"0이 아니라 90에서 시작하는 선은 작은 상승을 가파르게 보이게 만든다." },
  drill: [
   { n:"②", en:"They do not; someone always chooses which numbers to show.",
     ans:"S They · △V do not · S someone · M always · △V chooses · O which numbers to show",
     ko:"그렇지 않다. 어떤 숫자를 보여 줄지는 언제나 누군가가 고른다." },
   { n:"⑫", en:"Careful writers therefore report how the data was gathered, not only what it shows.",
     ans:"S Careful writers · M therefore · △V report · O how the data was gathered · M not only what it shows",
     ko:"그래서 신중한 필자는 자료가 어떻게 모였는지를 함께 밝힌다." },
   { n:"⑮", en:"A number is an answer, and every answer had a question first.",
     ans:"S A number · △V is · C an answer · [and] S every answer · △V had · O a question · M first",
     ko:"숫자는 하나의 답이고, 모든 답에는 먼저 질문이 있었다." }
  ]
 },
 syn: [
  { n:"⑩", name:"make + 목적어 + 동사원형 (사역)",
    q:"A line that starts at ninety «makes a small rise look» steep.",
    d:"<b>make + 목적어 + 동사원형</b>은 '~가 …하게 만들다'. to 를 붙이지 않는 것이 핵심이다.",
    k:"90에서 시작하는 선은 작은 상승을 가파르게 보이게 만든다." },
  { n:"⑭", name:"less A than B",
    q:"Honesty with data is «less about the figures than about the choices» behind them.",
    d:"<b>less A than B</b>는 'A라기보다 B다'. 무게를 B 쪽에 싣는 표현이다.",
    k:"자료의 정직함은 수치보다 그 뒤의 선택에 달려 있다." }
 ],
 synd: [
  { u:"구문 1", en:"A wide axis makes the same change seem small.",
    k:"넓은 축은 같은 변화를 작아 보이게 만든다." },
  { u:"구문 2", en:"The report was less a summary than an argument.",
    k:"그 보고서는 요약이라기보다 하나의 주장이었다." },
  { u:"구문 1 + 2", en:"A good chart makes the reader think less about colour than about the data.",
    k:"좋은 도표는 독자가 색보다 자료를 더 생각하게 만든다." }
 ],
 wtype: ["무관","정답","반대","무관","지엽"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["점수를 올리는 방법은 글의 관심사가 아니다"],["정답"],
       ["글은 도표가 늘 부정직하지는 않다고 전제한다 — 정반대다"],
       ["채점 방법은 예로 든 질문 하나일 뿐 주제가 아니다"],
       ["자료 공개를 줄이자는 주장은 글에 없다"]],
 src: [["④"],["⑩"],["⑦과 어긋남 — 누구도 거짓말쟁이로 몰지 않는다"],["⑫"],["⑭"]],
 kb: {
  title:"같은 자료, 다른 그림",
  lead:"고르는 순간 이미 해석이 시작된다.",
  items: [
   ["애스컴의 네 자료",
    "1973년 통계학자 프랜시스 애스컴은 평균·분산·상관계수가 모두 같은데 그림은 전혀 다른 네 개의 자료 묶음을 만들었다. 숫자 요약만 보고 판단하면 안 된다는 것을 한눈에 보여 준 사례로 지금도 인용된다."],
   ["생존자만 보고 세운 계획",
    "2차 대전 중 통계학자 에이브러햄 발드는 총알 자국이 몰린 자리가 아니라 자국이 없는 자리를 보강해야 한다고 조언했다. 돌아오지 못한 비행기는 자료에 없었기 때문이다. 오늘날 '생존 편향'이라 부른다."],
   ["y축을 어디서 시작할 것인가",
    "막대그래프는 0에서 시작하는 것이 원칙이고, 꺾은선그래프는 변화를 보이기 위해 잘라 쓰기도 한다. 어느 쪽이든 잘랐다면 밝히는 것이 규범이다."]
  ],
  ask:"최근에 본 통계 하나를 떠올려 보자. 그 숫자를 만들려면 누가 무엇을 골라야 했을까?"
 }
},
{
 no: "14", key: "neural",
 accent: "#8E5AA8", tint: "#F2EAF6", deep: "#5C3272",
 en: "The Machine That Learned to Guess",
 ko: "추측을 배운 기계",
 goal: "인공 신경망이 무엇을 학습하고 무엇을 학습하지 못하는지 설명할 수 있다.",
 fig: "Figure 1  층을 지나며 걸러지는 신호.",
 tip: "먼저 생각해 보자. 개와 고양이를 구별하는 규칙을 말로 적어 본다면 몇 줄이 필요할까?",
 sent: [
  "Try writing down the rule that tells a dog from a cat.",
  "Every rule you write will fail on some real animal.",
  "A neural network is never handed such a rule at any point.",
  "It is shown thousands of labelled pictures instead.",
  "Inside, numbers pass through layers, and each layer passes on what it found.",
  "Early layers notice edges; later ones notice ears, eyes, and shapes.",
  "When the answer is wrong, the network changes its numbers a little.",
  "Repeat this millions of times and the guesses grow accurate.",
  "But the network has learned the pattern in its examples, not the world.",
  "Feed it only photographs taken outdoors and it may quietly learn about grass.",
  "Such a system can be right for a reason nobody chose and nobody checked.",
  "It also cannot say in plain words why it answered as it did.",
  "The numbers are visible, yet no sentence explains them.",
  "This is why careful teams test a model on cases it has never seen.",
  "A machine that guesses well is not the same as a machine that knows."
 ],
 kor: [
  "개와 고양이를 가려내는 규칙을 적어 보려고 해 보라.",
  "당신이 적는 모든 규칙은 어떤 실제 동물 앞에서 무너질 것이다.",
  "인공 신경망은 어느 단계에서도 그런 규칙을 건네받지 않는다.",
  "대신 이름표가 붙은 사진 수천 장을 본다.",
  "안에서는 숫자들이 층을 지나가고, 각 층은 자기가 찾아낸 것을 다음으로 넘긴다.",
  "앞쪽 층은 가장자리를 알아채고, 뒤쪽 층은 귀와 눈과 형태를 알아챈다.",
  "답이 틀리면 신경망은 자기 숫자들을 조금씩 바꾼다.",
  "이 일을 수백만 번 되풀이하면 추측이 정확해진다.",
  "그러나 신경망이 배운 것은 자기 예시 안의 패턴이지 세계가 아니다.",
  "야외에서 찍은 사진만 먹이면, 그것은 조용히 풀에 대해 배워 버릴 수도 있다.",
  "그런 체계는 아무도 고르지 않았고 아무도 확인하지 않은 이유로 맞힐 수 있다.",
  "또한 그것은 왜 그렇게 답했는지를 평범한 말로 설명하지 못한다.",
  "숫자들은 다 보이지만, 그것을 설명해 주는 문장은 없다.",
  "신중한 팀이 한 번도 본 적 없는 사례로 모형을 시험하는 이유가 여기에 있다.",
  "잘 추측하는 기계가 곧 아는 기계인 것은 아니다."
 ],
 bank: [["label","④","이름표를 붙이다"],["layer","⑤","층"],["edge","⑥","가장자리"],
        ["accurate","⑧","정확한"],["pattern","⑨","패턴, 규칙성"],["intend","⑪","의도하다"]],
 defs: [["label","to mark something with its name"],
        ["layer","one level in a stack of levels"],
        ["edge","the line where a shape ends"],
        ["accurate","correct in every detail"],
        ["pattern","a regular way in which things repeat"],
        ["intend","to plan something on purpose"]],
 defOrder: [2,0,4,5,1,3],
 flow: [
  ["Problem","No written rule can tell a dog from a cat in every case",null],
  ["Method","The network is shown thousands of (  ①  ) pictures","labelled"],
  ["Learning","Wrong answers make it adjust its (  ②  ) a little each time","numbers"],
  ["Limit 1","It learns the pattern in its (  ③  ), not the world","examples"],
  ["Limit 2","It cannot say (  ④  ) it answered as it did","why"]
 ],
 flowBogi: "labelled · numbers · examples · why · rules · grass",
 para: [
  ["② Every rule you write will fail","No written rule covers every ______.","case"],
  ["⑧ the guesses grow accurate","Repetition makes the answers more ______.","exact"],
  ["⑨ the pattern in its examples, not the world","It learns its ______, not reality.","data"],
  ["⑪ right for a reason nobody intended","It can be correct by ______.","accident"],
  ["⑮ not the same as a machine that knows","Guessing well is not ______.","understanding"]
 ],
 paraBogi: "case · exact · data · accident · understanding · rule · design · doubting",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Tell a Dog from a Cat","Guessing Well Is Not Knowing",
       "Neural Networks Will Replace Teachers","A Guide to Taking Better Photographs",
       "Why Machines Should Never Be Trusted"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["신경망은 이름표가 붙은 사진을 대량으로 본다.","앞쪽 층은 가장자리 같은 단순한 특징을 알아챈다.",
       "신경망은 자기가 왜 그렇게 답했는지 문장으로 설명한다.","야외 사진만 주면 배경을 배워 버릴 수 있다.",
       "신중한 팀은 처음 보는 사례로 모형을 시험한다."], ans:3},
  {t:"write", q:"필자가 '잘 추측하는 것과 아는 것은 다르다'고 한 근거를 우리말 한 문장으로 써 보세요.",
   ans:"예시 안의 패턴만 익혀 아무도 의도하지 않은 이유로 맞힐 수 있고, 그 이유를 설명하지도 못하기 때문이다."}
 ],
 fl: {
  model: { n:"⑩",
   toks: [["Feed","v"],["it","m"],["only photographs taken outdoors","m"],["and","c"],
          ["it","s2"],["may quietly learn","v2"],["about grass","m"]],
   ko:"야외에서 찍은 사진만 먹이면, 그것은 조용히 풀에 대해 배워 버릴 수도 있다." },
  drill: [
   { n:"⑤", en:"Inside, numbers pass through layers, and each layer passes on what it found.",
     ans:"M Inside · S numbers · △V pass · M through layers · [and] S each layer · △V passes on · O what it found",
     ko:"안에서는 숫자들이 층을 지나가고, 각 층은 자기가 찾아낸 것을 다음으로 넘긴다." },
   { n:"⑨", en:"But the network has learned the pattern in its examples, not the world.",
     ans:"S the network · △V has learned · O the pattern in its examples · M not the world",
     ko:"그러나 신경망이 배운 것은 자기 예시 안의 패턴이지 세계가 아니다." },
   { n:"⑭", en:"This is why careful teams test a model on cases it has never seen.",
     ans:"S This · △V is · C why careful teams test a model on cases it has never seen",
     ko:"신중한 팀이 한 번도 본 적 없는 사례로 모형을 시험하는 이유가 여기에 있다." }
  ]
 },
 syn: [
  { n:"⑩", name:"명령문 + and + 절",
    q:"«Feed it only photographs taken outdoors and it may quietly learn» about grass.",
    d:"<b>명령문 + and</b>는 '~하라, 그러면 …할 것이다'. if 절과 같은 뜻으로 읽으면 된다.",
    k:"야외 사진만 먹이면 그것은 조용히 풀에 대해 배워 버릴 수도 있다." },
  { n:"④", name:"수동태 + 목적어 (show A B 의 수동형)",
    q:"It «is shown thousands of labelled pictures» instead.",
    d:"show A B 에서 A를 주어로 올린 형태. <b>be shown + 목적어</b>로 목적어 하나가 남는다.",
    k:"대신 그것은 이름표가 붙은 사진 수천 장을 보게 된다." }
 ],
 synd: [
  { u:"구문 1", en:"Change one label and the whole result may move.",
    k:"이름표 하나를 바꾸면 결과 전체가 움직일 수 있다." },
  { u:"구문 2", en:"The class was shown two photographs of the same street.",
    k:"학생들은 같은 거리를 찍은 사진 두 장을 보게 되었다." },
  { u:"구문 1 + 2", en:"Give it clean data and the model will be shown a fairer world.",
    k:"깨끗한 자료를 주면 그 모형은 더 공정한 세계를 보게 될 것이다." }
 ],
 wtype: ["지엽","정답","무관","무관","반대"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["개와 고양이는 문제를 여는 예시일 뿐이다"],["정답"],
       ["교사 대체 이야기는 글에 나오지 않는다"],["사진 촬영법은 글의 소재가 아니다"],
       ["글은 신중히 시험하면 쓸 수 있다고 본다 — 정반대다"]],
 src: [["④"],["⑥"],["⑫과 어긋남 — 왜 그렇게 답했는지 말하지 못한다"],["⑩"],["⑭"]],
 kb: {
  title:"기계가 엉뚱하게 맞히는 법",
  lead:"정답을 맞혔다고 이유까지 맞은 것은 아니다.",
  items: [
   ["늑대인가, 눈밭인가",
    "2016년 리베이로 연구진은 늑대와 허스키를 구별하도록 학습시킨 분류기가 실제로는 배경의 눈을 보고 판단한다는 것을 보였다. 정확도는 높았지만 근거는 엉뚱했다."],
   ["병원 표식을 배운 진단 모형",
    "여러 의료 영상 연구에서 모형이 병변이 아니라 촬영 기기나 병원 표식을 단서로 삼은 사례가 보고되었다. 다른 병원 자료로 시험하면 성능이 크게 떨어진다."],
   ["'설명 가능한 AI'라는 분야",
    "왜 그렇게 판단했는지를 사람이 검토할 수 있게 만드는 연구를 XAI라 부른다. 유럽연합 규정 등에서 자동 결정에 대한 설명 요구가 논의되면서 실무 과제가 되었다."]
  ],
  ask:"내가 어떤 문제를 '풀 줄 안다'고 할 때, 답만 맞히는 것과 이유를 아는 것을 어떻게 구별할 수 있을까?"
 }
},
{
 no: "15", key: "feed",
 accent: "#C24A62", tint: "#FAE7EB", deep: "#8B2740",
 en: "The Room That Only Agrees",
 ko: "동의만 돌아오는 방",
 goal: "추천 알고리즘이 의견을 좁히는 구조와 그 한계를 설명할 수 있다.",
 fig: "Figure 1  같은 방향으로만 넓어지는 방.",
 tip: "먼저 생각해 보자. 내 화면에 뜨는 글들은 누가 고른 것일까?",
 sent: [
  "A feed is not a window; it is a selection.",
  "Software watches what you stop to read and offers more of the same.",
  "The aim behind that choice is simple, and it is not agreement.",
  "The aim is attention, because attention is what advertisers pay for.",
  "Posts that make people angry hold attention very well.",
  "So the calmest account of an issue is rarely the one that spreads.",
  "Over months the feed narrows without ever announcing it.",
  "You still see disagreement, but mostly the weakest version of it.",
  "The other side arrives already made to look foolish.",
  "This is in one way worse than never meeting the other side at all.",
  "A reader who has seen only weak arguments believes the question is settled.",
  "Researchers disagree about how strong this effect is in practice.",
  "Some studies find that most people still meet a fairly wide mix of views.",
  "Even so, the machine has a direction, and the direction is not neutral.",
  "Knowing that the room was arranged is the first step out of it."
 ],
 kor: [
  "피드는 창이 아니라 선별이다.",
  "소프트웨어는 당신이 멈춰서 읽는 것을 지켜보고, 같은 것을 더 내놓는다.",
  "그 선택 뒤의 목적은 단순하며, 그것은 동의가 아니다.",
  "목적은 주의(注意)다. 광고주가 돈을 내는 대상이 바로 주의이기 때문이다.",
  "사람을 화나게 하는 글은 주의를 아주 잘 붙잡는다.",
  "그래서 어떤 사안에 대한 가장 차분한 설명은 좀처럼 퍼지지 않는다.",
  "여러 달에 걸쳐 피드는 그렇다고 알리는 일 없이 좁아진다.",
  "당신은 여전히 반대 의견을 보지만, 대개는 그중 가장 약한 형태다.",
  "반대편은 이미 어리석어 보이도록 다듬어진 채로 도착한다.",
  "이것은 어떤 면에서 반대편을 아예 만나지 않는 것보다 나쁘다.",
  "약한 논거만 본 독자는 그 문제가 이미 결판났다고 믿는다.",
  "이 효과가 실제로 얼마나 강한지에 대해서는 연구자들의 의견이 갈린다.",
  "어떤 연구들은 대부분의 사람이 여전히 꽤 폭넓은 견해를 접한다고 본다.",
  "그렇다 해도 그 기계에는 방향이 있고, 그 방향은 중립이 아니다.",
  "이 방이 누군가 배치한 것임을 아는 일이 거기서 빠져나오는 첫걸음이다."
 ],
 bank: [["selection","①","선별"],["attention","④","주의, 관심"],["spread","⑥","퍼지다"],
        ["narrow","⑦","좁아지다"],["settle","⑪","결판나다"],["neutral","⑭","중립의"]],
 defs: [["selection","a set of things chosen out of many"],
        ["attention","the act of directing the mind to something"],
        ["spread","to reach more and more people"],
        ["narrow","to become less wide"],
        ["settle","to be finally decided"],
        ["neutral","not favouring either side"]],
 defOrder: [1,3,5,0,4,2],
 flow: [
  ["What a feed is","A feed is a selection, not a window",null],
  ["The aim","Software chases (  ①  ), which is what advertisers buy","attention"],
  ["Side effect","Angry posts travel further than (  ②  ) ones","calm"],
  ["The real harm","You meet only the (  ③  ) version of the other side","weakest"],
  ["Honest limit","Researchers (  ④  ) about how strong the effect is","disagree"]
 ],
 flowBogi: "attention · calm · weakest · disagree · window · neutral",
 para: [
  ["① A feed is not a window","What you see has been ______ for you.","chosen"],
  ["⑥ rarely the one that spreads","Calm accounts travel ______ than angry ones.","less"],
  ["⑦ the feed narrows without ever announcing it","The change happens ______.","silently"],
  ["⑨ already made to look foolish","Opponents arrive in a ______ form.","weakened"],
  ["⑭ the direction is not neutral","The system carries a built-in ______.","bias"]
 ],
 paraBogi: "chosen · less · silently · weakened · bias · loudly · stronger · window",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How Advertising Companies Are Run","Meeting Only the Weakest Opposition",
       "Social Media Should Be Banned","Why Angry People Read More",
       "A History of the Internet Feed"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["피드의 목적은 동의가 아니라 주의를 붙잡는 것이다.","화나게 하는 글은 주의를 잘 붙잡는다.",
       "연구자들은 이 효과의 크기에 대해 의견이 일치한다.","약한 논거만 본 독자는 문제가 끝났다고 믿는다.",
       "필자는 방이 배치되었음을 아는 것이 첫걸음이라고 본다."], ans:3},
  {t:"write", q:"필자가 '아예 만나지 않는 것보다 나쁘다'고 한 이유를 우리말 한 문장으로 써 보세요.",
   ans:"약한 반대 논거만 보면 그 문제를 이미 다 따져 본 것으로 착각하게 되기 때문이다."}
 ],
 fl: {
  model: { n:"⑪",
   toks: [["A reader","s"],["who has seen only weak arguments","m"],["believes","v"],
          ["the question","s2"],["is settled","v2"]],
   ko:"약한 논거만 본 독자는 그 문제가 이미 결판났다고 믿는다." },
  drill: [
   { n:"④", en:"The aim is attention, because attention is what advertisers pay for.",
     ans:"S The aim · △V is · C attention · [because] S′ attention · △V′ is · C what advertisers pay for",
     ko:"목적은 주의다. 광고주가 돈을 내는 대상이 바로 주의이기 때문이다." },
   { n:"⑦", en:"Over months the feed narrows without ever announcing it.",
     ans:"M Over months · S the feed · △V narrows · M without ever announcing it",
     ko:"여러 달에 걸쳐 피드는 그렇다고 알리는 일 없이 좁아진다." },
   { n:"⑮", en:"Knowing that the room was arranged is the first step out of it.",
     ans:"S Knowing that the room was arranged · △V is · C the first step out of it",
     ko:"이 방이 누군가 배치한 것임을 아는 일이 거기서 빠져나오는 첫걸음이다." }
  ]
 },
 syn: [
  { n:"⑪", name:"주격 관계대명사절 + 현재완료",
    q:"A reader «who has seen only weak arguments» believes the question is settled.",
    d:"who 절이 주어 A reader 를 꾸민다. 주어가 길어져도 <b>본동사는 believes</b> 하나임을 놓치지 않는다.",
    k:"약한 논거만 본 독자는 그 문제가 결판났다고 믿는다." },
  { n:"⑮", name:"동명사 주어",
    q:"«Knowing that the room was arranged» is the first step out of it.",
    d:"동명사구가 주어이면 <b>단수 취급</b>해 is 를 쓴다. '~하는 것은'으로 옮긴다.",
    k:"그 방이 배치된 것임을 아는 일이 첫걸음이다." }
 ],
 synd: [
  { u:"구문 1", en:"A student who has read only one side often sounds certain.",
    k:"한쪽 이야기만 읽은 학생은 흔히 확신에 찬 것처럼 말한다." },
  { u:"구문 2", en:"Choosing your own sources takes more time than scrolling.",
    k:"자기 출처를 고르는 일은 화면을 넘기는 것보다 시간이 더 든다." },
  { u:"구문 1 + 2", en:"Asking who arranged the room is what a reader who has been fooled learns to do.",
    k:"누가 그 방을 배치했는지 묻는 일은, 속아 본 독자가 배우게 되는 일이다." }
 ],
 wtype: ["무관","정답","반대","지엽","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["광고 회사 운영 방식은 글에 나오지 않는다"],["정답"],
       ["글은 금지를 주장하지 않는다 — 정반대다"],
       ["화나는 글이 잘 퍼진다는 것은 근거의 한 부분일 뿐이다"],
       ["인터넷의 역사는 글의 소재가 아니다"]],
 src: [["③④"],["⑤"],["⑫과 어긋남 — 연구자들의 의견이 갈린다"],["⑪"],["⑮"]],
 kb: {
  title:"화면 뒤의 선택",
  lead:"보이지 않는 편집자가 하루에도 몇 번씩 목록을 고쳐 쓴다.",
  items: [
   ["'필터 버블'과 '메아리 방'",
    "필터 버블은 2011년 일라이 파리저가, 메아리 방은 그보다 앞서 캐스 선스타인이 널리 알린 말이다. 앞의 것은 알고리즘이 좁히는 쪽을, 뒤의 것은 사람들이 스스로 모이는 쪽을 가리킨다."],
   ["연구 결과는 한쪽으로 모이지 않는다",
    "2015년 페이스북 자료를 쓴 연구는 개인의 선택이 알고리즘보다 더 크게 작용한다고 보고했다. 반대로 추천의 영향이 크다는 연구도 있어, 크기를 두고 논쟁이 이어지는 중이다."],
   ["'허수아비 때리기'라는 오래된 이름",
    "상대의 가장 약한 주장을 대신 세워 놓고 무너뜨리는 방식을 논리학에서는 허수아비 논증이라 부른다. 피드가 자동으로 하는 일이 이것과 닮았다."]
  ],
  ask:"내 화면에 마지막으로 뜬 글 다섯 개를 떠올려 보자. 그중 내 생각과 다른 것은 몇 개였는가?"
 }
}
]};
