/* Unit 4 · Field 4 — Medicine & Health 의학·건강
   원서 Theme 16–20 의 주제를 예비고1 수준으로 다시 쓴 것. */
module.exports = {
 no: 4,
 field: "Medicine & Health",
 ko: "의학·건강",
 tagline: "몸을 다루는 지식 — 시계, 칼, 경계",
 next: { en: "Philosophy & Religion", ko: "믿음과 의심이 어떻게 답을 세워 왔는지 읽습니다", words: "175–205 words" },
 lessons: [
{
 no: "16", key: "clock",
 accent: "#3D6FA0", tint: "#E5EDF6", deep: "#254768",
 en: "The Clock You Cannot Move",
 ko: "옮길 수 없는 시계",
 goal: "몸속 시계가 왜 빨리 조정되지 않는지, 시차를 줄이는 방법의 근거가 무엇인지 설명할 수 있다.",
 fig: "Figure 1  손목시계는 한 번에, 몸속 시계는 하루에 한 시간씩.",
 tip: "먼저 생각해 보자. 비행기에서 내리자마자 시계는 맞출 수 있는데, 왜 몸은 그러지 못할까?",
 sent: [
  "When a plane lands, you change your watch in one second.",
  "Your body needs about a week to do the same thing.",
  "Deep in the brain sits a group of cells that keeps its own time.",
  "This clock runs on a cycle of roughly twenty-four hours even in total darkness.",
  "Light is the main signal that keeps it matched to the world outside.",
  "Morning light pushes the clock earlier; evening light pushes it later.",
  "Flying east asks the body to fall asleep before it is ready.",
  "Flying west only asks it to stay up longer, which is far easier.",
  "This is why the same distance can feel very different in the two directions.",
  "The body shifts by about one hour a day, and it cannot be hurried much.",
  "Still, the shift can be helped instead of fought.",
  "Travellers who seek morning light in the east recover faster than those who hide indoors.",
  "Eating and sleeping on the new clock also give the body a clearer signal.",
  "None of this removes jet lag, and no habit makes the cells move faster.",
  "It only lines up the signals so the clock is not pulled two ways at once."
 ],
 kor: [
  "비행기가 착륙하면 당신은 손목시계를 1초 만에 바꿔 맞춘다.",
  "몸이 같은 일을 하는 데는 일주일쯤 걸린다.",
  "뇌 깊은 곳에는 자기만의 시간을 지키는 세포 무리가 자리 잡고 있다.",
  "이 시계는 완전한 어둠 속에서도 대략 스물네 시간 주기로 돌아간다.",
  "빛은 그 시계를 바깥 세상에 맞춰 두는 주된 신호다.",
  "아침 빛은 시계를 앞으로 당기고, 저녁 빛은 뒤로 민다.",
  "동쪽으로 날아가면 몸은 준비되기도 전에 잠들라는 요구를 받는다.",
  "서쪽으로 가면 더 오래 깨어 있으라는 요구뿐이라, 훨씬 쉽다.",
  "같은 거리인데도 두 방향이 아주 다르게 느껴지는 이유가 이것이다.",
  "몸은 하루에 한 시간쯤 옮겨 가고, 그 속도를 크게 앞당길 수는 없다.",
  "그렇지만 그 이동은 맞서 싸우는 대신 도와줄 수 있다.",
  "동쪽에서 아침 빛을 찾아 나선 여행자는 실내에 숨어 있는 사람보다 빨리 회복한다.",
  "새 시각에 맞춰 먹고 자는 것도 몸에 더 분명한 신호를 준다.",
  "이 가운데 무엇도 시차를 없애 주지는 않으며, 어떤 습관도 세포를 더 빨리 움직이게 하지 못한다.",
  "다만 신호들을 나란히 맞춰, 시계가 양쪽으로 동시에 끌려가지 않게 할 뿐이다."
 ],
 bank: [["cell","③","세포"],["cycle","④","주기"],["signal","⑤","신호"],
        ["shift","⑩","옮겨 가다"],["hurry","⑩","서두르게 하다"],["recover","⑫","회복하다"]],
 defs: [["cell","the smallest living unit of a body"],
        ["cycle","a set of events that repeat in the same order"],
        ["signal","something that carries information to a receiver"],
        ["shift","to move from one position to another"],
        ["hurry","to make something happen sooner than usual"],
        ["recover","to return to a normal state after trouble"]],
 defOrder: [2,0,4,5,1,3],
 flow: [
  ["Contrast","A watch changes in a second; the body needs about a week",null],
  ["Cause","A group of brain cells keeps a (  ①  ) of about 24 hours","cycle"],
  ["The signal","(  ②  ) is what keeps that clock matched to the world","light"],
  ["Direction","Flying (  ③  ) is harder, since sleep is asked for too early","east"],
  ["What helps","Aligning light and meals stops the clock being pulled two (  ④  )","ways"]
 ],
 flowBogi: "cycle · light · east · ways · watch · darkness",
 para: [
  ["④ runs on a cycle of roughly twenty-four hours","The rhythm continues even without ______.","daylight"],
  ["⑧ which is far easier","Staying up late is ______ than sleeping early.","simpler"],
  ["⑩ it cannot be hurried much","The pace of the shift is nearly ______.","fixed"],
  ["⑫ recover faster than those who hide indoors","Morning light ______ the adjustment.","speeds"],
  ["⑮ the clock is not pulled two ways","Aligned signals remove the ______.","conflict"]
 ],
 paraBogi: "daylight · simpler · fixed · speeds · conflict · harder · delays · silence",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Sleep Well on a Plane","A Body Clock That Moves One Hour a Day",
       "Jet Lag Can Be Cured in a Night","The Best Cities to Visit by Air",
       "Why Darkness Is Bad for Health"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["몸속 시계는 어둠 속에서도 주기를 이어 간다.","아침 빛과 저녁 빛은 시계를 서로 반대 방향으로 민다.",
       "습관을 잘 지키면 세포가 더 빨리 움직인다.","서쪽으로 가는 편이 몸에는 더 수월하다.",
       "새 시각에 맞춰 먹는 것도 신호가 된다."], ans:3},
  {t:"write", q:"필자가 말하는 시차 적응 방법의 실제 효과를 우리말 한 문장으로 써 보세요.",
   ans:"적응 속도를 높이는 것이 아니라 신호들을 한 방향으로 맞춰 주는 것이다."}
 ],
 fl: {
  model: { n:"⑫",
   toks: [["Travellers","s"],["who seek morning light in the east","m"],["recover","v"],
          ["faster","m"],["than those who hide indoors","m"]],
   ko:"동쪽에서 아침 빛을 찾아 나선 여행자는 실내에 숨어 있는 사람보다 빨리 회복한다." },
  drill: [
   { n:"③", en:"Deep in the brain sits a group of cells that keeps its own time.",
     ans:"M Deep in the brain · △V sits · S a group of cells · M that keeps its own time",
     ko:"뇌 깊은 곳에는 자기만의 시간을 지키는 세포 무리가 자리 잡고 있다." },
   { n:"⑦", en:"Flying east asks the body to fall asleep before it is ready.",
     ans:"S Flying east · △V asks · O the body · M to fall asleep · [before] S′ it · △V′ is · C ready",
     ko:"동쪽으로 날아가면 몸은 준비되기도 전에 잠들라는 요구를 받는다." },
   { n:"⑮", en:"It only lines up the signals so the clock is not pulled two ways at once.",
     ans:"S It · M only · △V lines up · O the signals · [so] S′ the clock · △V′ is not pulled · M two ways at once",
     ko:"다만 신호들을 나란히 맞춰, 시계가 양쪽으로 동시에 끌려가지 않게 할 뿐이다." }
  ]
 },
 syn: [
  { n:"③", name:"장소 부사구 도치",
    q:"«Deep in the brain sits a group of cells» that keeps its own time.",
    d:"장소를 나타내는 말이 앞에 나오면 <b>동사 + 주어</b> 순서로 뒤집힌다. 진짜 주어는 sits 뒤에 있다.",
    k:"뇌 깊은 곳에 자기만의 시간을 지키는 세포 무리가 있다." },
  { n:"⑫", name:"비교급 + than + 대명사절",
    q:"Travellers who seek morning light «recover faster than those who hide» indoors.",
    d:"<b>than those who ~</b>는 '~하는 사람들보다'. those 는 people 을 대신하는 대명사다.",
    k:"아침 빛을 찾는 여행자는 실내에 숨는 사람들보다 빨리 회복한다." }
 ],
 synd: [
  { u:"구문 1", en:"Under the old hospital stood a room no one had opened.",
    k:"그 오래된 병원 아래에는 아무도 열어 보지 않은 방이 하나 있었다." },
  { u:"구문 2", en:"Patients who walk each morning sleep better than those who do not.",
    k:"아침마다 걷는 환자들은 그렇지 않은 사람들보다 잠을 더 잘 잔다." },
  { u:"구문 1 + 2", en:"Beside the window sat travellers who slept longer than those in the aisle.",
    k:"창가에는 통로 쪽 사람들보다 더 오래 잔 여행자들이 앉아 있었다." }
 ],
 wtype: ["무관","정답","반대","무관","지엽"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["기내 수면 요령은 글의 관심사가 아니다"],["정답"],
       ["글은 하룻밤에 낫지 않는다고 말한다 — 정반대다"],
       ["여행지 추천은 글에 나오지 않는다"],["어둠은 주기를 설명하는 조건일 뿐이다"]],
 src: [["④"],["⑥"],["⑭과 어긋남 — 어떤 습관도 세포를 더 빨리 움직이게 하지 못한다"],["⑧"],["⑬"]],
 kb: {
  title:"몸속 시계 이야기",
  lead:"시간은 손목에만 있는 것이 아니다.",
  items: [
   ["시계가 있는 자리",
    "포유류의 주 시계는 시상하부의 시교차상핵(SCN)에 있다. 눈에서 온 빛 정보가 이곳으로 직접 이어져, 하루 주기를 바깥 낮밤에 맞춘다."],
   ["동굴에서 보낸 여러 달",
    "1962년 미셸 시프르는 빛과 시계 없이 동굴에서 지내며 자기 리듬을 기록했다. 이후 여러 격리 실험에서 사람의 주기는 24시간에서 조금 벗어난 채로도 계속 돌아간다는 것이 확인되었다."],
   ["2017년 노벨 생리의학상",
    "홀·로스배시·영은 초파리에서 하루 주기를 만드는 유전자와 단백질의 되먹임 고리를 밝혀 상을 받았다. 시계가 비유가 아니라 실제 분자 장치라는 것을 보인 연구다."]
  ],
  ask:"주말에 늦게 자고 늦게 일어나면 월요일이 힘든 이유를, 이 글의 말로 설명해 보자."
 }
},
{
 no: "17", key: "surgery",
 accent: "#B04A4A", tint: "#F9E7E7", deep: "#7C2727",
 en: "The Surgeon Who Changed the Room",
 ko: "수술실을 바꾼 외과의사",
 goal: "핼스테드가 바꾼 것이 기술만이 아니라 절차와 훈련이었음을 설명할 수 있다.",
 fig: "Figure 1  속도를 버리고 얻은 것.",
 tip: "먼저 생각해 보자. 옛 수술실에서 가장 자랑스러운 기술은 '빠른 손'이었다. 왜 그랬을까?",
 sent: [
  "Before anaesthesia, speed was the greatest surgical skill.",
  "A leg could be removed in under a minute, and the patient screamed throughout.",
  "Once patients could be put to sleep, that reason for hurry disappeared.",
  "Many surgeons kept hurrying anyway, because habit is slower to change than knowledge.",
  "William Halsted worked in the other direction.",
  "He handled tissue gently, closed wounds in layers, and took as long as the work needed.",
  "His operations were slow, and his patients survived more often.",
  "He also changed the room itself.",
  "When a nurse's hands were harmed by the cleaning fluid, he had thin rubber gloves made for her.",
  "The gloves were meant for her skin, not for the patient.",
  "Only later did the profession see that they kept the wound cleaner too.",
  "Halsted's largest change was in training rather than technique.",
  "He built a long residency in which young doctors treated patients under watch for years.",
  "The idea that a surgeon is made slowly, not born, came from that programme.",
  "Modern hospitals still run on the shape he gave them."
 ],
 kor: [
  "마취가 있기 전, 속도는 가장 뛰어난 외과 기술이었다.",
  "다리 하나를 1분 안에 잘라 낼 수 있었고, 환자는 그 내내 비명을 질렀다.",
  "환자를 재울 수 있게 되자 서둘러야 할 그 이유는 사라졌다.",
  "그런데도 많은 외과의는 계속 서둘렀다. 습관은 지식보다 늦게 바뀌기 때문이다.",
  "윌리엄 핼스테드는 반대 방향으로 움직였다.",
  "그는 조직을 부드럽게 다루고, 상처를 층층이 닫았으며, 일에 필요한 만큼 시간을 썼다.",
  "그의 수술은 느렸고, 그의 환자들은 더 자주 살아남았다.",
  "그는 수술실 자체도 바꾸었다.",
  "한 간호사의 손이 소독액에 상하자, 그는 그녀를 위해 얇은 고무장갑을 만들게 했다.",
  "그 장갑은 환자가 아니라 그녀의 피부를 위한 것이었다.",
  "그것이 상처도 더 깨끗하게 지켜 준다는 사실은 나중에야 의료계가 알아보았다.",
  "핼스테드의 가장 큰 변화는 기술보다 훈련에 있었다.",
  "그는 젊은 의사들이 여러 해 동안 감독을 받으며 환자를 보는 긴 수련 과정을 세웠다.",
  "외과의는 타고나는 것이 아니라 천천히 만들어진다는 생각이 그 과정에서 나왔다.",
  "오늘날의 병원도 여전히 그가 만들어 준 틀 위에서 돌아간다."
 ],
 bank: [["anaesthesia","①","마취"],["tissue","⑥","조직"],["wound","⑥","상처"],
        ["survive","⑦","살아남다"],["profession","⑪","(전문) 직업, 의료계"],["residency","⑬","수련 과정"]],
 defs: [["anaesthesia","a state in which a patient feels no pain"],
        ["tissue","the material that living body parts are made of"],
        ["wound","an injury where the skin is broken"],
        ["survive","to stay alive after a danger"],
        ["profession","all the people who do one skilled job"],
        ["residency","a long period of supervised training"]],
 defOrder: [1,4,0,5,3,2],
 flow: [
  ["Old rule","Before anaesthesia, speed was the greatest surgical skill",null],
  ["Why it lasted","(  ①  ) changes more slowly than knowledge","habit"],
  ["Halsted's method","He worked slowly, and more patients (  ②  )","survived"],
  ["A side discovery","Gloves made for a nurse also kept the wound (  ③  )","cleaner"],
  ["The biggest change","A long (  ④  ) made surgeons slowly rather than quickly","residency"]
 ],
 flowBogi: "habit · survived · cleaner · residency · speed · tissue",
 para: [
  ["③ that reason for hurry disappeared","Anaesthesia removed the need for ______.","speed"],
  ["④ habit is slower to change than knowledge","Practice lags behind new ______.","learning"],
  ["⑦ his patients survived more often","Slower work raised the ______ rate.","survival"],
  ["⑩ meant for her skin, not for the patient","The gloves had a different first ______.","purpose"],
  ["⑭ a surgeon is made slowly, not born","Skill is ______ rather than inherited.","built"]
 ],
 paraBogi: "speed · learning · survival · purpose · built · silence · falling · natural",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Invention of Anaesthesia","How to Remove a Leg Quickly",
       "Slow Hands and a Long Apprenticeship","Rubber Gloves and Modern Fashion",
       "The Life Story of a Famous Nurse"], ans:3},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["마취 이전에는 속도가 중요한 기술이었다.","마취가 생긴 뒤에도 많은 외과의가 계속 서둘렀다.",
       "고무장갑은 처음부터 환자의 상처를 위해 만들어졌다.","핼스테드의 수술은 느렸지만 생존율이 높았다.",
       "그가 만든 수련 과정은 여러 해에 걸쳐 있었다."], ans:3},
  {t:"write", q:"필자가 핼스테드의 가장 큰 변화로 꼽은 것을 우리말 한 문장으로 써 보세요.",
   ans:"기술 자체보다, 외과의를 오래 감독하며 길러 내는 수련 제도를 세운 것이다."}
 ],
 fl: {
  model: { n:"⑪",
   toks: [["Only later","m"],["did","v"],["the profession","s"],["see","v"],
          ["that","c"],["they","s2"],["kept","v2"],["the wound cleaner too","m"]],
   ko:"그것이 상처도 더 깨끗하게 지켜 준다는 사실은 나중에야 의료계가 알아보았다." },
  drill: [
   { n:"④", en:"Many surgeons kept hurrying anyway, because habit is slower to change than knowledge.",
     ans:"S Many surgeons · △V kept hurrying · [because] S′ habit · △V′ is · C slower to change than knowledge",
     ko:"그런데도 많은 외과의는 계속 서둘렀다. 습관은 지식보다 늦게 바뀌기 때문이다." },
   { n:"⑨", en:"When a nurse's hands were harmed by the cleaning fluid, he had thin rubber gloves made for her.",
     ans:"[When] S′ a nurse's hands · △V′ were harmed · M by the cleaning fluid · S he · △V had · O thin rubber gloves made for her",
     ko:"한 간호사의 손이 소독액에 상하자, 그는 그녀를 위해 얇은 고무장갑을 만들게 했다." },
   { n:"⑬", en:"He built a long residency in which young doctors treated patients under watch for years.",
     ans:"S He · △V built · O a long residency · M in which young doctors treated patients under watch for years",
     ko:"그는 젊은 의사들이 여러 해 감독을 받으며 환자를 보는 긴 수련 과정을 세웠다." }
  ]
 },
 syn: [
  { n:"⑪", name:"부정어 도치 — Only + 부사구",
    q:"«Only later did the profession see» that they kept the wound cleaner too.",
    d:"Only 로 시작하는 부사구가 앞에 오면 <b>did + 주어 + 동사원형</b> 으로 도치된다.",
    k:"나중에야 의료계는 그것이 상처도 깨끗하게 지켜 준다는 것을 알아보았다." },
  { n:"⑨", name:"사역동사 have + 목적어 + p.p.",
    q:"He «had thin rubber gloves made» for her.",
    d:"<b>have + 목적어 + 과거분사</b>는 '~을 …되게 하다'. 남을 시켜 하게 한 일에 쓴다.",
    k:"그는 얇은 고무장갑을 만들게 했다." }
 ],
 synd: [
  { u:"구문 1", en:"Only after the war did hospitals adopt the new rule.",
    k:"전쟁이 끝난 뒤에야 병원들은 그 새 규칙을 받아들였다." },
  { u:"구문 2", en:"She had the instruments cleaned before every operation.",
    k:"그녀는 수술마다 기구를 깨끗이 닦아 두게 했다." },
  { u:"구문 1 + 2", en:"Only then did he have the report rewritten.",
    k:"그제서야 그는 그 보고서를 다시 쓰게 했다." }
 ],
 wtype: ["지엽","무관","정답","무관","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["마취는 배경으로 언급될 뿐 주제가 아니다"],["빠른 절단술을 가르치는 글이 아니다"],["정답"],
       ["장갑과 패션은 글에 나오지 않는다"],["간호사의 생애는 글의 소재가 아니다"]],
 src: [["①"],["④"],["⑩과 어긋남 — 환자가 아니라 간호사의 피부를 위한 것이었다"],["⑦"],["⑬"]],
 kb: {
  title:"수술실이 조용해지기까지",
  lead:"장비보다 절차가 사람을 살렸다.",
  items: [
   ["1846년, 통증이 사라진 날",
    "매사추세츠 종합병원에서 에테르 마취 수술이 공개 시연되었다. 이후 수술은 '얼마나 빠른가'가 아니라 '얼마나 정확한가'의 문제가 되었다."],
   ["장갑은 사랑에서 나왔다는 이야기",
    "핼스테드가 장갑을 주문한 간호사 캐럴라인 햄프턴은 뒷날 그의 아내가 되었다. 감염 예방을 위해 만든 것이 아니라, 소독액에 상한 손을 지키려던 것이 시작이었다."],
   ["손 씻기를 먼저 말한 사람",
    "1847년 제멜바이스는 의사들이 손을 씻자 산욕열 사망률이 크게 떨어진다는 것을 보였지만, 당대 의료계는 오래 받아들이지 않았다. 습관이 지식보다 늦게 바뀐다는 말의 다른 사례다."]
  ],
  ask:"우리 반에서 '원래 그렇게 해 왔으니까' 유지되는 규칙이 있는가? 그 이유는 지금도 유효한가?"
 }
},
{
 no: "18", key: "virus",
 accent: "#4A7C46", tint: "#E7F1E5", deep: "#2E5429",
 en: "Alive Enough to Matter",
 ko: "살아 있다고 하기엔 모자란 것",
 goal: "바이러스가 생물의 정의를 어떻게 흔드는지, 그 물음이 왜 실용적인지 설명할 수 있다.",
 fig: "Figure 1  껍질과 설명서, 그리고 빌려 쓰는 공장.",
 tip: "먼저 생각해 보자. '살아 있다'는 말의 조건을 세 가지만 적어 본다면 무엇을 쓰겠는가?",
 sent: [
  "A virus is a set of instructions wrapped in a coat of protein.",
  "On its own it does nothing at all.",
  "It does not eat, it does not grow, and it cannot copy itself even once.",
  "Left on a doorknob, it simply waits, sometimes for hours.",
  "Everything changes the moment it meets a suitable cell.",
  "It enters, hands over its instructions, and the cell obediently begins building new viruses.",
  "The machinery is borrowed; only the plan belongs to the virus.",
  "This is why biologists have argued for a century about whether viruses are alive.",
  "By most definitions they fail, because they cannot reproduce without help.",
  "Yet they evolve, they carry genes, and they shape every living thing around them.",
  "The argument is not merely a matter of words.",
  "How we classify something decides which tools we reach for.",
  "A medicine that attacks living cells will not touch a set of instructions.",
  "Vaccines work differently: they teach the body to recognise the coat.",
  "The border of life turns out to be a place where useful questions live."
 ],
 kor: [
  "바이러스는 단백질 껍질에 싸인 한 벌의 설명서다.",
  "혼자 있을 때 그것은 아무것도 하지 않는다.",
  "먹지도 않고, 자라지도 않으며, 단 한 번도 스스로를 복제하지 못한다.",
  "문손잡이 위에 놓이면 그저 기다린다. 때로는 몇 시간씩.",
  "알맞은 세포를 만나는 순간 모든 것이 달라진다.",
  "그것은 들어가 설명서를 건네고, 세포는 고분고분 새 바이러스를 만들기 시작한다.",
  "기계 장치는 빌린 것이고, 바이러스의 것은 설계도뿐이다.",
  "생물학자들이 한 세기 동안 바이러스가 살아 있는지를 두고 다퉈 온 이유가 이것이다.",
  "대부분의 정의로는 자격 미달인데, 도움 없이는 번식하지 못하기 때문이다.",
  "그런데도 그것들은 진화하고, 유전자를 지니며, 주위의 모든 생물을 빚어낸다.",
  "이 논쟁은 단순히 말의 문제만은 아니다.",
  "무언가를 어떻게 분류하느냐가 우리가 어떤 도구를 집어 들지를 정한다.",
  "살아 있는 세포를 공격하는 약은 한 벌의 설명서에는 닿지 못한다.",
  "백신은 다르게 작동한다. 몸에게 그 껍질을 알아보도록 가르친다.",
  "생명의 경계는 알고 보면 쓸모 있는 질문들이 사는 자리다."
 ],
 bank: [["protein","①","단백질"],["suitable","⑤","알맞은"],["borrow","⑦","빌리다"],
        ["reproduce","⑨","번식하다"],["evolve","⑩","진화하다"],["classify","⑫","분류하다"]],
 defs: [["protein","a substance that builds and runs living cells"],
        ["suitable","right for a particular purpose"],
        ["borrow","to use something that belongs to another"],
        ["reproduce","to produce new individuals of the same kind"],
        ["evolve","to change gradually over generations"],
        ["classify","to put things into groups by kind"]],
 defOrder: [3,0,5,2,4,1],
 flow: [
  ["What it is","A virus is instructions wrapped in a protein coat",null],
  ["Alone","By itself it cannot eat, grow, or (  ①  )","reproduce"],
  ["Inside a cell","It hands over its plan and (  ②  ) the cell's machinery","borrows"],
  ["The dispute","Biologists argue whether such a thing is (  ③  )","alive"],
  ["Why it matters","How we (  ④  ) it decides which medicines can work","classify"]
 ],
 flowBogi: "reproduce · borrows · alive · classify · protein · vaccine",
 para: [
  ["② On its own it does nothing at all.","Alone, a virus stays completely ______.","inactive"],
  ["⑦ The machinery is borrowed","The cell supplies the ______, not the virus.","equipment"],
  ["⑨ they cannot reproduce without help","They depend on a host to ______.","multiply"],
  ["⑪ not merely a matter of words","The debate has ______ consequences.","practical"],
  ["⑭ teach the body to recognise the coat","Vaccines train the body to ______ it.","identify"]
 ],
 paraBogi: "inactive · equipment · multiply · practical · identify · busy · verbal · ignore",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Clean a Doorknob Properly","A Question at the Border of Life",
       "Viruses Are Clearly Living Things","The Discovery of the First Vaccine",
       "Why Proteins Are the Basis of Food"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["바이러스는 혼자서는 스스로를 복제하지 못한다.","세포 안에서 쓰이는 기계 장치는 세포의 것이다.",
       "대부분의 정의에서 바이러스는 생물로 분류된다.","바이러스도 진화하고 유전자를 지닌다.",
       "백신은 몸이 껍질을 알아보게 가르친다."], ans:3},
  {t:"write", q:"필자가 이 논쟁을 '말의 문제만은 아니다'라고 한 이유를 우리말 한 문장으로 써 보세요.",
   ans:"어떻게 분류하느냐에 따라 어떤 치료 도구를 쓸 수 있는지가 달라지기 때문이다."}
 ],
 fl: {
  model: { n:"⑫",
   toks: [["How we classify something","s"],["decides","v"],["which tools","c"],
          ["we","s2"],["reach for","v2"]],
   ko:"무언가를 어떻게 분류하느냐가 우리가 어떤 도구를 집어 들지를 정한다." },
  drill: [
   { n:"④", en:"Left on a doorknob, it simply waits, sometimes for hours.",
     ans:"M Left on a doorknob · S it · M simply · △V waits · M sometimes for hours",
     ko:"문손잡이 위에 놓이면 그저 기다린다. 때로는 몇 시간씩." },
   { n:"⑤", en:"Everything changes the moment it meets a suitable cell.",
     ans:"S Everything · △V changes · [the moment] S′ it · △V′ meets · O a suitable cell",
     ko:"알맞은 세포를 만나는 순간 모든 것이 달라진다." },
   { n:"⑩", en:"Yet they evolve, they carry genes, and they shape every living thing around them.",
     ans:"S they · △V evolve · S they · △V carry · O genes · [and] S they · △V shape · O every living thing around them",
     ko:"그런데도 그것들은 진화하고, 유전자를 지니며, 주위의 모든 생물을 빚어낸다." }
  ]
 },
 syn: [
  { n:"④", name:"분사구문 (수동)",
    q:"«Left on a doorknob», it simply waits, sometimes for hours.",
    d:"과거분사로 시작하는 분사구문은 <b>수동</b>의 뜻이다. 'When it is left ~' 로 풀어 읽는다.",
    k:"문손잡이 위에 놓이면 그것은 그저 기다린다." },
  { n:"⑤", name:"the moment + 절 (접속사)",
    q:"Everything changes «the moment it meets» a suitable cell.",
    d:"<b>the moment</b>는 '~하는 순간'이라는 접속사로 쓰인다. as soon as 와 같은 뜻이다.",
    k:"알맞은 세포를 만나는 순간 모든 것이 달라진다." }
 ],
 synd: [
  { u:"구문 1", en:"Kept in the cold, the sample stayed usable for weeks.",
    k:"차게 보관되자 그 표본은 몇 주 동안 쓸 수 있는 상태로 남았다." },
  { u:"구문 2", en:"The alarm rang the moment the door opened.",
    k:"문이 열리는 순간 경보가 울렸다." },
  { u:"구문 1 + 2", en:"Left alone, the cell divides the moment it has enough food.",
    k:"그냥 두면 그 세포는 먹이가 충분해지는 순간 분열한다." }
 ],
 wtype: ["무관","정답","반대","무관","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["문손잡이는 상황을 보여 주는 예일 뿐이다"],["정답"],
       ["글은 대부분의 정의에서 자격 미달이라고 말한다 — 정반대다"],
       ["백신의 발견사는 글에 나오지 않는다"],["영양으로서의 단백질은 글의 소재가 아니다"]],
 src: [["③"],["⑦"],["⑨과 어긋남 — 대부분의 정의로는 자격 미달이다"],["⑩"],["⑭"]],
 kb: {
  title:"경계에 선 것들",
  lead:"분류가 흔들리면 도구도 흔들린다.",
  items: [
   ["항생제는 바이러스에 듣지 않는다",
    "항생제는 세균의 세포벽이나 단백질 합성을 노린다. 바이러스에는 그런 구조가 없어 효과가 없다. 감기에 항생제를 쓰지 않는 이유이며, 불필요한 사용은 내성만 키운다."],
   ["세균만큼 큰 바이러스",
    "2003년 발견된 미미바이러스는 지름이 약 0.75마이크로미터로 일부 세균보다 크고, 유전자도 수백 개를 지닌다. '단순한 껍질'이라는 그림이 흔들린 계기였다."],
   ["우리 유전체 안의 흔적",
    "사람 유전체의 약 8%는 과거 바이러스에서 온 서열로 추정된다. 그중 일부는 태반 형성에 관여하는 단백질을 만드는 데 쓰인다."]
  ],
  ask:"'살아 있다'의 조건을 세 가지 적어 보고, 바이러스가 그중 몇 개를 만족하는지 따져 보자."
 }
},
{
 no: "19", key: "wall",
 accent: "#8B5AA6", tint: "#F1EAF6", deep: "#59326F",
 en: "The Fence Around the Well",
 ko: "우물을 두른 울타리",
 goal: "예방이 왜 치료보다 눈에 덜 띄는지, 그럼에도 왜 우선하는지 설명할 수 있다.",
 fig: "Figure 1  일어나지 않은 일은 그래프에 남지 않는다.",
 tip: "먼저 생각해 보자. 아무 일도 일어나지 않은 하루를 어떻게 성과라고 부를 수 있을까?",
 sent: [
  "In 1854 cholera was killing people in a London street, and nobody knew why.",
  "John Snow marked each death on a map and watched a pattern appear.",
  "The deaths gathered tightly around a single water pump on Broad Street.",
  "He asked the council to remove the pump handle, and the outbreak faded.",
  "Snow could not see the bacterium; the microscope work came later.",
  "He only needed to see where the sick people had been drinking their water.",
  "Prevention often works like this, without a full explanation.",
  "It also works invisibly, which is its lasting political problem.",
  "A cure produces a grateful patient who can be photographed and thanked in public.",
  "Prevention produces a person who never became a patient at all.",
  "No one thanks a clean pipe, and no one remembers the illness they did not get.",
  "So budgets for prevention are cut first and restored last.",
  "The pattern repeats in every century, under every kind of government.",
  "Public health is the strange field where success looks like nothing happening.",
  "Learning to value that emptiness is harder than learning the science."
 ],
 kor: [
  "1854년 런던의 한 거리에서 콜레라가 사람들을 죽이고 있었지만, 아무도 이유를 몰랐다.",
  "존 스노는 죽음 하나하나를 지도에 표시했고, 하나의 무늬가 떠오르는 것을 보았다.",
  "죽음은 브로드가의 물 펌프 하나 주위에 빽빽하게 모여 있었다.",
  "그는 시 당국에 펌프 손잡이를 떼어 달라고 요청했고, 유행은 잦아들었다.",
  "스노는 세균을 볼 수 없었다. 현미경 연구는 나중 일이었다.",
  "그는 아픈 사람들이 어디서 물을 길어 마셔 왔는지만 보면 되었다.",
  "예방은 흔히 이렇게, 완전한 설명 없이도 작동한다.",
  "예방은 또한 눈에 띄지 않게 작동하는데, 그것이 오래 이어지는 정치적 문제다.",
  "치료는 사진을 찍고 사람들 앞에서 고마움을 표할 수 있는 환자를 만들어 낸다.",
  "예방은 애초에 환자가 되지 않은 사람을 만들어 낸다.",
  "깨끗한 수도관에 고마워하는 사람은 없고, 걸리지 않은 병을 기억하는 사람도 없다.",
  "그래서 예방 예산은 가장 먼저 깎이고 가장 늦게 되살아난다.",
  "이 무늬는 어느 세기에나, 어떤 정부 아래에서나 되풀이된다.",
  "공중보건은 성공이 아무 일도 없는 것처럼 보이는 이상한 분야다.",
  "그 텅 빔을 값지게 여기는 법을 배우는 일이 과학을 배우는 일보다 어렵다."
 ],
 bank: [["outbreak","④","(질병의) 유행, 발생"],["bacterium","⑤","세균"],["prevention","⑦","예방"],
        ["grateful","⑨","고마워하는"],["budget","⑫","예산"],["restore","⑫","되살리다"]],
 defs: [["outbreak","a sudden start of a disease in an area"],
        ["bacterium","a tiny living thing that can cause disease"],
        ["prevention","the act of stopping something before it starts"],
        ["grateful","feeling thanks for what someone has done"],
        ["budget","the money set aside for a purpose"],
        ["restore","to bring something back to an earlier state"]],
 defOrder: [2,0,4,1,5,3],
 flow: [
  ["Case","In 1854 Snow mapped cholera deaths around one water pump",null],
  ["What was enough","He acted without seeing the (  ①  )","bacterium"],
  ["Nature of prevention","It works (  ②  ), leaving nothing to point at","invisibly"],
  ["Political result","Prevention budgets are cut (  ③  ) and restored last","first"],
  ["Conclusion","Success in public health looks like (  ④  ) happening","nothing"]
 ],
 flowBogi: "bacterium · invisibly · first · nothing · pump · patient",
 para: [
  ["④ the outbreak faded","Removing the handle ______ the spread.","stopped"],
  ["⑦ without a full explanation","Action can come before complete ______.","understanding"],
  ["⑩ a person who never became a patient","Prevention leaves no visible ______.","result"],
  ["⑫ cut first and restored last","Prevention has the weakest ______.","protection"],
  ["⑮ harder than learning the science","Valuing emptiness is the greater ______.","difficulty"]
 ],
 paraBogi: "stopped · understanding · result · protection · difficulty · spread · proof · comfort",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Discovery of Bacteria","When Success Looks Like Nothing",
       "How to Draw a City Map","Why London Needed New Streets",
       "The Best Way to Treat Cholera"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["스노는 죽음의 위치를 지도에 표시했다.","그는 세균을 확인한 뒤에 펌프 손잡이를 떼게 했다.",
       "예방은 눈에 띄지 않게 작동한다.","예방 예산은 가장 먼저 깎이는 경향이 있다.",
       "필자는 이 무늬가 어느 시대에나 되풀이된다고 본다."], ans:2},
  {t:"write", q:"필자가 예방을 '정치적으로 불리하다'고 본 이유를 우리말 한 문장으로 써 보세요.",
   ans:"성과가 일어나지 않은 일이라 아무도 보거나 기억하지 못하기 때문이다."}
 ],
 fl: {
  model: { n:"⑪",
   toks: [["No one","s"],["thanks","v"],["a clean pipe","m"],["and","c"],["no one","s"],
          ["remembers","v"],["the illness they did not get","m"]],
   ko:"깨끗한 수도관에 고마워하는 사람은 없고, 걸리지 않은 병을 기억하는 사람도 없다." },
  drill: [
   { n:"②", en:"John Snow marked each death on a map and watched a pattern appear.",
     ans:"S John Snow · △V marked · O each death · M on a map · [and] △V watched · O a pattern appear",
     ko:"존 스노는 죽음 하나하나를 지도에 표시했고, 하나의 무늬가 떠오르는 것을 보았다." },
   { n:"⑤", en:"Snow could not see the bacterium; the microscope work came later.",
     ans:"S Snow · △V could not see · O the bacterium · S the microscope work · △V came · M later",
     ko:"스노는 세균을 볼 수 없었다. 현미경 연구는 나중 일이었다." },
   { n:"⑭", en:"Public health is the strange field where success looks like nothing happening.",
     ans:"S Public health · △V is · C the strange field · M where success looks like nothing happening",
     ko:"공중보건은 성공이 아무 일도 없는 것처럼 보이는 이상한 분야다." }
  ]
 },
 syn: [
  { n:"②", name:"지각동사 watch + 목적어 + 동사원형",
    q:"John Snow marked each death on a map and «watched a pattern appear».",
    d:"<b>watch·see·hear + 목적어 + 동사원형</b>은 '~가 …하는 것을 보다/듣다'. to 를 붙이지 않는다.",
    k:"그는 하나의 무늬가 떠오르는 것을 보았다." },
  { n:"⑭", name:"관계부사 where",
    q:"Public health is the strange field «where success looks like» nothing happening.",
    d:"<b>where</b>는 장소·분야를 가리키는 명사를 꾸미며, 뒤에 완전한 문장이 온다.",
    k:"공중보건은 성공이 아무 일도 없는 것처럼 보이는 분야다." }
 ],
 synd: [
  { u:"구문 1", en:"The nurse heard the machine stop in the next room.",
    k:"간호사는 옆방에서 기계가 멈추는 소리를 들었다." },
  { u:"구문 2", en:"This is the street where the pump once stood.",
    k:"여기가 예전에 그 펌프가 서 있던 거리다." },
  { u:"구문 1 + 2", en:"That is the ward where visitors watched the fever fall.",
    k:"저기가 방문객들이 열이 내리는 것을 지켜본 병동이다." }
 ],
 wtype: ["무관","정답","무관","지엽","무관"],
 stype: ["일치","반대","일치","일치","일치"],
 why: [["세균의 발견은 이 글보다 나중 일이라고 밝히고 있다"],["정답"],
       ["지도 그리는 법은 글의 관심사가 아니다"],
       ["런던은 사례의 무대일 뿐 주제가 아니다"],["콜레라 치료법은 글에 나오지 않는다"]],
 src: [["②"],["⑤과 어긋남 — 세균을 보지 못한 채로 조치했다"],["⑧"],["⑫"],["⑬"]],
 kb: {
  title:"보이지 않는 성과",
  lead:"막아 낸 일은 기록에 남지 않는다.",
  items: [
   ["브로드가의 펌프",
    "1854년 존 스노는 사망자 위치를 지도에 찍어 브로드가 펌프를 지목했고, 손잡이 제거 뒤 유행이 잦아들었다. 세균설이 자리 잡기 전이었지만 자료의 무늬만으로 충분했다. 역학(疫學)의 출발점으로 꼽힌다."],
   ["Y2K 역설",
    "1999년 대비 작업에 큰 비용이 들었고, 2000년에 큰 사고는 없었다. 그러자 '괜한 돈을 썼다'는 말이 나왔다. 잘 막아 낼수록 그 필요를 증명하기 어려워지는 구조를 보여 준다."],
   ["가장 값싼 개입",
    "세계보건기구는 안전한 식수와 위생, 예방접종을 비용 대비 효과가 가장 큰 보건 개입으로 꼽는다. 눈에 띄지 않는 쪽이 대개 더 싸고 더 많은 사람을 살린다."]
  ],
  ask:"'아무 일도 없었다'가 성과인 일이 내 생활에도 있는가? 무엇이 그것을 가능하게 했을까?"
 }
},
{
 no: "20", key: "burnout",
 accent: "#C0803A", tint: "#FAF0E1", deep: "#8A551A",
 en: "The Doctor Who Cannot Rest",
 ko: "쉴 수 없는 의사",
 goal: "의료 인력의 소진이 개인 문제가 아니라 제도 설계의 문제임을 설명할 수 있다.",
 fig: "Figure 1  당직표 위에 겹쳐 놓은 실수 곡선.",
 tip: "먼저 생각해 보자. 30시간을 깨어 있은 사람에게 중요한 결정을 맡겨도 될까?",
 sent: [
  "Medical training long treated exhaustion as a badge rather than a risk.",
  "Young doctors worked thirty hours at a stretch and were openly praised for it.",
  "The reasoning sounded noble: patients need someone who never leaves.",
  "Sleep research, gathered over several decades, told a different story.",
  "After about seventeen hours awake, performance falls to the level of mild drunkenness.",
  "Attention narrows, and errors of the careless kind become far more likely.",
  "A tired doctor is not lazy; a tired brain simply works worse.",
  "When hospitals shortened shifts, serious mistakes dropped in several studies.",
  "But shorter shifts create a new danger at every handover.",
  "Each time one doctor passes a patient to another, information can be lost.",
  "So the answer to the problem was never simply fewer hours on the ward.",
  "It was fewer hours plus a written, spoken, checked handover.",
  "Naming exhaustion a personal weakness had hidden a design problem for a century.",
  "Systems that depend on nobody ever being tired are badly built.",
  "Good design assumes the human being it actually has."
 ],
 kor: [
  "의학 수련은 오랫동안 탈진을 위험이 아니라 훈장처럼 다루었다.",
  "젊은 의사들은 서른 시간을 내리 일했고, 그 일로 드러내 놓고 칭찬을 받았다.",
  "그 논리는 고결하게 들렸다. 환자에게는 자리를 뜨지 않는 사람이 필요하다는 것이다.",
  "수십 년에 걸쳐 쌓인 수면 연구는 다른 이야기를 들려주었다.",
  "약 열일곱 시간을 깨어 있으면 수행 능력이 가벼운 취기 수준으로 떨어진다.",
  "주의는 좁아지고, 부주의한 종류의 실수가 훨씬 더 잘 일어난다.",
  "지친 의사가 게으른 것이 아니다. 지친 뇌가 그저 더 나쁘게 작동할 뿐이다.",
  "병원들이 근무 시간을 줄이자, 여러 연구에서 중대한 실수가 줄었다.",
  "그러나 짧아진 근무는 인계마다 새로운 위험을 만든다.",
  "한 의사가 환자를 다른 의사에게 넘길 때마다 정보가 사라질 수 있다.",
  "그래서 이 문제의 답은 결코 병동에서 보내는 시간을 줄이는 것만이 아니었다.",
  "시간을 줄이는 동시에, 적고 말하고 확인하는 인계를 갖추는 것이었다.",
  "탈진을 개인의 나약함이라 이름 붙인 일이 한 세기 동안 설계의 문제를 가려 왔다.",
  "아무도 지치지 않는다는 것을 전제로 돌아가는 체계는 잘못 지어진 것이다.",
  "좋은 설계는 실제로 자기 앞에 있는 사람을 전제한다."
 ],
 bank: [["exhaustion","①","탈진"],["stretch","②","(시간의) 연속"],["performance","⑤","수행 능력"],
        ["shift","⑧","근무 시간, 교대"],["handover","⑨","인계"],["assume","⑮","전제하다"]],
 defs: [["exhaustion","the state of being completely worn out"],
        ["stretch","a continuous period of time"],
        ["performance","how well a person does a task"],
        ["shift","a set period of work in a workplace"],
        ["handover","the act of passing responsibility to another"],
        ["assume","to take something as a starting condition"]],
 defOrder: [4,1,5,0,3,2],
 flow: [
  ["Old belief","Long hours were treated as a badge, not a risk",null],
  ["Evidence","After 17 hours awake, performance falls to (  ①  ) levels","drunken"],
  ["First fix","Shorter shifts lowered serious (  ②  ) in several studies","mistakes"],
  ["New risk","Every (  ③  ) is a chance to lose information","handover"],
  ["Real answer","Fewer hours plus a checked handover — a (  ④  ) problem","design"]
 ],
 flowBogi: "drunken · mistakes · handover · design · badge · attention",
 para: [
  ["① treated exhaustion as a badge","Tiredness was worn as a mark of ______.","honour"],
  ["⑦ A tired doctor is not lazy","Fatigue is not a failure of ______.","character"],
  ["⑨ shorter shifts create a new danger","Each fix brings its own ______.","cost"],
  ["⑬ had hidden a design problem","Blaming people ______ the real cause.","masked"],
  ["⑮ assumes the human being it actually has","Good systems plan for ______ people.","real"]
 ],
 paraBogi: "honour · character · cost · masked · real · shame · benefit · perfect",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How Much Sleep a Teenager Needs","Tiredness Is a Design Problem",
       "Doctors Should Simply Work Less","The History of Medical Schools",
       "Why Alcohol Slows the Brain"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["과거에는 긴 근무가 칭찬받는 일이었다.","열일곱 시간쯤 깨어 있으면 수행 능력이 크게 떨어진다.",
       "근무를 줄이자 인계의 위험도 함께 사라졌다.","인계 때 정보가 사라질 수 있다.",
       "필자는 탈진을 개인의 나약함으로 보지 않는다."], ans:3},
  {t:"write", q:"필자가 제시한 해답을 우리말 한 문장으로 써 보세요.",
   ans:"근무 시간을 줄이는 동시에 적고 말하고 확인하는 인계 절차를 함께 갖추는 것이다."}
 ],
 fl: {
  model: { n:"⑭",
   toks: [["Systems","s"],["that depend on nobody ever being tired","m"],
          ["are","v"],["badly built","c"]],
   ko:"아무도 지치지 않는다는 것을 전제로 돌아가는 체계는 잘못 지어진 것이다." },
  drill: [
   { n:"⑤", en:"After about seventeen hours awake, performance falls to the level of mild drunkenness.",
     ans:"M After about seventeen hours awake · S performance · △V falls · M to the level of mild drunkenness",
     ko:"약 열일곱 시간을 깨어 있으면 수행 능력이 가벼운 취기 수준으로 떨어진다." },
   { n:"⑩", en:"Each time one doctor passes a patient to another, information can be lost.",
     ans:"[Each time] S′ one doctor · △V′ passes · O a patient · M to another · S information · △V can be lost",
     ko:"한 의사가 환자를 다른 의사에게 넘길 때마다 정보가 사라질 수 있다." },
   { n:"⑬", en:"Naming exhaustion a personal weakness had hidden a design problem for a century.",
     ans:"S Naming exhaustion a personal weakness · △V had hidden · O a design problem · M for a century",
     ko:"탈진을 개인의 나약함이라 이름 붙인 일이 한 세기 동안 설계의 문제를 가려 왔다." }
  ]
 },
 syn: [
  { n:"⑩", name:"each time + 절 (접속사)",
    q:"«Each time one doctor passes» a patient to another, information can be lost.",
    d:"<b>each time</b>은 '~할 때마다'라는 접속사로 쓰인다. every time 도 같은 방식이다.",
    k:"한 의사가 환자를 다른 의사에게 넘길 때마다 정보가 사라질 수 있다." },
  { n:"⑬", name:"동명사 주어 + 과거완료",
    q:"«Naming exhaustion a personal weakness had hidden» a design problem for a century.",
    d:"동명사구가 주어이므로 단수. <b>had p.p.</b>는 지금 밝혀지기 전까지 이어져 온 사정을 나타낸다.",
    k:"탈진을 개인의 나약함이라 부른 일이 설계 문제를 가려 왔었다." }
 ],
 synd: [
  { u:"구문 1", en:"Each time the alarm sounded, two nurses checked the chart.",
    k:"경보가 울릴 때마다 간호사 두 명이 차트를 확인했다." },
  { u:"구문 2", en:"Calling the error bad luck had delayed the repair for years.",
    k:"그 오류를 불운이라 부른 일이 수리를 여러 해 미뤄 왔었다." },
  { u:"구문 1 + 2", en:"Each time they blamed a person, ignoring the system had cost them more.",
    k:"사람을 탓할 때마다, 체계를 무시한 일이 그들에게 더 큰 대가를 치르게 했었다." }
 ],
 wtype: ["무관","정답","지엽","무관","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["청소년 수면 시간은 글에 나오지 않는다"],["정답"],
       ["근무 축소만으로는 부족하다는 것이 글의 논지다"],
       ["의과대학의 역사는 글의 소재가 아니다"],["음주의 뇌 영향은 비교로만 언급된다"]],
 src: [["①②"],["⑤"],["⑨과 어긋남 — 인계라는 새 위험이 생긴다"],["⑩"],["⑦"]],
 kb: {
  title:"지치는 것을 전제로 짓기",
  lead:"사람은 규정대로 버티지 않는다.",
  items: [
   ["17시간과 혈중알코올농도",
    "1997년 도슨과 리드는 17~19시간 각성 상태의 수행 저하가 혈중알코올농도 0.05% 수준에 해당한다고 보고했다. 이후 근무시간 규제 논의의 근거로 자주 인용된다."],
   ["리비 지언 사건과 근무시간 규제",
    "1984년 뉴욕에서 한 환자가 사망한 사건을 계기로, 수련의 근무시간을 제한하는 규정이 도입되었다. 미국은 2003년 주당 80시간 상한을 전국 기준으로 삼았다."],
   ["I-PASS 라는 인계 양식",
    "환자 상태와 할 일을 정해진 순서로 적고 말한 뒤 되읽어 확인하는 방식이다. 여러 소아과 병원에서 도입 후 인계로 인한 유해사건이 유의하게 줄었다는 보고가 있다."]
  ],
  ask:"우리 학교에서 '정신력으로 버티라'고 말하는 상황이 있는가? 그것을 설계 문제로 바꾸어 말해 보자."
 }
}
]};
