/* Unit 5 · Field 5 — Philosophy & Religion 철학·종교
   원서 Theme 21–25 의 주제를 예비고1 수준으로 다시 쓴 것. */
module.exports = {
 no: 5,
 field: "Philosophy & Religion",
 ko: "철학·종교",
 tagline: "묻는 자리 — 무엇을 답할 수 있고 무엇을 답할 수 없는가",
 next: { en: "Media & IT", ko: "연결이 우리에게서 무엇을 가져가는지 읽습니다", words: "175–205 words" },
 lessons: [
{
 no: "21", key: "ritual",
 accent: "#6B5B95", tint: "#EEEBF6", deep: "#453A66",
 en: "What a Ritual Does",
 ko: "의례가 하는 일",
 goal: "종교적 의례가 공동체에서 맡는 역할을 사회적 기능의 관점에서 설명할 수 있다.",
 fig: "Figure 1  같은 시각에 같은 동작을 하는 사람들.",
 tip: "먼저 생각해 보자. 우리 집에도 해마다 같은 날 반복하는 일이 있는가? 그것을 그만두면 무엇이 사라질까?",
 sent: [
  "Scholars who study religion often begin with a question that sounds odd.",
  "They ask not whether a belief is true, but what the belief does.",
  "A ritual gathers people at the same hour and asks them to move together.",
  "Standing, kneeling, singing the same line — the body learns before the mind agrees.",
  "Emile Durkheim argued that such moments make a group feel like one thing.",
  "The feeling is real even for those who cannot explain it afterwards.",
  "Rituals also cut time into pieces that a person can hold.",
  "A week has a shape because something returns on the seventh day.",
  "Birth, marriage, and death are marked so that they are not simply endured.",
  "Beliefs carry memory as well, storing what a community wants to keep.",
  "A story repeated for centuries outlives the people who first told it.",
  "None of this settles the question of whether the beliefs are true.",
  "That is a separate question, and a different kind of evidence answers it.",
  "But the social work is visible, and it can be studied like any other pattern.",
  "Asking what a practice does is not the same as judging it."
 ],
 kor: [
  "종교를 연구하는 학자들은 흔히 이상하게 들리는 질문에서 출발한다.",
  "그들은 어떤 믿음이 참인지가 아니라, 그 믿음이 무엇을 하는지를 묻는다.",
  "의례는 같은 시각에 사람들을 모으고, 함께 움직이라고 요구한다.",
  "서고, 무릎 꿇고, 같은 구절을 노래하는 동안 — 마음이 동의하기 전에 몸이 먼저 배운다.",
  "에밀 뒤르켐은 그런 순간이 한 집단을 하나처럼 느끼게 만든다고 주장했다.",
  "그 느낌은 나중에 그것을 설명하지 못하는 사람에게도 실재한다.",
  "의례는 또한 시간을 사람이 붙들 수 있는 조각으로 잘라 준다.",
  "일주일이 하나의 모양을 갖는 것은 이레째에 무언가가 돌아오기 때문이다.",
  "태어남과 혼인과 죽음은 표시되어, 그저 견뎌 내는 일이 되지 않는다.",
  "믿음은 기억도 나르는데, 한 공동체가 지키고 싶어 하는 것을 담아 둔다.",
  "수백 년 되풀이된 이야기는 그것을 처음 말한 사람들보다 오래 살아남는다.",
  "이 가운데 무엇도 그 믿음이 참인지의 문제를 결판내지는 않는다.",
  "그것은 별개의 질문이며, 다른 종류의 증거가 답한다.",
  "그러나 그 사회적 작용은 눈에 보이며, 다른 어떤 무늬처럼 연구될 수 있다.",
  "어떤 관행이 무엇을 하는지 묻는 일은 그것을 판단하는 일과 같지 않다."
 ],
 bank: [["ritual","③","의례"],["kneel","④","무릎 꿇다"],["endure","⑨","견뎌 내다"],
        ["outlive","⑪","~보다 오래 남다"],["settle","⑫","결판내다"],["practice","⑮","관행"]],
 defs: [["ritual","a set of actions repeated in a fixed order"],
        ["kneel","to rest on your knees"],
        ["endure","to bear something difficult"],
        ["outlive","to continue after others have gone"],
        ["settle","to end a question by deciding it"],
        ["practice","something a group does regularly"]],
 defOrder: [1,4,0,5,2,3],
 flow: [
  ["The question","Scholars ask not whether a belief is true, but what it does",null],
  ["Function 1","Moving together makes a group feel like (  ①  ) thing","one"],
  ["Function 2","Returning events cut (  ②  ) into pieces people can hold","time"],
  ["Function 3","Repeated stories carry (  ③  ) beyond one lifetime","memory"],
  ["Limit","This never (  ④  ) whether the beliefs are true","settles"]
 ],
 flowBogi: "one · time · memory · settles · body · silence",
 para: [
  ["② not whether a belief is true, but what it does","They study the ______, not the truth.","function"],
  ["④ the body learns before the mind agrees","Action comes ______ of understanding.","ahead"],
  ["⑨ so that they are not simply endured","Marking events makes them ______.","meaningful"],
  ["⑪ outlives the people who first told it","A story lasts ______ its authors.","beyond"],
  ["⑮ not the same as judging it","Describing is different from ______.","evaluating"]
 ],
 paraBogi: "function · ahead · meaningful · beyond · evaluating · truth · behind · proving",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["Which Religion Is the True One","Asking What a Belief Does",
       "The Life of Emile Durkheim","Why People Should Attend Ceremonies",
       "A History of the Seven-Day Week"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["학자들은 믿음이 무엇을 하는지에서 출발한다.","의례는 사람들을 같은 시각에 모은다.",
       "필자는 이 연구가 믿음의 참·거짓도 판정한다고 본다.","되풀이된 이야기는 첫 화자보다 오래 남는다.",
       "필자는 기술하는 일과 판단하는 일을 구분한다."], ans:3},
  {t:"write", q:"필자가 '무엇을 하는지 묻는 일'과 '판단하는 일'을 구분한 이유를 우리말 한 문장으로 써 보세요.",
   ans:"참·거짓은 다른 종류의 증거가 답하는 별개의 질문이기 때문이다."}
 ],
 fl: {
  model: { n:"⑧",
   toks: [["A week","s"],["has","v"],["a shape","m"],["because","c"],["something","s2"],
          ["returns","v2"],["on the seventh day","m"]],
   ko:"일주일이 하나의 모양을 갖는 것은 이레째에 무언가가 돌아오기 때문이다." },
  drill: [
   { n:"②", en:"They ask not whether a belief is true, but what the belief does.",
     ans:"S They · △V ask · O not whether a belief is true, but what the belief does",
     ko:"그들은 어떤 믿음이 참인지가 아니라, 그 믿음이 무엇을 하는지를 묻는다." },
   { n:"⑤", en:"Emile Durkheim argued that such moments make a group feel like one thing.",
     ans:"S Emile Durkheim · △V argued · [that] S′ such moments · △V′ make · O a group feel like one thing",
     ko:"에밀 뒤르켐은 그런 순간이 한 집단을 하나처럼 느끼게 만든다고 주장했다." },
   { n:"⑭", en:"But the social work is visible, and it can be studied like any other pattern.",
     ans:"S the social work · △V is · C visible · [and] S it · △V can be studied · M like any other pattern",
     ko:"그러나 그 사회적 작용은 눈에 보이며, 다른 어떤 무늬처럼 연구될 수 있다." }
  ]
 },
 syn: [
  { n:"②", name:"not A but B — 의문사절 병렬",
    q:"They ask «not whether a belief is true, but what the belief does».",
    d:"<b>not A but B</b> 자리에 의문사절 둘이 나란히 왔다. 두 절 모두 ask 의 목적어다.",
    k:"그들은 믿음이 참인지가 아니라 그 믿음이 무엇을 하는지를 묻는다." },
  { n:"⑨", name:"so that + 절 (목적)",
    q:"Birth, marriage, and death are marked «so that they are not simply endured».",
    d:"<b>so that + 절</b>은 '~하도록'이라는 목적을 나타낸다. 앞의 행위가 노리는 결과다.",
    k:"태어남과 혼인과 죽음은 그저 견뎌 내는 일이 되지 않도록 표시된다." }
 ],
 synd: [
  { u:"구문 1", en:"The class discussed not who wrote it but why it was written.",
    k:"학생들은 누가 그것을 썼는지가 아니라 왜 쓰였는지를 논의했다." },
  { u:"구문 2", en:"The bell rings early so that everyone arrives together.",
    k:"모두가 함께 도착하도록 종이 일찍 울린다." },
  { u:"구문 1 + 2", en:"They kept the date not for comfort but so that no one would forget.",
    k:"그들이 그 날짜를 지킨 것은 위안 때문이 아니라 아무도 잊지 않도록 하기 위해서였다." }
 ],
 wtype: ["무관","정답","무관","반대","지엽"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["어느 종교가 참인지는 다루지 않는다고 밝히고 있다"],["정답"],
       ["뒤르켐의 생애는 글의 주제가 아니다"],
       ["글은 참석을 권하지 않는다 — 판단과 기술을 구분한다"],
       ["일주일의 유래는 예로 든 한 부분일 뿐이다"]],
 src: [["①②"],["③"],["⑫⑬과 어긋남 — 참·거짓은 별개의 질문이라고 했다"],["⑪"],["⑮"]],
 kb: {
  title:"함께 움직인다는 것",
  lead:"몸이 먼저 배우는 일들이 있다.",
  items: [
   ["뒤르켐의 '집합적 열광'",
    "1912년 『종교 생활의 원초적 형태』에서 뒤르켐은 사람들이 한자리에 모여 같은 동작을 할 때 생기는 고양된 감정을 집합적 열광이라 불렀다. 그는 이것이 사회가 스스로를 확인하는 방식이라고 보았다."],
   ["같이 걸으면 마음이 맞춰진다",
    "심리학 실험에서 낯선 사람들끼리 발을 맞춰 걷거나 함께 노래한 뒤에는 협력 과제 성적이 올라간다는 결과가 여러 차례 보고되었다. 동작의 동기화가 소속감을 만든다는 쪽의 근거로 쓰인다."],
   ["달력은 왜 이레인가",
    "칠일 주기는 천체 관측이 아니라 관습에서 왔다. 프랑스 혁명기와 소련이 각각 10일·5일 주기를 도입했지만 오래가지 못하고 되돌아갔다."]
  ],
  ask:"내가 매주 같은 요일에 반복하는 일이 있는가? 그것이 내 한 주의 모양을 어떻게 만들고 있는가?"
 }
},
{
 no: "22", key: "twoq",
 accent: "#3F7D5C", tint: "#E6F1EB", deep: "#245239",
 en: "Two Kinds of Question",
 ko: "두 종류의 질문",
 goal: "'어떻게'를 묻는 질문과 '무엇을 해야 하는가'를 묻는 질문의 차이를 설명할 수 있다.",
 fig: "Figure 1  같은 사실 위에 놓인 서로 다른 질문.",
 tip: "먼저 생각해 보자. '물이 100도에서 끓는다'는 사실에서 '물을 끓여야 한다'가 따라 나오는가?",
 sent: [
  "Darwin's account explains how living forms changed over long stretches of time.",
  "It describes variation, inheritance, and the slow filtering of survival.",
  "That is an answer to a question about mechanism.",
  "Many arguments treat it as an answer to a different question altogether.",
  "They read it as a claim about what human life is for.",
  "But a description of how something came about does not tell us how to live.",
  "Philosophers call this gap the difference between is and ought.",
  "No list of facts, however long, produces a duty on its own.",
  "The gap runs in both directions, which is easy to forget.",
  "A moral conviction cannot decide what happened in the fossil record either.",
  "Recognising the gap does not end disagreement, and it is not meant to.",
  "People still differ deeply about meaning, and those differences are real.",
  "What the gap does is keep two questions from being mistaken for one.",
  "A biologist and a believer may be answering different questions entirely.",
  "Much heat is produced by arguments that were never about the same thing."
 ],
 kor: [
  "다윈의 설명은 생명의 형태가 아주 긴 시간에 걸쳐 어떻게 변해 왔는지를 설명한다.",
  "그것은 변이와 유전, 그리고 생존이라는 느린 걸러 냄을 서술한다.",
  "그것은 작동 방식에 관한 질문에 대한 답이다.",
  "많은 논쟁은 그것을 전혀 다른 질문에 대한 답인 것처럼 다룬다.",
  "그들은 그것을 인간의 삶이 무엇을 위한 것인가에 대한 주장으로 읽는다.",
  "그러나 무언가가 어떻게 생겨났는지에 대한 서술은 어떻게 살아야 하는지를 말해 주지 않는다.",
  "철학자들은 이 간극을 '있다'와 '해야 한다'의 차이라고 부른다.",
  "아무리 긴 사실의 목록도 그것만으로 의무를 만들어 내지는 못한다.",
  "그 간극은 양쪽으로 다 나 있는데, 이 점은 잊히기 쉽다.",
  "도덕적 확신 역시 화석 기록에서 무슨 일이 있었는지를 정할 수는 없다.",
  "간극을 알아본다고 해서 이견이 끝나지는 않으며, 그것을 노린 것도 아니다.",
  "사람들은 여전히 의미에 대해 깊이 다르게 생각하고, 그 차이는 실재한다.",
  "그 간극이 하는 일은 두 질문이 하나로 오해되지 않게 막는 것이다.",
  "생물학자와 신앙인은 아예 다른 질문에 답하고 있는 것일 수 있다.",
  "애초에 같은 것을 두고 다툰 적이 없는 논쟁에서 많은 열기가 생겨난다."
 ],
 bank: [["variation","②","변이"],["inheritance","②","유전"],["mechanism","③","작동 방식"],
        ["duty","⑧","의무"],["conviction","⑩","확신"],["disagreement","⑪","이견"]],
 defs: [["variation","small differences among individuals"],
        ["inheritance","the passing of traits to offspring"],
        ["mechanism","the way a process actually works"],
        ["duty","something a person ought to do"],
        ["conviction","a firmly held belief"],
        ["disagreement","a state of holding different views"]],
 defOrder: [2,0,4,5,1,3],
 flow: [
  ["What it answers","Darwin's account explains the mechanism of change",null],
  ["The misreading","Some treat it as a claim about what life is (  ①  )","for"],
  ["The principle","Facts alone never produce a (  ②  )","duty"],
  ["Both directions","A conviction cannot decide the (  ③  ) record either","fossil"],
  ["What it achieves","It keeps two questions from being mistaken for (  ④  )","one"]
 ],
 flowBogi: "for · duty · fossil · one · meaning · variation",
 para: [
  ["⑥ does not tell us how to live","Description gives no ______ for action.","rule"],
  ["⑧ however long, produces a duty","Facts alone cannot create an ______.","obligation"],
  ["⑨ The gap runs in both directions","The limit applies to ______ sides.","both"],
  ["⑪ does not end disagreement","Naming the gap leaves the dispute ______.","open"],
  ["⑮ arguments that were never about the same thing","Much conflict comes from ______ questions.","confused"]
 ],
 paraBogi: "rule · obligation · both · open · confused · proof · closed · single",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How Fossils Are Dated","Two Questions That Are Often Confused",
       "Why Science Should Replace Belief","The Life and Voyages of Darwin",
       "Which Side Wins the Debate"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["다윈의 설명은 작동 방식에 관한 답이다.","사실의 목록만으로는 의무가 생기지 않는다.",
       "간극을 알아보면 이견이 사라진다.","도덕적 확신도 화석 기록을 정할 수는 없다.",
       "필자는 두 질문이 다를 수 있다고 본다."], ans:3},
  {t:"write", q:"필자가 말하는 '간극'이 실제로 하는 일을 우리말 한 문장으로 써 보세요.",
   ans:"서로 다른 두 질문이 같은 하나의 질문으로 오해되지 않게 막아 주는 일이다."}
 ],
 fl: {
  model: { n:"⑬",
   toks: [["What the gap does","s"],["is","v"],
          ["keep two questions from being mistaken for one","c"]],
   ko:"그 간극이 하는 일은 두 질문이 하나로 오해되지 않게 막는 것이다." },
  drill: [
   { n:"⑥", en:"But a description of how something came about does not tell us how to live.",
     ans:"S a description of how something came about · △V does not tell · O us · O how to live",
     ko:"그러나 무언가가 어떻게 생겨났는지에 대한 서술은 어떻게 살아야 하는지를 말해 주지 않는다." },
   { n:"⑧", en:"No list of facts, however long, produces a duty on its own.",
     ans:"S No list of facts · M however long · △V produces · O a duty · M on its own",
     ko:"아무리 긴 사실의 목록도 그것만으로 의무를 만들어 내지는 못한다." },
   { n:"⑮", en:"Much heat is produced by arguments that were never about the same thing.",
     ans:"S Much heat · △V is produced · M by arguments that were never about the same thing",
     ko:"애초에 같은 것을 두고 다툰 적이 없는 논쟁에서 많은 열기가 생겨난다." }
  ]
 },
 syn: [
  { n:"⑧", name:"however + 형용사 (양보)",
    q:"No list of facts, «however long», produces a duty on its own.",
    d:"<b>however + 형용사/부사</b>는 '아무리 ~하더라도'. no matter how 와 같은 뜻이다.",
    k:"아무리 긴 사실의 목록이라도 그것만으로 의무를 만들지 못한다." },
  { n:"⑬", name:"What절 주어 + is + 명사구",
    q:"«What the gap does is keep» two questions from being mistaken for one.",
    d:"<b>What ~ does is (to) 동사원형</b>은 '~가 하는 일은 …하는 것이다'. to 는 흔히 생략된다.",
    k:"그 간극이 하는 일은 두 질문을 갈라 두는 것이다." }
 ],
 synd: [
  { u:"구문 1", en:"However clear the data looks, it cannot tell us what is fair.",
    k:"자료가 아무리 분명해 보여도, 무엇이 공정한지는 말해 주지 못한다." },
  { u:"구문 2", en:"What the rule does is give everyone the same starting point.",
    k:"그 규칙이 하는 일은 모두에게 같은 출발점을 주는 것이다." },
  { u:"구문 1 + 2", en:"What the method does, however simple it seems, is keep the two apart.",
    k:"그 방법이 하는 일은, 아무리 단순해 보여도, 그 둘을 갈라 두는 것이다." }
 ],
 wtype: ["무관","정답","반대","무관","반대"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["화석 연대 측정법은 글에 나오지 않는다"],["정답"],
       ["글은 한쪽이 다른 쪽을 대체한다고 말하지 않는다 — 정반대다"],
       ["다윈의 생애와 항해는 글의 소재가 아니다"],
       ["글은 승패를 가리려는 것이 아니라고 말한다 — 정반대다"]],
 src: [["③"],["⑧"],["⑪과 어긋남 — 이견이 끝나지는 않는다고 했다"],["⑩"],["⑭"]],
 kb: {
  title:"사실과 당위 사이",
  lead:"다리 하나가 빠져 있는 논증들.",
  items: [
   ["흄이 지적한 한 걸음",
    "1739년 데이비드 흄은 논증이 '이다'로 이어지다가 갑자기 '해야 한다'로 넘어가는 대목을 지적하며, 그 전환에는 따로 설명이 필요하다고 썼다. 오늘날 '흄의 단두대'라고 부른다."],
   ["'자연스럽다'는 말의 함정",
    "자연에서 흔히 일어난다는 이유로 옳다고 결론짓는 것을 자연주의적 오류라 한다. 1903년 무어가 정식화했고, 지금도 광고와 논쟁에서 자주 등장한다."],
   ["교황청과 진화론",
    "1996년 요한 바오로 2세는 진화가 '하나의 가설 이상'이라고 언급했다. 기제에 관한 설명과 의미에 관한 질문을 분리해 다루는 입장의 한 예로 자주 인용된다."]
  ],
  ask:"'원래 그런 것이다'라는 말로 끝난 논쟁을 떠올려 보자. 거기서 빠져 있던 한 걸음은 무엇이었을까?"
 }
},
{
 no: "23", key: "sophist",
 accent: "#B5673A", tint: "#FAEDE4", deep: "#7F3F18",
 en: "Winning Without Being Right",
 ko: "옳지 않고도 이기는 법",
 goal: "설득의 기술과 참을 가리는 일이 어떻게 갈라지는지 예를 들어 설명할 수 있다.",
 fig: "Figure 1  이기는 길과 맞는 길이 갈라지는 지점.",
 tip: "먼저 생각해 보자. 토론에서 이긴 사람이 늘 옳은 사람일까?",
 sent: [
  "In ancient Athens, a citizen who could speak well could change his own life.",
  "Courts had no lawyers, so each man argued his case himself.",
  "Teachers appeared who promised to make any student persuasive.",
  "They were called sophists, and at first the word was not an insult.",
  "They taught structure, timing, and the art of anticipating an objection.",
  "Much of that teaching is still sound, and debate classes use it today.",
  "The trouble began with a further promise.",
  "Some claimed they could make the weaker argument appear the stronger.",
  "Plato attacked this fiercely, and the word has carried his scorn ever since.",
  "His complaint was not that persuasion is bad.",
  "It was that a skill aimed only at winning has no reason to stop at the truth.",
  "The same tools that clarify a good case can dress up a poor one.",
  "This is why we teach argument and evidence together rather than separately.",
  "A student who learns only to win becomes harder to correct, not easier.",
  "Rhetoric is a tool, and tools take the direction the hand gives them."
 ],
 kor: [
  "고대 아테네에서는 말을 잘하는 시민이 자기 삶을 바꿀 수 있었다.",
  "법정에는 변호사가 없어서, 저마다 자기 사건을 스스로 변론했다.",
  "어떤 학생이든 설득력 있게 만들어 주겠다고 약속하는 교사들이 나타났다.",
  "그들은 소피스트라 불렸고, 처음에 그 말은 욕이 아니었다.",
  "그들은 구성과 때 맞추기, 그리고 반론을 미리 내다보는 기술을 가르쳤다.",
  "그 가르침의 많은 부분은 지금도 타당해서, 오늘날 토론 수업이 그것을 쓴다.",
  "문제는 한 걸음 더 나아간 약속에서 시작되었다.",
  "일부는 더 약한 논거를 더 강해 보이게 만들 수 있다고 주장했다.",
  "플라톤은 이를 맹렬히 공격했고, 그 말은 이후로 그의 경멸을 지니고 다닌다.",
  "그의 불만은 설득이 나쁘다는 것이 아니었다.",
  "이기는 것만을 겨눈 기술에는 진실 앞에서 멈출 이유가 없다는 것이었다.",
  "좋은 주장을 또렷하게 만드는 바로 그 도구가 나쁜 주장을 그럴듯하게 꾸밀 수도 있다.",
  "우리가 논증과 증거를 따로가 아니라 함께 가르치는 이유가 이것이다.",
  "이기는 법만 배운 학생은 고치기 쉬워지는 것이 아니라 더 어려워진다.",
  "수사학은 도구이고, 도구는 그것을 쥔 손이 주는 방향을 따라간다."
 ],
 bank: [["citizen","①","시민"],["persuasive","③","설득력 있는"],["insult","④","모욕"],
        ["objection","⑤","반론"],["scorn","⑨","경멸"],["clarify","⑫","또렷하게 하다"]],
 defs: [["citizen","a legal member of a state"],
        ["persuasive","able to make others agree"],
        ["insult","a remark meant to offend"],
        ["objection","a reason given against a claim"],
        ["scorn","a feeling that something deserves no respect"],
        ["clarify","to make something easier to understand"]],
 defOrder: [3,0,5,1,4,2],
 flow: [
  ["Setting","In Athens each citizen argued his own case in court",null],
  ["The teachers","Sophists promised to make any student (  ①  )","persuasive"],
  ["What was useful","Structure, timing, and anticipating an (  ②  )","objection"],
  ["The further promise","Making the (  ③  ) argument appear the stronger","weaker"],
  ["Plato's point","A skill aimed only at winning need not stop at the (  ④  )","truth"]
 ],
 flowBogi: "persuasive · objection · weaker · truth · insult · silence",
 para: [
  ["④ at first the word was not an insult","The term became negative only ______.","later"],
  ["⑥ Much of that teaching is still sound","Part of their method remains ______.","useful"],
  ["⑩ not that persuasion is bad","Plato did not ______ persuasion itself.","reject"],
  ["⑫ can dress up a poor one","The same skill can ______ a weak case.","disguise"],
  ["⑮ tools take the direction the hand gives","A method has no ______ of its own.","aim"]
 ],
 paraBogi: "later · useful · reject · disguise · aim · early · praise · truth",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How Athenian Courts Were Organised","A Skill That Need Not Stop at the Truth",
       "Debate Classes Should Be Abolished","The Complete Biography of Plato",
       "Why Ancient Greeks Had No Lawyers"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["아테네 법정에는 변호사가 없었다.","'소피스트'는 처음부터 모욕적인 말이었다.",
       "그들이 가르친 기술의 일부는 지금도 쓰인다.","플라톤은 설득 자체를 나쁘다고 하지 않았다.",
       "필자는 논증과 증거를 함께 가르쳐야 한다고 본다."], ans:2},
  {t:"write", q:"필자가 논증과 증거를 함께 가르쳐야 한다고 본 이유를 우리말 한 문장으로 써 보세요.",
   ans:"이기는 기술만 익히면 나쁜 주장도 그럴듯하게 꾸미게 되어 고치기 어려워지기 때문이다."}
 ],
 fl: {
  model: { n:"⑪",
   toks: [["It","s"],["was","v"],["that","c"],["a skill aimed only at winning","s2"],
          ["has","v2"],["no reason to stop at the truth","m"]],
   ko:"이기는 것만을 겨눈 기술에는 진실 앞에서 멈출 이유가 없다는 것이었다." },
  drill: [
   { n:"②", en:"Courts had no lawyers, so each man argued his case himself.",
     ans:"S Courts · △V had · O no lawyers · [so] S′ each man · △V′ argued · O his case · M himself",
     ko:"법정에는 변호사가 없어서, 저마다 자기 사건을 스스로 변론했다." },
   { n:"⑧", en:"Some claimed they could make the weaker argument appear the stronger.",
     ans:"S Some · △V claimed · [that] S′ they · △V′ could make · O the weaker argument appear the stronger",
     ko:"일부는 더 약한 논거를 더 강해 보이게 만들 수 있다고 주장했다." },
   { n:"⑭", en:"A student who learns only to win becomes harder to correct, not easier.",
     ans:"S A student · M who learns only to win · △V becomes · C harder to correct, not easier",
     ko:"이기는 법만 배운 학생은 고치기 쉬워지는 것이 아니라 더 어려워진다." }
  ]
 },
 syn: [
  { n:"⑧", name:"make + 목적어 + 동사원형",
    q:"Some claimed they could «make the weaker argument appear» the stronger.",
    d:"<b>make + 목적어 + 동사원형</b>은 '~가 …하게 만들다'. appear 뒤에는 보어가 온다.",
    k:"더 약한 논거가 더 강해 보이게 만들 수 있다." },
  { n:"⑭", name:"형용사 + to부정사 (to 부정사의 부사적 용법)",
    q:"A student who learns only to win becomes «harder to correct», not easier.",
    d:"<b>형용사 + to부정사</b>는 '~하기에 …한'. correct 의 목적어는 앞의 주어다.",
    k:"이기는 법만 배운 학생은 고치기 더 어려워진다." }
 ],
 synd: [
  { u:"구문 1", en:"A good question can make a quiet class start talking.",
    k:"좋은 질문 하나가 조용한 교실을 말하게 만들 수 있다." },
  { u:"구문 2", en:"The old rule was simple to state but hard to follow.",
    k:"그 오래된 규칙은 말하기는 쉬웠지만 지키기는 어려웠다." },
  { u:"구문 1 + 2", en:"Practice makes the argument easier to build and harder to break.",
    k:"연습은 그 논증을 세우기 쉽고 무너뜨리기 어렵게 만든다." }
 ],
 wtype: ["지엽","정답","반대","무관","지엽"],
 stype: ["일치","반대","일치","일치","일치"],
 why: [["법정 조직은 배경으로만 언급된다"],["정답"],
       ["글은 토론 교육이 지금도 유용하다고 말한다 — 정반대다"],
       ["플라톤의 생애는 글의 소재가 아니다"],
       ["변호사가 없었다는 사실은 배경의 한 조각일 뿐이다"]],
 src: [["②"],["④과 어긋남 — 처음에는 욕이 아니었다"],["⑥"],["⑩"],["⑬"]],
 kb: {
  title:"말의 기술이 남긴 것",
  lead:"같은 도구가 두 방향으로 쓰인다.",
  items: [
   ["프로타고라스의 유명한 문장",
    "\"인간은 만물의 척도다\"라는 말은 소피스트 프로타고라스에게서 왔다. 절대적 기준을 의심한 이 문장은 상대주의 논쟁의 출발점으로 오래 인용되어 왔다."],
   ["아리스토텔레스의 세 가지 설득 수단",
    "『수사학』은 설득을 에토스(화자의 신뢰), 파토스(청중의 감정), 로고스(논증)로 나눈다. 플라톤과 달리 그는 수사학을 정당한 학문으로 다루었다."],
   ["오늘날의 이름들",
    "허수아비 논증, 인신공격, 미끄러운 비탈길 같은 오류 이름은 대부분 이 시기 논쟁에서 정리된 것이다. 이름을 아는 것만으로도 알아보기가 쉬워진다."]
  ],
  ask:"내가 최근에 이긴 말다툼을 떠올려 보자. 이겼을 때 나는 옳기도 했는가?"
 }
},
{
 no: "24", key: "stoic",
 accent: "#2E6E8E", tint: "#E3EFF4", deep: "#1B4A61",
 en: "The Part You Control",
 ko: "내가 어쩔 수 있는 몫",
 goal: "스토아의 '통제 구분'이 무엇을 말하고 무엇을 말하지 않는지 설명할 수 있다.",
 fig: "Figure 1  선 하나로 나뉘는 두 영역.",
 tip: "먼저 생각해 보자. 시험 결과와 시험 공부 중에서 내가 정말로 정할 수 있는 것은 어느 쪽일까?",
 sent: [
  "Epictetus was born a slave and taught philosophy after he was freed.",
  "His starting point was a single division.",
  "Some things are up to us, and some things are not.",
  "Our judgements and our efforts belong to the first group.",
  "Our reputation, our health, and the weather belong to the second.",
  "Suffering, he argued, comes from treating the second group as if it were the first.",
  "A runner who demands victory has staked himself on what he cannot control.",
  "A runner who demands good training has staked himself on what he can.",
  "The second runner may still lose, and he will still be disappointed.",
  "But the disappointment will not become the collapse of his whole footing.",
  "This is often misread as advice to stop caring.",
  "The Stoics cared a great deal and held public office throughout their lives.",
  "Marcus Aurelius wrote these notes while running an empire at war.",
  "The point was never to want less but to place wanting where it can act.",
  "Effort is the part that answers when you call it."
 ],
 kor: [
  "에픽테토스는 노예로 태어나 해방된 뒤 철학을 가르쳤다.",
  "그의 출발점은 단 하나의 구분이었다.",
  "어떤 것은 우리에게 달려 있고, 어떤 것은 그렇지 않다.",
  "우리의 판단과 노력은 앞의 무리에 속한다.",
  "우리의 평판과 건강과 날씨는 뒤의 무리에 속한다.",
  "괴로움은 뒤의 무리를 앞의 무리인 것처럼 다루는 데서 온다고 그는 주장했다.",
  "승리를 요구하는 주자는 자기가 통제할 수 없는 것에 자신을 걸어 둔 것이다.",
  "좋은 훈련을 요구하는 주자는 자기가 할 수 있는 것에 자신을 걸어 둔 것이다.",
  "두 번째 주자도 여전히 질 수 있고, 여전히 실망할 것이다.",
  "그러나 그 실망이 그가 딛고 선 자리 전체를 무너뜨리지는 않는다.",
  "이것은 흔히 신경을 끄라는 조언으로 잘못 읽힌다.",
  "스토아 철학자들은 몹시 많이 신경 썼고, 평생 공직을 맡았다.",
  "마르쿠스 아우렐리우스는 전쟁 중인 제국을 운영하면서 이 기록을 썼다.",
  "요점은 덜 원하라는 것이 아니라, 원함을 그것이 작동할 수 있는 자리에 놓으라는 것이었다.",
  "노력은 부르면 대답하는 쪽의 몫이다."
 ],
 bank: [["division","②","구분"],["judgement","④","판단"],["reputation","⑤","평판"],
        ["suffering","⑥","괴로움"],["stake","⑦","(~에) 걸다"],["collapse","⑩","무너짐"]],
 defs: [["division","a line drawn between two groups"],
        ["judgement","the act of forming an opinion"],
        ["reputation","what others generally think of you"],
        ["suffering","the experience of pain or distress"],
        ["stake","to risk something on an outcome"],
        ["collapse","a sudden falling apart"]],
 defOrder: [1,4,0,5,3,2],
 flow: [
  ["The division","Some things are up to us, and some things are not",null],
  ["Group one","Our (  ①  ) and our efforts","judgements"],
  ["Group two","Reputation, health, and the (  ②  )","weather"],
  ["The claim","Suffering comes from confusing the (  ③  ) group for the first","second"],
  ["The correction","Not to want (  ④  ), but to aim wanting where it can act","less"]
 ],
 flowBogi: "judgements · weather · second · less · victory · office",
 para: [
  ["⑥ treating the second group as if it were the first","Pain comes from ______ the two groups.","confusing"],
  ["⑦ has staked himself on what he cannot control","He bets on an ______ outcome.","uncertain"],
  ["⑩ will not become the collapse of his whole footing","Loss stays ______, not total.","partial"],
  ["⑪ misread as advice to stop caring","People mistake it for ______.","indifference"],
  ["⑭ not to want less but to place wanting","Redirect desire rather than ______ it.","shrink"]
 ],
 paraBogi: "confusing · uncertain · partial · indifference · shrink · sorting · certain · total",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Stop Caring About Results","Aiming Effort Where It Can Act",
       "The Roman Empire at War","Why Slaves Became Philosophers",
       "A Training Plan for Runners"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["에픽테토스는 노예로 태어났다.","판단과 노력은 우리에게 달린 쪽에 속한다.",
       "스토아 철학자들은 세상일에 관심을 끊고 물러났다.","좋은 훈련을 요구한 주자도 질 수 있다.",
       "요점은 덜 원하라는 것이 아니었다."], ans:3},
  {t:"write", q:"필자가 이 구분이 '신경을 끄라는 말이 아니다'라고 한 근거를 우리말 한 문장으로 써 보세요.",
   ans:"스토아 철학자들은 평생 공직을 맡으며 세상일에 깊이 관여했기 때문이다."}
 ],
 fl: {
  model: { n:"⑥",
   toks: [["Suffering","s"],[", he argued,",null],["comes","v"],["from treating the second group","m"],
          ["as if","c"],["it","s2"],["were","v2"],["the first","m"]],
   ko:"괴로움은 뒤의 무리를 앞의 무리인 것처럼 다루는 데서 온다고 그는 주장했다." },
  drill: [
   { n:"①", en:"Epictetus was born a slave and taught philosophy after he was freed.",
     ans:"S Epictetus · △V was born · C a slave · [and] △V taught · O philosophy · [after] S′ he · △V′ was freed",
     ko:"에픽테토스는 노예로 태어나 해방된 뒤 철학을 가르쳤다." },
   { n:"⑬", en:"Marcus Aurelius wrote these notes while running an empire at war.",
     ans:"S Marcus Aurelius · △V wrote · O these notes · M while running an empire at war",
     ko:"마르쿠스 아우렐리우스는 전쟁 중인 제국을 운영하면서 이 기록을 썼다." },
   { n:"⑭", en:"The point was never to want less but to place wanting where it can act.",
     ans:"S The point · △V was · M never · C to want less but to place wanting where it can act",
     ko:"요점은 덜 원하라는 것이 아니라 원함을 작동할 수 있는 자리에 놓으라는 것이었다." }
  ]
 },
 syn: [
  { n:"⑥", name:"as if + 가정법 과거",
    q:"Suffering comes from treating the second group «as if it were» the first.",
    d:"<b>as if + 주어 + 과거형</b>은 사실이 아닌 일을 가정한다. be동사는 인칭과 관계없이 were.",
    k:"뒤의 무리를 마치 앞의 무리인 것처럼 다루는 데서 온다." },
  { n:"⑬", name:"접속사 + 분사구문 (while ~ing)",
    q:"Marcus Aurelius wrote these notes «while running» an empire at war.",
    d:"<b>while + ~ing</b>는 주절과 동시에 일어난 일을 나타낸다. 주어가 같아서 생략되었다.",
    k:"그는 제국을 운영하면서 이 기록을 썼다." }
 ],
 synd: [
  { u:"구문 1", en:"He speaks about the plan as if it were already finished.",
    k:"그는 그 계획을 마치 이미 끝난 것처럼 말한다." },
  { u:"구문 2", en:"She took notes while listening to the lecture.",
    k:"그녀는 강의를 들으면서 필기를 했다." },
  { u:"구문 1 + 2", en:"He kept working as if nothing had changed, while waiting for the result.",
    k:"그는 결과를 기다리면서도 아무것도 달라지지 않은 것처럼 계속 일했다." }
 ],
 wtype: ["반대","정답","지엽","무관","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["글은 신경을 끄라는 말이 아니라고 밝힌다 — 정반대다"],["정답"],
       ["전쟁 중인 제국은 배경으로만 언급된다"],
       ["노예 출신이라는 사실은 도입의 한 조각일 뿐이다"],
       ["훈련 계획을 알려 주는 글이 아니다"]],
 src: [["①"],["④"],["⑫과 어긋남 — 평생 공직을 맡았다"],["⑨"],["⑭"]],
 kb: {
  title:"통제할 수 있는 것의 목록",
  lead:"경계를 그으면 힘 쓸 자리가 보인다.",
  items: [
   ["『엥케이리디온』 첫 문장",
    "에픽테토스의 편람은 \"어떤 것은 우리에게 달려 있고, 어떤 것은 그렇지 않다\"로 시작한다. 제자 아리아노스가 강의를 받아 적어 남긴 책이다."],
   ["전장에서 쓴 일기",
    "마르쿠스 아우렐리우스의 『명상록』은 출판을 염두에 두지 않은 자기 기록으로, 상당 부분이 게르만 원정 중에 쓰였다. 물러난 사람의 글이 아니라 일하는 사람의 글이다."],
   ["오늘날의 인지행동치료",
    "\"사람을 괴롭히는 것은 사건이 아니라 사건에 대한 견해다\"라는 에픽테토스의 문장은 CBT 교과서에 자주 인용된다. 창시자 아론 벡과 앨버트 엘리스가 직접 영향을 밝혔다."]
  ],
  ask:"요즘 나를 가장 힘들게 하는 일 하나를 골라, 내가 정할 수 있는 부분과 없는 부분으로 나눠 적어 보자."
 }
},
{
 no: "25", key: "wanting",
 accent: "#93476B", tint: "#F7E8EF", deep: "#67284A",
 en: "The Wanting That Never Ends",
 ko: "끝나지 않는 원함",
 goal: "쇼펜하우어의 욕망 구조 분석과 그가 제안한 해방의 통로를 설명할 수 있다.",
 fig: "Figure 1  올라설 때마다 다시 멀어지는 지평선.",
 tip: "먼저 생각해 보자. 간절히 바라던 것을 손에 넣었을 때, 그 기쁨은 얼마나 오래갔는가?",
 sent: [
  "Schopenhauer began from an observation anyone can check.",
  "Getting what you wanted feels wonderful, and the feeling does not last.",
  "The satisfied wish leaves a quiet space, and a new wish moves in.",
  "He called the force behind this restlessness the will.",
  "The will has no goal of its own; it only continues.",
  "On this account, pleasure is mostly the removal of a want rather than a positive gain.",
  "Boredom is what remains when nothing is missing, and he thought it revealing.",
  "His conclusion was famously dark, and many readers stop there.",
  "But he also described two ways out of the circle.",
  "The first is art, where for a moment you look without wanting anything.",
  "Music was his highest example, because it asks for nothing outside itself.",
  "The second is compassion, in which the wall between self and other thins.",
  "Neither escape is permanent, and he never claimed otherwise.",
  "Later thinkers disagreed sharply about whether the picture is accurate.",
  "Even so, the description of the treadmill is hard to forget once read."
 ],
 kor: [
  "쇼펜하우어는 누구나 확인해 볼 수 있는 관찰에서 시작했다.",
  "바라던 것을 얻는 일은 굉장하게 느껴지지만, 그 느낌은 오래가지 않는다.",
  "채워진 바람은 조용한 빈자리를 남기고, 새로운 바람이 그리로 들어온다.",
  "그는 이 들썩임 뒤의 힘을 '의지'라고 불렀다.",
  "의지에는 자기 목표가 없다. 그저 계속될 뿐이다.",
  "이 설명에 따르면 쾌락은 대개 적극적인 이득이라기보다 결핍의 제거다.",
  "지루함은 부족한 것이 없을 때 남는 것이며, 그는 그것이 많은 것을 드러낸다고 보았다.",
  "그의 결론은 어둡기로 유명해서, 많은 독자가 거기서 멈춘다.",
  "그러나 그는 이 원에서 빠져나가는 두 길도 서술했다.",
  "첫째는 예술인데, 거기서는 잠시 아무것도 원하지 않은 채로 바라보게 된다.",
  "음악이 그의 가장 높은 예였는데, 자기 바깥의 무엇도 요구하지 않기 때문이다.",
  "둘째는 연민이며, 그 안에서 나와 남 사이의 벽이 얇아진다.",
  "어느 탈출도 영구적이지 않고, 그도 그렇게 주장한 적이 없다.",
  "뒤의 사상가들은 이 그림이 정확한지를 두고 날카롭게 갈라졌다.",
  "그렇다 해도 그 쳇바퀴에 대한 서술은 한번 읽으면 잊기 어렵다."
 ],
 bank: [["satisfy","③","채우다, 만족시키다"],["restlessness","④","들썩임, 안절부절"],
        ["removal","⑥","제거"],["boredom","⑦","지루함"],["compassion","⑫","연민"],["permanent","⑬","영구적인"]],
 defs: [["satisfy","to meet a need or a wish"],
        ["restlessness","the state of being unable to settle"],
        ["removal","the act of taking something away"],
        ["boredom","the feeling of having nothing to engage you"],
        ["compassion","concern for the suffering of others"],
        ["permanent","lasting without end"]],
 defOrder: [3,0,5,1,4,2],
 flow: [
  ["Observation","Getting what you wanted feels wonderful, and then fades",null],
  ["The mechanism","A satisfied wish is replaced by a (  ①  ) one","new"],
  ["The name","He called the force behind this the (  ②  )","will"],
  ["Way out 1","In (  ③  ) you look for a moment without wanting","art"],
  ["Way out 2","In compassion the wall between self and other (  ④  )","thins"]
 ],
 flowBogi: "new · will · art · thins · boredom · music",
 para: [
  ["⑤ it only continues","The will moves without any ______.","destination"],
  ["⑥ the removal of a want rather than a gain","Pleasure is mainly ______, not addition.","relief"],
  ["⑦ what remains when nothing is missing","Boredom appears once desire is ______.","absent"],
  ["⑩ you look without wanting anything","Art suspends the act of ______.","wanting"],
  ["⑬ Neither escape is permanent","Both exits are only ______.","temporary"]
 ],
 paraBogi: "destination · relief · absent · wanting · temporary · purpose · gain · lasting",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Get What You Want","A Circle, and Two Doors Out of It",
       "Why Music Is Better Than Painting","The Complete Life of Schopenhauer",
       "Boredom Is Always Harmful"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["채워진 바람은 곧 새 바람으로 대체된다.","그는 쾌락을 주로 결핍의 제거로 보았다.",
       "그는 예술과 연민이 영구적인 해방이라고 주장했다.","음악을 가장 높은 예로 들었다.",
       "뒤의 사상가들은 이 그림을 두고 갈라졌다."], ans:3},
  {t:"write", q:"쇼펜하우어가 음악을 가장 높은 예로 든 이유를 우리말 한 문장으로 써 보세요.",
   ans:"음악은 자기 바깥의 무엇도 요구하지 않기 때문이다."}
 ],
 fl: {
  model: { n:"⑩",
   toks: [["The first","s"],["is","v"],["art","c"],[",",null],["where","c"],
          ["you","s2"],["look","v2"],["without wanting anything","m"]],
   ko:"첫째는 예술인데, 거기서는 잠시 아무것도 원하지 않은 채로 바라보게 된다." },
  drill: [
   { n:"③", en:"The satisfied wish leaves a quiet space, and a new wish moves in.",
     ans:"S The satisfied wish · △V leaves · O a quiet space · [and] S a new wish · △V moves in",
     ko:"채워진 바람은 조용한 빈자리를 남기고, 새로운 바람이 그리로 들어온다." },
   { n:"⑦", en:"Boredom is what remains when nothing is missing, and he thought it revealing.",
     ans:"S Boredom · △V is · C what remains when nothing is missing · [and] S he · △V thought · O it revealing",
     ko:"지루함은 부족한 것이 없을 때 남는 것이며, 그는 그것이 많은 것을 드러낸다고 보았다." },
   { n:"⑮", en:"Even so, the description of the treadmill is hard to forget once read.",
     ans:"M Even so · S the description of the treadmill · △V is · C hard to forget · M once read",
     ko:"그렇다 해도 그 쳇바퀴에 대한 서술은 한번 읽으면 잊기 어렵다." }
  ]
 },
 syn: [
  { n:"⑩", name:"계속적 용법의 관계부사 where",
    q:"The first is art, «where for a moment you look» without wanting anything.",
    d:"쉼표 뒤의 <b>where</b>는 앞의 명사를 보충 설명한다. '그런데 거기서는 ~' 으로 이어 읽는다.",
    k:"첫째는 예술인데, 거기서는 아무것도 원하지 않은 채 바라보게 된다." },
  { n:"⑮", name:"분사구문 축약 (once read)",
    q:"The description of the treadmill is hard to forget «once read».",
    d:"<b>once + 과거분사</b>는 'once it is read' 에서 주어와 be동사가 빠진 형태다.",
    k:"그 서술은 한번 읽고 나면 잊기 어렵다." }
 ],
 synd: [
  { u:"구문 1", en:"He returned to the hall, where the music had begun again.",
    k:"그는 강당으로 돌아갔는데, 거기서는 음악이 다시 시작되어 있었다." },
  { u:"구문 2", en:"The rule is simple once explained.",
    k:"그 규칙은 한번 설명하고 나면 간단하다." },
  { u:"구문 1 + 2", en:"She opened the letter, which was easy to understand once read aloud.",
    k:"그녀는 그 편지를 열었는데, 소리 내어 읽고 나니 이해하기 쉬웠다." }
 ],
 wtype: ["반대","정답","지엽","무관","반대"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["글은 원하는 것을 얻는 법을 다루지 않는다 — 정반대다"],["정답"],
       ["음악은 예술이라는 통로의 한 예일 뿐이다"],
       ["쇼펜하우어의 생애는 글의 소재가 아니다"],
       ["글은 지루함을 드러내 주는 것으로 본다 — 해롭다고만 하지 않는다"]],
 src: [["③"],["⑥"],["⑬과 어긋남 — 어느 탈출도 영구적이지 않다"],["⑪"],["⑭"]],
 kb: {
  title:"원함의 구조",
  lead:"채워도 줄지 않는 것에 관하여.",
  items: [
   ["'쾌락의 쳇바퀴'",
    "1971년 브릭먼과 캠벨이 이름 붙인 개념으로, 큰 행운이나 불운을 겪은 뒤에도 사람의 주관적 행복이 원래 수준으로 되돌아가는 경향을 가리킨다. 쇼펜하우어의 관찰과 겹치는 대목이 많다."],
   ["동양 사상과의 접점",
    "쇼펜하우어는 유럽 철학자 가운데 드물게 우파니샤드와 불교 문헌을 읽고 자기 체계에 끌어들였다. 욕망과 고통을 잇는 그의 도식은 그 독서와 무관하지 않다."],
   ["니체가 갈라선 지점",
    "니체는 쇼펜하우어를 스승처럼 읽었지만, 같은 관찰에서 정반대 결론을 냈다. 원함을 끄는 대신 그것을 긍정하는 쪽으로 방향을 돌린 것이다."]
  ],
  ask:"최근에 간절히 원했던 것 하나를 떠올려 보자. 손에 넣은 뒤 그 자리에 무엇이 들어왔는가?"
 }
}
]};
