/* Unit 8 · Field 8 — Politics, Law & History 정치·법·역사
   원서 Theme 36–40 의 주제를 예비고1 수준으로 다시 쓴 것. */
module.exports = {
 no: 8,
 field: "Politics, Law & History",
 ko: "정치·법·역사",
 tagline: "만들어진 것들 — 규칙과 이야기와 제도",
 next: { en: "Education, Psychology & Language", ko: "배우고 기억하는 방식을 읽습니다", words: "175–205 words" },
 lessons: [
{
 no: "36", key: "thrift",
 accent: "#38618F", tint: "#E6EDF5", deep: "#213E63",
 en: "When Everyone Saves at Once",
 ko: "모두가 한꺼번에 아낄 때",
 goal: "개인에게 합리적인 행동이 전체에서는 반대로 작용할 수 있음을 설명할 수 있다.",
 fig: "Figure 1  한 사람의 지출이 다른 사람의 소득이 되는 고리.",
 tip: "먼저 생각해 보자. 불황에 아껴 쓰는 것은 현명한 일이다. 모두가 그렇게 하면 어떻게 될까?",
 sent: [
  "A family that fears losing work will spend less and save more.",
  "Considered alone, that decision is careful and sensible.",
  "The trouble is that one household's spending is another household's income.",
  "When every family cuts at once, the incomes they were protecting shrink.",
  "Shops sell less, hire fewer people, and the fear that started it turns out to be right.",
  "Economists call this the paradox of thrift.",
  "It is a case where the sum of good choices produces a bad result.",
  "This is why governments often spend during a downturn instead of saving.",
  "Someone has to keep buying while everyone else is afraid to.",
  "Central banks act on the same logic by making borrowing cheaper.",
  "How much of this works, and for how long, is genuinely disputed.",
  "Some argue the debt merely moves the cost to a later year.",
  "Others reply that a deep recession also costs later, through skills that decay unused.",
  "The disagreement is about size and timing, not about the mechanism.",
  "Almost no one denies that the loop exists."
 ],
 kor: [
  "일자리를 잃을까 두려운 가정은 덜 쓰고 더 저축한다.",
  "따로 떼어 놓고 보면 그 결정은 신중하고 분별 있다.",
  "문제는 한 가구의 지출이 다른 가구의 소득이라는 점이다.",
  "모든 가정이 한꺼번에 줄이면, 그들이 지키려던 소득이 오히려 줄어든다.",
  "상점은 덜 팔고 사람을 덜 쓰며, 그 시작이 된 두려움은 결국 맞는 말이 된다.",
  "경제학자들은 이것을 '절약의 역설'이라고 부른다.",
  "좋은 선택들의 합이 나쁜 결과를 만드는 사례다.",
  "정부가 불황기에 아끼는 대신 흔히 지출하는 이유가 이것이다.",
  "다른 모두가 무서워서 못 사는 동안 누군가는 계속 사야 한다.",
  "중앙은행도 빌리는 값을 싸게 만드는 방식으로 같은 논리를 따른다.",
  "이 가운데 얼마나 효과가 있는지, 또 얼마나 오래가는지는 실제로 논쟁 중이다.",
  "어떤 이들은 그 빚이 비용을 뒤의 해로 옮길 뿐이라고 주장한다.",
  "다른 이들은 깊은 불황도 쓰이지 않아 녹슨 기술을 통해 뒤에 비용을 물린다고 답한다.",
  "그 이견은 크기와 시기에 관한 것이지, 작동 방식에 관한 것이 아니다.",
  "그 고리가 존재한다는 것을 부정하는 사람은 거의 없다."
 ],
 bank: [["household","③","가구, 세대"],["income","③","소득"],["shrink","④","줄어들다"],
        ["downturn","⑧","경기 하강, 불황"],["dispute","⑪","논쟁하다"],["recession","⑬","불황"]],
 defs: [["household","all the people living in one home"],
        ["income","money received for work or investment"],
        ["shrink","to become smaller in size or amount"],
        ["downturn","a period when business activity falls"],
        ["dispute","to argue against something"],
        ["recession","a long fall in a country's economic activity"]],
 defOrder: [3,0,5,1,4,2],
 flow: [
  ["One family","Fearing job loss, a family spends less and saves more",null],
  ["The loop","One household's spending is another household's (  ①  )","income"],
  ["The result","When all cut at once, the fear proves itself (  ②  )","right"],
  ["The name","Economists call this the paradox of (  ③  )","thrift"],
  ["The dispute","Not about the mechanism but about size and (  ④  )","timing"]
 ],
 flowBogi: "income · right · thrift · timing · saving · debt",
 para: [
  ["② Considered alone, that decision is sensible","In isolation the choice is ______.","reasonable"],
  ["⑤ the fear that started it turns out to be right","The worry becomes ______.","self-fulfilling"],
  ["⑦ the sum of good choices produces a bad result","Individual sense adds up to collective ______.","harm"],
  ["⑨ while everyone else is afraid to","Someone must spend when others ______.","withdraw"],
  ["⑭ about size and timing, not the mechanism","They argue over ______, not the process.","degree"]
 ],
 paraBogi: "reasonable · self-fulfilling · harm · withdraw · degree · reckless · groundless · benefit",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Save Money at Home","When Good Choices Add Up Badly",
       "Governments Should Never Borrow","A History of Central Banking",
       "Why Shops Close in Winter"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["한 가구의 지출은 다른 가구의 소득이다.","중앙은행은 빌리는 값을 낮추는 방식으로 대응한다.",
       "경제학자들은 이 고리의 존재 자체를 두고 갈라진다.","깊은 불황도 뒤에 비용을 남긴다는 반론이 있다.",
       "따로 보면 아끼는 결정은 분별 있는 것이다."], ans:3},
  {t:"write", q:"필자가 정리한 경제학자들 사이 이견의 초점을 우리말 한 문장으로 써 보세요.",
   ans:"작동 방식이 아니라 개입의 크기와 시기를 두고 갈린다는 것이다."}
 ],
 fl: {
  model: { n:"④",
   toks: [["When","c"],["every family","s2"],["cuts","v2"],["at once","m"],[",",null],
          ["the incomes they were protecting","s"],["shrink","v"]],
   ko:"모든 가정이 한꺼번에 줄이면, 그들이 지키려던 소득이 오히려 줄어든다." },
  drill: [
   { n:"③", en:"The trouble is that one household's spending is another household's income.",
     ans:"S The trouble · △V is · [that] S′ one household's spending · △V′ is · C another household's income",
     ko:"문제는 한 가구의 지출이 다른 가구의 소득이라는 점이다." },
   { n:"⑨", en:"Someone has to keep buying while everyone else is afraid to.",
     ans:"S Someone · △V has to keep · O buying · [while] S′ everyone else · △V′ is · C afraid to",
     ko:"다른 모두가 무서워서 못 사는 동안 누군가는 계속 사야 한다." },
   { n:"⑬", en:"Others reply that a deep recession also costs later, through skills that decay unused.",
     ans:"S Others · △V reply · [that] S′ a deep recession · △V′ costs · M later, through skills that decay unused",
     ko:"다른 이들은 깊은 불황도 쓰이지 않아 녹슨 기술을 통해 뒤에 비용을 물린다고 답한다." }
  ]
 },
 syn: [
  { n:"②", name:"분사구문 (과거분사, 조건)",
    q:"«Considered alone», that decision is careful and sensible.",
    d:"과거분사 분사구문은 수동. 'If it is considered alone' 로 풀어 읽는다.",
    k:"따로 떼어 놓고 보면 그 결정은 신중하고 분별 있다." },
  { n:"⑨", name:"keep + 동명사",
    q:"Someone has to «keep buying» while everyone else is afraid to.",
    d:"<b>keep + ~ing</b>는 '계속 ~하다'. 뒤의 afraid to 다음에는 buy 가 생략되었다.",
    k:"누군가는 계속 사야 한다." }
 ],
 synd: [
  { u:"구문 1", en:"Measured over ten years, the loss looks much smaller.",
    k:"10년에 걸쳐 재어 보면 그 손실은 훨씬 작아 보인다." },
  { u:"구문 2", en:"The factory kept running through the whole winter.",
    k:"그 공장은 겨울 내내 계속 돌아갔다." },
  { u:"구문 1 + 2", en:"Judged by output alone, the plant kept improving every year.",
    k:"생산량만으로 판단하면 그 공장은 해마다 계속 나아지고 있었다." }
 ],
 wtype: ["무관","정답","반대","무관","지엽"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["가계 절약 요령은 글의 관심사가 아니다"],["정답"],
       ["글은 정부 지출의 논거를 함께 싣는다 — 정반대다"],
       ["중앙은행의 역사는 글에 나오지 않는다"],
       ["상점 이야기는 고리를 설명하는 한 단계일 뿐이다"]],
 src: [["③"],["⑩"],["⑮과 어긋남 — 고리의 존재는 거의 부정되지 않는다"],["⑬"],["②"]],
 kb: {
  title:"모으면 달라지는 것들",
  lead:"개인의 합이 곧 전체가 되지는 않는다.",
  items: [
   ["'절약의 역설'",
    "1936년 케인스가 정식화해 널리 알려졌지만, 비슷한 지적은 그 이전 문헌에도 있었다. 개인에게 옳은 행동이 모이면 반대 결과를 낳는다는 점에서 '구성의 오류'의 대표 사례로 꼽힌다."],
   ["경기장에서 일어서기",
    "앞사람이 일어서면 더 잘 보인다. 모두가 일어서면 아무도 더 잘 보이지 않고 다리만 아프다. 같은 구조를 설명할 때 자주 쓰이는 비유다."],
   ["논쟁이 남아 있는 자리",
    "재정 지출이 소득을 얼마나 늘리는지를 나타내는 '승수'의 크기는 시기와 조건에 따라 달라진다는 것이 여러 연구의 결론이다. 그래서 이견이 크기와 시기에 집중된다."]
  ],
  ask:"우리 반 모두가 각자에게 합리적인 선택을 했는데 결과가 나빴던 일이 있는가?"
 }
},
{
 no: "37", key: "camera",
 accent: "#A9503A", tint: "#F8EBE6", deep: "#77301C",
 en: "The Room and the Camera",
 ko: "방과 카메라",
 goal: "전달 매체의 변화가 정치 지도자의 일하는 방식을 어떻게 바꾸었는지 설명할 수 있다.",
 fig: "Figure 1  기자 몇 명, 라디오 한 대, 카메라 수천 대.",
 tip: "먼저 생각해 보자. 말하는 방식이 바뀌면 말하는 내용도 바뀔까?",
 sent: [
  "For most of the nineteenth century a president spoke mainly to a room.",
  "Speeches were printed the next day, edited by whoever ran the paper.",
  "The audience was real but slow, and it arrived through other people's hands.",
  "Radio removed those hands in a single step.",
  "Franklin Roosevelt used it to speak into kitchens without a newspaper in between.",
  "His tone changed to match the setting: quieter, closer, more like explanation than oratory.",
  "Television changed the calculation again, because now appearance carried argument.",
  "After the first televised debate in 1960, radio listeners and viewers reported different winners.",
  "The claim is often exaggerated, but the worry it raised was new and lasting.",
  "Each new channel narrowed the gap between saying and being heard.",
  "That sounds like pure gain, and part of it is.",
  "Yet a leader who can reach everyone directly can also bypass everyone who would question him.",
  "The press was slow, but it asked follow-up questions.",
  "Every technology that shortens the distance also removes something that stood in the middle.",
  "What stood there is worth naming before it goes."
 ],
 kor: [
  "19세기 대부분 동안 대통령은 주로 하나의 방을 향해 말했다.",
  "연설은 이튿날 인쇄되었고, 신문을 운영하는 사람이 손질했다.",
  "청중은 실재했지만 느렸고, 다른 사람들의 손을 거쳐 도착했다.",
  "라디오는 그 손들을 단번에 없앴다.",
  "프랭클린 루스벨트는 그것으로 신문을 사이에 두지 않고 부엌을 향해 말했다.",
  "그의 어조도 그 자리에 맞게 바뀌었다. 더 조용하고, 더 가깝고, 웅변보다 설명에 가까웠다.",
  "텔레비전은 셈을 또 한 번 바꾸었다. 이제 겉모습이 논증을 실어 날랐기 때문이다.",
  "1960년 첫 텔레비전 토론 뒤, 라디오 청취자와 시청자가 서로 다른 승자를 말했다.",
  "이 주장은 흔히 과장되지만, 그것이 불러온 걱정은 새롭고도 오래갔다.",
  "새 통로가 생길 때마다 말하는 것과 들리는 것 사이의 거리가 좁아졌다.",
  "그것은 순전한 이득처럼 들리고, 일부는 실제로 그렇다.",
  "그러나 모두에게 곧장 닿을 수 있는 지도자는 자기에게 따져 물을 모두를 건너뛸 수도 있다.",
  "언론은 느렸지만, 뒤이어 캐묻는 질문을 했다.",
  "거리를 줄이는 모든 기술은 그 가운데 서 있던 무언가도 함께 치운다.",
  "거기 서 있던 것이 무엇인지는 사라지기 전에 이름을 붙여 둘 만하다."
 ],
 bank: [["edit","②","손질하다"],["oratory","⑥","웅변"],["exaggerate","⑨","과장하다"],
        ["narrow","⑩","좁히다"],["bypass","⑫","건너뛰다"],["follow-up","⑬","뒤이은"]],
 defs: [["edit","to change a text before it is published"],
        ["oratory","the art of formal public speaking"],
        ["exaggerate","to state something as larger than it is"],
        ["narrow","to make the distance between two things smaller"],
        ["bypass","to go around something instead of through it"],
        ["follow-up","done to check or continue an earlier action"]],
 defOrder: [4,0,5,2,3,1],
 flow: [
  ["Before","A president spoke to a room, and editors carried it onward",null],
  ["Radio","It removed the (  ①  ) that had stood in between","hands"],
  ["Television","Now (  ②  ) carried part of the argument","appearance"],
  ["The gain","Each channel (  ③  ) the gap between saying and hearing","narrowed"],
  ["The cost","Direct reach also lets a leader (  ④  ) the questioners","bypass"]
 ],
 flowBogi: "hands · appearance · narrowed · bypass · debate · silence",
 para: [
  ["③ it arrived through other people's hands","The message passed through ______.","intermediaries"],
  ["⑥ more like explanation than oratory","His style became less ______.","formal"],
  ["⑨ The claim is often exaggerated","The story is usually ______.","overstated"],
  ["⑫ can also bypass everyone who would question","Direct reach can avoid ______.","scrutiny"],
  ["⑭ removes something that stood in the middle","Shortening distance costs a ______.","filter"]
 ],
 paraBogi: "intermediaries · formal · overstated · scrutiny · filter · audiences · casual · proven",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Life of Franklin Roosevelt","What Disappears When the Distance Shortens",
       "Television Ruined Politics","How to Give a Radio Speech",
       "Newspapers Were Always Fair"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["19세기 연설은 신문을 거쳐 전해졌다.","라디오는 중간의 손들을 없앴다.",
       "필자는 1960년 토론 이야기를 그대로 사실로 받아들인다.","언론은 느렸지만 캐묻는 질문을 했다.",
       "새 통로마다 말과 들림 사이 거리가 좁아졌다."], ans:3},
  {t:"write", q:"필자가 지적한 '거리가 좁아진 대가'를 우리말 한 문장으로 써 보세요.",
   ans:"중간에서 따져 묻던 존재가 함께 사라진다는 것이다."}
 ],
 fl: {
  model: { n:"⑫",
   toks: [["Yet","c"],["a leader","s"],["who can reach everyone directly","m"],
          ["can also bypass","v"],["everyone who would question him","m"]],
   ko:"그러나 모두에게 곧장 닿을 수 있는 지도자는 자기에게 따져 물을 모두를 건너뛸 수도 있다." },
  drill: [
   { n:"②", en:"Speeches were printed the next day, edited by whoever ran the paper.",
     ans:"S Speeches · △V were printed · M the next day · M edited by whoever ran the paper",
     ko:"연설은 이튿날 인쇄되었고, 신문을 운영하는 사람이 손질했다." },
   { n:"⑧", en:"After the first televised debate in 1960, radio listeners and viewers reported different winners.",
     ans:"M After the first televised debate in 1960 · S radio listeners and viewers · △V reported · O different winners",
     ko:"1960년 첫 텔레비전 토론 뒤, 라디오 청취자와 시청자가 서로 다른 승자를 말했다." },
   { n:"⑭", en:"Every technology that shortens the distance also removes something that stood in the middle.",
     ans:"S Every technology · M that shortens the distance · △V removes · O something that stood in the middle",
     ko:"거리를 줄이는 모든 기술은 그 가운데 서 있던 무언가도 함께 치운다." }
  ]
 },
 syn: [
  { n:"②", name:"복합관계대명사 whoever",
    q:"Speeches were printed the next day, edited by «whoever ran» the paper.",
    d:"<b>whoever</b>는 'anyone who'. 뒤에 동사가 바로 오며, 절 전체가 by 의 목적어다.",
    k:"신문을 운영하는 사람이 누구든 그 사람이 손질했다." },
  { n:"⑫", name:"주격 관계대명사절이 주어를 꾸밈",
    q:"«A leader who can reach everyone directly» can also bypass everyone who would question him.",
    d:"who 절이 주어를 꾸며 주어가 길어졌다. 본동사는 <b>can bypass</b> 하나다.",
    k:"모두에게 곧장 닿을 수 있는 지도자는 따져 물을 사람들을 건너뛸 수도 있다." }
 ],
 synd: [
  { u:"구문 1", en:"Whoever arrives first opens the hall.",
    k:"먼저 도착하는 사람이 누구든 그 사람이 강당을 연다." },
  { u:"구문 2", en:"A rule that everyone understands is easier to keep.",
    k:"모두가 이해하는 규칙이 지키기 더 쉽다." },
  { u:"구문 1 + 2", en:"Whoever writes the summary decides what readers who skim will learn.",
    k:"요약을 쓰는 사람이 누구든, 훑어 읽는 독자가 무엇을 알게 될지를 그 사람이 정한다." }
 ],
 wtype: ["무관","정답","반대","무관","반대"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["루스벨트의 생애는 글의 주제가 아니다"],["정답"],
       ["글은 이득도 함께 인정한다 — 정반대다"],
       ["연설하는 방법을 알려 주는 글이 아니다"],
       ["글은 신문이 늘 공정했다고 하지 않는다 — 정반대다"]],
 src: [["②③"],["④"],["⑨과 어긋남 — 흔히 과장된다고 적었다"],["⑬"],["⑩"]],
 kb: {
  title:"중간에 서 있던 것들",
  lead:"통로가 바뀌면 말도 바뀐다.",
  items: [
   ["'노변정담'",
    "루스벨트는 1933년부터 라디오로 국민에게 직접 설명하는 방송을 이어 갔다. 원고는 어려운 낱말을 걷어 내고 대화체로 다듬어졌고, 이 형식 자체가 이후 정치 화법의 기준이 되었다."],
   ["1960년 토론을 둘러싼 이야기",
    "라디오 청취자는 닉슨을, 시청자는 케네디를 승자로 봤다는 이야기는 널리 알려졌지만, 근거가 된 조사의 표본과 방법에 한계가 있다는 지적이 오래 있어 왔다. 인용할 때 조심할 대목이다."],
   ["기자회견이라는 장치",
    "정례 기자회견은 지도자가 준비되지 않은 질문에 답하게 만드는 제도다. 형식과 횟수는 정권마다 달라지지만, '뒤이어 캐묻기'가 가능한 자리라는 점이 핵심으로 꼽힌다."]
  ],
  ask:"내가 뉴스를 접하는 통로는 무엇인가? 그 사이에 누가 서 있는가, 아니면 아무도 없는가?"
 }
},
{
 no: "38", key: "arthur",
 accent: "#6B5498", tint: "#EFEBF7", deep: "#453370",
 en: "The Man Who Assembled a King",
 ko: "왕을 조립한 사람",
 goal: "하나의 전설이 어떻게 만들어지고 '역사'로 자리 잡는지 설명할 수 있다.",
 fig: "Figure 1  조각들이 한 사람의 손에서 하나가 되는 자리.",
 tip: "먼저 생각해 보자. 우리가 '옛날부터 전해 온다'고 믿는 이야기는 정말 옛날부터 그 모습이었을까?",
 sent: [
  "Before 1136 the name Arthur appears only in scattered fragments.",
  "A line in a Welsh poem, a battle list, a saint's tale mentioning him in passing.",
  "There is no court, no round table, and no sword in a stone.",
  "Then Geoffrey of Monmouth wrote a long book in Latin called The History of the Kings of Britain.",
  "He presented it as history and claimed an ancient source nobody has ever found.",
  "In it Arthur becomes a full king with a reign, campaigns, and a betrayal at the end.",
  "The book was copied across Europe faster than almost anything before it.",
  "Later writers then added what their own audiences wanted.",
  "French poets supplied the romance; a Cistercian cycle supplied the grail.",
  "Malory gathered the pieces again in English three centuries later.",
  "Each layer was written by someone answering the taste of a particular year.",
  "Calling the result a legend is accurate but slightly misleading.",
  "It suggests a slow drift, when much of it was composed on purpose.",
  "Traditions often have authors, and the authors are often forgotten.",
  "What we inherit as ancient is frequently the work of one busy writer."
 ],
 kor: [
  "1136년 이전에 '아서'라는 이름은 흩어진 조각들에만 나타난다.",
  "웨일스 시의 한 행, 전투 목록 하나, 지나가듯 그를 언급하는 성인전 하나.",
  "궁정도, 원탁도, 바위에 꽂힌 검도 없다.",
  "그러다 몬머스의 제프리가 『브리튼 왕들의 역사』라는 긴 책을 라틴어로 썼다.",
  "그는 그것을 역사로 내놓았고, 아무도 찾은 적 없는 고대의 원전을 근거로 들었다.",
  "그 안에서 아서는 치세와 원정과 마지막의 배신을 갖춘 온전한 왕이 된다.",
  "그 책은 그 이전 거의 어떤 책보다 빠르게 유럽 곳곳으로 필사되었다.",
  "그 뒤의 필자들은 저마다 자기 독자가 원하는 것을 덧붙였다.",
  "프랑스 시인들이 연애담을 댔고, 시토회 연작이 성배를 댔다.",
  "맬러리는 세 세기 뒤 영어로 그 조각들을 다시 그러모았다.",
  "각 층은 특정한 해의 취향에 답하던 누군가가 쓴 것이다.",
  "그 결과를 '전설'이라 부르는 것은 정확하지만 조금 오해를 부른다.",
  "그 말은 천천히 흘러온 것 같은 인상을 주는데, 상당 부분은 일부러 지어졌다.",
  "전통에는 흔히 저자가 있고, 그 저자는 흔히 잊힌다.",
  "우리가 '오래된 것'으로 물려받는 것은 자주 부지런한 한 사람의 작품이다."
 ],
 bank: [["scattered","①","흩어진"],["fragment","①","조각"],["reign","⑥","치세, 통치기"],
        ["betrayal","⑥","배신"],["misleading","⑫","오해를 부르는"],["inherit","⑮","물려받다"]],
 defs: [["scattered","spread out over a wide area"],
        ["fragment","a small broken part of something"],
        ["reign","the period during which a ruler rules"],
        ["betrayal","the act of breaking someone's trust"],
        ["misleading","giving a wrong impression"],
        ["inherit","to receive from those who came before"]],
 defOrder: [2,0,5,1,4,3],
 flow: [
  ["Before 1136","Arthur exists only in scattered fragments",null],
  ["The book","Geoffrey presented an invented life as (  ①  )","history"],
  ["The spread","It was (  ②  ) across Europe with unusual speed","copied"],
  ["The layers","Later writers added the romance and the (  ③  )","grail"],
  ["The point","Traditions often have (  ④  ), and we forget them","authors"]
 ],
 flowBogi: "history · copied · grail · authors · legend · Latin",
 para: [
  ["⑤ claimed an ancient source nobody has found","His evidence cannot be ______.","verified"],
  ["⑦ copied across Europe faster than almost anything","It spread with unusual ______.","speed"],
  ["⑪ answering the taste of a particular year","Each layer reflects its own ______.","era"],
  ["⑬ much of it was composed on purpose","The growth was partly ______.","deliberate"],
  ["⑮ the work of one busy writer","What seems ancient may be ______.","authored"]
 ],
 paraBogi: "verified · speed · era · deliberate · authored · doubted · delay · accidental",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Rules of the Round Table","Traditions Often Have Authors",
       "Geoffrey Was a Careful Historian","How Latin Spread Through Europe",
       "Why Legends Should Not Be Read"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["1136년 이전 아서는 흩어진 조각에만 나온다.","제프리는 자기 책을 역사로 내놓았다.",
       "필자는 제프리가 신뢰할 만한 원전을 제시했다고 본다.","맬러리는 세 세기 뒤 영어로 다시 모았다.",
       "각 층은 그 시대의 취향에 답한 것이다."], ans:3},
  {t:"write", q:"필자가 '전설'이라는 말이 오해를 부른다고 한 이유를 우리말 한 문장으로 써 보세요.",
   ans:"천천히 흘러온 것 같은 인상을 주지만 상당 부분은 특정한 사람이 일부러 지은 것이기 때문이다."}
 ],
 fl: {
  model: { n:"⑬",
   toks: [["It","s"],["suggests","v"],["a slow drift","m"],["when","c"],
          ["much of it","s2"],["was composed","v2"],["on purpose","m"]],
   ko:"그 말은 천천히 흘러온 것 같은 인상을 주는데, 상당 부분은 일부러 지어졌다." },
  drill: [
   { n:"⑤", en:"He presented it as history and claimed an ancient source nobody has ever found.",
     ans:"S He · △V presented · O it · M as history · [and] △V claimed · O an ancient source nobody has ever found",
     ko:"그는 그것을 역사로 내놓았고, 아무도 찾은 적 없는 고대의 원전을 근거로 들었다." },
   { n:"⑪", en:"Each layer was written by someone answering the taste of a particular year.",
     ans:"S Each layer · △V was written · M by someone answering the taste of a particular year",
     ko:"각 층은 특정한 해의 취향에 답하던 누군가가 쓴 것이다." },
   { n:"⑮", en:"What we inherit as ancient is frequently the work of one busy writer.",
     ans:"S What we inherit as ancient · △V is · M frequently · C the work of one busy writer",
     ko:"우리가 '오래된 것'으로 물려받는 것은 자주 부지런한 한 사람의 작품이다." }
  ]
 },
 syn: [
  { n:"⑪", name:"현재분사구의 명사 수식",
    q:"Each layer was written by «someone answering the taste» of a particular year.",
    d:"<b>명사 + 현재분사구</b>는 '~하고 있는 …'. who was answering 에서 who was 가 빠진 형태다.",
    k:"특정한 해의 취향에 답하고 있던 누군가가 썼다." },
  { n:"⑬", name:"대조의 when",
    q:"It suggests a slow drift, «when much of it was composed» on purpose.",
    d:"여기서 <b>when</b>은 시간이 아니라 '~인데도'라는 대조를 나타낸다. 앞뒤가 어긋날 때 쓴다.",
    k:"그런 인상을 주는데, 실은 상당 부분이 일부러 지어졌다." }
 ],
 synd: [
  { u:"구문 1", en:"The letter was signed by a clerk working late that night.",
    k:"그 편지는 그날 밤 늦게까지 일하던 서기가 서명한 것이었다." },
  { u:"구문 2", en:"He called it a discovery, when the answer had been printed for years.",
    k:"그는 그것을 발견이라 불렀는데, 그 답은 여러 해째 인쇄되어 있었다." },
  { u:"구문 1 + 2", en:"They praised a tradition reaching back centuries, when one man had invented it.",
    k:"그들은 수백 년을 거슬러 올라가는 전통이라며 기렸는데, 한 사람이 지어낸 것이었다." }
 ],
 wtype: ["무관","정답","반대","무관","반대"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["원탁의 규칙은 글에 나오지 않는다"],["정답"],
       ["글은 아무도 찾지 못한 원전이라고 적는다 — 정반대다"],
       ["라틴어의 전파는 글의 주제가 아니다"],
       ["글은 전설을 읽지 말라고 하지 않는다 — 정반대다"]],
 src: [["①"],["⑤"],["⑤과 어긋남 — 아무도 찾은 적 없는 원전이라고 했다"],["⑩"],["⑪"]],
 kb: {
  title:"오래된 것처럼 보이는 것들",
  lead:"전통에도 만들어진 날짜가 있다.",
  items: [
   ["1136년의 베스트셀러",
    "몬머스의 제프리가 쓴 『브리튼 왕들의 역사』는 필사본이 200부 넘게 전해질 만큼 널리 퍼졌다. 당대에도 뉴버그의 윌리엄 같은 이들이 사료로서의 신빙성을 의심했다."],
   ["성배와 원탁이 들어온 시점",
    "원탁은 12세기 후반 웨이스의 작품에, 성배 이야기는 크레티앵 드 트루아 이후의 프랑스 문헌에 등장한다. 처음부터 있던 요소가 아니라 나중에 더해진 층이다."],
   ["'만들어진 전통'",
    "1983년 홉스봄과 레인저는 오래되어 보이는 국가 의례 상당수가 19세기 이후에 고안되었음을 여러 사례로 보였다. 전통의 나이를 확인하는 습관을 남긴 연구다."]
  ],
  ask:"우리 학교나 동네에 '옛날부터'라고 알려진 관행이 있는가? 언제 시작됐는지 확인할 수 있을까?"
 }
},
{
 no: "39", key: "harvest",
 accent: "#47784A", tint: "#E8F1E7", deep: "#2C4F2E",
 en: "The Bargain Nobody Signed",
 ko: "아무도 서명하지 않은 거래",
 goal: "농경으로의 전환이 가져온 이득과 대가를 함께 설명할 수 있다.",
 fig: "Figure 1  늘어난 사람 수와 낮아진 키.",
 tip: "먼저 생각해 보자. 먹을 것이 늘어나면 사람들은 반드시 더 건강해질까?",
 sent: [
  "For most of human history people gathered food and followed it.",
  "That life is often described as short and desperate, and it was neither simple nor safe.",
  "But skeletons from the last hunting societies tell a more complicated story.",
  "They are taller on average than the farming skeletons that follow them.",
  "They show fewer signs of the diseases that come from crowding.",
  "Their teeth are in better condition, because grain is hard on teeth.",
  "Farming did not arrive because it made individual lives more comfortable.",
  "It arrived because it produced more calories from the same piece of ground.",
  "More calories meant more children, and more children meant more farmers.",
  "Once a region filled with farmers, going back was no longer possible.",
  "The land could not feed that many people any other way.",
  "Farming also created something new: a harvest that could be stored.",
  "Stored grain can be counted, taxed, taken, and defended.",
  "Kings, armies, and written records all follow the granary rather than the field.",
  "The bargain bought numbers and permanence, and it was paid for in health and freedom."
 ],
 kor: [
  "인류 역사의 대부분 동안 사람들은 먹을 것을 모으며 그것을 따라다녔다.",
  "그 삶은 흔히 짧고 절박했다고 서술되며, 실제로 단순하지도 안전하지도 않았다.",
  "그러나 마지막 수렵 사회들의 유골은 좀 더 복잡한 이야기를 들려준다.",
  "그들은 뒤이은 농경 사회의 유골보다 평균 키가 크다.",
  "밀집에서 오는 질병의 흔적도 더 적다.",
  "치아 상태도 더 좋은데, 곡물이 이에 가혹하기 때문이다.",
  "농경은 개인의 삶을 더 편안하게 만들어서 온 것이 아니다.",
  "같은 땅에서 더 많은 열량을 뽑아냈기 때문에 온 것이다.",
  "열량이 늘자 아이가 늘었고, 아이가 늘자 농부가 늘었다.",
  "한 지역이 농부로 가득 차고 나면 되돌아가는 일은 더 이상 가능하지 않았다.",
  "그 땅은 다른 어떤 방식으로도 그만한 사람을 먹일 수 없었다.",
  "농경은 또 하나 새로운 것을 만들었다. 저장할 수 있는 수확이었다.",
  "저장된 곡물은 셀 수 있고, 세금 매길 수 있고, 빼앗을 수 있고, 지킬 수 있다.",
  "왕과 군대와 문자 기록은 모두 밭이 아니라 곳간을 따라온다.",
  "그 거래는 수와 지속성을 사들였고, 값은 건강과 자유로 치러졌다."
 ],
 bank: [["gather","①","(먹을 것을) 모으다"],["skeleton","③","유골"],["crowding","⑤","밀집"],
        ["calorie","⑧","열량"],["harvest","⑫","수확"],["granary","⑭","곡물 창고"]],
 defs: [["gather","to collect food that grows wild"],
        ["skeleton","the set of bones of a body"],
        ["crowding","the state of too many living close together"],
        ["calorie","a unit of energy in food"],
        ["harvest","the crop gathered in one season"],
        ["granary","a building for storing grain"]],
 defOrder: [1,4,0,5,3,2],
 flow: [
  ["The common picture","Hunting life was short and desperate",null],
  ["What bones show","Earlier skeletons are (  ①  ) and have better teeth","taller"],
  ["Why farming won","It produced more (  ②  ) from the same ground","calories"],
  ["Why it locked in","A filled region could not (  ③  ) that many any other way","feed"],
  ["What it created","A stored harvest that can be counted and (  ④  )","taxed"]
 ],
 flowBogi: "taller · calories · feed · taxed · shorter · gathered",
 para: [
  ["③ tell a more complicated story","The evidence is not ______.","simple"],
  ["⑦ did not arrive because it made lives comfortable","Comfort was not the ______.","cause"],
  ["⑩ going back was no longer possible","The change became ______.","irreversible"],
  ["⑬ counted, taxed, taken, and defended","Stored grain invites ______.","control"],
  ["⑮ paid for in health and freedom","The gain carried a real ______.","cost"]
 ],
 paraBogi: "simple · cause · irreversible · control · cost · complex · result · reward",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Grow Grain Successfully","What Farming Bought and What It Cost",
       "Hunting Life Was Better in Every Way","The Origin of Written Language",
       "Why Teeth Decay in Modern Diets"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["수렵 사회 유골이 평균 키가 더 크다.","농경은 같은 땅에서 더 많은 열량을 냈다.",
       "필자는 수렵 생활이 모든 면에서 더 나았다고 본다.","저장된 곡물은 세금 매길 수 있다.",
       "인구가 늘고 나면 되돌아갈 수 없었다."], ans:3},
  {t:"write", q:"필자가 말하는 '거래'의 내용을 우리말 한 문장으로 써 보세요.",
   ans:"더 많은 인구와 지속성을 얻는 대신 건강과 자유를 값으로 치른 것이다."}
 ],
 fl: {
  model: { n:"⑩",
   toks: [["Once","c"],["a region","s2"],["filled","v2"],["with farmers","m"],[",",null],
          ["going back","s"],["was","v"],["no longer possible","c"]],
   ko:"한 지역이 농부로 가득 차고 나면 되돌아가는 일은 더 이상 가능하지 않았다." },
  drill: [
   { n:"④", en:"They are taller on average than the farming skeletons that follow them.",
     ans:"S They · △V are · C taller · M on average, than the farming skeletons that follow them",
     ko:"그들은 뒤이은 농경 사회의 유골보다 평균 키가 크다." },
   { n:"⑨", en:"More calories meant more children, and more children meant more farmers.",
     ans:"S More calories · △V meant · O more children · [and] S more children · △V meant · O more farmers",
     ko:"열량이 늘자 아이가 늘었고, 아이가 늘자 농부가 늘었다." },
   { n:"⑭", en:"Kings, armies, and written records all follow the granary rather than the field.",
     ans:"S Kings, armies, and written records · M all · △V follow · O the granary · M rather than the field",
     ko:"왕과 군대와 문자 기록은 모두 밭이 아니라 곳간을 따라온다." }
  ]
 },
 syn: [
  { n:"⑩", name:"Once + 절 (접속사)",
    q:"«Once a region filled» with farmers, going back was no longer possible.",
    d:"<b>Once</b>는 '일단 ~하고 나면'이라는 접속사다. 뒤 절에는 결과가 온다.",
    k:"일단 한 지역이 농부로 가득 차고 나면 되돌아갈 수 없었다." },
  { n:"②", name:"neither A nor B",
    q:"That life is often described as short and desperate, and it was «neither simple nor safe».",
    d:"<b>neither A nor B</b>는 'A도 B도 아니다'. 두 형용사를 나란히 부정한다.",
    k:"그 삶은 단순하지도 안전하지도 않았다." }
 ],
 synd: [
  { u:"구문 1", en:"Once the grain was stored, the village needed a guard.",
    k:"일단 곡물이 저장되고 나자 그 마을에는 지킬 사람이 필요해졌다." },
  { u:"구문 2", en:"The winter was neither long nor especially cold that year.",
    k:"그해 겨울은 길지도 특별히 춥지도 않았다." },
  { u:"구문 1 + 2", en:"Once the count began, the harvest was neither theirs nor free.",
    k:"일단 셈이 시작되자 그 수확은 그들의 것도 아니고 공짜도 아니었다." }
 ],
 wtype: ["무관","정답","반대","지엽","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["곡물 재배법은 글의 관심사가 아니다"],["정답"],
       ["글은 수렵 생활도 안전하지 않았다고 적는다 — 정반대다"],
       ["문자는 결과로 언급된 여러 항목 중 하나일 뿐이다"],
       ["현대 식단의 충치는 글에 나오지 않는다"]],
 src: [["④"],["⑧"],["②과 어긋남 — 단순하지도 안전하지도 않았다고 했다"],["⑬"],["⑩⑪"]],
 kb: {
  title:"곳간이 만든 것들",
  lead:"저장할 수 있게 되자 셀 수 있게 되었다.",
  items: [
   ["유골이 말해 주는 것",
    "여러 지역의 고고학 자료에서 농경 도입 이후 평균 신장이 줄고 충치와 영양 결핍 흔적이 늘어나는 경향이 보고되었다. 다만 지역과 시기에 따라 편차가 커서 일반화에는 주의가 필요하다."],
   ["문자의 첫 용도",
    "메소포타미아의 초기 점토판 다수는 시나 법이 아니라 곡물·가축의 수량 기록이다. 문자가 회계에서 시작되었다는 근거로 자주 인용된다."],
   ["왜 되돌아가지 못했나",
    "농경은 단위 면적당 열량을 크게 늘리는 대신 인구를 그만큼 늘린다. 인구가 늘어난 뒤에는 수렵채집으로 되돌아가도 같은 인구를 먹일 수 없어, 사실상 한 방향의 문이 된다."]
  ],
  ask:"편리해졌지만 되돌아갈 수 없게 된 변화가 내 생활에도 있는가?"
 }
},
{
 no: "40", key: "letters",
 accent: "#B04A62", tint: "#FAE8EC", deep: "#7E2A3F",
 en: "The Committee That Wrote Letters",
 ko: "편지를 쓴 위원회",
 goal: "극적인 사건보다 느린 조직 만들기가 어떻게 더 큰 변화를 만드는지 설명할 수 있다.",
 fig: "Figure 1  한 도시의 항구와, 열세 곳을 잇는 선.",
 tip: "먼저 생각해 보자. 큰 변화를 만들려면 큰 사건이 필요할까?",
 sent: [
  "Most accounts of the American Revolution begin with a dramatic scene.",
  "Tea in a harbour, shots on a green, a document signed in summer.",
  "The scenes are real, but they explain less than they appear to.",
  "A crowd can be gathered in a night and dispersed just as fast.",
  "What turned scattered anger into a movement was slower and much duller.",
  "In 1772 Samuel Adams helped set up a committee of correspondence in Boston.",
  "Its work was to write letters to other towns and to answer the ones that came back.",
  "Within a year, towns across Massachusetts had committees of their own.",
  "Within two, the colonies were exchanging accounts of the same events.",
  "A grievance in one port became known, in the same words, in another.",
  "This is unglamorous work, and it is why the response could be coordinated at all.",
  "Adams understood that outrage without a channel simply fades.",
  "The letters built the channel before the outrage arrived.",
  "Historians still argue about how decisive the committees were.",
  "They do not argue about whether patient organisation matters."
 ],
 kor: [
  "미국 혁명에 관한 대부분의 설명은 극적인 장면에서 시작한다.",
  "항구에 쏟아진 차, 잔디밭 위의 총성, 여름에 서명된 한 장의 문서.",
  "그 장면들은 실재하지만, 보이는 것만큼 많은 것을 설명하지는 않는다.",
  "군중은 하룻밤에 모을 수 있고, 그만큼 빨리 흩어질 수도 있다.",
  "흩어진 분노를 하나의 운동으로 바꾼 것은 더 느리고 훨씬 심심한 일이었다.",
  "1772년 새뮤얼 애덤스는 보스턴에 통신위원회를 세우는 일을 도왔다.",
  "그 위원회의 일은 다른 도시에 편지를 쓰고, 돌아온 편지에 답하는 것이었다.",
  "한 해 안에 매사추세츠 곳곳의 도시가 저마다 위원회를 갖게 되었다.",
  "두 해 안에 식민지들은 같은 사건에 대한 기록을 주고받고 있었다.",
  "한 항구에서 생긴 불만이 다른 항구에서 같은 표현으로 알려졌다.",
  "이것은 화려하지 않은 일이며, 그렇기에 대응이 조율될 수 있었던 것이다.",
  "애덤스는 통로 없는 분노는 그저 사그라진다는 것을 알고 있었다.",
  "그 편지들은 분노가 도착하기 전에 통로를 만들어 두었다.",
  "역사가들은 그 위원회가 얼마나 결정적이었는지를 두고 여전히 다툰다.",
  "끈질긴 조직화가 중요한지를 두고는 다투지 않는다."
 ],
 bank: [["dramatic","①","극적인"],["disperse","④","흩어지다"],["correspondence","⑥","통신, 편지 왕래"],
        ["grievance","⑩","불만"],["coordinate","⑪","조율하다"],["decisive","⑭","결정적인"]],
 defs: [["dramatic","striking and full of action"],
        ["disperse","to scatter in different directions"],
        ["correspondence","the exchange of letters"],
        ["grievance","a complaint about unfair treatment"],
        ["coordinate","to make separate parts work together"],
        ["decisive","settling the outcome of something"]],
 defOrder: [3,0,5,1,4,2],
 flow: [
  ["The usual story","Revolution is told through dramatic scenes",null],
  ["Why that fails","A crowd gathers in a night and (  ①  ) as fast","disperses"],
  ["What Adams built","A committee of (  ②  ) writing to other towns","correspondence"],
  ["The result","The same grievance became known in the same (  ③  )","words"],
  ["The principle","Outrage without a (  ④  ) simply fades","channel"]
 ],
 flowBogi: "disperses · correspondence · words · channel · harbour · document",
 para: [
  ["③ they explain less than they appear to","The scenes are less ______ than they look.","explanatory"],
  ["⑤ slower and much duller","The real cause was ______.","unexciting"],
  ["⑨ exchanging accounts of the same events","Colonies shared a common ______.","record"],
  ["⑫ outrage without a channel simply fades","Anger needs a ______ to last.","structure"],
  ["⑮ do not argue about whether it matters","On that point they ______.","agree"]
 ],
 paraBogi: "explanatory · unexciting · record · structure · agree · decisive · thrilling · differ",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Night the Tea Was Thrown","The Channel Built Before the Anger",
       "Dramatic Events Explain Everything","A Guide to Writing Formal Letters",
       "Why Boston Was the Largest Port"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["위원회의 일은 편지를 쓰고 답하는 것이었다.","한 해 안에 여러 도시가 위원회를 세웠다.",
       "역사가들은 끈질긴 조직화의 중요성 자체를 두고 갈라진다.","군중은 빨리 모이고 빨리 흩어진다.",
       "필자는 극적인 장면이 실재한다고 인정한다."], ans:3},
  {t:"write", q:"애덤스가 이해하고 있었던 것을 우리말 한 문장으로 써 보세요.",
   ans:"통로가 없으면 분노는 그저 사그라지므로, 분노가 오기 전에 통로를 먼저 만들어 두어야 한다는 것이다."}
 ],
 fl: {
  model: { n:"⑤",
   toks: [["What turned scattered anger into a movement","s"],["was","v"],
          ["slower and much duller","c"]],
   ko:"흩어진 분노를 하나의 운동으로 바꾼 것은 더 느리고 훨씬 심심한 일이었다." },
  drill: [
   { n:"⑦", en:"Its work was to write letters to other towns and to answer the ones that came back.",
     ans:"S Its work · △V was · C to write letters to other towns and to answer the ones that came back",
     ko:"그 위원회의 일은 다른 도시에 편지를 쓰고, 돌아온 편지에 답하는 것이었다." },
   { n:"⑪", en:"This is unglamorous work, and it is why the response could be coordinated at all.",
     ans:"S This · △V is · C unglamorous work · [and] S it · △V is · C why the response could be coordinated at all",
     ko:"이것은 화려하지 않은 일이며, 그렇기에 대응이 조율될 수 있었던 것이다." },
   { n:"⑬", en:"The letters built the channel before the outrage arrived.",
     ans:"S The letters · △V built · O the channel · [before] S′ the outrage · △V′ arrived",
     ko:"그 편지들은 분노가 도착하기 전에 통로를 만들어 두었다." }
  ]
 },
 syn: [
  { n:"⑤", name:"What절 주어",
    q:"«What turned scattered anger into a movement was» slower and much duller.",
    d:"<b>What + 절</b>이 주어이며 단수로 받는다. '~한 것은'으로 옮긴다.",
    k:"흩어진 분노를 운동으로 바꾼 것은 더 느린 일이었다." },
  { n:"⑦", name:"to부정사 보어 (병렬)",
    q:"Its work was «to write letters ... and to answer» the ones that came back.",
    d:"be동사 뒤 <b>to부정사</b>가 보어다. and 로 묶인 두 to부정사가 대등하게 이어진다.",
    k:"그 일은 편지를 쓰고 답하는 것이었다." }
 ],
 synd: [
  { u:"구문 1", en:"What kept the group together was a weekly meeting.",
    k:"그 모임을 지탱한 것은 주간 회의였다." },
  { u:"구문 2", en:"His plan was to visit each town and to record what he heard.",
    k:"그의 계획은 각 도시를 방문하고 들은 것을 기록하는 것이었다." },
  { u:"구문 1 + 2", en:"What mattered most was to keep writing and to keep answering.",
    k:"가장 중요했던 것은 계속 쓰고 계속 답하는 일이었다." }
 ],
 wtype: ["지엽","정답","반대","무관","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["차 사건은 도입의 한 장면일 뿐이다"],["정답"],
       ["글은 극적인 장면이 설명하는 바가 적다고 말한다 — 정반대다"],
       ["편지 쓰는 요령은 글의 관심사가 아니다"],["항구 규모는 글에 나오지 않는다"]],
 src: [["⑦"],["⑧"],["⑮과 어긋남 — 그 점은 다투지 않는다고 했다"],["④"],["③"]],
 kb: {
  title:"느린 일이 남긴 것",
  lead:"사건보다 구조가 오래간다.",
  items: [
   ["1772년 보스턴 통신위원회",
    "새뮤얼 애덤스 등이 주도해 만든 이 위원회는 각 도시에 서한을 보내 권리 침해 사례를 정리·공유했다. 이듬해까지 매사추세츠 100곳 넘는 타운에 유사 조직이 생겼다."],
   ["같은 말로 알려진다는 것",
    "각지에서 벌어진 일이 같은 표현과 같은 순서로 기록되면, 대응도 같은 언어로 조율된다. 통신위원회의 실질적 성과로 흔히 꼽히는 부분이다."],
   ["역사학의 논쟁",
    "위원회의 영향력을 크게 보는 해석과, 이미 형성된 여론을 반영했을 뿐이라는 해석이 함께 있다. 다만 조직화된 소통망 자체의 중요성은 양쪽 모두 인정한다."]
  ],
  ask:"우리 반에서 무언가를 바꾸려면, 사건과 조직 가운데 무엇을 먼저 만들어야 할까?"
 }
}
]};
