/* Unit 10 · Field 10 — Economy & Business 경제·경영 */
module.exports = {
 no: 10,
 field: "Economy & Business",
 ko: "경제·경영",
 tagline: "값이 붙는 자리 — 나눔·이야기·불안·욕구",
 next: { en: "Environment, Resources & Ecology", ko: "함께 쓰는 것을 어떻게 지킬지 읽습니다", words: "175–205 words" },
 lessons: [
{
 no: "46", key: "gini",
 accent: "#39628C", tint: "#E6EDF4", deep: "#204261",
 en: "One Number, Many Countries",
 ko: "숫자 하나, 여러 나라",
 goal: "지니계수가 무엇을 요약하고 무엇을 감추는지 설명할 수 있다.",
 fig: "Figure 1  같은 계수, 다른 사회.",
 tip: "먼저 생각해 보자. '평균 소득'만 알면 그 나라를 안다고 할 수 있을까?",
 sent: [
  "Comparing how equally two countries share their income sounds simple.",
  "It stops sounding simple the moment you try to write it as one number.",
  "The Gini coefficient does exactly that, on a scale from zero to one.",
  "Zero would mean everyone receives the same amount.",
  "One would mean a single household receives everything.",
  "Real countries sit between about 0.25 and 0.6, and the figure travels well.",
  "Journalists like it because two nations can be placed side by side in a sentence.",
  "The trouble is that very different shapes can produce the same score.",
  "A country where the top earns hugely can match one where the bottom earns almost nothing.",
  "The number cannot tell you which of those two it is describing.",
  "It also says nothing about who makes the rules.",
  "Studies of legislative influence find that policy tracks the preferences of higher earners more closely.",
  "That is a claim about power, and no distribution figure captures it.",
  "The coefficient remains useful, and abandoning it would lose real information.",
  "It is a headline, and headlines are read before articles, not instead of them."
 ],
 kor: [
  "두 나라가 소득을 얼마나 고르게 나누는지 견주는 일은 간단해 보인다.",
  "그것을 하나의 숫자로 적으려는 순간부터 간단하지 않게 된다.",
  "지니계수는 바로 그 일을 0에서 1까지의 척도로 해낸다.",
  "0은 모두가 같은 양을 받는다는 뜻이 될 것이다.",
  "1은 한 가구가 전부를 받는다는 뜻이 될 것이다.",
  "실제 나라들은 대략 0.25에서 0.6 사이에 있고, 이 수치는 여기저기 잘 옮겨 다닌다.",
  "기자들이 이것을 좋아하는 이유는 두 나라를 한 문장 안에 나란히 놓을 수 있기 때문이다.",
  "문제는 아주 다른 모양이 같은 점수를 낼 수 있다는 것이다.",
  "위쪽이 어마어마하게 버는 나라와 아래쪽이 거의 못 버는 나라가 같은 값이 될 수 있다.",
  "그 숫자는 자기가 둘 중 어느 쪽을 서술하고 있는지 말해 주지 못한다.",
  "그것은 또 누가 규칙을 만드는지에 대해서는 아무 말도 하지 않는다.",
  "입법 영향력을 다룬 연구들은 정책이 고소득층의 선호를 더 가깝게 따라간다는 것을 밝혀 왔다.",
  "그것은 권력에 관한 주장이고, 어떤 분배 수치도 그것을 담아내지 못한다.",
  "이 계수는 여전히 쓸모가 있으며, 버린다면 실제 정보를 잃게 된다.",
  "그것은 표제이고, 표제는 기사보다 먼저 읽히는 것이지 기사 대신 읽히는 것이 아니다."
 ],
 bank: [["income","①","소득"],["coefficient","③","계수"],["scale","③","척도"],
        ["household","⑤","가구"],["legislative","⑫","입법의"],["distribution","⑬","분배"]],
 defs: [["income","money received over a period of time"],
        ["coefficient","a number that summarises a measurement"],
        ["scale","a range used for measuring"],
        ["household","all the people living in one home"],
        ["legislative","having to do with making laws"],
        ["distribution","the way something is shared out"]],
 defOrder: [2,0,5,1,4,3],
 flow: [
  ["What it does","One number summarises how income is shared",null],
  ["Why it spreads","Two nations fit side by side in a single (  ①  )","sentence"],
  ["Limit 1","Very different (  ②  ) can produce the same score","shapes"],
  ["Limit 2","It says nothing about who makes the (  ③  )","rules"],
  ["Fair verdict","It is a (  ④  ), read before the article, not instead of it","headline"]
 ],
 flowBogi: "sentence · shapes · rules · headline · scale · power",
 para: [
  ["② the moment you try to write it as one number","Summarising removes ______.","detail"],
  ["⑧ different shapes can produce the same score","One value fits many ______.","patterns"],
  ["⑩ cannot tell you which of those two","The figure is ______ about the cause.","silent"],
  ["⑫ policy tracks the preferences of higher earners","Influence is unevenly ______.","distributed"],
  ["⑭ abandoning it would lose real information","Dropping it costs genuine ______.","knowledge"]
 ],
 paraBogi: "detail · patterns · silent · distributed · knowledge · noise · single · loud",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Calculate a Coefficient","A Headline, Not the Whole Article",
       "The Gini Coefficient Is Useless","Which Country Is the Fairest",
       "Why Journalists Cannot Do Maths"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["지니계수는 0에서 1 사이의 척도다.","다른 모양이 같은 점수를 낼 수 있다.",
       "필자는 이 계수를 버려야 한다고 본다.","이 수치는 누가 규칙을 만드는지 말하지 않는다.",
       "실제 나라들은 대략 0.25~0.6 사이에 있다."], ans:3},
  {t:"write", q:"필자가 이 계수를 '표제'에 비유한 뜻을 우리말 한 문장으로 써 보세요.",
   ans:"먼저 읽고 방향을 잡는 데 쓸 뿐, 기사 자체를 대신할 수는 없다는 뜻이다."}
 ],
 fl: {
  model: { n:"⑧",
   toks: [["The trouble","s"],["is","v"],["that","c"],["very different shapes","s2"],
          ["can produce","v2"],["the same score","m"]],
   ko:"문제는 아주 다른 모양이 같은 점수를 낼 수 있다는 것이다." },
  drill: [
   { n:"②", en:"It stops sounding simple the moment you try to write it as one number.",
     ans:"S It · △V stops · O sounding simple · [the moment] S′ you · △V′ try · M to write it as one number",
     ko:"그것을 하나의 숫자로 적으려는 순간부터 간단하지 않게 된다." },
   { n:"⑫", en:"Studies of legislative influence find that policy tracks the preferences of higher earners more closely.",
     ans:"S Studies of legislative influence · △V find · [that] S′ policy · △V′ tracks · O the preferences of higher earners · M more closely",
     ko:"입법 영향력 연구들은 정책이 고소득층의 선호를 더 가깝게 따라간다는 것을 밝혀 왔다." },
   { n:"⑮", en:"It is a headline, and headlines are read before articles, not instead of them.",
     ans:"S It · △V is · C a headline · [and] S headlines · △V are read · M before articles, not instead of them",
     ko:"그것은 표제이고, 표제는 기사보다 먼저 읽히는 것이지 기사 대신 읽히는 것이 아니다." }
  ]
 },
 syn: [
  { n:"②", name:"stop + 동명사 / the moment 접속사",
    q:"It «stops sounding» simple «the moment you try» to write it as one number.",
    d:"<b>stop + ~ing</b>는 '~하기를 멈추다'. <b>the moment</b>는 '~하는 순간'이라는 접속사다.",
    k:"하나의 숫자로 적으려는 순간 간단하게 들리기를 멈춘다." },
  { n:"⑨", name:"where 관계부사 + 비교",
    q:"A country «where the top earns hugely» can match one where the bottom earns almost nothing.",
    d:"<b>where</b>가 country 를 꾸미고, one 은 a country 를 대신하는 대명사다.",
    k:"위쪽이 크게 버는 나라가 아래쪽이 거의 못 버는 나라와 같아질 수 있다." }
 ],
 synd: [
  { u:"구문 1", en:"He stopped arguing the moment the data appeared.",
    k:"자료가 나온 순간 그는 논쟁하기를 멈췄다." },
  { u:"구문 2", en:"A city where rents are high loses the workers it needs.",
    k:"임대료가 높은 도시는 필요한 노동자를 잃는다." },
  { u:"구문 1 + 2", en:"A town where jobs vanish stops growing the moment the young leave.",
    k:"일자리가 사라지는 마을은 젊은이들이 떠나는 순간 성장하기를 멈춘다." }
 ],
 wtype: ["무관","정답","반대","무관","무관"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["계산 방법은 글의 관심사가 아니다"],["정답"],
       ["글은 버리면 정보를 잃는다고 말한다 — 정반대다"],
       ["나라 순위를 매기는 글이 아니다"],["기자를 깎아내리는 내용은 글에 없다"]],
 src: [["③"],["⑧"],["⑭과 어긋남 — 여전히 쓸모가 있다고 했다"],["⑪"],["⑥"]],
 kb: {
  title:"요약이 놓치는 것",
  lead:"한 줄로 줄이면 무언가는 빠진다.",
  items: [
   ["로렌츠 곡선과 지니",
    "1905년 로렌츠가 그린 누적 분포 곡선의 면적 비율이 지니계수다. 곡선의 모양이 달라도 면적이 같으면 계수는 같아진다."],
   ["같은 값, 다른 사회",
    "상위가 크게 버는 경우와 하위가 거의 못 버는 경우가 같은 계수로 나올 수 있다. 그래서 상위 10% 점유율 같은 지표를 함께 보는 것이 관례가 되었다."],
   ["정책과 선호의 거리",
    "길런스와 페이지의 2014년 연구를 비롯한 여러 분석에서, 미국 정책이 중위 소득층보다 고소득층 선호와 더 높은 상관을 보인다고 보고되었다. 분배 지표만으로는 잡히지 않는 차원이다."]
  ],
  ask:"우리 반을 숫자 하나로 요약한다면 무엇이 좋을까? 그 숫자가 놓치는 것은 무엇일까?"
 }
},
{
 no: "47", key: "conflict",
 accent: "#A85440", tint: "#F8EBE7", deep: "#763322",
 en: "The Trouble Inside",
 ko: "안쪽의 갈등",
 goal: "이야기의 내적 갈등이 왜 광고에도 쓰이는지, 그 한계가 무엇인지 설명할 수 있다.",
 fig: "Figure 1  바깥의 적과 안쪽의 갈등.",
 tip: "먼저 생각해 보자. 기억에 남는 이야기의 주인공은 대개 무엇과 싸우는가?",
 sent: [
  "A story where the hero simply defeats a monster is easy to follow and easy to forget.",
  "The ones that stay involve a character who wants two things that cannot both be had.",
  "Safety and honesty. Loyalty and truth. Staying and leaving.",
  "The outer events then become a way of forcing that choice into the open.",
  "Writers have known this for a very long time.",
  "Marketing discovered it more recently and uses it constantly.",
  "The strongest advertisements rarely claim that a product is good.",
  "They stage a small internal conflict and place the product at the resolution.",
  "A parent who wants to work and to be present. A student who wants rest and results.",
  "Nothing is asserted, so nothing has to be proved.",
  "This is more effective than a list of features, and also harder to argue with.",
  "You cannot fact-check a feeling of recognition.",
  "That is exactly why the technique deserves attention rather than alarm.",
  "The same device that makes a novel worth rereading can sell a thing you do not need.",
  "Learning to notice the shape is not the same as refusing to enjoy it."
 ],
 kor: [
  "주인공이 그저 괴물을 물리치는 이야기는 따라가기 쉽고 잊기도 쉽다.",
  "남는 이야기는 둘 다 가질 수 없는 두 가지를 원하는 인물을 담고 있다.",
  "안전과 정직. 의리와 진실. 머무는 것과 떠나는 것.",
  "그러면 바깥의 사건들은 그 선택을 드러내 놓게 만드는 방편이 된다.",
  "작가들은 아주 오래전부터 이것을 알고 있었다.",
  "마케팅은 더 나중에 이를 발견했고, 끊임없이 쓴다.",
  "가장 강한 광고는 제품이 좋다고 주장하는 일이 드물다.",
  "그것들은 작은 내적 갈등을 무대에 올리고, 그 해소 지점에 제품을 놓는다.",
  "일하고 싶으면서 곁에 있고 싶은 부모. 쉬고 싶으면서 성적도 원하는 학생.",
  "아무것도 주장하지 않으므로, 아무것도 증명할 필요가 없다.",
  "이것은 기능 목록보다 효과적이고, 반박하기도 더 어렵다.",
  "알아봄의 느낌은 사실 확인을 할 수가 없다.",
  "바로 그렇기 때문에 이 기법은 경계보다 주의를 기울일 가치가 있다.",
  "소설을 다시 읽게 만드는 그 장치가 필요 없는 물건을 팔 수도 있다.",
  "그 모양을 알아보는 법을 배우는 일이 그것을 즐기기를 거부하는 일은 아니다."
 ],
 bank: [["defeat","①","물리치다"],["loyalty","③","의리"],["resolution","⑧","해소"],
        ["assert","⑩","주장하다"],["feature","⑪","기능"],["recognition","⑫","알아봄"]],
 defs: [["defeat","to win against someone in a fight"],
        ["loyalty","firm support for a person or group"],
        ["resolution","the point at which a difficulty is settled"],
        ["assert","to state something firmly as true"],
        ["feature","a part or quality of a product"],
        ["recognition","the sense of knowing something already"]],
 defOrder: [1,4,0,5,3,2],
 flow: [
  ["Weak story","A hero simply defeats a monster",null],
  ["Strong story","A character wants two things that cannot both be (  ①  )","had"],
  ["The borrowing","Advertising stages the conflict and places the product at the (  ②  )","resolution"],
  ["Why it works","Nothing is asserted, so nothing must be (  ③  )","proved"],
  ["The response","Notice the shape rather than sound the (  ④  )","alarm"]
 ],
 flowBogi: "had · resolution · proved · alarm · monster · feature",
 para: [
  ["① easy to follow and easy to forget","Simple plots leave no ______.","trace"],
  ["④ forcing that choice into the open","Events make the conflict ______.","visible"],
  ["⑩ Nothing is asserted","No claim means no ______.","burden"],
  ["⑫ cannot fact-check a feeling","Recognition resists ______.","testing"],
  ["⑮ not the same as refusing to enjoy it","Awareness need not end ______.","pleasure"]
 ],
 paraBogi: "trace · visible · burden · testing · pleasure · memory · hidden · proof",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Write a Monster Story","A Device That Sells and a Device That Lasts",
       "Advertising Should Be Banned","The Best Novels of the Century",
       "Why Feature Lists Always Work"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["남는 이야기는 인물의 내적 갈등을 담는다.","강한 광고는 제품이 좋다고 주장하지 않는 편이다.",
       "필자는 이 기법을 금지해야 한다고 본다.","알아봄의 느낌은 사실 확인이 어렵다.",
       "같은 장치가 소설과 광고에 함께 쓰인다."], ans:3},
  {t:"write", q:"필자가 이 기법이 '반박하기 어렵다'고 한 이유를 우리말 한 문장으로 써 보세요.",
   ans:"주장을 하지 않으므로 사실 확인할 대상 자체가 없기 때문이다."}
 ],
 fl: {
  model: { n:"②",
   toks: [["The ones that stay","s"],["involve","v"],["a character","m"],
          ["who wants two things that cannot both be had","m"]],
   ko:"남는 이야기는 둘 다 가질 수 없는 두 가지를 원하는 인물을 담고 있다." },
  drill: [
   { n:"⑧", en:"They stage a small internal conflict and place the product at the resolution.",
     ans:"S They · △V stage · O a small internal conflict · [and] △V place · O the product · M at the resolution",
     ko:"그것들은 작은 내적 갈등을 무대에 올리고, 그 해소 지점에 제품을 놓는다." },
   { n:"⑩", en:"Nothing is asserted, so nothing has to be proved.",
     ans:"S Nothing · △V is asserted · [so] S′ nothing · △V′ has to be proved",
     ko:"아무것도 주장하지 않으므로, 아무것도 증명할 필요가 없다." },
   { n:"⑮", en:"Learning to notice the shape is not the same as refusing to enjoy it.",
     ans:"S Learning to notice the shape · △V is not · C the same as refusing to enjoy it",
     ko:"그 모양을 알아보는 법을 배우는 일이 그것을 즐기기를 거부하는 일은 아니다." }
  ]
 },
 syn: [
  { n:"②", name:"관계대명사절 이중 수식",
    q:"The ones that stay involve «a character who wants two things that cannot both be had».",
    d:"who 절이 character 를, that 절이 two things 를 각각 꾸민다. 꾸미는 말이 겹칠 때 <b>본동사</b>를 먼저 찾는다.",
    k:"둘 다 가질 수 없는 두 가지를 원하는 인물을 담고 있다." },
  { n:"⑮", name:"the same as + 동명사",
    q:"Learning to notice the shape is «not the same as refusing» to enjoy it.",
    d:"<b>A is the same as B</b>에서 B 자리에 동명사가 왔다. 'A는 B와 같지 않다'로 옮긴다.",
    k:"알아보는 일이 거부하는 일과 같지는 않다." }
 ],
 synd: [
  { u:"구문 1", en:"The books that last describe people who choose between two goods.",
    k:"오래 남는 책들은 두 가지 좋은 것 사이에서 고르는 사람을 그린다." },
  { u:"구문 2", en:"Reading fast is not the same as reading well.",
    k:"빨리 읽는 일이 잘 읽는 일과 같지는 않다." },
  { u:"구문 1 + 2", en:"Noticing the trick that works is not the same as escaping it.",
    k:"통하는 수법을 알아보는 일이 거기서 벗어나는 일과 같지는 않다." }
 ],
 wtype: ["무관","정답","반대","무관","반대"],
 stype: ["일치","일치","반대","일치","일치"],
 why: [["괴물 이야기 쓰는 법은 글의 관심사가 아니다"],["정답"],
       ["글은 경계보다 주의를 기울이자고 말한다 — 정반대다"],
       ["명작 목록은 글에 나오지 않는다"],
       ["글은 기능 목록이 덜 효과적이라고 말한다 — 정반대다"]],
 src: [["②"],["⑦"],["⑬과 어긋남 — 금지가 아니라 주의를 말했다"],["⑫"],["⑭"]],
 kb: {
  title:"이야기의 뼈대",
  lead:"같은 틀이 소설과 광고에 함께 쓰인다.",
  items: [
   ["내적 갈등과 외적 갈등",
    "창작론에서는 인물이 세계와 맞서는 외적 갈등과, 인물 안의 두 욕구가 맞서는 내적 갈등을 나눈다. 오래 기억되는 이야기는 대개 후자를 축으로 삼는다."],
   ["광고가 빌려 온 것",
    "1960년대 이후 광고는 제품 설명에서 정체성과 상황을 다루는 쪽으로 옮겨 갔다. 주장 대신 장면을 제시하면 반박 지점이 사라진다는 점이 자주 지적된다."],
   ["'보여 주고 말하지 말라'",
    "글쓰기에서 오래된 조언이지만, 설득에서는 다른 함의를 갖는다. 말하지 않은 주장은 검증하기도 어렵다."]
  ],
  ask:"기억에 남는 광고 하나를 떠올려 보자. 거기서 인물은 무엇과 무엇 사이에 있었는가?"
 }
},
{
 no: "48", key: "gig",
 accent: "#4A6B52", tint: "#E9F1EA", deep: "#2F4A36",
 en: "The Decline of Stable Jobs",
 ko: "안정된 일자리가 줄어들 때",
 goal: "고용 형태의 변화가 위험을 누구에게 옮기는지 설명할 수 있다.",
 fig: "Figure 1  위험이 옮겨 가는 자리.",
 tip: "먼저 생각해 보자. '내가 시간을 정한다'는 말은 언제나 좋은 소식일까?",
 sent: [
  "For most of the twentieth century, a job meant one employer and a long relationship.",
  "You were hired, you stayed, and the firm carried the risk of a slow quarter.",
  "That arrangement is no longer the only shape work takes.",
  "Companies now buy labour the way they buy electricity, in the amounts they need.",
  "Platforms match a driver, a translator, or a cleaner to a task within minutes.",
  "For the worker the appeal is real: you choose the hours and answer to no manager.",
  "The cost is that the risk has quietly moved from the firm to the individual.",
  "An empty afternoon used to be the company's problem, and now it is yours.",
  "Pensions, sick pay, and training were bundled into the old contract without anyone noticing.",
  "Unbundled, they become purchases that a variable income struggles to make.",
  "Defenders argue that flexibility suits students, carers, and anyone leaving a rigid office.",
  "Critics reply that a choice made under pressure is not much of a choice.",
  "Several countries have begun writing a third category between employee and contractor.",
  "Whether that solves the problem or simply names it remains an open question.",
  "The real issue is not that work has changed, but who absorbs the shock."
 ],
 kor: [
  "20세기의 대부분 동안 직업이란 한 고용주와 맺는 긴 관계를 뜻했다.",
  "채용되면 계속 머물렀고, 실적이 나쁜 분기의 위험은 회사가 떠안았다.",
  "그런 방식은 이제 일이 취하는 유일한 모양이 아니다.",
  "기업들은 이제 필요한 만큼만, 전기를 사듯 노동을 산다.",
  "플랫폼은 기사나 번역가나 청소 노동자를 몇 분 안에 일감과 연결한다.",
  "노동자에게 그 매력은 진짜다. 시간을 직접 고르고 어떤 관리자에게도 답하지 않는다.",
  "대가는 위험이 회사에서 개인에게로 조용히 옮겨 갔다는 점이다.",
  "비어 있는 오후는 예전에는 회사의 문제였지만 이제는 당신의 문제다.",
  "연금과 병가 수당과 교육은 아무도 눈치채지 못한 채 옛 계약 안에 묶여 있었다.",
  "묶음이 풀리면 그것들은 들쭉날쭉한 소득으로는 감당하기 힘든 구매가 된다.",
  "옹호하는 쪽은 유연성이 학생과 돌봄을 맡은 사람, 경직된 사무실을 떠나는 이들에게 맞는다고 말한다.",
  "비판하는 쪽은 압박 속에서 한 선택은 선택이라 하기 어렵다고 답한다.",
  "여러 나라가 피고용인과 도급업자 사이의 제3의 범주를 쓰기 시작했다.",
  "그것이 문제를 푸는 것인지 그저 이름을 붙이는 것인지는 아직 열린 물음이다.",
  "진짜 문제는 일이 변했느냐가 아니라, 이제 누가 그 충격을 흡수하느냐다."
 ],
 bank: [["employer","①","고용주"],["arrangement","③","방식"],["appeal","⑥","매력"],
        ["pensions","⑨","연금"],["flexibility","⑪","유연성"],["shock","⑮","충격"]],
 defs: [["employer","a person or firm that pays people to work"],
        ["arrangement","a way that things are organised"],
        ["appeal","the quality that makes something attractive"],
        ["pensions","money paid regularly after a working life"],
        ["flexibility","the freedom to change to fit a situation"],
        ["shock","a sudden blow that must be taken by someone"]],
 defOrder: [4,1,5,0,3,2],
 flow: [
  ["The old shape","One employer carried the risk of a slow quarter",null],
  ["What changed","Firms now buy labour in the (  ①  ) they need","amounts"],
  ["The trade","Free hours, minus the (  ②  ) once bundled in","benefits"],
  ["Who pays now","The empty afternoon belongs to the (  ③  )","worker"],
  ["Open question","A third legal (  ④  ) may name it or fix it","category"]
 ],
 flowBogi: "amounts · benefits · worker · category · manager · pressure",
 para: [
  ["② the firm carried the risk of a slow quarter","The employer used to ______ the loss.","absorb"],
  ["⑦ the risk has quietly moved from the firm","The burden has been ______ downward.","shifted"],
  ["⑨ bundled into the old contract","Protections came ______ with the job.","automatically"],
  ["⑩ a variable income struggles to make","Unsteady pay makes them hard to ______.","afford"],
  ["⑫ a choice made under pressure","Constraint ______ the meaning of choice.","weakens"]
 ],
 paraBogi: "absorb · shifted · automatically · afford · weakens · widens · random · refuse",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["Why Platforms Match Jobs So Fast","Who Carries the Risk Now",
       "The End of All Employment Contracts","How to Earn More by Working Less",
       "A Guide to Choosing Your Own Hours"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["기업은 필요한 만큼 노동을 사들인다.","위험은 회사에서 개인 쪽으로 옮겨 갔다.",
       "연금과 병가 수당은 옛 계약에 묶여 있었다.","필자는 제3의 범주가 문제를 해결했다고 본다.",
       "비판하는 쪽은 압박 속의 선택을 문제 삼는다."], ans:4},
  {t:"write", q:"'충격을 흡수하는 쪽'이 어떻게 달라졌는지 우리말 한 문장으로 써 보세요.",
   ans:"예전에는 한산한 시기의 손실을 회사가 떠안았지만, 이제는 그 위험을 개인이 직접 지게 되었다."}
 ],
 fl: {
  model: { n:"⑦",
   toks: [["The cost","s"],["is","v"],["that","c"],["the risk","s2"],
          ["has quietly moved","v2"],["from the firm to the individual","m"]],
   ko:"대가는 위험이 회사에서 개인에게로 조용히 옮겨 갔다는 점이다." },
  drill: [
   { n:"②", en:"You were hired, you stayed, and the firm carried the risk of a slow quarter.",
     ans:"S You · △V were hired · S you · △V stayed · [and] S the firm · △V carried · O the risk of a slow quarter",
     ko:"채용되면 계속 머물렀고, 실적이 나쁜 분기의 위험은 회사가 떠안았다." },
   { n:"⑫", en:"Critics reply that a choice made under pressure is not much of a choice.",
     ans:"S Critics · △V reply · [that] S′ a choice · M made under pressure · △V′ is · C not much of a choice",
     ko:"비판하는 쪽은 압박 속에서 한 선택은 선택이라 하기 어렵다고 답한다." },
   { n:"⑮", en:"The real issue is not that work has changed, but who absorbs the shock.",
     ans:"S The real issue · △V is · C not that work has changed, but who absorbs the shock",
     ko:"진짜 문제는 일이 변했느냐가 아니라, 이제 누가 그 충격을 흡수하느냐다." }
  ]
 },
 syn: [
  { n:"④", name:"the way + 절 / in the amounts",
    q:"Companies now buy labour «the way they buy» electricity, in the amounts they need.",
    d:"<b>the way + 절</b>은 '~하는 방식대로'라는 뜻으로 접속사처럼 쓰인다.",
    k:"기업은 전기를 사는 방식대로 노동을 산다." },
  { n:"⑩", name:"분사구문 + 관계대명사 that",
    q:"«Unbundled», they become purchases «that a variable income struggles to» make.",
    d:"앞의 <b>Unbundled</b>는 '묶음이 풀리면'이라는 분사구문이고, that 절이 purchases 를 꾸민다.",
    k:"묶음이 풀리면 그것들은 들쭉날쭉한 소득으로 감당하기 힘든 구매가 된다." }
 ],
 synd: [
  { u:"구문 1", en:"She solves problems the way her teacher did.",
    k:"그녀는 선생님이 하던 방식대로 문제를 푼다." },
  { u:"구문 2", en:"Rebuilt, the bridge became a road that everyone uses.",
    k:"다시 지어지자 그 다리는 모두가 쓰는 길이 되었다." },
  { u:"구문 1 + 2", en:"Unpaid, the work becomes a duty that nobody counts the way a job is counted.",
    k:"보수가 없으면 그 일은 직업을 세는 방식대로는 아무도 세어 주지 않는 의무가 된다." }
 ],
 wtype: ["지엽","정답","반대","무관","배경"],
 stype: ["일치","일치","일치","반대","일치"],
 why: [["플랫폼의 속도는 한 문장에 나오는 세부일 뿐이다"],["정답"],
       ["옛 계약이 사라졌다고 하지 않았다 — 유일한 모양이 아닐 뿐이다"],
       ["소득을 늘리는 방법은 글의 관심사가 아니다"],
       ["시간 선택은 매력을 설명하는 배경으로만 언급된다"]],
 src: [["④"],["⑦"],["⑨"],["⑭과 어긋남 — 아직 열린 물음이라고 했다"],["⑫"]],
 kb: {
  title:"위험은 어디로 가는가",
  lead:"고용의 모양이 바뀌면 위험의 자리도 바뀐다.",
  items: [
   ["표준 고용 관계",
    "20세기 중반의 '표준 고용'은 기간의 정함이 없고 전일제이며 사회보험이 붙는 형태를 가리킨다. 이 묶음이 당연해 보였던 것은 계약 안에 함께 들어 있었기 때문이다."],
   ["플랫폼 노동과 분류",
    "플랫폼 종사자를 피고용인으로 볼지 자영업자로 볼지를 두고 각국에서 다툼이 이어졌다. 영국 대법원의 2021년 우버 판결처럼 중간적 지위를 인정한 사례가 대표적이다."],
   ["위험의 개인화",
    "실업·질병·노후처럼 집단이 나누어 지던 위험이 개인의 선택 문제로 옮겨 가는 흐름을 사회학에서는 '위험의 개인화'라고 부른다."]
  ],
  ask:"내가 아는 일자리 하나를 떠올려 보자. 일이 없는 날의 손해는 누구의 몫인가?"
 }
},
{
 no: "49", key: "store",
 accent: "#6B4E8C", tint: "#EFE9F6", deep: "#493165",
 en: "The Hidden Psychological Game for Shoppers",
 ko: "매장이 거는 조용한 게임",
 goal: "매장 설계가 구매 결정에 어떻게 개입하는지 설명할 수 있다.",
 fig: "Figure 1  매장은 길을 설계한다.",
 tip: "먼저 생각해 보자. 계획에 없던 물건을 사 본 적이 있는가? 그때 무엇이 달랐을까?",
 sent: [
  "A supermarket looks like a plain warehouse, but it is closer to a designed path.",
  "Milk and bread sit at the back, so the most common errand walks you past everything else.",
  "The route is no accident, and neither is the light above the fruit.",
  "Slower music has been found to lengthen the time customers spend in the aisles.",
  "Longer visits tend to produce fuller baskets, which is the only measure that matters here.",
  "Prices ending in nine survive because the eye reads the first digit and moves on.",
  "A shelf at eye level earns more than the same shelf near the floor.",
  "Suppliers know this, and they pay for the height.",
  "None of these tricks forces anyone to buy a thing.",
  "They simply tilt a hundred small decisions in one direction.",
  "Defenders call this good service, since a pleasant shop is not a crime.",
  "Critics answer that the shopper is playing a game whose rules were never explained.",
  "The asymmetry is the point: one side has data, and the other has a list.",
  "Knowing the design does not switch it off, but it does change what you notice.",
  "You can still enjoy the shop while seeing the shape of the floor."
 ],
 kor: [
  "슈퍼마켓은 평범한 창고처럼 보이지만, 사실은 설계된 길에 더 가깝다.",
  "우유와 빵은 안쪽에 있어서, 가장 흔한 심부름이 나머지 전부를 지나가게 만든다.",
  "그 동선은 우연이 아니고, 과일 위의 조명도 마찬가지다.",
  "느린 음악이 손님이 통로에서 보내는 시간을 늘린다는 것이 밝혀져 왔다.",
  "머무는 시간이 길수록 장바구니는 더 차고, 여기서 중요한 척도는 그것뿐이다.",
  "9로 끝나는 가격이 살아남는 이유는 눈이 첫 자리를 읽고 넘어가기 때문이다.",
  "눈높이의 선반은 바닥 가까운 같은 선반보다 더 많이 번다.",
  "공급업체들은 이것을 알고, 그 높이에 값을 치른다.",
  "이 수법들 가운데 무엇도 누군가에게 사라고 강요하지는 않는다.",
  "그것들은 그저 백 개의 작은 결정을 한쪽으로 기울일 뿐이다.",
  "기분 좋은 가게가 죄는 아니므로, 옹호하는 쪽은 이것을 좋은 서비스라고 부른다.",
  "비판하는 쪽은 손님이 규칙을 들어 본 적 없는 게임을 하고 있다고 답한다.",
  "요점은 비대칭이다. 한쪽에는 자료가 있고, 다른 쪽에는 장 볼 목록이 있다.",
  "설계를 안다고 그것이 꺼지지는 않지만, 무엇이 보이는지는 달라진다.",
  "바닥의 모양을 보면서도 그 가게를 여전히 즐길 수 있다."
 ],
 bank: [["warehouse","①","창고"],["aisles","④","통로"],["digit","⑥","자릿수"],
        ["suppliers","⑧","공급업체"],["tilt","⑩","기울이다"],["asymmetry","⑬","비대칭"]],
 defs: [["warehouse","a large building for storing goods"],
        ["aisles","the passages between rows of shelves"],
        ["digit","any of the numbers from 0 to 9"],
        ["suppliers","firms that provide goods to a shop"],
        ["tilt","to lean or push in one direction"],
        ["asymmetry","a lack of balance between two sides"]],
 defOrder: [3,5,0,2,1,4],
 flow: [
  ["The look","A shop that seems like an ordinary warehouse",null],
  ["The design","Staples at the back make the errand cross the (  ①  )","aisles"],
  ["The tools","Light, music and shelf (  ②  ) all do quiet work","height"],
  ["The claim","Nobody is forced; a hundred choices merely (  ③  )","tilt"],
  ["The verdict","Seeing the (  ④  ) changes what you notice","design"]
 ],
 flowBogi: "aisles · height · tilt · design · price · crime",
 para: [
  ["② the most common errand walks you past everything","Layout ______ the shopper's route.","directs"],
  ["④ Slower music has been found to lengthen the time","Tempo affects how long people ______.","stay"],
  ["⑥ the eye reads the first digit and moves on","Attention stops at the ______ number.","leading"],
  ["⑩ tilt a hundred small decisions in one direction","Many tiny choices are gently ______.","nudged"],
  ["⑬ one side has data, and the other has a list","The two sides are unequally ______.","informed"]
 ],
 paraBogi: "directs · stay · leading · nudged · informed · blocked · leave · final",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Cheapest Way to Fill a Basket","A Floor Plan That Argues With You",
       "Why Supermarkets Should Be Banned","How Suppliers Choose Their Prices",
       "The History of the Modern Warehouse"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["우유와 빵은 매장 안쪽에 놓인다.","느린 음악은 머무는 시간을 늘린다.",
       "눈높이 선반은 바닥 쪽보다 더 많이 번다.","필자는 이런 설계가 구매를 강요한다고 본다.",
       "설계를 알아도 그것이 사라지지는 않는다."], ans:4},
  {t:"write", q:"필자가 말한 '비대칭'이 무엇 사이의 것인지 우리말 한 문장으로 써 보세요.",
   ans:"자료를 쌓아 두고 설계하는 매장과, 장 볼 목록 하나만 들고 오는 손님 사이의 정보 차이를 말한다."}
 ],
 fl: {
  model: { n:"⑤",
   toks: [["Longer visits","s"],["tend to produce","v"],["fuller baskets",null],
          ["which","s2"],["is","v2"],["the only measure that matters here","m"]],
   ko:"머무는 시간이 길수록 장바구니는 더 차고, 그것이 여기서 유일하게 중요한 척도다." },
  drill: [
   { n:"②", en:"Milk and bread sit at the back, so the most common errand walks you past everything else.",
     ans:"S Milk and bread · △V sit · M at the back · [so] S the most common errand · △V walks · O you · M past everything else",
     ko:"우유와 빵은 안쪽에 있어서, 가장 흔한 심부름이 나머지 전부를 지나가게 만든다." },
   { n:"⑥", en:"Prices ending in nine survive because the eye reads the first digit and moves on.",
     ans:"S Prices · M ending in nine · △V survive · [because] S′ the eye · △V′ reads · O the first digit · △V′ moves on",
     ko:"9로 끝나는 가격이 살아남는 이유는 눈이 첫 자리를 읽고 넘어가기 때문이다." },
   { n:"⑫", en:"Critics answer that the shopper is playing a game whose rules were never explained.",
     ans:"S Critics · △V answer · [that] S′ the shopper · △V′ is playing · O a game · M whose rules were never explained",
     ko:"비판하는 쪽은 손님이 규칙을 들어 본 적 없는 게임을 하고 있다고 답한다." }
  ]
 },
 syn: [
  { n:"④", name:"have been found to + 동사원형",
    q:"Slower music «has been found to lengthen» the time customers spend in the aisles.",
    d:"<b>be found to+동사원형</b>은 '~하는 것으로 밝혀지다'. 현재완료 수동으로 연구 결과를 전한다.",
    k:"느린 음악이 통로에서 보내는 시간을 늘린다는 것이 밝혀졌다." },
  { n:"⑫", name:"소유격 관계대명사 whose",
    q:"the shopper is playing a game «whose rules» were never explained.",
    d:"<b>whose</b>는 앞의 명사(game)가 가진 것을 이어 준다. '그 게임의 규칙'으로 읽는다.",
    k:"손님은 규칙이 설명된 적 없는 게임을 하고 있다." }
 ],
 synd: [
  { u:"구문 1", en:"Short breaks have been found to improve memory.",
    k:"짧은 휴식이 기억을 좋게 한다는 것이 밝혀졌다." },
  { u:"구문 2", en:"We entered a building whose doors opened by themselves.",
    k:"우리는 문이 저절로 열리는 건물에 들어갔다." },
  { u:"구문 1 + 2", en:"A shop whose lights are warm has been found to hold visitors longer.",
    k:"조명이 따뜻한 가게가 손님을 더 오래 붙든다는 것이 밝혀졌다." }
 ],
 wtype: ["무관","정답","반대","지엽","배경"],
 stype: ["일치","일치","일치","반대","일치"],
 why: [["가장 싸게 사는 법은 글이 다루지 않는다"],["정답"],
       ["금지하자는 주장이 아니다 — 알아차리라고 한다"],
       ["공급업체 이야기는 두 문장에 그치는 세부다"],
       ["창고는 첫 문장의 비유로만 나온다"]],
 src: [["②"],["④"],["⑦"],["⑨와 어긋남 — 강요하지는 않는다고 했다"],["⑭"]],
 kb: {
  title:"매장은 어떻게 말을 거는가",
  lead:"설계는 말없이 권한다.",
  items: [
   ["동선과 필수품 배치",
    "우유·달걀 같은 필수품을 입구에서 먼 곳에 두는 배치는 유통업의 오래된 관행이다. 목적지까지 가는 동안 다른 진열대를 지나게 하려는 설계다."],
   ["매장 음악 연구",
    "1982년 밀리먼의 연구는 느린 배경음악이 매장 체류 시간과 매출을 늘렸다고 보고했다. 이후 조명·향기·혼잡도에 대한 후속 연구가 이어졌다."],
   ["9로 끝나는 가격",
    "왼쪽 자리 효과로 설명된다. 2.99를 3보다 2에 가까운 값으로 인식한다는 것이다."]
  ],
  ask:"자주 가는 가게의 배치를 떠올려 보자. 내가 늘 지나치게 되는 진열대는 어디인가?"
 }
},
{
 no: "50", key: "veblen",
 accent: "#B0782A", tint: "#F8EFDC", deep: "#7C5312",
 en: "When Higher Prices Increase Demand",
 ko: "값이 오르면 더 팔리는 물건",
 goal: "가격이 신호로 작동하는 예외적 경우를 설명할 수 있다.",
 fig: "Figure 1  가격표가 하는 말.",
 tip: "먼저 생각해 보자. 값이 두 배가 되면 사람들은 늘 덜 살까?",
 sent: [
  "The first rule anyone learns in economics is that demand falls as price rises.",
  "The rule holds for rice, for petrol, and for almost everything on a shelf.",
  "It fails for a small family of goods, and the failure is instructive.",
  "A handbag that doubles in price can sell more units than before.",
  "Nothing inside the bag has changed, and the stitching is the same.",
  "What changed is the message the price sends to everyone who sees it.",
  "Thorstein Veblen described this in 1899 as consumption meant to be observed.",
  "The good is bought partly for the buyer and partly for the audience.",
  "This only works while the price stays out of most people's reach.",
  "A luxury that everyone can afford stops performing the job it was bought for.",
  "Brands therefore protect scarcity as carefully as they protect quality.",
  "The pattern is easy to mock and harder to escape.",
  "School uniforms, wedding rules, and gifts all carry similar signals.",
  "Reading a price as information about goods misses half of what it does.",
  "It is also information about the person who is willing to pay it."
 ],
 kor: [
  "경제학에서 누구나 처음 배우는 규칙은 값이 오르면 수요가 줄어든다는 것이다.",
  "그 규칙은 쌀에도, 휘발유에도, 진열대의 거의 모든 것에도 들어맞는다.",
  "그것은 작은 무리의 상품에서 어긋나는데, 그 어긋남이 많은 것을 알려 준다.",
  "값이 두 배가 된 손가방이 예전보다 더 많이 팔릴 수 있다.",
  "가방 안의 무엇도 달라지지 않았고, 바느질도 그대로다.",
  "달라진 것은 그 가격이 그것을 보는 모든 사람에게 보내는 메시지다.",
  "소스타인 베블런은 1899년에 이것을 남에게 보이기 위한 소비라고 설명했다.",
  "그 물건은 얼마간은 구매자를 위해, 얼마간은 관객을 위해 사는 것이다.",
  "이것은 값이 대다수의 손이 닿지 않는 곳에 머무는 동안에만 작동한다.",
  "누구나 살 수 있는 사치품은 그것이 사들여진 목적을 더는 수행하지 못한다.",
  "그래서 브랜드들은 품질을 지키는 만큼이나 조심스럽게 희소성을 지킨다.",
  "이 패턴은 비웃기는 쉽고 빠져나오기는 더 어렵다.",
  "교복도, 결혼식의 관례도, 선물도 모두 비슷한 신호를 지닌다.",
  "가격을 상품에 대한 정보로만 읽으면 그것이 하는 일의 절반을 놓친다.",
  "그것은 그 값을 기꺼이 치르려는 사람에 대한 정보이기도 하다."
 ],
 bank: [["demand","①","수요"],["instructive","③","시사하는 바가 큰"],["stitching","⑤","바느질"],
        ["consumption","⑦","소비"],["audience","⑧","관객"],["scarcity","⑪","희소성"]],
 defs: [["demand","the amount buyers want at a price"],
        ["instructive","useful for teaching something"],
        ["stitching","the line of thread joining pieces"],
        ["consumption","the buying and using of goods"],
        ["audience","the people who are watching"],
        ["scarcity","the state of being hard to obtain"]],
 defOrder: [2,4,1,5,0,3],
 flow: [
  ["The usual rule","When price rises, demand normally falls",null],
  ["The exception","A bag that doubles in price can sell (  ①  )","more"],
  ["Why","The price itself carries a (  ②  ) to onlookers","message"],
  ["The condition","It works only while the price stays out of (  ③  )","reach"],
  ["The lesson","A price is information about the (  ④  ) too","buyer"]
 ],
 flowBogi: "more · message · reach · buyer · quality · stitching",
 para: [
  ["③ It fails for a small family of goods","The law has known ______.","exceptions"],
  ["⑥ the message the price sends to everyone","The tag itself ______ something.","signals"],
  ["⑧ partly for the buyer and partly for the audience","Buying serves a ______ purpose too.","social"],
  ["⑩ stops performing the job it was bought for","Wide access ______ the signal.","destroys"],
  ["⑫ easy to mock and harder to escape","Recognising it does not ______ us.","free"]
 ],
 paraBogi: "exceptions · signals · social · destroys · free · hides · rare · repair",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["Why Rice and Petrol Obey the Rule","A Price Is a Message, Not Just a Cost",
       "Luxury Brands Should Lower Their Prices","How to Judge the Quality of a Handbag",
       "The Life and Work of Thorstein Veblen"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["대부분의 상품은 값이 오르면 수요가 준다.","값이 오른 가방이 더 많이 팔릴 수 있다.",
       "브랜드는 희소성을 조심스럽게 지킨다.","필자는 이 패턴에서 벗어나기 쉽다고 본다.",
       "가격은 사는 사람에 대한 정보이기도 하다."], ans:4},
  {t:"write", q:"가격을 상품 정보로만 읽으면 '절반을 놓친다'고 한 이유를 우리말로 써 보세요.",
   ans:"가격은 그 값을 기꺼이 치르려는 사람에 대한 정보이기도 한데, 그 절반을 보지 못하기 때문이다."}
 ],
 fl: {
  model: { n:"⑩",
   toks: [["A luxury","s"],["that","c"],["everyone","s2"],["can afford","v2"],
          ["stops","v"],["performing the job it was bought for",null]],
   ko:"누구나 살 수 있는 사치품은 그것이 사들여진 목적을 더는 수행하지 못한다." },
  drill: [
   { n:"③", en:"It fails for a small family of goods, and the failure is instructive.",
     ans:"S It · △V fails · M for a small family of goods · [and] S the failure · △V is · C instructive",
     ko:"그것은 작은 무리의 상품에서 어긋나는데, 그 어긋남이 많은 것을 알려 준다." },
   { n:"⑨", en:"This only works while the price stays out of most people's reach.",
     ans:"S This · M only · △V works · [while] S′ the price · △V′ stays · M out of most people's reach",
     ko:"이것은 값이 대다수의 손이 닿지 않는 동안에만 작동한다." },
   { n:"⑮", en:"It is also information about the person who is willing to pay it.",
     ans:"S It · △V is · C also information about the person · [who] △V′ is willing to pay it",
     ko:"그것은 그 값을 기꺼이 치르려는 사람에 대한 정보이기도 하다." }
  ]
 },
 syn: [
  { n:"⑨", name:"while 접속사 + stay out of",
    q:"This only works «while the price stays» out of most people's reach.",
    d:"<b>while</b>은 '~하는 동안'이라는 조건을 만든다. stay out of ~ 는 '~ 밖에 머물다'.",
    k:"값이 대다수의 손이 닿지 않는 동안에만 이것이 작동한다." },
  { n:"⑭", name:"동명사 주어 + what 명사절",
    q:"«Reading a price» as information about goods misses half of «what it does».",
    d:"동명사구가 주어이고, <b>what it does</b>는 '그것이 하는 일'이라는 명사절이다.",
    k:"가격을 상품 정보로만 읽으면 그것이 하는 일의 절반을 놓친다." }
 ],
 synd: [
  { u:"구문 1", en:"The trick works while nobody looks closely.",
    k:"아무도 자세히 보지 않는 동안 그 수법은 통한다." },
  { u:"구문 2", en:"Counting steps tells us little about what walking does.",
    k:"걸음 수를 세는 일은 걷기가 하는 일을 거의 알려 주지 않는다." },
  { u:"구문 1 + 2", en:"Naming a problem helps while people still remember what it cost.",
    k:"문제에 이름을 붙이는 일은 사람들이 그 대가를 기억하는 동안에는 도움이 된다." }
 ],
 wtype: ["배경","정답","반대","무관","지엽"],
 stype: ["일치","일치","일치","반대","일치"],
 why: [["일반 규칙은 예외를 소개하기 위한 배경이다"],["정답"],
       ["값을 내리라는 주장은 없다 — 오히려 희소성을 지킨다고 했다"],
       ["가방의 품질을 판정하는 글이 아니다"],
       ["베블런은 한 문장에만 등장하는 세부다"]],
 src: [["①"],["④"],["⑪"],["⑫와 어긋남 — 빠져나오기는 더 어렵다고 했다"],["⑮"]],
 kb: {
  title:"가격이 보내는 신호",
  lead:"값은 숫자이면서 동시에 말이다.",
  items: [
   ["베블런재와 기펜재",
    "값이 오를 때 수요가 느는 예외로 베블런재(과시 소비)와 기펜재(열등재의 소득효과)가 함께 거론된다. 두 경우의 이유는 서로 다르다."],
   ["「유한계급론」",
    "베블런은 1899년 저작에서 '과시적 소비'라는 말을 썼다. 소비의 목적 일부가 남에게 보이는 데 있다는 관찰이다."],
   ["희소성 관리",
    "한정판, 대기 명단, 유통 제한은 값을 지키기 위한 장치로 자주 설명된다. 접근이 쉬워질수록 신호의 값이 떨어지기 때문이다."]
  ],
  ask:"값이 비싸서 더 갖고 싶었던 물건이 있는가? 그때 나는 무엇을 사고 있었던 걸까?"
 }
}
]};
