/* Unit 11 · Field 11 — Environment, Resources & Ecology 환경·자원·생태 */
module.exports = {
 no: 11,
 field: "Environment, Resources & Ecology",
 ko: "환경·자원·생태",
 tagline: "함께 쓰는 것 — 규칙·유역·대기·고통·공감",
 next: { en: "Current Affairs", ko: "지금 벌어지고 있는 일들을 읽습니다", words: "175–205 words" },
 lessons: [
{
 no: "51", key: "commons",
 accent: "#2F7268", tint: "#E3F0EE", deep: "#1C4E46",
 en: "Property Rights to Natural Resources",
 ko: "자연 자원에는 주인이 있는가",
 goal: "공유 자원이 망가지는 구조와 그 해법의 조건을 설명할 수 있다.",
 fig: "Figure 1  울타리가 없는 자리.",
 tip: "먼저 생각해 보자. 주인이 없는 것을 잘 지키려면 무엇이 필요할까?",
 sent: [
  "Nobody owns the sea, and that is exactly where the trouble starts.",
  "A field has a fence, a name on a document, and someone who loses money if it is ruined.",
  "A fishery has none of these, so every boat has a reason to take one more.",
  "Each captain knows the stock is falling and knows that restraint alone will not save it.",
  "Economists call this pattern the tragedy of the commons.",
  "The usual remedy is to hand the resource to an owner who will care about next year.",
  "Private quotas have rebuilt some fisheries that free access had emptied.",
  "Yet ownership travels badly across water, air, and moving animals.",
  "A river crosses borders, and a cloud refuses to stay above one farm.",
  "Elinor Ostrom studied villages that solved this without markets or governments.",
  "Their rules were local, written by the users, and enforced by neighbours.",
  "Monitoring was cheap because everyone could see everyone else's boat.",
  "Her work suggests that the question is not private or public.",
  "It is whether the people who bear the cost also make the rules.",
  "Where those two come apart, the resource usually loses."
 ],
 kor: [
  "바다는 누구의 것도 아닌데, 문제가 시작되는 지점이 바로 거기다.",
  "밭에는 울타리가 있고, 문서에 이름이 있고, 망가지면 손해를 보는 사람이 있다.",
  "어장에는 그 가운데 무엇도 없어서, 모든 배가 한 마리 더 잡을 이유를 갖는다.",
  "선장마다 어족이 줄고 있음을 알고, 자기만 참아서는 그것을 구할 수 없음도 안다.",
  "경제학자들은 이 패턴을 공유지의 비극이라고 부른다.",
  "흔한 처방은 내년을 걱정할 주인에게 그 자원을 넘기는 것이다.",
  "개인별 어획 할당은 자유로운 접근이 비워 놓았던 어장 몇 곳을 되살렸다.",
  "그러나 소유권은 물과 공기와 움직이는 동물을 잘 건너가지 못한다.",
  "강은 국경을 넘고, 구름은 한 농장 위에만 머물기를 거부한다.",
  "엘리너 오스트롬은 시장도 정부도 없이 이를 풀어낸 마을들을 연구했다.",
  "그들의 규칙은 지역적이었고, 쓰는 사람들이 만들었으며, 이웃이 지키게 했다.",
  "모두가 서로의 배를 볼 수 있었기 때문에 감시 비용이 쌌다.",
  "그의 연구는 문제가 사유냐 공유냐가 아님을 시사한다.",
  "문제는 비용을 지는 사람들이 규칙도 만드는가이다.",
  "그 둘이 갈라지는 곳에서는 대개 자원이 진다."
 ],
 bank: [["fishery","③","어장"],["restraint","④","자제"],["commons","⑤","공유지"],
        ["quotas","⑦","할당량"],["borders","⑨","국경"],["monitoring","⑫","감시"]],
 defs: [["fishery","an area where fish are caught"],
        ["restraint","the act of holding oneself back"],
        ["commons","land or water shared by all"],
        ["quotas","fixed shares that each may take"],
        ["borders","the lines between countries"],
        ["monitoring","the act of watching to check"]],
 defOrder: [5,2,0,4,1,3],
 flow: [
  ["The setting","Water that belongs to nobody in particular",null],
  ["The pull","Every boat gains by taking (  ①  ) more","one"],
  ["Remedy 1","Give it an (  ②  ) who thinks about next year","owner"],
  ["The limit","Rivers and clouds cross every (  ③  )","border"],
  ["Remedy 2","Local (  ④  ) written and watched by the users","rules"]
 ],
 flowBogi: "one · owner · border · rules · market · profit",
 para: [
  ["① Nobody owns the sea","The resource has no single ______.","claimant"],
  ["③ every boat has a reason to take one more","Individual gain ______ the group.","outruns"],
  ["⑦ some fisheries that free access had emptied","Open entry had ______ the stock.","drained"],
  ["⑫ everyone could see everyone else's boat","Watching cost almost ______.","nothing"],
  ["⑭ the people who bear the cost also make the rules","Deciders should be the ______ ones.","affected"]
 ],
 paraBogi: "claimant · outruns · drained · nothing · affected · owner · fills · distant",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Catch More Fish Each Year","Who Should Write the Rules",
       "Private Property Solves Everything","A Short History of the Fishing Boat",
       "Why Rivers Cross Borders"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["밭에는 망가지면 손해를 보는 주인이 있다.","할당제가 어장을 되살린 사례가 있다.",
       "오스트롬은 시장 없이 문제를 푼 마을을 연구했다.","필자는 사유화가 모든 자원에 통한다고 본다.",
       "감시 비용이 싼 것이 규칙 유지에 도움이 되었다."], ans:4},
  {t:"write", q:"마지막 문장의 '갈라지는 둘'이 무엇인지 우리말 한 문장으로 써 보세요.",
   ans:"비용을 실제로 지는 사람들과 규칙을 만드는 사람들이 서로 다른 경우를 말한다."}
 ],
 fl: {
  model: { n:"⑭",
   toks: [["It","s"],["is","v"],["whether","c"],["the people who bear the cost","s2"],
          ["also make","v2"],["the rules",null]],
   ko:"문제는 비용을 지는 사람들이 규칙도 만드는가이다." },
  drill: [
   { n:"③", en:"A fishery has none of these, so every boat has a reason to take one more.",
     ans:"S A fishery · △V has · O none of these · [so] S every boat · △V has · O a reason to take one more",
     ko:"어장에는 그 가운데 무엇도 없어서, 모든 배가 한 마리 더 잡을 이유를 갖는다." },
   { n:"⑩", en:"Elinor Ostrom studied villages that solved this without markets or governments.",
     ans:"S Elinor Ostrom · △V studied · O villages · [that] △V′ solved · O this · M without markets or governments",
     ko:"엘리너 오스트롬은 시장도 정부도 없이 이를 풀어낸 마을들을 연구했다." },
   { n:"⑫", en:"Monitoring was cheap because everyone could see everyone else's boat.",
     ans:"S Monitoring · △V was · C cheap · [because] S′ everyone · △V′ could see · O everyone else's boat",
     ko:"모두가 서로의 배를 볼 수 있었기 때문에 감시 비용이 쌌다." }
  ]
 },
 syn: [
  { n:"⑥", name:"be + to부정사 보어 / 관계대명사 who",
    q:"The usual remedy is «to hand» the resource to an owner «who will care» about next year.",
    d:"<b>be + to부정사</b>가 보어로 쓰여 '~하는 것이다'가 된다. who 절이 owner 를 꾸민다.",
    k:"흔한 처방은 내년을 걱정할 주인에게 자원을 넘기는 것이다." },
  { n:"⑭", name:"whether 명사절",
    q:"It is «whether the people» who bear the cost also make the rules.",
    d:"<b>whether</b> 절이 보어 자리에 와서 '~인지 아닌지'라는 명사절이 된다.",
    k:"문제는 비용을 지는 사람들이 규칙도 만드는가이다." }
 ],
 synd: [
  { u:"구문 1", en:"The plan is to give the land to a family who will farm it.",
    k:"그 계획은 농사지을 가족에게 그 땅을 주는 것이다." },
  { u:"구문 2", en:"The real test is whether the promise survives a bad year.",
    k:"진짜 시험은 그 약속이 나쁜 해를 견디는가이다." },
  { u:"구문 1 + 2", en:"The question is whether the plan is to trust people who live there.",
    k:"문제는 그 계획이 거기 사는 사람들을 믿는 것인가 하는 점이다." }
 ],
 wtype: ["무관","정답","반대","배경","지엽"],
 stype: ["일치","일치","일치","반대","일치"],
 why: [["더 많이 잡는 법은 글의 관심사가 아니다"],["정답"],
       ["사유화가 만능이라고 하지 않았다 — 한계를 함께 짚는다"],
       ["배는 상황을 설명하는 배경으로만 나온다"],
       ["강이 국경을 넘는다는 것은 한 문장의 세부다"]],
 src: [["②"],["⑦"],["⑩"],["⑧과 어긋남 — 물·공기·동물에는 잘 통하지 않는다고 했다"],["⑫"]],
 kb: {
  title:"주인 없는 것을 지키는 법",
  lead:"규칙은 울타리를 대신할 수 있다.",
  items: [
   ["공유지의 비극",
    "1968년 하딘의 논문으로 널리 알려진 개념이다. 각자에게 합리적인 선택이 모이면 전체가 손해를 보는 구조를 가리킨다."],
   ["개별 어획 할당",
    "어획량을 배마다 나눠 주고 사고팔 수 있게 한 제도다. 일부 어장에서 자원 회복 효과가 보고되었지만, 할당이 소수에게 몰리는 문제도 지적된다."],
   ["오스트롬의 여덟 가지 원칙",
    "1990년 오스트롬은 스위스 목초지, 일본 입회지, 필리핀 관개 조합 등을 비교해 공동 관리가 성공하는 조건을 정리했다. 경계의 명확성, 이용자의 규칙 제정 참여, 값싼 감시가 그중에 있다."]
  ],
  ask:"우리 학교에서 '누구의 것도 아니라서' 잘 관리되지 않는 곳이 있는가?"
 }
},
{
 no: "52", key: "lake",
 accent: "#2E6E8E", tint: "#E4EFF4", deep: "#194C64",
 en: "Urban Lake Restoration",
 ko: "도시 호수를 되살리는 일",
 goal: "호수의 상태가 유역 전체의 결과임을 설명할 수 있다.",
 fig: "Figure 1  물은 마지막에 도착한다.",
 tip: "먼저 생각해 보자. 물이 더러워졌다면 물부터 고쳐야 할까?",
 sent: [
  "The lake in the middle of the city turned green one summer and stayed that way.",
  "Residents blamed the ducks, then the boats, then a factory that had closed.",
  "The actual cause was arriving invisibly with every rainfall.",
  "Lawn fertiliser, road dust, and dog waste all ran off the streets into one basin.",
  "Nutrients feed algae, algae block the light, and the plants below the surface die.",
  "When those plants die, the sediment loosens and releases still more nutrients.",
  "A lake in this state keeps feeding itself long after the inflow is reduced.",
  "The city first tried the visible remedy and dredged the bottom at great expense.",
  "The water cleared for two seasons and then turned green again.",
  "The second attempt worked on the streets instead of the water.",
  "Rain gardens, swept gutters, and planted verges intercepted the runoff before it arrived.",
  "Nothing about this looked like restoration, and no photograph showed a difference.",
  "Four years later the lake held plants, insects, and a returning heron.",
  "The lesson is that a lake is the last page of its catchment.",
  "Reading only the last page explains very little."
 ],
 kor: [
  "도시 한가운데의 호수가 어느 여름 초록으로 변하더니 그대로 있었다.",
  "주민들은 오리를 탓하고, 배를 탓하고, 문 닫은 공장을 탓했다.",
  "실제 원인은 비가 올 때마다 눈에 보이지 않게 도착하고 있었다.",
  "잔디 비료와 도로 먼지와 개의 배설물이 모두 거리에서 한 웅덩이로 흘러들었다.",
  "영양분은 조류를 키우고, 조류는 빛을 막고, 수면 아래 식물은 죽는다.",
  "그 식물이 죽으면 바닥 퇴적물이 헐거워지면서 영양분을 더 많이 내놓는다.",
  "이 상태의 호수는 유입이 줄어든 뒤에도 오랫동안 스스로를 계속 먹인다.",
  "시는 먼저 눈에 보이는 처방을 택해 큰돈을 들여 바닥을 준설했다.",
  "물은 두 계절 동안 맑아졌다가 다시 초록으로 변했다.",
  "두 번째 시도는 물이 아니라 거리에서 이루어졌다.",
  "빗물 정원과 청소한 배수구와 심어 놓은 가장자리가 유출수를 도착 전에 붙잡았다.",
  "이 가운데 무엇도 복원처럼 보이지 않았고, 어떤 사진도 차이를 보여 주지 못했다.",
  "4년 뒤 그 호수에는 식물과 곤충과 돌아온 왜가리가 있었다.",
  "교훈은 호수가 그 유역의 마지막 쪽이라는 것이다.",
  "마지막 쪽만 읽어서는 설명되는 것이 거의 없다."
 ],
 bank: [["residents","②","주민"],["fertiliser","④","비료"],["nutrients","⑤","영양분"],
        ["sediment","⑥","퇴적물"],["runoff","⑪","유출수"],["catchment","⑭","유역"]],
 defs: [["residents","the people who live in a place"],
        ["fertiliser","material added to help plants grow"],
        ["nutrients","substances that living things need"],
        ["sediment","material that settles at the bottom"],
        ["runoff","water that flows off the land"],
        ["catchment","the area that drains into one place"]],
 defOrder: [4,0,5,1,3,2],
 flow: [
  ["The symptom","A city lake that turned green and stayed green",null],
  ["First guess","Residents blamed ducks, boats and an old (  ①  )","factory"],
  ["Real cause","Nutrients arriving with every (  ②  )","rainfall"],
  ["Failed fix","Dredging cleared the water for two (  ③  )","seasons"],
  ["Real fix","Work on the streets that feed the (  ④  )","catchment"]
 ],
 flowBogi: "factory · rainfall · seasons · catchment · heron · algae",
 para: [
  ["③ arriving invisibly with every rainfall","The cause was ______ but constant.","unseen"],
  ["⑦ keeps feeding itself long after the inflow","The problem became ______.","self-feeding"],
  ["⑧ tried the visible remedy and dredged the bottom","The city chose the ______ answer.","obvious"],
  ["⑫ no photograph showed a difference","Real progress was hardly ______.","visible"],
  ["⑭ a lake is the last page of its catchment","The water only ______ the land.","records"]
 ],
 paraBogi: "unseen · self-feeding · obvious · visible · records · loud · erases · brief",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["How to Dredge a Lake Properly","The Lake Is the Last Page",
       "Why Ducks Should Be Removed","A Guide to Growing Algae",
       "The Cost of Building City Parks"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["영양분이 늘면 조류가 빛을 막는다.","준설 뒤 물은 두 계절만 맑았다.",
       "두 번째 시도는 거리에서 이루어졌다.","필자는 눈에 보이는 처방이 더 낫다고 본다.",
       "4년 뒤 호수에 식물과 곤충이 돌아왔다."], ans:4},
  {t:"write", q:"호수를 '유역의 마지막 쪽'이라 부른 이유를 우리말 한 문장으로 써 보세요.",
   ans:"호수의 상태는 유역에서 일어난 일들이 쌓인 결과라서, 물만 봐서는 원인을 알 수 없기 때문이다."}
 ],
 fl: {
  model: { n:"⑦",
   toks: [["A lake in this state","s"],["keeps","v"],["feeding itself",null],
          ["long after","c"],["the inflow","s2"],["is reduced","v2"]],
   ko:"이 상태의 호수는 유입이 줄어든 뒤에도 오랫동안 스스로를 계속 먹인다." },
  drill: [
   { n:"⑥", en:"When those plants die, the sediment loosens and releases still more nutrients.",
     ans:"[When] S′ those plants · △V′ die · S the sediment · △V loosens · △V releases · O still more nutrients",
     ko:"그 식물이 죽으면 퇴적물이 헐거워지면서 영양분을 더 많이 내놓는다." },
   { n:"⑪", en:"Rain gardens, swept gutters, and planted verges intercepted the runoff before it arrived.",
     ans:"S Rain gardens, swept gutters, and planted verges · △V intercepted · O the runoff · [before] S′ it · △V′ arrived",
     ko:"빗물 정원과 청소한 배수구와 심어 놓은 가장자리가 유출수를 도착 전에 붙잡았다." },
   { n:"⑭", en:"The lesson is that a lake is the last page of its catchment.",
     ans:"S The lesson · △V is · [that] S′ a lake · △V′ is · C the last page of its catchment",
     ko:"교훈은 호수가 그 유역의 마지막 쪽이라는 것이다." }
  ]
 },
 syn: [
  { n:"⑦", name:"keep + ~ing / long after 접속사",
    q:"A lake in this state «keeps feeding» itself «long after the inflow» is reduced.",
    d:"<b>keep + ~ing</b>는 '계속 ~하다'. long after 는 '~한 뒤로도 한참'이라는 접속사다.",
    k:"이 상태의 호수는 유입이 줄어든 뒤로도 한참 스스로를 먹인다." },
  { n:"⑪", name:"세 겹 주어 + before 접속사",
    q:"Rain gardens, swept gutters, and planted verges intercepted the runoff «before it arrived».",
    d:"세 개의 명사구가 하나의 주어를 이룬다. <b>before</b> 절이 시점을 정한다.",
    k:"세 가지 장치가 유출수를 도착하기 전에 붙잡았다." }
 ],
 synd: [
  { u:"구문 1", en:"The engine keeps running long after the driver leaves.",
    k:"운전자가 떠난 뒤로도 한참 엔진이 계속 돈다." },
  { u:"구문 2", en:"Nets, walls, and lights kept the birds out before dawn.",
    k:"그물과 벽과 조명이 새벽 전에 새들을 막았다." },
  { u:"구문 1 + 2", en:"Roots, gravel, and grass keep holding water long after the rain stops.",
    k:"뿌리와 자갈과 풀이 비가 그친 뒤로도 한참 물을 계속 붙든다." }
 ],
 wtype: ["지엽","정답","반대","무관","무관"],
 stype: ["일치","일치","일치","반대","일치"],
 why: [["준설은 실패한 첫 시도로만 나오는 세부다"],["정답"],
       ["오리를 탓한 것은 틀린 짐작이었다고 했다"],
       ["조류를 기르는 법과는 무관하다"],["공원 예산 이야기는 글에 없다"]],
 src: [["⑤"],["⑨"],["⑩"],["⑧~⑬과 어긋남 — 보이지 않는 쪽이 효과가 있었다"],["⑬"]],
 kb: {
  title:"물은 마지막에 온다",
  lead:"호수의 색은 유역의 성적표다.",
  items: [
   ["부영양화",
    "질소와 인이 늘면 조류가 급격히 번성하고, 죽은 조류가 분해되며 산소를 소모해 물속 생물이 죽는다. 도시 하천과 호수에서 흔히 관찰된다."],
   ["내부 부하",
    "퇴적물에 쌓인 인이 산소가 없는 상태에서 다시 물로 녹아 나오는 현상이다. 외부 유입을 줄여도 회복이 늦어지는 주된 이유로 꼽힌다."],
   ["비점오염과 저영향개발",
    "특정 배출구가 없는 오염을 비점오염이라 한다. 빗물 정원·투수 포장·식생 수로처럼 물이 땅에 스미게 하는 설계를 저영향개발이라 부른다."]
  ],
  ask:"우리 동네에 비가 오면 물이 어디로 모이는지 따라가 본 적이 있는가?"
 }
},
{
 no: "53", key: "mars",
 accent: "#A65A3C", tint: "#F7EAE4", deep: "#77361D",
 en: "Modifying Mars' Atmosphere",
 ko: "화성의 대기를 바꾼다면",
 goal: "화성 대기를 두껍게 만드는 계획의 논리와 한계를 설명할 수 있다.",
 fig: "Figure 1  얼마나 두꺼워질 수 있는가.",
 tip: "먼저 생각해 보자. 공기를 '더 두껍게' 만들면 숨을 쉴 수 있게 될까?",
 sent: [
  "Mars has an atmosphere, but it is thin enough to be almost useless.",
  "The pressure at the surface is less than one percent of ours.",
  "Water cannot stay liquid there, and an unprotected body would not last long.",
  "The obvious fix is to make the atmosphere thicker.",
  "Frozen carbon dioxide sits at the poles and inside the soil.",
  "Warm the planet slightly and some of it should return to the air.",
  "That gas would trap heat, which would release more gas, which would trap more heat.",
  "The idea depends on there being enough carbon dioxide to start with.",
  "A recent survey of the known reserves suggests there is not.",
  "Even releasing everything available would raise the pressure to about seven percent.",
  "That is thicker air, but it is still not air anyone could breathe.",
  "Importing gas from elsewhere in the solar system is discussed seriously.",
  "The timescales involved are measured in centuries rather than decades.",
  "Meanwhile the same physics explains what our own thin blanket does here.",
  "A planet is easier to change by accident than on purpose."
 ],
 kor: [
  "화성에도 대기가 있지만, 거의 쓸모없을 만큼 얇다.",
  "지표면의 기압은 우리 기압의 1퍼센트에도 못 미친다.",
  "그곳에서 물은 액체로 남을 수 없고, 보호받지 못한 몸은 오래 버티지 못한다.",
  "분명해 보이는 해법은 대기를 더 두껍게 만드는 것이다.",
  "얼어붙은 이산화탄소가 극지방과 토양 속에 있다.",
  "행성을 조금 데우면 그 일부가 공기로 돌아올 것이다.",
  "그 기체가 열을 가두고, 그것이 기체를 더 내놓고, 그것이 열을 더 가둘 것이다.",
  "이 발상은 애초에 충분한 이산화탄소가 있느냐에 달려 있다.",
  "알려진 저장량을 조사한 최근 연구는 그렇지 않다고 말한다.",
  "구할 수 있는 것을 전부 방출해도 기압은 7퍼센트 정도까지 오를 뿐이다.",
  "그것은 더 두꺼운 공기이긴 하지만, 누군가 숨 쉴 수 있는 공기는 아니다.",
  "태양계의 다른 곳에서 기체를 실어 오는 방안이 진지하게 논의된다.",
  "여기 관련된 시간 규모는 수십 년이 아니라 수백 년 단위로 잰다.",
  "한편 같은 물리학이 우리 자신의 얇은 담요가 여기서 하는 일을 설명한다.",
  "행성은 일부러 바꾸기보다 실수로 바꾸기가 더 쉽다."
 ],
 bank: [["atmosphere","①","대기"],["pressure","②","기압"],["poles","⑤","극지방"],
        ["trap","⑦","가두다"],["reserves","⑨","저장량"],["timescales","⑬","시간 규모"]],
 defs: [["atmosphere","the layer of gases around a planet"],
        ["pressure","the force pushing on a surface"],
        ["poles","the top and bottom of a planet"],
        ["trap","to hold something so it cannot escape"],
        ["reserves","a supply kept for later use"],
        ["timescales","the lengths of time involved"]],
 defOrder: [3,0,5,2,4,1],
 flow: [
  ["The problem","Air too thin for water or for people",null],
  ["The plan","Warm the planet so frozen (  ①  ) returns","gas"],
  ["The loop","Trapped heat frees more gas, which traps more (  ②  )","heat"],
  ["The check","Known reserves are not (  ③  )","enough"],
  ["The lesson","A planet changes more easily by (  ④  )","accident"]
 ],
 flowBogi: "gas · heat · enough · accident · water · purpose",
 para: [
  ["② less than one percent of ours","Martian air is extremely ______.","thin"],
  ["⑦ trap heat, which would release more gas","The process would ______ itself.","reinforce"],
  ["⑨ recent survey of the known reserves","Evidence ______ the plan.","undermines"],
  ["⑪ still not air anyone could breathe","Thicker is not the same as ______.","breathable"],
  ["⑮ easier to change by accident than on purpose","Unplanned change is ______.","easier"]
 ],
 paraBogi: "thin · reinforce · undermines · breathable · easier · dense · proves · harder",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["A Plan That Runs Out of Gas","How to Live on Mars Today",
       "The Coldest Place in the Solar System","Why Carbon Dioxide Is Harmless",
       "Building Rockets for Long Journeys"], ans:1},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["화성 지표 기압은 지구의 1퍼센트에 못 미친다.","극지방과 토양에 언 이산화탄소가 있다.",
       "전부 방출해도 기압은 7퍼센트 정도다.","필자는 곧 화성 공기를 마실 수 있다고 본다.",
       "관련된 시간 규모는 수백 년 단위다."], ans:4},
  {t:"write", q:"마지막 문장이 지구에 대해 무엇을 말하는지 우리말 한 문장으로 써 보세요.",
   ans:"행성의 대기는 일부러 바꾸기는 어려워도 의도치 않게는 쉽게 바뀐다는 뜻이다."}
 ],
 fl: {
  model: { n:"⑧",
   toks: [["The idea","s"],["depends on","v"],
          ["there being enough carbon dioxide",null],["to start with","m"]],
   ko:"이 발상은 애초에 충분한 이산화탄소가 있느냐에 달려 있다." },
  drill: [
   { n:"③", en:"Water cannot stay liquid there, and an unprotected body would not last long.",
     ans:"S Water · △V cannot stay · C liquid · M there · [and] S an unprotected body · △V would not last · M long",
     ko:"그곳에서 물은 액체로 남을 수 없고, 보호받지 못한 몸은 오래 버티지 못한다." },
   { n:"⑦", en:"That gas would trap heat, which would release more gas, which would trap more heat.",
     ans:"S That gas · △V would trap · O heat · [which] △V′ would release · O more gas · [which] △V′ would trap · O more heat",
     ko:"그 기체가 열을 가두고, 그것이 기체를 더 내놓고, 그것이 열을 더 가둘 것이다." },
   { n:"⑭", en:"Meanwhile the same physics explains what our own thin blanket does here.",
     ans:"M Meanwhile · S the same physics · △V explains · O what our own thin blanket does here",
     ko:"한편 같은 물리학이 우리 자신의 얇은 담요가 여기서 하는 일을 설명한다." }
  ]
 },
 syn: [
  { n:"⑦", name:"계속적 용법 which 의 연쇄",
    q:"That gas would trap heat, «which would release» more gas, «which would trap» more heat.",
    d:"콤마 뒤의 <b>which</b>는 앞 내용을 받아 이어 간다. 두 번 이어지며 되먹임을 보여 준다.",
    k:"그 기체가 열을 가두고, 그것이 기체를 더 내놓고, 그것이 열을 더 가둔다." },
  { n:"⑧", name:"depend on + there being",
    q:"The idea «depends on there being» enough carbon dioxide to start with.",
    d:"전치사 뒤라서 there is 가 <b>there being</b>이라는 동명사 형태로 온다.",
    k:"그 발상은 충분한 이산화탄소가 있느냐에 달려 있다." }
 ],
 synd: [
  { u:"구문 1", en:"The road flooded, which closed the school, which upset the town.",
    k:"길이 잠겼고, 그 때문에 학교가 문을 닫았고, 그것이 마을을 뒤흔들었다." },
  { u:"구문 2", en:"Everything depends on there being a second chance.",
    k:"모든 것은 두 번째 기회가 있느냐에 달려 있다." },
  { u:"구문 1 + 2", en:"The plan depends on there being rain, which fills the wells, which feed the fields.",
    k:"그 계획은 비가 오느냐에 달려 있는데, 비는 우물을 채우고 우물은 밭을 먹인다." }
 ],
 wtype: ["정답","반대","지엽","반대","무관"],
 stype: ["일치","일치","일치","반대","일치"],
 why: [["정답"],["오늘 화성에 사는 법이 아니라 대기를 바꾸는 계획을 다룬다"],
       ["극지방은 이산화탄소가 있는 장소로만 나온다"],
       ["이산화탄소가 해롭지 않다는 말은 어디에도 없다"],
       ["로켓 제작은 다루지 않는다"]],
 src: [["②"],["⑤"],["⑩"],["⑪과 어긋남 — 숨 쉴 수 있는 공기는 아니라고 했다"],["⑬"]],
 kb: {
  title:"대기를 바꾼다는 것",
  lead:"두껍게 만드는 일과 숨 쉴 수 있게 만드는 일은 다르다.",
  items: [
   ["화성의 대기",
    "주성분은 이산화탄소이고 지표 기압은 약 6밀리바로 지구의 1퍼센트에 못 미친다. 이 압력에서는 물이 액체로 오래 머물기 어렵다."],
   ["2018년의 계산",
    "자코스키와 에드워즈는 극관·토양·암석에 남은 이산화탄소를 모두 합해도 현재 기술로 도달 가능한 기압이 크게 부족하다고 보고했다."],
   ["양의 되먹임",
    "기온이 오르면 얼음이 녹고, 드러난 표면이 열을 더 흡수해 다시 기온이 오르는 구조를 양의 되먹임이라 한다. 지구 기후 논의에서도 같은 개념이 쓰인다."]
  ],
  ask:"지구의 대기를 우리가 '실수로' 바꾼 사례에는 무엇이 있을까?"
 }
},
{
 no: "54", key: "painres",
 accent: "#7A4A6B", tint: "#F4E9F1", deep: "#542F49",
 en: "Ethical Dilemmas of Pain Research in Animals",
 ko: "통증 연구가 안고 있는 문제",
 goal: "동물 통증 연구에서 유용성과 도덕적 부담이 맞물리는 구조를 설명할 수 있다.",
 fig: "Figure 1  같은 사실에서 나오는 두 가지.",
 tip: "먼저 생각해 보자. 아픔을 연구하려면 무엇이 필요할까?",
 sent: [
  "Pain research has an uncomfortable requirement built into its own question.",
  "To learn how pain works, someone has to be in pain.",
  "For most of the last century that someone has been an animal.",
  "The results have been useful, and modern surgery would be unthinkable without them.",
  "The difficulty appears when you ask why a mouse is chosen at all.",
  "It is chosen because its nervous system is close enough to ours to be informative.",
  "That closeness is also the reason the mouse can suffer.",
  "The more useful an animal is as a model, the stronger its claim on us becomes.",
  "The usefulness and the moral problem come from the same fact.",
  "Regulations respond with limits rather than answers.",
  "Researchers must replace animals where possible, reduce numbers, and refine procedures.",
  "These three words are printed in every ethics application in the field.",
  "Critics say the rules manage discomfort without ever confronting it.",
  "Defenders reply that a system with rules is better than one without.",
  "Neither side claims the question has been settled."
 ],
 kor: [
  "통증 연구에는 그 질문 자체에 불편한 요구가 들어 있다.",
  "통증이 어떻게 작동하는지 알려면 누군가는 아파야 한다.",
  "지난 세기의 대부분 동안 그 누군가는 동물이었다.",
  "그 결과들은 유용했고, 현대 외과 수술은 그것들 없이는 생각할 수 없을 것이다.",
  "어려움은 애초에 왜 생쥐가 선택되는지 물을 때 나타난다.",
  "생쥐가 선택되는 이유는 그 신경계가 우리와 충분히 가까워 정보를 주기 때문이다.",
  "그 가까움은 동시에 생쥐가 고통을 느낄 수 있는 이유이기도 하다.",
  "동물이 모델로서 유용할수록, 그 동물이 우리에게 갖는 권리 주장도 강해진다.",
  "유용함과 도덕적 문제가 같은 사실에서 나온다.",
  "규정은 답 대신 한계를 내놓는 방식으로 대응한다.",
  "연구자는 가능한 곳에서 동물을 대체하고, 수를 줄이고, 절차를 개선해야 한다.",
  "이 세 단어는 이 분야의 모든 윤리 심의 신청서에 인쇄되어 있다.",
  "비판하는 쪽은 그 규칙이 불편함을 직면하지 않은 채 관리만 한다고 말한다.",
  "옹호하는 쪽은 규칙이 있는 체계가 없는 체계보다 낫다고 답한다.",
  "어느 쪽도 이 문제가 해결되었다고 주장하지는 않는다."
 ],
 bank: [["requirement","①","요구"],["informative","⑥","정보를 주는"],["suffer","⑦","고통을 느끼다"],
        ["claim","⑧","권리 주장"],["regulations","⑩","규정"],["refine","⑪","개선하다"]],
 defs: [["requirement","something that must be done"],
        ["informative","giving useful knowledge"],
        ["suffer","to feel pain or distress"],
        ["claim","a demand for what one is owed"],
        ["regulations","official rules that control something"],
        ["refine","to improve by small changes"]],
 defOrder: [2,5,0,4,1,3],
 flow: [
  ["The requirement","To study pain, something must be in pain",null],
  ["The choice","A mouse is used because it is (  ①  )","informative"],
  ["The paradox","The same closeness lets the mouse (  ②  )","suffer"],
  ["The response","Rules set limits: replace, reduce, (  ③  )","refine"],
  ["The verdict","The question stays (  ④  )","open"]
 ],
 flowBogi: "informative · suffer · refine · open · cheap · settled",
 para: [
  ["② someone has to be in pain","Knowledge here has a ______.","cost"],
  ["⑥ close enough to ours to be informative","Similarity makes it ______.","useful"],
  ["⑧ the stronger its claim on us becomes","Value and duty rise ______.","together"],
  ["⑩ respond with limits rather than answers","Rules ______ the problem, not solve it.","manage"],
  ["⑮ Neither side claims the question is settled","The debate remains ______.","unresolved"]
 ],
 paraBogi: "cost · useful · together · manage · unresolved · free · apart · closed",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["Why Mice Cannot Feel Anything","The Same Fact Cuts Both Ways",
       "How to Perform Modern Surgery","Rules That Solved an Old Problem",
       "A History of Laboratory Buildings"], ans:2},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["통증을 연구하려면 누군가는 아파야 한다.","생쥐는 신경계가 우리와 가까워 선택된다.",
       "규정은 대체·감소·개선을 요구한다.","필자는 이 문제가 이미 해결되었다고 본다.",
       "비판하는 쪽은 규칙이 관리만 한다고 본다."], ans:4},
  {t:"write", q:"필자가 말한 '같은 사실'이 무엇인지 우리말 한 문장으로 써 보세요.",
   ans:"동물의 신경계가 우리와 닮았다는 사실이 연구에 유용한 이유이자 그 동물이 고통을 느끼는 이유라는 것이다."}
 ],
 fl: {
  model: { n:"⑥",
   toks: [["It","s"],["is chosen","v"],["because","c"],["its nervous system","s2"],
          ["is","v2"],["close enough to ours to be informative","m"]],
   ko:"생쥐가 선택되는 이유는 그 신경계가 우리와 충분히 가까워 정보를 주기 때문이다." },
  drill: [
   { n:"②", en:"To learn how pain works, someone has to be in pain.",
     ans:"M To learn how pain works · S someone · △V has to be · M in pain",
     ko:"통증이 어떻게 작동하는지 알려면 누군가는 아파야 한다." },
   { n:"⑪", en:"Researchers must replace animals where possible, reduce numbers, and refine procedures.",
     ans:"S Researchers · △V must replace · O animals · M where possible · △V reduce · O numbers · △V refine · O procedures",
     ko:"연구자는 가능한 곳에서 동물을 대체하고, 수를 줄이고, 절차를 개선해야 한다." },
   { n:"⑭", en:"Defenders reply that a system with rules is better than one without.",
     ans:"S Defenders · △V reply · [that] S′ a system with rules · △V′ is · C better than one without",
     ko:"옹호하는 쪽은 규칙이 있는 체계가 없는 체계보다 낫다고 답한다." }
  ]
 },
 syn: [
  { n:"⑥", name:"형용사 + enough to 부정사",
    q:"its nervous system is «close enough to ours to be» informative.",
    d:"<b>형용사 + enough + to부정사</b>는 '~할 만큼 충분히 …한'이라는 뜻이다.",
    k:"그 신경계는 정보를 줄 만큼 우리와 충분히 가깝다." },
  { n:"⑧", name:"the 비교급 ~, the 비교급 …",
    q:"«The more useful» an animal is as a model, «the stronger» its claim on us becomes.",
    d:"<b>the+비교급 ~, the+비교급 …</b>은 '~할수록 더 …하다'라는 뜻이다.",
    k:"동물이 모델로 유용할수록 우리에게 갖는 권리 주장도 강해진다." }
 ],
 synd: [
  { u:"구문 1", en:"The room was quiet enough for us to hear the clock.",
    k:"그 방은 우리가 시계 소리를 들을 만큼 조용했다." },
  { u:"구문 2", en:"The longer he waited, the harder the choice became.",
    k:"오래 기다릴수록 그 선택은 더 어려워졌다." },
  { u:"구문 1 + 2", en:"The closer a copy is to the original, the harder it is to spot.",
    k:"복제가 원본에 가까울수록 알아채기가 더 어렵다." }
 ],
 wtype: ["반대","정답","지엽","반대","무관"],
 stype: ["일치","일치","일치","반대","일치"],
 why: [["생쥐가 고통을 느낄 수 있다는 것이 글의 전제다"],["정답"],
       ["현대 외과 수술은 유용성의 예로만 나온다"],
       ["규칙이 문제를 해결했다고 하지 않았다"],
       ["실험실 건물의 역사와는 무관하다"]],
 src: [["②"],["⑥"],["⑪"],["⑮와 어긋남 — 어느 쪽도 해결되었다고 하지 않는다"],["⑬"]],
 kb: {
  title:"닮았기 때문에 생기는 문제",
  lead:"쓸모와 책임이 같은 자리에서 나온다.",
  items: [
   ["3R 원칙",
    "1959년 러셀과 버치가 제안한 대체(replacement)·감소(reduction)·개선(refinement)의 세 원칙이다. 오늘날 대부분의 나라에서 동물실험 심의 기준으로 쓰인다."],
   ["동물 통증의 판정",
    "동물이 통증을 느끼는지 판단할 때 회피 학습, 스스로 진통제를 택하는 행동, 평소와 다른 행동 변화 등이 지표로 쓰인다. 논의는 어류와 두족류까지 넓어져 왔다."],
   ["윤리 심의 위원회",
    "연구 계획은 미리 위원회 심사를 거친다. 예상되는 이익과 동물이 겪을 고통을 견주는 절차이지만, 그 비교 자체가 논쟁의 대상이기도 하다."]
  ],
  ask:"어떤 이익이 있으면 다른 존재의 고통을 정당화할 수 있을까? 그 기준은 누가 정해야 할까?"
 }
},
{
 no: "55", key: "empathy",
 accent: "#6C7A3A", tint: "#EFF2E2", deep: "#48541F",
 en: "Darwin's View on Empathy in Animals",
 ko: "다윈이 본 동물의 공감",
 goal: "다윈의 논의에서 공감이 어떤 자리를 차지하는지 설명할 수 있다.",
 fig: "Figure 1  기억되는 절반과 잊힌 절반.",
 tip: "먼저 생각해 보자. '적자생존'이라는 말은 정말 다윈의 것일까?",
 sent: [
  "Darwin is remembered for competition, which is only half of what he wrote.",
  "The Descent of Man spends many pages on sympathy rather than struggle.",
  "He collected reports of animals that helped one another at some cost.",
  "A blind pelican fed by its companions appears in his notes.",
  "Monkeys were described rescuing a keeper from an angry baboon.",
  "Darwin did not treat these stories as decoration.",
  "He argued that social instincts were themselves shaped by selection.",
  "A group whose members warn and defend each other survives longer than one that does not.",
  "Sympathy, in this reading, is not the opposite of fitness but a source of it.",
  "Later writers narrowed the theory into a slogan about the strongest.",
  "The phrase survival of the fittest was not even his own.",
  "Modern work on rats freeing trapped companions has revived his older question.",
  "Whether such acts show feeling or reflex is still argued.",
  "What is no longer argued is that they exist.",
  "Darwin would have found the second point more interesting than the first."
 ],
 kor: [
  "다윈은 경쟁으로 기억되지만, 그것은 그가 쓴 것의 절반일 뿐이다.",
  "『인간의 유래』는 투쟁보다 공감에 여러 쪽을 쓴다.",
  "그는 어떤 대가를 치르면서 서로를 도운 동물들의 보고를 모았다.",
  "동료들이 먹여 준 눈먼 펠리컨이 그의 기록에 나온다.",
  "성난 개코원숭이에게서 사육사를 구해 낸 원숭이들이 서술되었다.",
  "다윈은 이 이야기들을 장식으로 다루지 않았다.",
  "그는 사회적 본능 자체가 선택에 의해 다듬어졌다고 주장했다.",
  "구성원들이 서로 경고하고 지켜 주는 무리는 그렇지 않은 무리보다 오래 살아남는다.",
  "이렇게 읽으면 공감은 적합도의 반대가 아니라 그 원천이다.",
  "후대의 저술가들은 그 이론을 가장 강한 자에 관한 구호로 좁혀 놓았다.",
  "'적자생존'이라는 표현은 심지어 그의 것도 아니었다.",
  "갇힌 동료를 풀어 주는 쥐에 대한 최근 연구가 그의 오래된 질문을 되살렸다.",
  "그런 행동이 감정을 보여 주는지 반사인지는 여전히 논쟁 중이다.",
  "더는 논쟁되지 않는 것은 그런 행동이 존재한다는 사실이다.",
  "다윈이라면 첫 번째보다 두 번째 쪽을 더 흥미로워했을 것이다."
 ],
 bank: [["competition","①","경쟁"],["sympathy","②","공감"],["companions","④","동료"],
        ["instincts","⑦","본능"],["fitness","⑨","적합도"],["reflex","⑬","반사"]],
 defs: [["competition","the act of trying to win against others"],
        ["sympathy","the sharing of another's feeling"],
        ["companions","others that live or travel together"],
        ["instincts","behaviour that is not learned"],
        ["fitness","the ability to survive and reproduce"],
        ["reflex","an automatic reaction to something"]],
 defOrder: [4,1,5,0,3,2],
 flow: [
  ["The half we know","Darwin remembered only for competition",null],
  ["The other half","Many pages of The Descent of Man on (  ①  )","sympathy"],
  ["The evidence","Reports of animals helping at some (  ②  )","cost"],
  ["The argument","Social instincts were shaped by (  ③  )","selection"],
  ["Today","Rats freeing companions revive the (  ④  )","question"]
 ],
 flowBogi: "sympathy · cost · selection · question · slogan · struggle",
 para: [
  ["① which is only half of what he wrote","His view is often ______.","simplified"],
  ["③ animals that helped one another at some cost","Helping was not ______.","free"],
  ["⑧ survives longer than one that does not","Cooperation ______ a group.","strengthens"],
  ["⑩ narrowed the theory into a slogan","The idea was ______ by others.","flattened"],
  ["⑭ no longer argued is that they exist","Their existence is now ______.","accepted"]
 ],
 paraBogi: "simplified · free · strengthens · flattened · accepted · costly · denied · widened",
 check: [
  {t:"title", q:"이 글의 제목으로 가장 알맞은 것은?",
   ch:["The Half of Darwin We Forgot","Why Animals Never Help Each Other",
       "A Short Biography of Charles Darwin","How Baboons Attack Their Keepers",
       "The Origin of a Famous Slogan"], ans:1},
  {t:"fact", q:"이 글의 내용과 일치하지 <b>않는</b> 것은?",
   ch:["『인간의 유래』는 공감에 여러 쪽을 쓴다.","눈먼 펠리컨의 사례가 그의 기록에 있다.",
       "다윈은 사회적 본능도 선택의 산물로 보았다.","필자는 '적자생존'이 다윈의 표현이라고 본다.",
       "쥐에 대한 최근 연구가 오래된 질문을 되살렸다."], ans:4},
  {t:"write", q:"다윈이 더 흥미로워했을 '두 번째'가 무엇인지 우리말 한 문장으로 써 보세요.",
   ans:"동물이 대가를 치르며 서로 돕는 행동이 실제로 존재한다는 사실 자체를 말한다."}
 ],
 fl: {
  model: { n:"⑦",
   toks: [["He","s"],["argued","v"],["that","c"],["social instincts","s2"],
          ["were themselves shaped","v2"],["by selection","m"]],
   ko:"그는 사회적 본능 자체가 선택에 의해 다듬어졌다고 주장했다." },
  drill: [
   { n:"①", en:"Darwin is remembered for competition, which is only half of what he wrote.",
     ans:"S Darwin · △V is remembered · M for competition · [which] △V′ is · C only half of what he wrote",
     ko:"다윈은 경쟁으로 기억되지만, 그것은 그가 쓴 것의 절반일 뿐이다." },
   { n:"⑨", en:"Sympathy, in this reading, is not the opposite of fitness but a source of it.",
     ans:"S Sympathy · M in this reading · △V is · C not the opposite of fitness but a source of it",
     ko:"이렇게 읽으면 공감은 적합도의 반대가 아니라 그 원천이다." },
   { n:"⑫", en:"Modern work on rats freeing trapped companions has revived his older question.",
     ans:"S Modern work on rats · M freeing trapped companions · △V has revived · O his older question",
     ko:"갇힌 동료를 풀어 주는 쥐에 대한 최근 연구가 그의 오래된 질문을 되살렸다." }
  ]
 },
 syn: [
  { n:"⑨", name:"not A but B",
    q:"Sympathy, in this reading, is «not the opposite» of fitness «but a source» of it.",
    d:"<b>not A but B</b>는 'A가 아니라 B'라는 뜻으로 두 자리를 짝지어 읽는다.",
    k:"공감은 적합도의 반대가 아니라 그 원천이다." },
  { n:"⑫", name:"현재분사 수식 + 현재완료",
    q:"Modern work on rats «freeing trapped» companions «has revived» his older question.",
    d:"<b>freeing</b> 이하가 rats 를 뒤에서 꾸민다. has revived 는 지금까지 이어진 결과를 말한다.",
    k:"갇힌 동료를 풀어 주는 쥐 연구가 오래된 질문을 되살렸다." }
 ],
 synd: [
  { u:"구문 1", en:"The problem is not the rule but the way it is used.",
    k:"문제는 규칙이 아니라 그것이 쓰이는 방식이다." },
  { u:"구문 2", en:"A study on birds building nests has changed our view.",
    k:"둥지를 짓는 새에 대한 연구가 우리 시각을 바꾸어 놓았다." },
  { u:"구문 1 + 2", en:"Work on people helping strangers has shown not weakness but strength.",
    k:"낯선 이를 돕는 사람들에 대한 연구는 약함이 아니라 강함을 보여 주었다." }
 ],
 wtype: ["정답","반대","무관","지엽","배경"],
 stype: ["일치","일치","일치","반대","일치"],
 why: [["정답"],["동물이 서로 돕는다는 것이 글의 핵심 자료다"],
       ["다윈의 생애를 다루는 글이 아니다"],
       ["개코원숭이 일화는 한 문장의 예시다"],
       ["'적자생존'은 논지를 받치는 배경으로만 나온다"]],
 src: [["②"],["④"],["⑦"],["⑪과 어긋남 — 그의 표현이 아니었다고 했다"],["⑫"]],
 kb: {
  title:"다윈이 쓴 나머지 절반",
  lead:"경쟁만 읽으면 절반을 놓친다.",
  items: [
   ["『인간의 유래』",
    "1871년 저작에서 다윈은 도덕 감정의 기원을 다루며 사회적 본능과 공감을 길게 논의했다. 동물의 협력 사례도 여럿 인용했다."],
   ["'적자생존'이라는 말",
    "이 표현은 허버트 스펜서가 만들었고, 다윈은 1869년 『종의 기원』 5판에서야 받아들여 썼다. 흔히 다윈이 처음 쓴 말로 알려져 있다."],
   ["쥐의 구조 행동",
    "2011년 바르탈 등의 실험에서 쥐는 갇힌 동료를 풀어 주었고, 초콜릿이 함께 놓여 있어도 나누어 먹는 경우가 관찰되었다. 감정인지 학습된 반응인지는 계속 논의 중이다."]
  ],
  ask:"내가 누군가를 도운 일 가운데 나에게 손해였던 것이 있는가? 왜 그랬을까?"
 }
}
]};
